### ISSUE TITLE
Compatibility with current symengine dev version

### ISSUE THREAD

**Issue by tamiko** [dealii/dealii#10016]
I have uniform fallout with the current development version of symengine, trying again locally with version 0.6.0:
  https://cdash.43-1.org/viewTest.php?onlyfailed&buildid=5978

**Comment by jppelteret** [comment]
I'm going to be doing a version bump for SymEngine in an upcoming PR, so if the tests pass with 0.6 then I'd say that you shouldn't worry about any failures.

**Comment by tamiko** [comment]
@jppelteret On my laptop version symengine-0.6 is fine verifying on the tester now.

**Comment by jppelteret** [comment]
Agreed 100%. In the past I had a lot of test breakages between versions. It was often due to the terms in expressions being reordered, or some optimisations being done leading to simplifications in the expressions. Without seeing the test results, its hard to say if that's the case here. If so, and these become be a huge pain, then I'll just convert the tests to be numeric in nature and will output the expressions to `stdout`.

**Comment by jppelteret** [comment]
Oh, these results do not look good at all...
```
symengine/basic_05.debug: DIFF failed. ------ First 20 lines of numdiff output:
----------------
##2       #:4   <== 2.91338e+13
##2       #:4   ==> -8.30679e+11
@ Absolute error = 2.9964479000e+13, Relative error = 3.6072272201e+1
```
```
symengine/basic_04.debug: DIFF failed. ------ First 20 lines of numdiff output:
----------------
##2       #:4   <== 2.41358e+13
##2       #:4   ==> 4.68324e-307
@ Absolute error = 2.4135800000e+13, Relative error = 5.1536543077e+319
```
Those both look like one of the evaluation methods (probably the `LambdaOptimizer`) is not producing the correct results. But it seems to work properly with some compilers but not others (the newer ones), right?

The last test, `basic_06`, _might_ be failing due to a reordering of terms. So I should then look into the other tests to see if it could be a related issue (and consequently the report simply looks more bleak than it really is). I can't  say for sure though, but I've noticed that in the past when moving from machine to machine. I might have to adjust the SymEngine test's output to be less sensitive to this.

**Comment by jppelteret** [comment]
I'm currently building against SymEngine 0.7, so I'll try to see if I can prepare a fix in time. Otherwise we might just have to limit compatibility to 0.6 and below for the release.
