### ISSUE TITLE
Bug in AffineConstraintsData

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#10284]
Here's a bug that takes a good long time to explain -- story time: 

`AffineConstraints::distribute_local_to_global()` in its various incarnations uses an object of type `internals::AffineConstraintsData<number>` as a scratch object to work on. That class is, in essence, a singleton:
```
  template <typename number>
  class AffineConstraintsData
  {
  public:
    struct ScratchData
    { ... };

   ...

  private:
    /**
     * The actual data object that contains a scratch data for each thread.
     */
    static Threads::ThreadLocalStorage<ScratchData> scratch_data;
  };
```
All accesses are then through the `static` member variable, which is thread-local and consequently doesn't get in the way as long as each thread on which `AffineConstraints::distribute_local_to_global()` doesn't get interrupted by another call to the same function while it works. (But there is a check that would abort the program with an error if that were to happen.)

The bug now happens in the following context: If one configures deal.II with `DEAL_II_WITH_THREADS=OFF`, then the thread-local variable expands to just one global variable (it's `static` after all). That's fine if we're really just running single-threaded, but maybe we want to use `std::async` anyway -- in other words, we don't want to use the TBB facilities but just the C++11 ones. Why would one want to do that? Because we don't support the TBB on Windows -- so `DEAL_II_WITH_THREADS=OFF`, but maybe we want to run a few things in parallel anyway. For example, if one wanted to solve the PDE with different parameter values: an embarrassingly parallel  problem.

Well, back to the issue at hand: `scratch_data` in that case exists only once, but multiple threads all want to call `AffineConstraints::distribute_local_to_global()` on their respective data structures, and that is going to create trouble.

So how do we address this kind of thing?

**Comment by tamiko** [comment]
We had been pretty consistent in using `ThreadLocalStorage` for all our caching. I'd say it is time simply reimplement the class using native C++11 thread support (and remove the dependency on tbb by throwing out `tbb::enumerable_thread_specific<T>`). This should be little more than using a `std::map<std::thread::id, T>` and guarding an insert with a mutex.
This has the advantage that we can simply implement `ThreadLocalStorage` independent of any configuration! (I seriously hope no one is banking on the implementation to reduce to a raw pointer if thread support is disabled :smile:)


<off topic>
In addition, I think for 9.3 most of our thread support detection and configuration could be cleaned up (essentially throwing out the posix thread configuration and tbb). For example, I have used openmp for the last few projects (which enjoys built-in compiler support) and which I prefer quite  a bit over tbb.

We could, for example, introduce `DEAL_II_WITH_OPENMP` instead of `DEAL_II_WITH_THREADS` and if openmp support is not found only provide suppor for `ThreadLocalStorage` and our low level thread interface.
</off topic>

**Comment by bangerth** [comment]
Implicitly, what this issue really uncovers is what semantics we want to give to `DEAL_II_WITH_THREADS=OFF`: That deal.II *promises* to not use threads on its own, or that we *require* that user code also doesn't use threads. I don't think we ever thought about that.

**Comment by bangerth** [comment]
Here's what I'll try to do: The problem is that `AffineConstraintsData` uses a global (`static` variable). Instead, we should make that variable a member of `AffineConstraints`. This way, separate threads using separate `AffineConstraints` objects don't step on each other.

**Comment by bangerth** [comment]
Not fixed yet.

**Comment by bangerth** [comment]
Nope, I think that the problem may have been worked around, but that it isn't properly fixed yet. I still have plans for this :-)

**Comment by bangerth** [comment]
Well, still not fixed :-)

**Comment by luca-heltai** [comment]
@bangerth : why do you say so?

> Because we don't support the TBB on Windows -- so DEAL_II_WITH_THREADS=OFF

We actually do. We have some configurations with TBB working perfectly fine on MSVSC.
