### ISSUE TITLE
Particles: Need a way to get notified when a particle is lost

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#10350]
@gassmoeller For the particle tutorial, I'd like to know if a particle is lost, for example because I'd like to count the ones leaving through a particular part of the domain.

I believe that right now, these particles are just deleted. Would it be possible to have a signal to which one can attach oneself that is triggered for each particle that is deleted? Maybe with a pointer to the particle, its current position, etc? Is there a way to assess whether it has left the domain or whether we just can't find a cell it's in (in the parallel context)?

**Comment by gassmoeller** [comment]
I think that should be possible, but it will require some changes to the used data structures in `sort_particles_into_subdomains_and_cells`. Currently we do not keep track of which particles are reinserted and which ones are lost and we need to make sure the tracking does not mess up the scalability of the function. It would probably be a signal that gets a list of all the locally lost particles (instead of triggering once per particle).
Do you want me to take a look into creating such a signal?

**Comment by bangerth** [comment]
If you have time and interest, that would be fantastic! 

I think there's no downside to calling it once for each particle. The number of particles lost is probably going to be small, and I'm pretty sure that the cost of the call is substantially smaller than moving a particle, for example.

**Comment by gassmoeller** [comment]
See #10362, I think that should allow you to do what you intend in the step.
