### ISSUE TITLE
Better visibility for the AD feature from recent versions of deal.ii (beginning from 9.1)

### ISSUE THREAD

**Issue by krishnakumarg1984** [dealii/dealii#10366]
Automatic differentiation example is currently included in Step-33. This is slightly harder to access because

1.  Euler laws of gas dynamics are generally a more specialised problem to CFD (and not in the solid mechanics community) and thus a lot of people will miss out, and

2. Lots of beginners will never reach Step-33 (or will take a long time to reach there)

It would lend better visibility to the AD feature if Step-15 can incorporate it showing the Newton method. I claim better visibility because solving non-linear PDEs is such a common task and lots of new users will anyway come to Step-15. It is also very error prone to manually formulate the Newton-update equation. So, AD will be the perfect candidate to make life easier here. 

Can we at least consider this for the Step-15 extension section?

**Comment by jppelteret** [comment]
Firstly, let me say that your suggestion has caught our interest; @bangerth in particular agrees that this would be a nice tutorial to have a variant for that uses AD.

Although not yet visible to the community, I have already two AD/SD tutorials lined up for integration into the library. Both of them have full implementations but are yet to be documented. The first is one that shows how to use AD and SD to linearise nonlinear, coupled constitutive laws (one non-dissipative, one dissipative). The second uses AD to implement (and/or verify an implementation) of one-field finite strain elasticity. The first is really useful, because of the coupled nature of the equations. The second is really useful because it will not only show how to use the new AD framework to linearise finite element residuals, but it also add a simpler finite strain elasticity tutorial that the library has been lacking ever since step-44 was added. The jump from step-18 to step-44 is very large, and this would bridge the gap there.

So finishing these is the priority for me, and I don't have the time resources to deviate from my current plan. We can certainly consider extending step-15, but its always just a question of manpower to get it done. Naturally we’d always be happy to get contributions from the community, and whoever tackles it would have our support in getting it implemented.

**Comment by krishnakumarg1984** [comment]
Thank you. Is the AD example now finalized? Can a beginner in AD use Step-72 to understand how things work? Is this issue worth closing now?

**Comment by masterleinad** [comment]
step-72 is a work in progress.
