### ISSUE TITLE
Allow changing the quadrature for a FEValuesBase object?

### ISSUE THREAD

**Issue by gassmoeller** [dealii/dealii#10370]
We have a number of places in the particle steps (and ASPECT) that do the following:
```
for (all cells)
{
    std::vector<Point<dim>> particle_positions = ... some locations;
    const Quadrature<dim> quadrature_formula(particle_positions);
    FEValues<dim>         fe_value(mapping,
                fe,
                quadrature_formula,
                update_values);

  .. do_something
}
```

This could be much simpler (and save some memory allocations) if we could to the following:
```
const Quadrature<dim> quadrature_formula;
FEValues<dim>         fe_value(mapping,
            fe,
            quadrature_formula,
            update_values);
for (all cells)
{
    std::vector<Point<dim>> particle_positions = ... some locations;
    const Quadrature<dim> quadrature_formula(particle_positions);
    fe_value.set_quadrature(quadrature_formula);
    fe_value.reinit(cell);
}
```

The `set_quadrature` would need to invalidate the current cell of course. Do you think it makes sense to introduce such a function? Should it instead be implemented as a `reinit(cell,quadrature)` function? Are there any obvious difficulties that I do not see at the moment?

**Comment by bangerth** [comment]
Maybe calling it `replace_quadrature()` to make it even clearer that we're invalidating all internal data structures?

This isn't faster than what we're doing right now. You're just saving a single line of code. On the downside, you'd have to make some variables non-`const`. I think that the current setup has the benefit of making it clear that you're starting from scratch.

**Comment by kronbichler** [comment]
If that is really a pressing need, one thing that could be done more efficiently in case there is pressing need is to provide the evaluation of *all* basis functions (and their gradients, or whatever an `UpdateFlags` object instructs us to do) in a single point. This is potentially more efficient because we could only query the 1D polynomials in a tensor product element that needs to be collected only once. However, this requires a new interface going through the `FiniteElement` class, asking the specific classes like `FE_Poly` to do those things for us. We need to touch the `FiniteElement` interfaces soon anyway because I really want the tensor product information to get filled there (-> #9544), so we might get something like that into the interface as well. It needs thorough discussion, though.
