### ISSUE TITLE
How to implement moving mesh

### ISSUE THREAD

**Issue by Liu0813** [dealii/dealii#10544]
Hi, I want to solve the gas dynamics Euler equation in lagrangian/ALE frame. In this case, the computational mesh changes with time, so how should I solve this problem using dealii? And is there any tutorial?

**Comment by drwells** [comment]
I don't think that we have an ALE tutorial program. Instead of moving meshes, we typically use a class like `MappingQEulerian` which represents the displacement of the mesh with a finite element field: I'm not an expert in ALE methods but looking at that class might help you figure out what to do.

Would it be possible for you to also post this question to the mailing list? There are many more people on the mailing list than on GitHub so you may be able to find someone there who has worked on a similar project.

**Comment by drwells** [comment]
@Liu0813 do you have further questions on this topic?

**Comment by bangerth** [comment]
Actually, step-18 moves the mesh.

**Comment by Liu0813** [comment]
Thank you for your suggestion. Everything is clear.
