### ISSUE TITLE
PETScVectorBase::max and ::min are currently deprecated

### ISSUE THREAD

**Issue by alexrobomind** [dealii/dealii#10556]
Recently, the functions ::min and ::max of PETScVectorBase were marked as deprecated in #10398 .  They are very convenient short-hand expressions for what is otherwise an extra call to VecMin / VecMax that requires the manual set-up of an intermediate temporary variable. They also don't seem to conflict with any existing interface.

I would like to discuss this change, as I am personally quite fond of using these functions e.g. for diagnostic purposes.

**Comment by drwells** [comment]
I should respond since I am the guilty party - see #10398.

The problem that we have in the library now is that we would really like to have a consistent linear algebra interface for everything (petsc, Tpetra, Epetra, and our own native class) - in all cases we should inherit from `VectorSpaceVector`. Hence part of my work for this upcoming release is to convert our PETSc vector class to use this common interface.

Unfortunately, that means that we really need to deprecate some of these functions that were only ever implemented for PETSc. It's not ideal that we need to do this but its the only way to realize the goal of compatible linear algebra.

It's not ideal (and definitely not as pretty as the current version) but it should be pretty easy to workaround this deprecation by writing helper functions that wrap the calls to `VecMin` and `VecMax`. Would that work for you?

**Comment by alexrobomind** [comment]
I can always just sub-class the vector-classes and add the needed functionality myself, so that is not a problem.

What I am confused about is, how having these functions for PETSc-specific functionality prevents vectors from inheriting from VectorSpaceVector, since that class neither uses the function names, nor does it offer an alternative way to compute that information (hence my above "no conflicts with existing interface"). I am a bit worried that this represents a general change in direction for the "vendor-specific" deal.II wrapper classes to only expose functionality needed by the deal.II core, and not the additional capabilities provided by external libraries.

I might be a bit sensitive to this, but I have spent a good time in the past re-implementing functionality that a library I am using is in principle capable of doing, but doesn't let me access due to interface constraints (examples include TensorFlow making it harder and harder to get the actual graphs, ParaSails - even when used directly in PETSc - making it extremely difficult to read the preconditioner matrix and deal.II not letting me modify the contents of the MGConstrainedDofs object to change the nature of periodicity constraints)

**Comment by drwells** [comment]
My intent with this change is to make it easier to switch between different vector classes by offering the same deal.II interface in all cases - see, for example, the generic linear algebra headers or step-40 (we try to support a common set of operations across all backends).

> I am a bit worried that this represents a general change in direction for the "vendor-specific" deal.II wrapper classes to only expose functionality needed by the deal.II core, and not the additional capabilities provided by external libraries.

I took up this project so that I can use PETSc with SNES in another project I am working on. To me, the main value of the PETSc wrappers is that we can get a `Vec` out and do our own manipulations outside of things directly supported by deal.II. I do not think we will ever make the underlying objects unavailable (for example, there is also `EpetraWrappers::Vector::trilinos_vector()`.

> deal.II not letting me modify the contents of the MGConstrainedDofs object to change the nature of periodicity constraints

I have never had to do this myself but, given that we require the user to set up a sequence of `MGLevelObject`s I am honestly surprised that this is not possible. I haven't tried to do this but I have found it straightforward in the past to add very strange constraints to a non-multigrid system. Could you open a separate issue for this?

**Comment by bangerth** [comment]
As an update, the functions are still there, but are still deprecated:
```
    /**
     * Return the value of the vector element with the largest negative value.
     *
     * @deprecated This function has been deprecated to improve compatibility
     * with other classes inheriting from VectorSpaceVector. If you need to
     * use this functionality then use the PETSc function VecMin instead.
     */
    DEAL_II_DEPRECATED
    real_type
    min() const;

    /**
     * Return the value of the vector element with the largest positive value.
     *
     * @deprecated This function has been deprecated to improve compatibility
     * with other classes inheriting from VectorSpaceVector. If you need to
     * use this functionality then use the PETSc function VecMax instead.
     */
    DEAL_II_DEPRECATED
    real_type
    max() const;
```

**Comment by bangerth** [comment]
We have made it easier recently to get the PETSc `Vec` object out of vectors. If someone needs to call specific PETSc functions on a deal.II wrapper vector, this is easy enough. So let us close this issue -- there is a relatively straightforward workaround after all.
