### ISSUE TITLE
QGaussLogR does invalid math

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#1058]
This is another issue uncovered by #965:

`QGaussLogR` has this code:
```
template<>
QGaussLogR<1>::QGaussLogR(const unsigned int n,
                          const Point<1> origin,
                          const double alpha,
                          const bool factor_out_singularity)
[...]
{
  [...]
    if (factor_out_singularity == true)
    for (unsigned int i=0; i<size(); ++i)
      {
        Assert( this->quadrature_points[i] != origin,
                ExcMessage("The singularity cannot be on a Gauss point of the same order!") );
=>      this->weights[i] /= std::log(std::abs( (this->quadrature_points[i]-origin)[0] )/alpha );
```
The assertion correctly filters out the case where we apply the log to a zero argument. But, in `tests/codim_one/integrate_log_2`, we end up with a case where `origin[0]=0`, `quadrature_points[i][0]==alpha`, and consequently `log` is applied to 1.0 as argument, yielding zero. This then ends up dividing by zero.

I don't understand this code. @luca-heltai : Do you recall what this code does and what we need to do if this case happens? Apparently, it happens in actual codes.

**Comment by luca-heltai** [comment]
This code integrates functions with a logarithmic weight, i.e., it computes the integral $\int_a^b -log|x-x_0| f(x) dx$ for arbitary functions $f(x)$. The rationale behind the `factor_out_singularity` option is that often you know that f(x) has an asymptotic behavior on $(a,b)$ which is similar to $log|x-x_0|$, and you want to use a quadrature formula which works for $f$ directly. This can be done by factoring out from the quadrature weights the $-log|x-x_0|$ part, so that the final quadrature formula is good for logarithmically singular functions $f$. The user has to make sure this is possible, i.e., the argument of $log|x-x_0|$ should not be zero, if you want to factor it out. 

I believe we should add in the Assert a check for this case as well. It should *not* happen in actual codes. This happens if the cell you are integrating is the segment [0,1], you put origin in 0, and use a quadrature formula with end points. 

This is not compatible with the typical usage of this quadrature formula, which of course would not make sense in this case. I'll add an Assert that check that this does not happen, and fix the test.
