### ISSUE TITLE
Choose between DEAL_II_WITH_TET_SUPPORT and DEAL_II_WITH_SIMPLEX_SUPPORT

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#10606]
See the discussion at the bottom of #10573. We need to settle this before the next release.

**Comment by rezarastak** [comment]
`TET` is easier to understand in the context of FE modeling. `SIMPLEX` has a more consistent meaning in the dimension-independent context.

**Comment by masterleinad** [comment]
I think we generally try to be precise in our naming and therefore prefer "Simplex" over "Tet" (of course I might be biased by having more a math than an engineering background).

**Comment by blaisb** [comment]
I think Simplex is more appropriate since it is consistent with the dimension-independent nature of deal.II.
It is also the nomenclature used by the FENICS project (e.g. https://launchpadlibrarian.net/83776282/fenics-book-2011-10-27-final.pdf). Coming from a pure engineering background, I still find the notion of simplex to be intuitive.
