### ISSUE TITLE
Dimension Independent programing in step 18

### ISSUE THREAD

**Issue by salrakan** [dealii/dealii#10881]
Hi, 

I just have a simple remark for step 18. 

in the incremental boundary conditions class, the values vector is given a specified value instead of a dimension dependent (dim) value. 

This can lead to problems when trying to change the dimension of the problem. 

Thanks

**Comment by bangerth** [comment]
Can you point out which specific code piece you are referring to?

**Comment by salrakan** [comment]
Dear Prof. Bangreth 

Sir, Thank you for your response. 
In step 18 on line 659 (values(2)).  I thing it would be better if was a dim function like the body force class.

I am using this equation as part of my PhD research phase field multi-physics model. I am using a 2-D rectangular domain and I had errors when trying to run the program.  

I though I wanted to point this out 

Thank you

**Comment by masterleinad** [comment]
@salrakan Do you want to create pull request for that?

**Comment by jppelteret** [comment]
Unfortunately, I think that making this tutorial run in 2d (if that is what is, indirectly, being suggested it should) is a little more complicated than changing one or two lines of code. For starters, the problem is really set up to be 3d from the outset, using the [`GridGenerator::cylindrical_shell()`](https://dealii.org/current/doxygen/deal.II/namespaceGridGenerator.html#a760789a93b1e0fe7f5c2675c31b6f14f) that only works in 3d. The way that the [boundary IDs are setup](https://github.com/dealii/dealii/blob/master/examples/step-18/step-18.cc#L767-L769) also assumes 3d. So the "issue" that is being raised here extends beyond the single line of code that has been indicated. Probably the same can be said of other tutorials.

Although it has been predominantly constructed in a dimension independent way, there are some improvements that could be made. @salrakan is right that on line https://github.com/dealii/dealii/blob/master/examples/step-18/step-18.cc#L659 the accessed value is out of bounds in 2d. What might be good is adding some asserts to indicate that the `IncrementalBoundaryValues` class is only valid in 3d. But I wouldn't go so far as to clutter up the tutorial by having an `Assert(dim == 3)` before the third element of any vector/array/whatever is accessed.

**Comment by salrakan** [comment]
Thank all you for your feedback.

**Comment by tjhei** [comment]
> value is out of bounds in 2d.

We could write it as ``values(dim-1)``, but I agree with your assessment otherwise, JP.

> But I wouldn't go so far as to clutter up the tutorial by having an `Assert(dim == 3)`

Agreed. Notice that the expression itself should generate the same Assert.
