### ISSUE TITLE
Discussion: best option to integrate a deal.II-preCICE example

### ISSUE THREAD

**Issue by uekerman** [dealii/dealii#10934]
This issue is to discuss whether and how we could integrate a deal.II-preCICE example in the deal.II world.

[preCICE](https://www.precice.org/) is a coupling library. You can use it to couple, for example, deal.II and OpenFOAM for fluid-structure interaction. In this example, the solid mechanics are implemented with deal.II and for the fluid mechanics some OpenFOAM solver is used. preCICE is a library, so both the deal.II application and OpenFOAM need to call preCICE. preCICE further follows a peer-to-peer approach. This means that there is no additional central instance (such as a coupling server) needed.
A tutorial for preCICE is typically more complicated than a tutorial for a stand-alone solver or library as it requires another code to couple to. 

## Software overview

A coupled simulation with deal.II and OpenFOAM has the following components:
* The deal.II application program, which uses the deal.II library and the deal.II-preCICE adapter.
* The deal.II-preCICE adapter, which uses the deal.II library and the preCICE library.
* OpenFOAM, which uses the OpenFOAM-preCICE adapter.
* The OpenFOAM-preCICE adapter, which is a plug-in library of OpenFOAM and uses the preCICE library.
* The preCICE library (with [Dependencies](https://github.com/precice/precice/wiki/Dependencies)). 

## Status quo

The deal.II-preCICE adapter and the application code are built together and hosted [here](https://github.com/precice/dealii-adapter). deal.II can "only" be used as the solid mechanics code in a partitioned FSI simulation. Configuration files for complete coupled simulations are hosted in the tutorials repository of preCICE (e.g. [a perpendicular elastic flap in channel flow with OpenFOAM](https://github.com/precice/tutorials/tree/master/FSI/flap_perp_2D/OpenFOAM-deal.II)). These tutorials are automatically run as weekly regression tests, currently against the master branch of deal.II. 

## Motivation

From preCICE perspective, including some sort of deal.II-preCICE example in the deal.II world would serve two purposes:

**(V)** Visibility: Users of deal.II see that there is an option for external coupling to other codes via preCICE.

**(S)** Sustainability: At an early stage, we get triggered if the deal.II-preCICE adapter fails to work with the current develop version of deal.II. Necessary maintainability work is presumably easy to explain (and document in an issue) by deal.II developers (who know what has changed in deal.II).

## Options

**(T1) deal.II + OpenFOAM**

Take a full coupled tutorial with two solver codes as currently used in the preCICE tutorials.

External dependencies:
* preCICE
* OpenFOAM 
* [OpenFOAM-preCICE adapter](https://github.com/precice/openfoam-adapter)

My opinion: this is better kept in the preCICE tutorials. The dependencies are probably just too many.

**(T2) deal.II + deal.II**

Extend the existing deal.II-preCICE adapter to also handle the fluid side of a fluid-structure interaction and then couple deal.II with deal.II.

External dependencies:
* preCICE

My opinion: extending the adapter is too much for the moment (but interesting for later). Coupling deal.II with itself is not the main idea behind preCICE. Black-box coupling is simply not the best choice here.

**(T3) deal.II + recorded values**

We are currently working on a mechanism to "record" previous simulations and then "replay" one of the coupled solvers. We could record OpenFOAM and then do a unidirectional coupling between the recorded values (basically force values at the interface over time) and deal.II. 

External dependencies:
* preCICE
* [ASTE](https://github.com/precice/aste) (basically a single Python script is needed)

My opinion: not optimal, but could be a good compromise. The necessary work is doable. Dependencies are manageable. We could then link from this case to the full deal.II-OpenFOAM tutorial in the preCICE tutorials if somebody wants to take the next step.

**(T4) deal.II + dummy**

Again a unidirectional coupling, but this time from a dummy C++ application to deal.II. The dummy application provides some forces and could be directly shipped with the tutorial.

External dependencies:
* preCICE

My opinion: the option to go with if **(T3)** has still too many dependencies or is regarded too complicated. Physics will be less interesting (with **(T3)** we could do the solid part of the Turek and Hron FSI3 for example). 

For all variants, an open question is whether to move the [complete deal.II adapter repository](https://github.com/precice/dealii-adapter) or only [the application class](https://github.com/precice/dealii-adapter/blob/master/linear_elasticity/linear_elasticity.cc) (and for example turn the adapter into a library).

## Location

* deal.II tutorials

My gut feeling is that the dependencies are too unusual for the deal.II tutorials.

* [deal.II code gallery](https://github.com/dealii/code-gallery)

Could be a good place. The open point then is **(S)**. 

The readme of the gallery says:

> The examples in the code-gallery of periodically adjusted so that they maintain compatibility with a "recent" version of the deal.II

How is this checked for? Is there a CI?

## Alternative

Leave everything as it is and maybe find other solutions to **(V)** and **(S)**.

**Comment by bangerth** [comment]
@uekerman I agree that the code gallery is probably the better place. We didn't have all that clear a direction for the tutorial until around step-32, but since have really tried very hard to limit tutorial programs to illustrating *how to use specific features of deal.II*. Some of the earlier programs (say, step-14, step-31, step-32) don't quite do that as well, but the ones that came after are reasonably good at it.

As such, what you propose would be a better fit for the code gallery where we have less restrictions. There are also less requirements on the extent and quality of the documentation. Finally, we generally leave it to the authors to determine what they think is interesting or worthwhile showing -- we're happy to take whatever program anyone has, as long as they are willing to make it available to the deal.II community as a starting point for others. So, I think you should go with the code gallery, and determine for yourself what you want to show: T1, T2, T3, or T4 are all ok with us -- in fact, if that's what you'd like, you can make these into four programs that depend on each other.

As for checking/updating with newer deal.II version: That's one release step. We do our best to keep programs up to date, though it depends on the person doing the check being able to install all dependencies.

**Comment by DavidSCN** [comment]
As another option we could simplify things and step away from our existing coupled deal.II codes. They include a lot of unimportant aspects and complexities which shadow the basic concept of preCICE and how to use preCICE with deal.II. In fact, most of the preCICE related deal.II code is summarized in a single class with around 300 lines of code. 

Hence, the idea is to integrate a light variant of the core class in an as simple as possible deal.II code so that we could explain the deal.II specific code parts and illustrate the concept of coupling via preCICE. Though the resulting program will not compute something physically meaningful (in the sense of coupling), it serves the educational purpose much better. As a side effect, we get rid of any external dependency apart from the most basic preCICE version itself. I think this conceptual direction would fit better in the tutorial programs since it shows how to use deal.II with preCICE.

How could the concrete tutorial look like?
preCICE is essentially a tool for surface coupling. Integrating it in step-4 (as the most simple tutorial program) we could just map the result on the boundary to another mesh held by another participant/executable. So, we solve the Laplace equation with one participant and just receive the mapped solution on the boundary on another participant and write in to an output file. The result would look like this (right mesh has been shifted). How about this idea?
![](https://user-images.githubusercontent.com/33414590/94359072-3d1f5700-00a5-11eb-9168-7f9a97bdbed2.png)

**Comment by peterrum** [comment]
@DavidSCN I like the idea very much! Maybe you could share the link to you code here (or already open a PR).

Two questions/remarks from my side:
- I guess it would be the best if you could move all code into a single file. Maybe even have a single `main` and the program is configured on command line.
- How I understand you description is that you have two triangulations at the same position (depicted above as left and right). You apply DBC for the *left* domain and solve the problem. The boundary values are then interpolated to the right domain. As far as I see we would not have to solve an equation system in this case. Am I right? 

I would suggest to make the example slightly more complex. A single domain is subdivided into two parts (maybe even overlapping).  One subdomain is processed by program A and the other by program B. Both solve a Poisson problem and are coupled via the shared interface. We could use a Dirchlet-Neumann approach to solve the problem or an additive and/or multiplicative Schwarz approach. It would nice to be able to solve the 150 year old problem by H. A. Schwarz (see also the picutre in https://en.wikipedia.org/wiki/Schwarz_alternating_method and https://www.ngzh.ch/archiv/1870_15/15_3/15_19.pdf).

**Comment by DavidSCN** [comment]
>  Maybe you could share the link to you code here (or already open a PR).

So, the first draft version used for the figure above can be found in my fork https://github.com/DavidSCN/dealii/tree/step-75/examples/step-75

> I guess it would be the best if you could move all code into a single file. Maybe even have a single main and the program is configured on command line.

I also had this in mind and see your point. It reduces some duplication and leads to a clear structure of the whole simulation. In order to emphasize, however, that both participants are completely independent I thought it would be better to split them in two separate files (and executables). I can change it of course

> How I understand you description is that you have two triangulations at the same position (depicted above as left and right). You apply DBC for the left domain and solve the problem. The boundary values are then interpolated to the right domain. As far as I see we would not have to solve an equation system in this case. Am I right?

Correct.

> I would suggest to make the example slightly more complex. A single domain is subdivided into two parts (maybe even overlapping). One subdomain is processed by program A and the other by program B. Both solve a Poisson problem and are coupled via the shared interface. We could use a Dirchlet-Neumann approach to solve the problem or an additive and/or multiplicative Schwarz approach. 

Making it more complex is of course possible and a Dirichlet-Neumann coupling is for physical application cases the most convenient way to solve the coupled system. If we merge both codes in a single file, the `solve` and `assemble` steps are present anyway, so there would be mainly some work for the boundary conditions left. I would prefer the shared coupling interface variant over the overlapping domain variant, because in the majority of application cases the coupling happens across a defined interface with clearly decomposed domains. Of course, the Schwarz problem/overlapping domains would be feasible with preCICE, but the setup leads to different interfaces, where data is exchanged, namely (from a participant perspective) reading at the boundary of each participant and writing in the domain of each participant. These additional interfaces and their handling is in my opinion inappropriate for a first :wink: basic-conceptual tutorial. The boundary-coupled variant is a good idea and serves probably also better to illustrate the concept of coupling in general.

**Comment by bangerth** [comment]
I'm a fan of breaking complex things into two simpler steps. I like your suggestion of a simple program that just illustrates the idea. If we continue to think of the code gallery, then there is also no reason not to think about two programs if that's something you'd like to pursue.

**Comment by DavidSCN** [comment]
To summarize the discussion: we provide a small program dealing with a Laplace problem, either unidirectional as simplest variant or in a coupled fashion. Maybe we can decide on this detail later in an upcoming PR, where the concrete differences will be better visible. If I understand @bangerth correct, the preferred location for the program would be the code-gallery, right? My impression is that the higher quality standard of the tutorial programs in general would be beneficial because the user simply appreciate the tutorials more due to a more comprehensive documentation.
