### ISSUE TITLE
Implementing multi-physics problem

### ISSUE THREAD

**Issue by mclarenr** [dealii/dealii#10941]
Hi, 

I apologize if this not where its supposed to be. 

I have a question regrading multi-physics problem implementation. 

I am developing a program that will solve the steady-state thermal conduction (laplace) first and then the allen-Cahn equation.

both of the problems are solved on the same mesh, however due to the nature of my specific implementation they solved separately. To solve the allen-Cahn equation, I need to evaluate temperature dependent functions at each node in the domain.

Hence, they only share the same triangulation, but everything else is separate.

My question is, how to use the solution vector from the thermal conduction (the temperature) in the assembly of the allen-cahn equation ?

**Comment by masterleinad** [comment]
> I apologize if this not where its supposed to be.

These kind of questions are best asked in the [Google Groups](https://groups.google.com/g/dealii).

**Comment by jppelteret** [comment]
Hi @mclarenr,

As @masterleinad pointed out, we have a dedicated forum to answering these sorts of questions. It's better (for us and you) to post it there, because it then gets the attention of the community as a whole, and you can perhaps get input from a variety of people with different ideas. What's discussed is also then available in a single location for everyone to reference.

So if you go ahead and ask it again on the forum, I will point you towards an example (yet to be finalised) that solves a thermal and electromechanical problem in a staggered manner, and all of the fields are coupled to each other. So the thermal problem references the mechanical deformation, and the electromechanical problem requires the temperature too. This would give you a hint as to one way that you could structure your problem.

**Comment by mclarenr** [comment]
@masterleinad @jppelteret  thank you for your clarification.
