### ISSUE TITLE
Provide a mechanism to update ghost_particles location and properties without regenerating them

### ISSUE THREAD

**Issue by blaisb** [dealii/dealii#11093]
Dear all, 
I hope you are well. As always, thank you very much for taking the time.
Our recent benchmark on our usage of the particle methods has highlighted some limitations in the code when it runs in parallel. These could not have been planned or identified by @gassmoeller, there is absolutely not an ounce of blame in what follows. I think @gassmoeller work on particles is just awesome.

Let me describe our application case and things will be clearer. We are implementing a DEM method in Lethe using the particles structures (see : https://www.youtube.com/watch?v=__5UGx4fQps&feature=youtu.be for an example of DEM). On a single core, it has exactly the performance we need right now and everything is perfect (it about 10% faster than LIGGGHTS, a state of the art DEM code based on LAMMPS).

What is important to know about DEM is that we do not need to call sort_particles_into_subdomain_and_cells every iteration. We actually do it every X iterations, where X is the frequency at which we want to couple DEM and the background equations being solved on the mesh.

Currently, deal.II does not provide any mechanism to update the ghost particles location and properties without calling exchange_ghost_particles. However, exchange_ghosts is a very expensive operation. Here is the code for exchange_ghost_particles: https://www.dealii.org/developer/doxygen/deal.II/particle__handler_8cc_source.html#l01160

There are two sub issues to this issue.
The first one is that at every exchange_ghost_particles() the following structure is generated:

    
     std::vector<std::set<unsigned int>> vertex_to_neighbor_subdomain(
       triangulation->n_vertices());
     for (const auto &cell : triangulation->active_cell_iterators())
       {
         if (cell->is_ghost())
           for (const unsigned int v : GeometryInfo<dim>::vertex_indices())
             vertex_to_neighbor_subdomain[cell->vertex_index(v)].insert(
               cell->subdomain_id());
       }

This is a relatively expensive operation since we are doing it millions of times. This sub issue can be solved easily using a deal.II cache I believe, like my PR from last year on sort_particles_into_subdomain_and_cells(). No worries here.

The second issue is more profound. At every call, exchange_ghost_particles() clears the entire ghost_particles structure and rebuilds it from scratch, assuming that ghost particles may have changed cells and everything. The underlying assumption is that we are calling sort_particles_into_subdomain_and_cells at every time step. Regretfully, this is not what we are doing. 

My proposition would be to add a simple function called update_ghost_particles() which would only update the ghost particles location and property, without recreating the entire ghost particles data structure. Effectively it would "just" send the information from the owner of the real particles to the owner of the equivalent ghost particles and use this information to update the ghost location and property. However, this is significantly more challenging since this new function would need to know which processors own the ghost derived from real particles. I would like to do this cleanly and contribute it back to deal.II because I am sure it can be helpful to others down the line.

Would any of you have suggestions. tips or ideas as to what is the best way to implement this? I will do a PR for the first sub issue next week, but for the second part, I would greatly appreciate your advice (maybe @peterrum , @gassmoeller , @bangerth or @kronbichler  ?)

**Comment by kronbichler** [comment]
This sounds reasonable to me.

Regarding the second `update_ghost_particles` function and from a higher level point of view without intimate knowledge on all ingredients yet, I wonder how much structure we can use for the derivation of the communication pattern. If we have a fully unstructured approach just going through a global particle id, we would use the `ConsensusAlgorithms` approaches written by @peterrum which can figure out what to exchange and do the exchange in a fully unstructured way. If we know ghost owners through the ghost layer of the mesh (and have that information up to date), it would of course be much cheaper because we only need the point-to-point communication setup of the ghost layer, which we could cache from both sides of the communication. The question would be whether your code @blaisb can make such a guarantee, i.e., that we do not leave the ghost layer and into the artificial cells for which we lack this information. Alternatively, we could also set up a somewhat wider communication "stencil" with one of the consensus algorithms.

**Comment by peterrum** [comment]
>  If we have a fully unstructured approach just going through a global particle id, we would use the ConsensusAlgorithms approaches written by @peterrum which can figure out what to exchange and do the exchange in a fully unstructured way. If we know ghost owners through the ghost layer of the mesh (and have that information up to date), it would of course be much cheaper because we only need the point-to-point communication setup of the ghost layer, which we could cache from both sides of the communication.

I am not sure if `ConsensusAlgorithms` is really of use here as the algorithm is implemented here. The consensus algorithms are targeted for sparse dynamic communication patterns: but here we already know the source and target processes (due to symmetry of neighborhood of processes).

I guess the new `update_ghost_particles()` function would still call `send_recv_particles(ghost_particles_by_domain, ghost_particles);` maybe with an additional argument not to insert particles:

https://github.com/dealii/dealii/blob/d2d482dceca7b0b986791c78656d45eda1e4148b/source/particles/particle_handler.cc#L1435-L1459

but to update their properties (although I am not sure how that can be done with the multi maps). Said that, I think it would be also a good idea to cache the communication pattern.

**Comment by kronbichler** [comment]
> [...] but here we already know the source and target processes (due to symmetry of neighborhood of processes).

That's what I was referring to with the question whether we need to think about the case that particles leave the ghost domain in between the full updates, or whether we could use the communication pattern of the mesh. There might be other things preventing that part (e.g. how do you determine the boundary of the domain in a DEM approach), but I guess the exchange farther away needs an unstructured sparse communication.
