### ISSUE TITLE
FE_Nedelec for degree=8？

### ISSUE THREAD

**Issue by HaoWangCyy** [dealii/dealii#11146]
Do you know the expression of base function and interpolation function? Or in which literature is the explanation of the assault?

**Comment by drwells** [comment]
Try looking at the documentation of the `PolynomialsNedelec` class:

https://www.dealii.org/developer/doxygen/deal.II/classPolynomialsNedelec.html

These implement the polynomials proposed by Nédélec's 1980 paper.

Since this is not an issue related to the library I am going to go ahead and close this. Please ask any followup questions on the mailing list.
