### ISSUE TITLE
Brainstorming - Re-design the data storage structure used in the ParticleHandler

### ISSUE THREAD

**Issue by blaisb** [dealii/dealii#11206]
I think it would be interesting to have an issue where we discuss long term plans for redesigning the data structure used to store the particles within the mesh. Right now the multimap has multiples issues, notably related to memory fragmentation and the fact that it makes it expensive to loop over the particles.

This is obviously a long term project, but I would like to gather all of your opinions on this: @kronbichler @peterrum @luca-heltai @gassmoeller .

**Comment by bangerth** [comment]
Some of my recent changes have also made it possible to re-shuffle the memory used for particle properties so that one accesses particle properties in-memory-order when iterating over particles. This would require one additional re-direction, but would probably reduce cache misses.

**Comment by gassmoeller** [comment]
I agree this will be a valuable discussion. To get the discussion started: There are two alternatives that I had considered briefly before settling on the multimap we already had from an earlier implementation (see below). Of course there may be other structures I am not aware of or have not considered so we should not limit this discussion to these options.

(i) An unordered multimap. Smallest implementation change to the current structure. Gets around the logarithmic cost for accessing a particular cell. Iteration over the container is no longer in order of cells of a triangulation, but since access cost is constant that should not be such a problem. insertion/deletion is similar to now. Particle data is still fragmented.

(ii) two separate containers, one for particle storage (a simple array/vector or similar or the storage we currently use for the dynamic properties), one for storing particle-cell associations (e.g. a linked list of cell iterators). This would require periodic sorts (to keep particles in the same cell in similar memory locations) and manual updates if particles are removed or added. To keep things fast we want to avoid frequent memory allocations and sorting of the whole container, i.e. we would need to keep some sort of list of empty storage locations to fill up with arriving particles before reallocating and would need a mechanism to decide when to sort the container.

I would be interested to hear other suggestions/thoughts.

**Comment by bangerth** [comment]
Out of curiosity, do we know for sure that iteration over particles is expensive? In the existing particle tutorials, we access particles as we loop through cells, and the fact that particles are stored in the same order as cells is quite convenient and makes it rather cheap to find the particles associated with the current cell -- just keep iterating starting from the last particle of the previous cell. I think that's actually a good system.

Memory fragmentation: I presume you mean the memory used to store the particles themselves? Do we know that that is an actual issue?

**Comment by blaisb** [comment]
That's a very good question. The problem is it really depends on the use case we make of particles. If we always access particles when looping over cells (e.g. particle tracking) then the current data storage seems to be reliable (however, maybe @kronbichler can comment more on the data fragmentation). However, if the majority of the time we access particles themselves, without connecting their use to the mesh, then clearly the current structure is inefficient. In our code right now, a good 15-20% is spent just looping over the particles for simple operations (displacing their physical location). This is because we do a lot of operations on the particles that are not related to the mesh. In a way, this could be considered a wrongful use of the particles class because this is so far from what they were originally intended for.

I was always taught in my scientific computing courses that large array storing classes should be avoided because of how inefficient it can be, I am unsure if it is true in this case (or maybe I was taught wrong things, which also highly possible). However, I can point to a majority of codes (GROMACS, LAMMPS) which use particle and try to avoid the container of classes type of structure.

To be honest, I do not know what would be the best solution in terms of efficiency and I believe it will really depend on the use we make of the particles. One thing I have found really annoying in the present context however is that if you know a particle id, it is very difficult to get that particle. This I find is a very limiting element.

:)!

**Comment by bangerth** [comment]
Ah, I didn't remember that you don't need the association with cells. That said, I would be greatly surprised if *iterating* over particles takes the time, rather than *doing* something with the particles. In the end, a `std::multimap` is not an inefficient data structure for sequential iteration, though it may be if you're specifically searching for a particle in it. It would be interesting to see if you could run your programs in `callgrind`, for example, to see which functions actually are expensive.

As for the `id` -> particle map, this makes sense and it shouldn't be very difficult to add a map that provides this kind of access. One issue is that the `id`s stored on each processor are not sequential. So you'd have to expect some kind of `O(log (# of particles on processor))` kind of behavior for access. But we have good classes for this (`IndexSet::nth_index_in_set()` will do).

**Comment by luca-heltai** [comment]
Let me also add to the discussion that the `Particle` object at the moment is inconsistent (i.e., it contains a reference position, but not the cell it refers to, exactly because of the way it was thought to be stored).

What do you think would be the best structure?

- locations/reference locations/properties
- cells and IndexSet (into indices for the first block of vectors)
- maps of ids to indices

and then methods to sort things out?

**Comment by kronbichler** [comment]
@bangerth  That said, I would be greatly surprised if iterating over particles takes the time, rather than doing something with the particles.

I already did some benchmarks back in #10991 and, maybe more to the point, https://github.com/dealii/dealii/pull/11046#issuecomment-710122584, which suggests that it is the iteration that takes time. To be more precise, I ran another test with callgrind right now and comment on the findings. My benchmark is step-68 ran in 3D and with Q3 elements, using 1.5 million particles, and a `MappingQGeneric(3)` to make the evaluation somewhat challenging and non-trivial compared to iterating over particles. I use the contribution from #11046 for reasonable evaluation speeds. With this, I record the following instruction counts in the `euler_step_interpolated` function for the first 10 steps:
- Total instruction count 15.0 billion
- `FEPointEvaluation::evaluate` takes 12.7 billion instructions
- `Particle::get_properties()` takes 530 million instructions
- `_Rb_tree_increment` for the multimap: 250 million instructions
- Collection of data in vectors and all other function calls: 260 million instructions
- Instructions spent by code in function: 1.27 billion instructions, of which around 300 million instrs for the update of the particle location via the velocity and another 350 million instrs for setting the properties. Around 500 million instrs are around the call to `_Rb_tree_increment`, which I would count as belonging to the particle iteration, but it is difficult to judge for sure from the assembly code. The remaining instructions are spread around a bit (like `cell->get_dof_values()`), but since they are less than 100 million I would not bother.

Now this would suggest that the iteration is not that critical. However, I also ran the code with timers enabled, which showed the following:
- the `FEPointEvaluation::evaluate` takes around 0.70 seconds across those 10 time steps
- the things I do before this call, notably `cell->get_dof_values()` and the iteration over the particles to extract the reference position and to put the particle iterator into a vector, takes 0.95 seconds
- the things I do after `evaluate`, namely updating the reference location via the velocity and storing the velocity from the stored particle iterators, takes 0.48 seconds

So this is quite different from the instruction counts from callgrind. Given that `FEPointEvaluation::evaluate` works well with caches, we must assume that the remaining code does work as well with the hardware. Since the computations (update particle location, extract dof values, storing some pointers in the vectors and resizing the tensors to the right size are all well-cached, the only item that remains is the iteration over the particles. I believe it is a combination of three topics that make it slow:
- the walk over the iterators does miss caches, which leads to some latency and possible throughput issues in the memory hierarchy
- since the data is spread out in memory, hardware prefetching does not help enough to cover these latencies which walking through the list; we might have this effect also for the properties
- the instruction count for iterating through the data suggests that we spend around 50 instructions per particle, which I think is too much

**Comment by kronbichler** [comment]
As to a data structure, I would suggest someone to report from what is the literature or in lecture material regarding HPC data structures for particles, or to look those up. My limited insight into particles would suggest for the following layout, taking into consideration what @luca-heltai @gassmoeller and @blaisb said above:
- I think all *data* of the particles should be stored in plain arrays like the properties. This data is sorted every `n` time steps to improve data locality, where `n` is at least 20 to 100 iterations through that data (particle time steps).
- All that the particle class contains is an index into those data arrays. No pointers or other stuff, so `sizeof(Particle)==sizeof(unsigned int)` (or maybe 64 bit integer, I don't know if that matters).
- The particles 
- The particle handler further keeps to each cell a list of integer numbers or pointers to those particles. This could be some vector or other array-like container. Given that `Particle` is only 4 bytes, I think it would be cheap to remove and sort those in every step a particle moves from one cell to another.
- Maybe some other global array in the particle handler (or somewhere similarly) that allows to translate from the particle index back to the cell it is located on.

Take this list with a grain of salt as I might be over-simplifying some operations and miss certain aspects of a particle code. My HPC expertise is primarily on other aspects like PDE solvers, but I believe that a scheme like the above would be a good step forward given the considerations above.

**Comment by gassmoeller** [comment]
I agree with all the optimizations you mentioned, and many of them can be done even without changing any algorithms, just by moving stored data from the Particle to the PropertyPool class and reorganizing it into multiple continuous arrays, one for each particle property (one for position. one for each other property). One of the challenges will be that you do not want to move all data just because a single particle in the middle of the arrays has left the local domain. So the PropertyPool would need to keep track of allocated but unowned handles and reuse them for new particles.

I think the critical point for the cost of the iterator increment though will be the third bullet point you mentioned above (which data container to choose for the cell->particle association). Changing this container structure will be the part that requires changes to the other algorithms in ParticleHandler and will require benchmarking of the sort and transfer algorithms. Keeping, e.g., a vector of vectors of particles (for each cell the particles in that cell) is conceptually simple and we should definitely try it if we do not settle on something else, but its speed for different algorithms compared to the multimap is not clear to me. Iteration over particles is certainly faster (although we would need to build some iteration logic into the particle iterator to be able to seamlessly iterate over all cells), searching for a specific cell is also much faster as long as we can index into the outer vector by something like active cell index. But insertion/deletion I can not estimate. It will depend on how reallocation and movement (when a cell vector exceeds its capacity) compares to the data movement happening in a multimap.

**Comment by gassmoeller** [comment]
I gave this some more thought and build a little example benchmark program to test different container structures (gist attached, [particle_benchmark.cc.txt](https://github.com/dealii/dealii/files/5632188/particle_benchmark.cc.txt)). It turns out if we can make the particle class small (in the test `sizeof(particle)` was `sizeof(unsigned int)` as suggested by @kronbichler) then a vector of vectors is uniformly faster than a multimap and it in particular scales better with number of particles per cell, although it is not orders of magnitude, more between 2X and 30X. I also varied the number of cells, but it does not change the relative timings. I tested particle insertion, iteration over particles, and deletion of random particles (randomly 25% of total particles) and implemented all in the most efficient way I could think of for the two containers. Here are the most relevant timings:

1e5 cells, 5 particles per cell (this is closest to my use case in ASPECT):
```
+---------------------------------+-----------+------------+------------+
| Deletion from multimap          |         1 |   0.00719s |        20% |
| Deletion from vector            |         1 |   0.00399s |        11% |
| Insertion into multimap         |         1 |    0.0121s |        33% |
| Insertion into vector           |         1 |    0.0033s |         9% |
| Iteration over multimap         |         1 |   0.00261s |       7.1% |
| Iteration over vector           |         1 |   0.00105s |       2.9% |
| Setup insertion                 |         1 |         0s |         0% |
+---------------------------------+-----------+------------+------------+
```

1e5 cells, 500 particles per cell:
```
+---------------------------------+-----------+------------+------------+
| Deletion from multimap          |         1 |     0.711s |        21% |
| Deletion from vector            |         1 |      0.36s |        11% |
| Insertion into multimap         |         1 |      1.06s |        32% |
| Insertion into vector           |         1 |    0.0534s |       1.6% |
| Iteration over multimap         |         1 |     0.243s |       7.3% |
| Iteration over vector           |         1 |    0.0121s |      0.37% |
| Setup insertion                 |         1 |   0.00143s |         0% |
+---------------------------------+-----------+------------+------------+
```
(I also tested 50 particles per cell which lies in between the other two as expected)

So particle deletion is always twice as fast using the vector, and insertion and iteration are always faster for the vector with increasing margins (2-3X for 5 PPC, ~20X for 500 PPC). Since access is also easier and more intuitive for the vector I would argue we should plan on using that one. Do you agree?

We can probably divide the work into two separate lines: Making the particle class smaller by moving information into the PropertyPool instead, and separately changing the container structure in ParticleHandler and adapting the algorithms accordingly. Maybe we can do this without even changing the interface.

**Comment by kronbichler** [comment]
@gassmoeller these are exciting numbers, thanks a lot for setting up a benchmark and sharing the numbers. So it seems very promising to try with the vector variant. The speedups are really good and better than I anticipated, so I am happy that my idea did work out.

> We can probably divide the work into two separate lines: Making the particle class smaller by moving information into the PropertyPool instead, and separately changing the container structure in ParticleHandler and adapting the algorithms accordingly. Maybe we can do this without even changing the interface.

That sounds like an excellent plan! Count me in on helping to program or review things; however, I have an overly busy schedule for the week in front of me, so I expect substantial efforts first after that.

**Comment by gassmoeller** [comment]
> That sounds like an excellent plan! Count me in on helping to program or review things; however, I have an overly busy schedule for the week in front of me, so I expect substantial efforts first after that.

I took a first step in #11314, but I will be pretty much busy for the next two weeks as well. We can continue then.

**Comment by blaisb** [comment]
> > That sounds like an excellent plan! Count me in on helping to program or review things; however, I have an overly busy schedule for the week in front of me, so I expect substantial efforts first after that.
> 
> I took a first step in #11314, but I will be pretty much busy for the next two weeks as well. We can continue then.

Count me in to help and review also!
I think  your use case (between 5 and 50 particles per cell) is extremely reasonable and should cover a lot of applications. Our case falls exactly into this. Thank you very much for this work!

**Comment by peterrum** [comment]
We have made huge progress regarding the restructuring of the particle infrastructure since the last release. The remainder can be done after the release. Adjusting the milestone.

**Comment by peterrum** [comment]
Can we close this issue? Are we all happy with the new design?

**Comment by kronbichler** [comment]
I think the new design works well, and we made a number of improvements both for the 9.3 release and after that. So from my point of view this can be closed.

**Comment by blaisb** [comment]
Agreed. I think this was nice teamwork. The new design is robust, faster and easier to understand.
The addition of the local index by @kronbichler  also enables  a lot more possibilities in parallel (e.g. storing particle propertie in local vectors instead of putting everything as properties, etc.).

I think we have reached a very mature point here...

**Comment by peterrum** [comment]
Than let's close!
