### ISSUE TITLE
Tensor Basis Transformations

### ISSUE THREAD

**Issue by nmuch** [dealii/dealii#11351]
The `dealii::Physics::Transformations` namspace contrains various push-forward and pull-back methods that use tensor basis transformation functions located in the `dealii::interal::Physics` namespace. These `transformation_contraction` methods are useful and could be move to the non-internal Transformations namespace.

Everything related can be found [here](https://github.com/dealii/dealii/blob/master/include/deal.II/physics/transformations.h)

**Comment by jppelteret** [comment]
Hi @nmuch! Thanks for the suggestion. I think that you'll find that the contravariant push-forward transformation does exactly what you're wanting. The description of this particular set of operations can be found [here in the documentation](https://dealii.org/current/doxygen/deal.II/namespacePhysics_1_1Transformations_1_1Contravariant.html#a99291817612d5b89133747d91b92991a). Would you agree? Here's the [relevant source code](https://github.com/dealii/dealii/blob/master/include/deal.II/physics/transformations.h#L979-L1030), if you want to verify this for yourself. So I don't think that its necessary to expose this internal operation, because there is always the option just to use `Physics::Transformations::Contravariant::push_forward()` even if the input `F` does not represent the deformation gradient tensor, as documented. Do you have a particular application in mind that doesn't fit into the paradigm of push-forward/pull-back transforms?

**Comment by nmuch** [comment]
@jppelteret you are right, `Physics::Transformations::Contravariant::push_forward()` does exactly the same as `dealii::internal::Physics::transformation_contraction()`. In the documentation is specifies F as the deformation gradient tensor but any Basis Matrix works. Maybe that's just a naming thing..

I want to perform a basis transformation on symmetric 4-Tensors. The application is rotating anisotropic structural stiffness tensors into the frame of reference. Implementing a naive basis transformation for that case is painful and using Contravariant push forwad did not attract my attention because of the naming.

**Comment by jppelteret** [comment]
Ok, after hearing the application I agree that moving (and renaming) this function could be useful to a wider audience. Would you like to open a PR for this? (BTW. I recognise that it would find [immediate use in step-18](https://github.com/dealii/dealii/blob/master/examples/step-18/step-18.cc#L1716-L1718).)
