### ISSUE TITLE
fe/mapping_fe_field_real_to_unit_b2_mask failing

### ISSUE THREAD

**Issue by tamiko** [dealii/dealii#1138]
What about this one test that keeps failing on all testing sites? [1]

[1] http://cdash.kyomu.43-1.org/testDetails.php?test=16722329&build=10086

**Comment by bangerth** [comment]
This is discussed in #1025 and is related to #1017. I'm going to close the latter since the synopsis is of that one is now wrong. @luca-heltai and @mtezzele promised a fix.

**Comment by tjhei** [comment]
I looked into it for a few minutes:
The case that fails tries to interpolate from a given FESystemto a FE_Q with different number of components and shape functions using a square interpolation matrix (that needs to be inverted). That won't work of course.

**Comment by luca-heltai** [comment]
I think the issue is the following: interpolation using an *interpolation matrix* do require to invert what in Lagrangian FE is always the Identity Matrix. 

@mtezzele , if we want this to work, we should extract a square matrix corresponding to the masked dofs, invert that, and then copy it back to the rectangular interpolation matrix, with the other dofs set to zero.
