### ISSUE TITLE
AffineConstraints: wrong values after calling distribute using parallel::distributed & hp::DoFHandler

### ISSUE THREAD

**Issue by DominicSoldner** [dealii/dealii#11533]
We encountered some problems for a "growing domain" problem setting, where we have to change (over time) the fe-index of certain cells (from FE-Nothing to FE-Someting). In this small example we reproduce the error as depicted in the three pictures.

In the first step we manually set values for the lower half of the domain (FE_Q(2)) to 1e-5, while the upper half is FE_Nothing (pic_start). We then store for all cells that are NOT FE-Nothing (currently only the lower half) the dof values (1e-5). In a next step we assign the upper half an FE-index which leads to FE_Q(2) instead of FE_Nothing, re-setup everything, write manually values for all dofs of the upper half (2e-5) and eventually use the "stored" values from the lower half using "cell->set_dof_values".

To this point everything works as expected (pic_WAffineConstraints). If we then call the ".distribute" function of AffineConstraints we obtain the result of the third picture (pic_WoAffineConstraints). We saw this also using FE_Q(1) but only for larger problems (still don't know why). In the given example both pictures can be reproduced by solely commenting in/out the call to the distribute function of AffineConstrains in the function "Step4<dim>::reset_dof_values".

Does anyone have an idea what is going on here? 

Your help is much appreciated :) 

Best
![Pic_start](https://user-images.githubusercontent.com/67272040/104598768-41cd4280-5677-11eb-9fc1-b9f8d7fb65eb.jpeg)
![Pic_WoAffineConstraints](https://user-images.githubusercontent.com/67272040/104598856-57426c80-5677-11eb-85fb-5997a5d439b5.jpeg)
![Pic_WAffineConstraints](https://user-images.githubusercontent.com/67272040/104598838-53164f00-5677-11eb-9515-8cda5265abaa.jpeg)

[stepXY.zip](https://github.com/dealii/dealii/files/5814735/stepXY.zip)

**Comment by Rombur** [comment]
Do you have the problem in serial or only with MPI? How many processors do we need to use to reproduce the bug?

**Comment by DominicSoldner** [comment]
I get the same results with MPI using 1,2 and 3 processes

**Comment by Rombur** [comment]
@DominicSoldner There is no bug. The problem is due to visualization. The way visualization tools work is by creating a bunch of triangles and then doing a linear interpolation. This works well for linear finite element but not for higher order. This is way deal.II allows you to "refine" the mesh before output (see [here](https://dealii.org/developer/doxygen/deal.II/classDataOut.html#a5eb51872b8736849bb7e8d2007fae086)). By default, we do not refine mesh before output and this is what you get
![visit0001](https://user-images.githubusercontent.com/368538/104657963-e6f41500-568f-11eb-91aa-0e7f74548444.png)
Now if I refine the mesh, here is what I get 
![visit0000](https://user-images.githubusercontent.com/368538/104657998-f70bf480-568f-11eb-81aa-e671adbe3bb1.png)
This makes a lot more sense. When you apply the constraints, some dofs disappear because their value is set by the coarser cell. Since you have set all these dofs to 2, they propagate to the constrained dofs

**Comment by chburkhardt** [comment]
This is the output I got for FE_Q(2) elements without calling 'constraints.distribute(..)' and using 'build_patches(2)':

![Pic_WoAffineConstraints_BuildPatches2](https://user-images.githubusercontent.com/67148693/104697547-35e18f00-5710-11eb-936f-19a93c2746a1.jpeg)

and this is what I got for the same setting and additionally using 'constraints.distribute(...)'

![Pic_WAffineConstraints_BuildPatches2](https://user-images.githubusercontent.com/67148693/104697975-df288500-5710-11eb-86ca-a8a128866db5.jpeg)

As far as I interpret these results, the problem is not directly due to the 'constrains.distribute(...)' call but happens earlier. The output shows that the dof value of the upper right coarse cell (which is now refined via build_patches(2)) at the hanging node is not overwritten by the 'set_dof_values()' call of the finer cells that share this hanging node. And as @Rombur stated the coarser cells value is then propagated by 'constraints.distribute(..)' to the constrained dof values. 

Is it true that a 'set_dof_value(...)' call for the finer cell at hanging nodes has no influence on the outcome of the constrained dof as long as the hanging node dof value on the coarser cell is not changed, because the 'constraints.distribute(...)' call will always use the value set by the coarser cell?

**Comment by DominicSoldner** [comment]
Yes the coarse cell "wins" (has to) but I don't understand why it does not use the updated nodal values, as they are compressed (insert) after every loop over the cells. Hope this makes sense :). We assumed that once we write the "old" values using set-dof-values, followed by compress, that also the dof-value of the upper cell (for Q2 the "hanging node" is an actual dof coupled to the dof of the two adjecent child cells) would be overwritten.

**Comment by Rombur** [comment]
@DominicSoldner I guess the question is does `set_dof_values` skips the constrained dofs. There are two different `set_dof_values` functions in deal.II one clearly states that it does not set constrained dofs the other (the one you are using) does not say anything. It should be easy to check this: create a second vector and instead of using `set_dof_values` just get the local indices and fill the vector by hand. If the vectors are different then it means that `set_dof_values` skip the constrained dofs and we need to update the documentation.

**Comment by Rombur** [comment]
I finally understand what's going on. I should have reread the hanging node [module](https://dealii.org/developer/doxygen/deal.II/group__constraints.html) earlier...  If you look at the figure of the third bullet point, you see that the coarse cell and the fine cell both have nodal dofs at the same vertex and we use AffineConstraints to ensure that the values are the same. This means that you don't overwrite the new value with the old one. Both exist and AffineConstraints decide which one will overwrite the other. The fact that the figure looks fine for the other points is just luck due to the geometry. If you activate the lower cells instead of the upper ones, you would probably get the wrong result.

**Comment by chburkhardt** [comment]
I took a closer look at the dof indices of the concering cells and the AffineConstraint entries. 

![growing_domain](https://user-images.githubusercontent.com/67148693/105825177-9948a800-5fbf-11eb-9ed3-07fe0a187f88.png)

The dofs highlighted in the red circle exist twice, once on the finer cell side and once on the coarser cell side. The one on the finer cell side is constrained to the one on the coarser cell side via an identity constraint. Every value set from the coarser cell side by <code> set_dof_values(...) </code> will overrule the value one on the finer cell side when calling <code> constraints.distribute(...) </code>  and set it accordingly. This is also in agreement with the corresponding manual entry on <code> [set_dof_values](https://dealii.org/current/doxygen/deal.II/classDoFCellAccessor.html#aab5ad1e494efeff0f3c192874df9ffd2)(...) </code> and basically what @Rombur said. Sorry, but it took me a while to figure out what was going on. 
The workaround we (@DominicSoldner and I) used for our growing domain problem solved that issue for us (while being limited to FE_Q(2) elements) by taking care of the identity constrained dofs.  If one comes to the same issue this might help.
Another possibility is to enforce the same refinement level and the same FE type of the newly activated cells and the old ones. 


[step-4-workaround.txt](https://github.com/dealii/dealii/files/5885829/step-4-workaround.txt)

**Comment by bangerth** [comment]
@Rombur is correct in all his explanations. @DominicSoldner: Do you agree that there is no bug? To me, the pictures look continuous at all nodes, and you should only ever expect the solution to be continuous after calling `distribute()`. (It is true that one *could* eliminate the fine side hanging node here, but we don't have the infrastructure to do that and so use an identity costraint instead.)

If you agree that there is no bug, please close.

**Comment by DominicSoldner** [comment]
@Rombur and @bangerth Yes I totally agree that there is no bug but we got confused. I really appreciate your advise and explanations. Thanks again :).

**Comment by bangerth** [comment]
You're not the first one who got fooled by visualization not faithfully showing what is really happening. It happens so frequently that we wrote a whole FAQ entry about it :-)
https://github.com/dealii/dealii/wiki/Frequently-Asked-Questions#in-my-graphical-output-the-solution-appears-discontinuous-at-hanging-nodes
