### ISSUE TITLE
Generalize global_active_cell_index for p:s:T (without artificial cells)

### ISSUE THREAD

**Issue by peterrum** [dealii/dealii#11860]
Once #11858 is merged, the `global_active_cell_index` functions will also work for p:s:T. However, the info is only available for locally-owned cells and for a single helo of cells. This issue is a reminder to extend the algorithms so that in the case of p:s:T without artificial cells all cells get an appropriate index.

**Comment by marcfehling** [comment]
The following tests rely on this feature:
- `mpi/prepare_coarsening_and_refinement_01.mpirun=4` and `mpi/prepare_coarsening_and_refinement_02.mpirun=4` fail because they rely on this feature.
- `mpi/prepare_coarsening_and_refinement_03.mpirun=4.debug` softlocks.
- `mpi/prepare_coarsening_and_refinement_04` has this check for `p:s:T` disabled right now.

If desired, we can disable the `p:s:T` parts of all these tests like in the last one.

**Comment by peterrum** [comment]
Isn't this fixed by #11901?

**Comment by marcfehling** [comment]
> Isn't this fixed by #11901?

Indeed, it fixed it. I didn't rebase on `master` the last time I ran my testsuite. Sorry about that.
