### ISSUE TITLE
Update comment DoFCellAccessor::get_dof_indices()

### ISSUE THREAD

**Issue by peterrum** [dealii/dealii#11886]
The following comment:

https://github.com/dealii/dealii/blob/e3bd0d963ab5b3a3db2745bd9dfb4a052c616e4a/include/deal.II/dofs/dof_accessor.h#L1837-L1873

seems to be a bit old. What are the plans here?

**Comment by bangerth** [comment]
What specifically do you think is outdated? I must be missing something obvious here :-)

**Comment by peterrum** [comment]
> What specifically do you think is outdated? I must be missing something obvious here :-)

The doxygen comment (which is already a couple of years old) says that the functionality will be depricated. But nothing has happened since than!? What are the current plan here?

**Comment by kronbichler** [comment]
I guess you refer to the case of `get_dof_indices` **called for non-active cells** right? I see no reason why we shouldn't simply raise an exception on that now, given that it has been around for a while. The problem is that we can't show deprecation warnings here, so we must resort to a radical step (which I think we should do now).

**Comment by peterrum** [comment]
OK. I'll submit a PR!
