### ISSUE TITLE
Misleading TriaAccessor::vertex_indices() vs CellAccessor::vertex_index()?

### ISSUE THREAD

**Issue by kronbichler** [dealii/dealii#12336]
Looking at the current interface of the cell accessor classes, I noticed the following:
- The function https://github.com/dealii/dealii/blob/2fd0379961c8fe6b3195795f349c3cccf71aab79/include/deal.II/grid/tria_accessor.h#L1695-L1700 which contains the range of the indices on the local cell, say 0 to 7 for a hex
- The function https://github.com/dealii/dealii/blob/2fd0379961c8fe6b3195795f349c3cccf71aab79/include/deal.II/grid/tria_accessor.h#L2010-L2011 as the singular form of the above, which suggests as if this were the access to one of those entries. However, the numbers are actually the global vertex numbers in the triangulation.

Since the `vertex_indices` function was introduced for the 9.2 release in #10560, I want to quickly confirm if I am the only one disturbed by it. And I also don't have a better solution except for very long names that nobody would use.

**Comment by drwells** [comment]
This tripped me up a few times but I got used to it.

We could rename this to `local_vertex_indices` (and do the same for faces et al) or similar to make it less ambiguous.

**Comment by bangerth** [comment]
Yes, I've also thought that we may not have named these well. It's too bad that these functions are already used all over the tutorial programs.

I don't know how to fix this. I'm not in favor of `local_vertex_indices` because we also use `local_dof_indices` all over the place in the tutorials, even though these are the *global* indices of the DoFs that happen to live locally on the current cell. We could think about renaming these arrays to `global_dof_indices_on_cell` or something in a separate step.

**Comment by kronbichler** [comment]
I don't think we have a good idea immediately, and the release has happened, so I don't see how keeping this open would help us.
