### ISSUE TITLE
Problem in insert_global_particles

### ISSUE THREAD

**Issue by shahabgol** [dealii/dealii#12496]
There is a problem in insert_global_particles used in Lethe-DEM.
An extra particle is inserted at the center or corner of the triangulation (box). This is new and it did not happen using previous versions of deal.II.
So, I tried to find the commit after which this problem appears:
https://github.com/dealii/dealii/commit/870f097bc9ce582dd0a9e738990567256fc228d7
As insert_global_particles has three input arguments (insertion_position, global_bounding_boxes, and particle_properties), I checked these arguments and I believe the problem originates from a change in the mentioned commit in global_bounding_boxes.
@blaisb @gassmoeller @peterrum @kronbichler I would appreciate it if you could help with this issue

**Comment by blaisb** [comment]
A first wild guess, but could it be because of the tolerance parameter that was introduced (https://github.com/dealii/dealii/commit/870f097bc9ce582dd0a9e738990567256fc228d7#diff-e5ceab61fa9d695e5ecb26f3c0b82e9b07ff73103ec6986fbb4c1da577203ee3R1013)
Could this lead to point duplication accross multiple cores?

**Comment by blaisb** [comment]
@shahabgol What I would suggest is that you make a very small executable that reproduces the case you encounter with just a call to insert_global_particles. This way it would be easier to help you identify what is the reason for what is happening. If it related to the tolerance, the solution might just be to pass an additional argument to insert_global_particles that includes the tolerance, if it is something else, then we can at least debug it in a strict deal.II context. :)

**Comment by blaisb** [comment]
After much investigation with @shahabgol and discussion with @peterrum. The issue is that insert_global_particles does not work correctly with the new distributed_compute_point_location when a particle lies **exactly** on a face. In this case, the insertion mechanism will try to insert two particles instead of one, because insert_global_particles assumes a unicity of the cell and this is not coherent with the behaviour of distributed_compute_point_location. @peterrum  had a fix in mind so I'll wait for him :). Otherwise we can modify insert_global_particles to adjust to the behaviour.
