### ISSUE TITLE
Bug in example 68 and 70?

### ISSUE THREAD

**Issue by prashjha** [dealii/dealii#12586]
Hello,

While working out the particle examples, I may have found some bugs (or not). In example 68 (see [line 544](https://github.com/dealii/dealii/blob/d97777ecf7c3e022930e3981d2410e9b977b1475/examples/step-68/step-68.cc#L544)), we have an outer loop over particles and then an inner loop over particles of cells that host outer loop particle. It seems that a particle may be encountered multiple times inside the inner loop due to this design. And therefore multiply accounted particle will have its location updated multiple times. The same issue could affect example 70 (see [line 1457](https://github.com/dealii/dealii/blob/d97777ecf7c3e022930e3981d2410e9b977b1475/examples/step-70/step-70.cc#L1457)).

Does it make sense? Or have I missed something?

Thanks and regards,
Prashant

**Comment by peterrum** [comment]
To me the code looks correct. Let me shortly explain what happens. The goal is loop over all cells that contain particles. One could do this like
```cpp
for(const auto & cell : triangulation.active_cell_iterators())
  {
    if(particle_handler.n_particles_in_cell(cell)==0)
      continue;

    for(const auto & pic : particle_handler.particles_in_cell(cell))
      // TODO
  }
```
However, this code loops over all cell; even if they don't contain any particles. To not have to loop over all cells, we instead loop over all particles and get the corresponding cell. Within the loop over all particles in the cell, we also increment the outer particle iterator.
```cpp
auto particle = particle_handler.begin();
while (particle != particle_handler.end())
  {
    const auto cell = particle->get_surrounding_cell();
    for (auto &p : particle_handler.particles_in_cell(cell))
      {
        // TODO
        ++particle;
      }
}
```
This way, we actually encounter each cell only once (this implementation used to be more efficient than the first one). However, the code makes the implicit assumption that each particle is stored according to its cell owner. @prashjha I hope the explanation makes the logic more clear!

However in the last months, we have rewritten large parts of the internal data structures of the particle infrastructure so that I think the first version should be now as efficient as the second one. If this is the case, I would suggest to rewrite the function in step 68 and 70: the first version is much more readable! @blaisb What do you think?

**Comment by prashjha** [comment]
@peterrum yes it makes sense. I missed the fact that increment ++particle is happening inside inner loop so the advance in particle iterator is accurate. Thanks for the explanation and excellent library.

**Comment by blaisb** [comment]
> To me the code looks correct. Let me shortly explain what happens. The goal is loop over all cells that contain particles. One could do this like
> 
> ```c++
> for(const auto & cell : triangulation.active_cell_iterators())
>   {
>     if(particle_handler.n_particles_in_cell(cell)==0)
>       continue;
> 
>     for(const auto & pic : particle_handler.particles_in_cell(cell))
>       // TODO
>   }
> ```
> 
> However, this code loops over all cell; even if they don't contain any particles. To not have to loop over all cells, we instead loop over all particles and get the corresponding cell. Within the loop over all particles in the cell, we also increment the outer particle iterator.
> 
> ```c++
> auto particle = particle_handler.begin();
> while (particle != particle_handler.end())
>   {
>     const auto cell = particle->get_surrounding_cell();
>     for (auto &p : particle_handler.particles_in_cell(cell))
>       {
>         // TODO
>         ++particle;
>       }
> }
> ```
> 
> This way, we actually encounter each cell only once (this implementation used to be more efficient than the first one). However, the code makes the implicit assumption that each particle is stored according to its cell owner. @prashjha I hope the explanation makes the logic more clear!
> 
> However in the last months, we have rewritten large parts of the internal data structures of the particle infrastructure so that I think the first version should be now as efficient as the second one. If this is the case, I would suggest to rewrite the function in step 68 and 70: the first version is much more readable! @blaisb What do you think?

Agreed. I don't think there an added benefits now to skipping over cells that don't have particles because from my understanding, the new vector data structure is faster to access than the previous multimap. If you want I can make a PR to address that for next release.

**Comment by kronbichler** [comment]
I would add that the increment function of the particle accessor related to second variant of the code above also steps through all cells and thus, there would be no performance difference, see the code here: https://github.com/dealii/dealii/blob/d97777ecf7c3e022930e3981d2410e9b977b1475/include/deal.II/particles/particle_accessor.h#L771-L779

**Comment by peterrum** [comment]
> If you want I can make a PR to address that for next release.

Sounds good. In the meantime, let's close the issue.
