### ISSUE TITLE
Missing identity constraints in 3D.

### ISSUE THREAD

**Issue by marcfehling** [dealii/dealii#12626]
When calling `DoFTools::make_hanging_node_constraints` on an hp-adapted mesh in 3D, it may happen that not all identity constraints are recognized. See this [tests/hp/identity_constraints_02](https://github.com/dealii/dealii/blob/master/tests/hp/identity_constraints_02.cc) and its corresponding [output](https://github.com/dealii/dealii/blob/master/tests/hp/identity_constraints_02.output).

Dof identities on any mesh object will only be recognized it the dof is actually present on the most dominating element on this mesh object. This is not always the case for lines in 3D, which can have more than two different FEs assigned to them.

For example, if a line has Q1, Q2, and Q4 elements assigned, the central dof of both Q2 and Q4 elements will not be treated by an identity constraint because the dominating Q1 element has no such dof. The identity will be recognized however if that line would have Q2, Q3, and Q4 elements assigned for example.

Further, we do not unify dofs on lines in 3D, so dof duplicates have to be treated by identity constraints. We need to adjust the algorithm so that we identitfy _all_ constraints.

Bug found in #12623. See description for more information.
@bangerth -- FYI

**Comment by bangerth** [comment]
Yes, for unification we need to implement all pairwise comparisons. I think I know how to do that. For constraints, we probably need to do things in a hierarchy. I think I know how to do that as well, but that's going to be more work.

This is indeed a bug: The solution will not actually be continuous on these sorts of lines. I suspect that the effect is relatively minimal in practice because few people will have been computing in 3d with hp. @marcfehling Let's put this onto the list of things we want to address for 10.0, but let's not hold up the work on the paper if we can.
