### ISSUE TITLE
Timoshenko beam elements

### ISSUE THREAD

**Issue by j8asic** [dealii/dealii#12653]
Does deal.ii support 1D beam elements (Timoshenko, or at least Euler-Bernoulli) in 3D space?

**Comment by drwells** [comment]
No, we do not - elements for beams, AFAIK (it's not the kind of solid mechanics I do) require continuous derivatives (since the original equation has four derivatives and we integrate by parts twice) and we do not presently implement any elements like that in deal.II. We do support 1D elements in 3D but not any with continuous derivatives.
