### ISSUE TITLE
manifold_id set wrong for simplices

### ISSUE THREAD

**Issue by richardschu** [dealii/dealii#12689]
Hi everyone,
I might have found a bug (or my use of manifolds is not intended):
When creating a simplex mesh and attaching a manifold to _only some, but not all_ cells, may create 'holes'.
My testcase is a circular disc with a circular inclusion, assigning a `SphericalManifold` based on `cell->material_id()` here shown with a quad mesh:
![quad](https://user-images.githubusercontent.com/69867655/130238999-2223bf33-d156-4227-9571-f1c9675cae67.png)

So far so good, but when I use triangles instead of quadrilaterals and proceed as before, triangles on the inner interface are not curved as can be seen here (including the quad mesh as a white `wireframe` from above as reference):
![tri](https://user-images.githubusercontent.com/69867655/130239234-15e6911e-7018-4b40-b8b7-894350b2c679.png)

The cells, where I assigned the manifold are mapped correctly, but the triangles have a default `FlatManifold` it seems, leading to holes. This mesh is not produced in debug mode, since in that case the code stops with
`The violated condition was: 
    check_all_manifold_ids_identical(cell)
Additional information: 
    All entities of a cell need to have the same manifold id as the cell has.`
which is why I assume the manifold_id from the outer ring is not correctly communicated at the interface? Why does this work with quads then?
A MWE with the .msh files is attached:
[circ_inclusion.txt](https://github.com/dealii/dealii/files/7021741/circ_inclusion.txt)
[circ_inclusion_simplex.txt](https://github.com/dealii/dealii/files/7021742/circ_inclusion_simplex.txt)
[conv_hex_to_simplex.txt](https://github.com/dealii/dealii/files/7021844/conv_hex_to_simplex.txt)

I would be glad if you could take a look - if I can be of any help, please let me know ; )
Have a nice weekend & greetings from Graz!

**Comment by peterrum** [comment]
`MappingFE` works currently only for a single manifold, since the following lines of code are not as general as in the `MappingQ` case:

https://github.com/dealii/dealii/blob/208d70583f97a62e976bc007e6e099aa6c79dd1b/source/fe/mapping_fe.cc#L2277-L2300

vs.

https://github.com/dealii/dealii/blob/208d70583f97a62e976bc007e6e099aa6c79dd1b/source/fe/mapping_q.cc#L1678-L1773

At the moment, the cell (manifolds) creates all new support points (this is why ` All entities of a cell need to have the same manifold id as the cell has.` is checked). Instead, the cell should only create the support points inside of the cell and the rest should be generated by the line and face manifolds. The additional complexity - compared to MappingQ - is that the code needs to be general and to work for all types of cell types: even for simplex, wedges, and pyramids. When I have extended the `MappingFE` class so that it can be of higher order back in January, I didn't find a quick solution for that. But @richardschu if you would be willing to work on this, I would be happy to help you to get started!

**Comment by richardschu** [comment]
Thanks for the clearification - I will start off by reading the `geometry paper` (https://arxiv.org/abs/1910.09824) and then try to understand the implementation in `MappingQ`. Would you say that the needed adaptions are limited to `compute_mapping_support_points`? At least for simplices I should be able to implement the needed changes, I guess!

**Comment by peterrum** [comment]
> Would you say that the needed adaptions are limited to compute_mapping_support_points?

Yes and the setup of the interpolation matrices: 

https://github.com/dealii/dealii/blob/208d70583f97a62e976bc007e6e099aa6c79dd1b/source/fe/mapping_fe.cc#L864-L871

Let me quickly explain what `compute_mapping_support_points()` (currently) does. It first reads the points of the vertices and computes the new support points by transforming the reference points returned by `get_unit_support_points()` to real space using the manifold attached to the cell.

What actually would be needed to be done is to use the correct manifold for the new points lying on lines and faces. I am not sure how you can identify if a point lies on a line/face or on which one (but I guess one could hardcode it for now and use a dynamic cast) but to get the surrounding vertex indices you can use:
 
https://github.com/dealii/dealii/blob/44b6aadb35aca2333e4bfb6c9ce29c613f4dc9e9/include/deal.II/grid/connectivity.h#L177-L230

and the classes below. 

Short: instead of one interpolation, one needs to perform multiple interpolations: first over all lines, after that over all faces, and finally over the cell (if there is a new support point in the inside - as in the case of a wedge).

**Comment by peterrum** [comment]
@luca-heltai

**Comment by bangerth** [comment]
What should we do here in view of the release coming? Can this be fixed within the next week?

**Comment by richardschu** [comment]
I planned to work on this finally after handing in my thesis - so, mid July. I did not look further into this issue since I did not need it for my own work though!

**Comment by kronbichler** [comment]
Let us move the milestone then, we need to live with the current behavior.

**Comment by kronbichler** [comment]
@richardschu I assume this is not something we fix for the next two weeks, so I'm adjusting the target milestone.
