### ISSUE TITLE
constant_modes for PreconditionAMG

### ISSUE THREAD

**Issue by gfcas** [dealii/dealii#12854]
For our multiphysics application problem, we would like to use the exact functionalities of tutorial step-46 (hp+FE_Nothing) but with p:d:Tria+Trilinos and solve the linear system with GMRES+AMG. While rewriting the tutorial step-46 to test the functionalities, we encountered the following problem:

The AMG preconditioner does not work so well. As a first step, we made it work by renumbering the system component wise, increasing the number of cycles, and also increasing the number after the GMRES restarts.

We think, that we have to tell the AMG preconditioner somehow the vector-components. Therefore we found the ``constant_modes``. However, we can't get the constant modes for the ``FESystem`` containing an ``FE_Nothing`` object because there is no function in ``FE_Nothing`` that overloads the ``get_constant_modes()`` function of the ``FiniteElement`` class.

I haven`t looked at this in more detail, but would there be a simple solution to this problem? Quite naively, I would have set the entries for this component to null or not at all, since FE_Nothing does not distribute DOFs.

At least the ``TrilinosWrappers::SolverDirect`` works, but should not be the final solver.

**Comment by sebproell** [comment]
I just ran into the same issue with `FE_Nothing`. Actually my code works in release mode since the asserts are not triggered. The computed `constant_modes` provided to AMG seem to reduce iterations in my linear solver. Thus, I wonder if there is an easy fix for the case of `FE_Nothing`. I guess the constant modes of FE_Nothing should return an empty Table. `DoFTools::extract_constant_modes` already seems to skip cells w/o any dofs anyway, so it may only be a matter of adapting the asserts. I will see if I can make it work locally.

**Comment by gfcas** [comment]
Thanks @sebproell for your patch in #13313. Now I had the time to test the patch for my problem. Unfortunately this patch does not cover my application case. Did it solved your problem?

**Comment by sebproell** [comment]
@gfcas Yes, it solved my problem, which uses FE_Q and FE_Nothing.
