### ISSUE TITLE
Support for Kokkos in deal.II

### ISSUE THREAD

**Issue by Rombur** [dealii/dealii#12894]
In PR https://github.com/dealii/dealii/pull/12821, we have talked about using Kokkos inside deal.II. Before we do this, there are a couple of things we should decide:
 - where we will use Kokkos: just to replace CUDA? everywhere?
 - what the interface should look like?

Where to use Kokkos
-------------------
While I don't think we need to use Kokkos everywhere, I am also against limiting the use of Kokkos to the CUDA code that we have now. Sure we would gain the ability to run the current CUDA code on all the different GPUs but we could do the same with OpenMP target and we wouldn't need an extra dependency. An example of code benefiting from using Kokkos is LinearAlgebra::distributed::Vector. Using Kokkos would simplify some of the implementation. Obviously, we would not touch the vectorization code but there is a lot of code that could be simplified. There are other places that could benefit from running on the GPU. For example, Tensor partially supports CUDA so this could be extended. Obviously the changes will be very incremental and we will start with the CUDA code but I think it would be good to think where using Kokkos is acceptable and where it will not be allowed.

Interface
---------
Kokkos has the concept of MemorySpace and ExecutionSpace. The MemorySpace is where the memory is allocated: on the host, using cudaMalloc, using cudaMallocManaged, etc. The ExecutionSpace is how we are going to perform operations: in serial, using OpenMP, using std::thread, etc. Some of the combinations of MemorySpace/ExecutionSpace are not compatible (you cannot allocate memory on the host and then, use it in a CUDA kernel). If we take for example LA:d::Vector, we go from 
```c++
template<typename Number, typename MemorySpace = MemorySpace::Host>
class LinearAlgebra::distributed::Vector<Number, MemorySpace>
```
to
```c++
template<typename Number, typename MemorySpace = Kokkos::HostSpace, typename
ExecutionSpace = Kokkos::DefaultHostExecutionSpace>
class LinearAlgebra::distributed::Vector<Number, MemorySpace, ExecutionSpace>
```
In this case, the default host execution space is one chosen by Kokkos which depends on which backends were enable when compiling Kokkos. Each ExecutionSpace in Kokkos has an associated default MemorySpace. Therefore, another possible interface would look like:
```c++
template<typename Number, typename ExecutionSpace = Kokkos::DefaultHostExecutionSpace>
class LinearAlgebra::distributed::Vector<Number, ExecutionSpace>
```
Similarly, each MemorySpace in Kokkos has a default ExecutionSpace. So the following would also be a valide interface:
```c++
template<typename Number, typename MemorySpace = Kokkos::HostSpace>
class LinearAlgebra::distributed::Vector<Number, MemorySpace>
```
Kokkos has also default MemorySpace/ExecutionSpace and thus we could write
```c++
template<typename Number>
class LinearAlgebra::distributed::Vector<Number>
```
However this means that if you compile Kokkos with CUDA support, LA:d::Vector will only work on the GPU. You won't be able to use it on the host unless you recompile Kokkos not to have GPU support.

There are other things that we should decide. I will keep with the LA:d::Vector example but this does not mean it is limited to that case. Let's say that you add two vectors. What do we do if the MemorySpace is different? What do we do if the ExecutionSpace is different? Should the  `add` function be able to use a different ExecutionSpace than the rest of the class. There is one more thing about the ExecutionSpace. If you want to use things like CUDA streams or have the code asynchronous, you have to create one or multiple ExecutionSpace objects and pass them around. Should the constructor accepts ExecutionSpace object? Should `add` accepts one?

I went in a lot (too much?) of details so that everybody is aware of all the possible choices. My preference for the interface would be the following:
We template the classes only on the ExecutionSpace or the MemorySpace. I haven't encountered a case where I really wanted to control both the MemorySpace and the ExecutionSpace. The question is then what you want to control. If we template on the ExecutionSpace, the user controls if the code is run in serial or using OpenMP but they cannot control the use of CUDA UVM versus CUDA. They cannot use host pinned memory. If the user controls the MemorySpace, they will be able to control CUDA UVM versus CUDA but they won't be able to control Serial versus OpenMP. I slightly prefer the template on the MemorySpace because the MemorySpace controls compatibility with external libraries that don't use Kokkos. I'm also of the opinion that objects should only works with objects using the same MemorySpace and we should forget everything about the ExecutionSpace objects for streams or asynchronicity. These objects would clutter the interface for a capability that few people will require.

Potential problems
------------------
- Build system: integrating Kokkos in our build system may not be straightforward when we enable CUDA.
- Trilinos: Trilinos snapshots Kokkos and does not allow to use an external version of Kokkos. The interaction of Kokkos in our code and in Trilinos may be straightforward or ugly. I have not clue.

More info on Kokkos
-------------------
https://github.com/kokkos/kokkos-tutorials
https://github.com/kokkos/kokkos/wiki

**Comment by masterleinad** [comment]
> While I don't think we need to use Kokkos everywhere, I am also against limiting the use of Kokkos to the CUDA code that we have now. Sure we would gain the ability to run the current CUDA code on all the different GPUs but we could do the same with OpenMP target and we wouldn't need an extra dependency. An example of code benefiting from using Kokkos is LinearAlgebra::distributed::Vector. Using Kokkos would simplify some of the implementation. Obviously, we would not touch the vectorization code but there is a lot of code that could be simplified. There are other places that could benefit from running on the GPU. For example, Tensor partially supports CUDA so this could be extended. Obviously the changes will be very incremental and we will start with the CUDA code but I think it would be good to think where using Kokkos is acceptable and where it will not be allowed.

I think the main intent is to use `Kokkos` in all the places where we are currently using `Cuda`, i.e. for `LA::distributed::Vector`  and `MatrixFree`. I would leave the CudaWrappers preconditioners, matrices and vectors, though, since they most of them are calling `CUDA`-spedific functions that are not easily replaceable by `Kokkos`. Also note that `Tpetra` should provide aternatives that are portable.
I don't think that we should use `Kokkos` in our own Matrix classes or the CPU-MatrixFree implementation.


Regarding the interface for `LinearAlgebra::distributed::Vector` I would go with
> template<typename Number, typename MemorySpace = Kokkos::HostSpace, typename
ExecutionSpace = typename MemorySpace::execution_space>
class LinearAlgebra::distributed::Vector<Number, MemorySpace, ExecutionSpace>

(or templating on `Kokkos::Device`) In my opinion, it's enough to provide the memory space and an execution space can also be provided if desired.

> Let's say that you add two vectors. What do we do if the MemorySpace is different? What do we do if the ExecutionSpace is different? Should the add function be able to use a different ExecutionSpace than the rest of the class. There is one more thing about the ExecutionSpace. If you want to use things like CUDA streams or have the code asynchronous, you have to create one or multiple ExecutionSpace objects and pass them around. Should the constructor accepts ExecutionSpace object? Should add accepts one?

For adding vectors I would just resort to the two-argument variant of  `Kokkos::deep_copy` (at least initially). I think we can add support for execution space instances later.

**Comment by bangerth** [comment]
The regular `Vector` and `SparseMatrix` classes have plenty of uses of `parallel_for` loops that we currently map onto the TBB but that could just as well use Kokkos functionality. It would be relatively easy to do that there.

Restricting the interface to only selecting memory space or execution space seems reasonable to me. If we don't currently foresee a need to mix and match different execution and memory spaces, then let's not offer it for now. If someone discovers a compelling use case, we can always reconsider -- though at least past experience seems to suggest that that might not be likely. But I'm also ok with @kronbichler 's suggestion of keeping both as template arguments and simply defaulting the execution space to the execution space associated with the memory space.

I have one suggestion, though: Instead of defaulting the (execution or memory) space to whatever Kokkos was configured for, could we just always select the CPU as the default? We're never going to port the entire code base to GPUs, and so I see little value in choosing a default that depends on a cmake flag when Kokkos was configured. I'd much rather default to CPU and if a user wants something different, then they need to say so in the code (and not at configuration time). This way, the *code* is the only normative place for what is happening, and cmake is the normative place for what is allowed in the code. This seems to match deal.II's behavior in other places with the possible exception of 64-bit indices.

**Comment by bangerth** [comment]
For those of you who know Kokkos, have the things mentioned here been addressed? Can we close this issue?

**Comment by Rombur** [comment]
We can close this. I don't think there is a point in keeping this issue open any longer
