### ISSUE TITLE
Run source files through doxygen as well

### ISSUE THREAD

**Issue by thingishness** [dealii/dealii#1303]
It would be useful to have the documentation link to the source code at the end of each function description so a user can review the source code for more information.

**Comment by bangerth** [comment]
#1356 implements this for the most part. I've looked through a bunch of class pages and almost all functions indeed have a link to their implementation. The exception being `Triangulation` where doxygen appears to have missed all links into `tria.cc` -- almost excusable, since real men have gotten lost many times in that file before as well.
