### ISSUE TITLE
Compilation Error when Combining IteratorFilter with FEInterfaceValues

### ISSUE THREAD

**Issue by simonsticko** [dealii/dealii#13169]
The code below uses an iterator filter together with `FEInterfaceValues` but gives a rather unexpected compilation error with gcc 10.3.0. I don't understand if the problem is with the filter, the `reinit` function or the compiler.

```c++
#include <deal.II/base/quadrature_lib.h>

#include <deal.II/dofs/dof_handler.h>

#include <deal.II/fe/fe_interface_values.h>
#include <deal.II/fe/fe_q.h>

#include <deal.II/grid/filtered_iterator.h>

using namespace dealii;

int
main()
{
  const int dim = 2;

  const FE_Q<dim>       fe(1);
  const QGauss<dim - 1> quadrature(1);

  FEInterfaceValues<dim> fe_interface_values(fe, quadrature, update_default);


  DoFHandler<dim> dof_handler;
  for (const auto &cell : dof_handler.active_cell_iterators() |
                            IteratorFilters::ActiveFEIndexEqualTo(0))
    {
      const unsigned int invalid_subface = numbers::invalid_unsigned_int;
      const unsigned int face_index      = 0;

      fe_interface_values.reinit(cell,
                                 face_index,
                                 invalid_subface,
                                 cell->neighbor(face_index),
                                 cell->neighbor_of_neighbor(face_index),
                                 invalid_subface);
    }
}
```
Compilation error:
```
[ 50%] Building CXX object CMakeFiles/example.dir/example.cc.o
In file included from /home/simon/workspace/sandbox/example.cc:8:
/home/simon/bin/dealii/include/deal.II/grid/filtered_iterator.h: In instantiation of ‘bool dealii::FilteredIterator<BaseIterator>::PredicateTemplate<Predicate>::operator()(const BaseIterator&) const [with Predicate = dealii::TriaIterator<dealii::DoFCellAccessor<2, 2, false> >; BaseIterator = dealii::TriaActiveIterator<dealii::DoFCellAccessor<2, 2, false> >]’:
/home/simon/bin/dealii/include/deal.II/grid/filtered_iterator.h:1343:1:   required from here
/home/simon/bin/dealii/include/deal.II/grid/filtered_iterator.h:1346:19: error: no match for call to ‘(const dealii::TriaIterator<dealii::DoFCellAccessor<2, 2, false> >) (const dealii::TriaActiveIterator<dealii::DoFCellAccessor<2, 2, false> >&)’
 1346 |   return predicate(bi);
      |          ~~~~~~~~~^~~~
make[2]: *** [CMakeFiles/example.dir/build.make:82: CMakeFiles/example.dir/example.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:95: CMakeFiles/example.dir/all] Error 2
make: *** [Makefile:103: all] Error 2
```

**Comment by jppelteret** [comment]
Hi @simonsticko. I'm busy looking at this in #13170. You're right that there's a problem here, and its a subtle one. The issue here is that `cell` and `cell->neighbor()` do not return the same *type* of iterators. You can see this by dropping in a few extra lines of code:
```c++
  for (const auto &cell :
       filter_iterators(dof_handler.active_cell_iterators(),
                        IteratorFilters::ActiveFEIndexEqualTo(0))) // or using operator|
{
          const auto cell_neighbor = cell->neighbor(face_index);

          using C1 = typename std::decay<decltype(cell)>::type;
          using C2 = typename std::decay<decltype(cell_neighbor)>::type;
          static_assert(std::is_same<C1, C2>::value,
                        "Cell iterator types are not identical.");
}
```
In the test that I setup based off of what you provided here (thanks, btw.), `C1` is  a `dealii::FilteredIterator<dealii::TriaActiveIterator<dealii::DoFCellAccessor<3, 3, false> > >` while `C2` is of type `dealii::TriaIterator<dealii::DoFCellAccessor<3, 3, false> >`. I'm going to try to try to use the [`identity`](https://www.dealii.org/developer/doxygen/deal.II/structidentity.html) struct to decouple the iterator types, as we do in `mesh_loop()` and other places.

**Comment by jppelteret** [comment]
> I'm going to try to try to use the [`identity`](https://www.dealii.org/developer/doxygen/deal.II/structidentity.html) struct to decouple the iterator types, as we do in `mesh_loop()` and other places.

Actually, this is done and (having thought about it for 5 seconds longer) wouldn't be the right thing to do anyway. We likely need to introduce a second iterator type to this `FEInterfaceValues::reinit()` method.

**Comment by bangerth** [comment]
Yes, the problem is that with filters, the type is some `FilteredIterator<X>` type, which is convertible to `X` but not anything else. In the example, `X` is an *active cell iterator*, whereas the thing you want to compare it against is a `Y` = *iterator, not necessarily active*. 

I'm not entirely sure how to work around this. It's definitely a flaw in the system right now.
