### ISSUE TITLE
p4est installation script cannot find `p4est_config.h` file, causing compilation error

### ISSUE THREAD

**Issue by lucasmyers97** [dealii/dealii#13194]
In the dealii p4est installation instructions located [here](https://dealii.org/current/external-libs/p4est.html), the installation script does not work quite right (perhaps because p4est has updated their directory structure). Hence, when run it throws an error that it cannot find `p4est_config.h`, and later that p4est did not get built with zlib support. The error is caused by lines 125 and 142 of [p4est-setup.sh](https://dealii.org/current/external-libs/p4est-setup.sh). 

To fix it, I replaced `$BUILD_FAST/src/p4est_config.h` with `$BUILD_FAST/config/p4est_config.h`, and the same for the `$BUILD_DEBUG` line. Not sure how to suggest a change to the documentation, or whether there needs to be some cleverness with version checking to leave the setup script how it is for older versions, and change it for newer versions.

**Comment by marcfehling** [comment]
You are using an old version of the installation script. Try using this one [p4est_setup.sh](https://dealii.org/developer/external-libs/p4est-setup.sh).

This should have been fixed in #12426. Let us know if the new script works.

Might be worth considering to mark the patch #12426 for a potential new point release?

**Comment by lucasmyers97** [comment]
Yup, works perfectly, thanks for the update!
