### ISSUE TITLE
Pytrilinos fail during test

### ISSUE THREAD

**Issue by VictorEijkhout** [dealii/dealii#13383]
```
/usr/bin/gmake  -f tests/quick_tests/CMakeFiles/step.release.run.dir/build.make tests/quick_tests/CMakeFiles/step.release.run.dir/build
gmake[7]: Entering directory '/tmp/dealii-build'
cd /tmp/dealii-build/tests/quick_tests && /tmp/dealii-build/tests/quick_tests/step.release > step.release-OK 2>&1 || ( echo step.release:\ RUN\ failed.\ Output: && cat step.release-OK && rm step.release-OK && exit 1 )
step.release: RUN failed. Output:
/tmp/dealii-build/tests/quick_tests/step.release: symbol lookup error: /scratch/tacc/apps/intel19/impi19_0/trilinos/13.0.1/lib/libpytrilinos.so.13: undefined symbol: PyObject_GenericGetAttr
```

This is not fatal so I'm letting it slide. Is this dependent on the trilinos version?

**Comment by drwells** [comment]
`PyObject_GenericGetAttr` is a part of the [python API](https://docs.python.org/3.10/c-api/object.html#c.PyObject_GenericGetAttr) - it looks like `libpytrilinos` is underlinked. We do not use PyTrilinos, so this failure is unrelated to any configuration of our own python bindings.

There's nothing that we can change on our end to fix this so I am going to close this issue. For what it's worth, I personally have always disabled pytrilinos on my machines since I frequently run into this or other issues with the package. The Trilinos dependencies we use are documented [here](https://www.dealii.org/current/external-libs/trilinos.html).
