### ISSUE TITLE
Does MatrixFree::initialize_dof_vector() set vector entries to zero?

### ISSUE THREAD

**Issue by nfehn** [dealii/dealii#13480]
If I see it correctly, I could not find this information in the documentation, see 
https://www.dealii.org/developer/doxygen/deal.II/classMatrixFree.html#a6389c1e91648d277bdd81af095b5296c

**Comment by kronbichler** [comment]
Yes, it does, because the function calls https://github.com/dealii/dealii/blob/baf78cb810d186296f083aa0c464c6a88aaaba6d/include/deal.II/matrix_free/matrix_free.h#L2266-L2267 which in turn does https://github.com/dealii/dealii/blob/baf78cb810d186296f083aa0c464c6a88aaaba6d/include/deal.II/lac/la_parallel_vector.templates.h#L661-L662
Do you want to add this information to the documentation here:
https://github.com/dealii/dealii/blob/baf78cb810d186296f083aa0c464c6a88aaaba6d/include/deal.II/matrix_free/matrix_free.h#L1525-L1547
