### ISSUE TITLE
doxygen: Simplex tags move functions from namespace

### ISSUE THREAD

**Issue by tjhei** [dealii/dealii#13509]
The function ``GridIn::read_msh()`` (and probably others), are part of the "simplex support page" but they also got removed from the GridIn namespace:
https://www.dealii.org/developer/doxygen/deal.II/classGridIn.html
(click on ``read_msh`` on that page or search for ``read_msh``)

I think ``@ingroup simplex`` is to blame. We should try if ``@relates`` or ``@relatesalso`` works better.

**Comment by bangerth** [comment]
Yes, a function can only be in one group.

Broader question: Should we just remove the "simplex" tag? At this point, simplices are known to work well, they're no longer special.

**Comment by tjhei** [comment]
If the simplex group is complete and not out of date, I think it still useful information. How do I discover if simplices are supported for some function/class X? I don't think we document "works with simplices" in the text. Then having the tag is useful.
@peterrum ?

**Comment by peterrum** [comment]
> At this point, simplices are known to work well, they're no longer special.

Do we!? Nice to hear that it works for you!

> If the simplex group is complete and not out of date, I think it still useful information. How do I discover if simplices are supported for some function/class X? I don't think we document "works with simplices" in the text. Then having the tag is useful. @peterrum ?

I also think a tag would be nice as long as we state that the simplices are experimental and we don't have tutorials!

**Comment by bangerth** [comment]
On 3/9/22 12:54, Peter Munch wrote:
>     At this point, simplices are known to work well, they're no longer special.
> 
> Do we!? Nice to hear that it works for you!

Absolutely. I had to write a good number of patches about half a year ago to 
support one application, but I built a whole industry project on it and it 
works just fine.

I'm sure there are a million other places that are still in need of updating, 
but I'd say that overall, simplices work just fine.


>     If the simplex group is complete and not out of date, I think it still
>     useful information. How do I discover if simplices are supported for some
>     function/class X? I don't think we document "works with simplices" in the
>     text. Then having the tag is useful. @peterrum <https://github.com/peterrum> ?
> 
> I also think a tag would be nice as long as we state that the simplices are 
> experimental and we don't have tutorials!

The problem is that that list isn't up to date. We've fixed a lot of places 
over time where a function implicitly assumed hypercube cells and now no 
longer does, but we didn't update the documentation. Have a module gives the 
impression that whatever is listed there is all that currently supports 
simplices, but that's not actually the case.

**Comment by peterrum** [comment]
> For the moment, the page has example code that is useful, so it might be good to keep it.

-> https://github.com/dealii/dealii/pull/11581
