### ISSUE TITLE
For load balancing, should weights of cells be of type `double`?

### ISSUE THREAD

**Issue by marcfehling** [dealii/dealii#13555]
As suggested in [#13451](https://github.com/dealii/dealii/pull/13451#pullrequestreview-916094344):

> [...][W]hat about changing the return type from unsigned int to double? I really find annoying and error prone that one has to multiply by 100 to be able to make distinguishing in the range of percentage possible!

`p4est` requires signed 32-bit integers as weights for each quadrant. I don't know right now what other partitioners like Zoltan or Metis require. But we could switch to `double` on our side, and convert the values to whatever the external partitioners require.

As we deprecate the old weighting signal in #13451, we should discuss the possibility of changing the datatype before the next release.

**Comment by tjhei** [comment]
How would you do the conversion to double without knowing the range of values used?

**Comment by bangerth** [comment]
Let's not do as suggested. `GridTools::partition()` and `SparsityTools::partition()` also take `unsigned int` weights per cell, and that is (historically) because METIS uses `signed int` as a cell weight and we just adjusted the signedness. (We don't currently support weighting with Zoltan, see #7315, but I believe that Zoltan wants floating point weights.)

As @tjhei pointed out, we cannot easily convert from `double` to some kind of integer type because it is not easy to figure out how to scale the former into the range of the latter. (I think he meant "from double" instead of "to double".)

**Comment by marcfehling** [comment]
I also do not like floating point values for this matter.

Let's close this issue.
