### ISSUE TITLE
I want to develop a spectral element code based on the dealii, what is your suggestions?

### ISSUE THREAD

**Issue by ztdepztdep** [dealii/dealii#13588]
I want to develop a spectral element code based on the dealii, what is your suggestions?
which tutorial should i study first.

**Comment by drwells** [comment]
If you want to use spectral elements then you should look at the matrix-free solvers, since they typically use higher approximation orders. In particular, step-66 solves a Cahn-Hilliard problem and step-67 solves a hyperbolic evolution problem.

There are more people on the mailing list with expertise on these subjects than here in the issue tracker - if you have more questions that place is a much better resource than the issue tracker.

Since this isn't about an issue with the library I will go ahead and close this.
