### ISSUE TITLE
How to visualize .vtu files from step-79? What software would be suitable?

### ISSUE THREAD

**Issue by CODER591** [dealii/dealii#13619]
Hello, currently I am trying to visualize the step-79 from examples.

I have built the  example locally, and have visualized the .stl file.
Also I have installed Visit(latest version) to visualize those generated .vtu files(as was referred to step-22), but I am seeing white screen, seems it cant process that file
I am not sure what software to use to see the intermediate parts of that topological optimization process.

I have searched for the .vtu visualization tutorial, but have found nothing.

Thanks!

**Comment by drwells** [comment]
You should be able to plot the density in VisIt and get something like this:

![visit0000](https://user-images.githubusercontent.com/3917035/163573508-56da84a2-1270-4fc0-81ef-8386dd72c6de.png)

One possible problem is that STL is a 3D format and the VTU files generated by deal.II here are 2D, and VisIt cannot load both 2D and 3D files at the same time. Since this isn't an issue with the library I'm going to go ahead and close this issue.

If this still doesn't work for you, could you please post this again on the mailing list? Thanks!

**Comment by CODER591** [comment]
Everyting is OK with Visit.

Heh, seems I have figured out why I have seen the blank page.
I should`ve add some options to left window.
![image](https://user-images.githubusercontent.com/33939665/164337313-218aaab4-b9c6-45e6-bd36-a5703a52b5de.png)

Could you share screenshot of your left window(share all settings)?
