### ISSUE TITLE
Improve locally_relevant_dofs for DoFHandler(parallel::shared::Triangulation)

### ISSUE THREAD

**Issue by davydden** [dealii/dealii#1368]
https://github.com/dealii/dealii/pull/212 introduced parallel shared triangulation. 
Currently a DoFHandler object built upon this triangulation as locally relevant dofs returns an IndexSet with all DoFs [0, n_dofs()), which is clearly not efficient. 

I think the following steps are to be done:

1. Introduce a function which returns 1-cell thickness layer surrounding cells with given quality (e.g. subdomain_id() == X). @jppelteret Jean-Paul already does this inside his continuum-mechanics code, but for active_fe_index(), as far as I recall. Hopefully this can be generalised with some lambda-function tricks.

2. Introduce another function which uses (1) to create a proper IndexSet for locally_relevant_dofs. 

3. Use (2) inside `distribute_dofs()` (around https://github.com/dealii/dealii/blob/master/source/dofs/dof_handler_policy.cc#L972) and in `renumber_dofs()` to update the NumberCache.

**Comment by bangerth** [comment]
Actually, I think the current behavior (of marking *all* DoFs as locally relevant) is correct -- and useful, if one doesn't want to ship data around all the time, you can just keep a global vector where everything is a ghost.

My preference would be to tackle this in a different way: Let `parallel::shared::Triangulation` take a flag at construction time that decides between the following two options:
* Mark all cells with their correct subdomain id (as is done right now, leading to all cells either being locally owned or ghost).
* Mark only one layer of cells around the locally owned cells with their correct subdomain id (the remaining ones then becoming artificial). This would require throwing subdomain ids away from cells for which we don't want to know this information.

If you chose the latter case during construction of the triangulation, then `DoFTools::locally_relevant_dofs()` will simply ignore the artificial cells and do what you want.

**Comment by davydden** [comment]
agree. That would still require some function like (1) above to get that one layer of cells. I would say it is still useful to have it outside of DoFHandler class.

**Comment by bangerth** [comment]
Correct. Namespace `GridTools` would be the appropriate place for this.

**Comment by jppelteret** [comment]
I've been chatting with @davydden about this and, in particular, the corner cases surrounding step (1), that is defining a cell layer around a specified subdomain. With reference to the attached image I'd like to discuss the primary issue with my current implementation and perhaps get some ideas on how to design an efficient algorithm that will work under all scenarios.

Assuming that the cell marked "X" is the only one for which we wish to extract a cell layer (highlighted in yellow) that shares the vertices of cell X, then my algorithm can (relatively efficiently) take care of the 2-d and 3-d cases that look like subfigures 1-3. The difficulty in each case is making sure that all cells that share the vertex marked in green are picked up, and currently I use at most 2 levels of face traversals to collect the cell layer. One would suspect that this covers most of the structured and unstructured meshes that people might use.

However, as shown in subfigure 4 it is conceivable that with a very irregular grid this strategy will no longer work. One could cluster many cells around the green vertex, which would require an inordinate number of face traversals which cannot be predicted or optimised due to the random orientation of the faces in unstructured meshes. A fallback approach would be to use `GridTools::find_cells_adjacent_to_vertex` or `GridTools::find_active_cell_around_point`, but I think that this would be prohibitively expensive since each call loops over the whole triangulation.

My best thought thus far would be to do a single loop over the triangulation, store all active cells sharing a vertex in a map (presumably with the vertex global id being the key). One can then loop again over the cells in the subdomain of interest (or just fetch them if we mark them during the first tria loop) and grab the cell layer by fetching the map entries corresponding to the cell's vertices. Assuming that during refinement we force only 1 level difference between adjacent cells then I think that this algorithm would work during refinement/coarsening.

Any thoughts or comments?

![cell_layer](https://cloud.githubusercontent.com/assets/10460610/9359919/b15cc886-4693-11e5-9ea7-feb3686d51c8.jpg)

**Comment by bangerth** [comment]
> However, as shown in subfigure 4 it is conceivable that with a very
> irregular grid this strategy will no longer work.

Right. Now also think of a 2d situation where the domain consists of two 
parts that only touch in one vertex. For one of the cells that meet in 
this vertex, you want to find the other one, but you can't find them via 
face traversals. Same in 3d for two parts of the domain that are only 
connected via an edge.


> random orientation of the faces in unstructured meshes. A fallback
> approach would be to use |GridTools::find_cells_adjacent_to_vertex| or
> |GridTools::find_active_cell_around_point|, but I think that this would
> be prohibitively expensive since each call loops over the whole
> triangulation.

Yes, that's too expensive because you order your loops wrongly.


> My best thought thus far would be to do a single loop over the
> triangulation, store all active cells sharing a vertex in a map
> (presumably with the vertex global id being the key). One can then loop
> again over the cells in the subdomain of interest (or just fetch them if
> we mark them during the first tria loop) and grab the cell layer by
> fetching the map entries corresponding to the cell's vertices. Assuming
> that during refinement we force only 1 level difference between adjacent
> cells then I think that this algorithm would work during
> refinement/coarsening.


I think this algorithm is storing too much information. How about this:
```
   std::set<unsigned int> vertices_on_locally_owned_cells;
   for (cell=...)
     if (cell->is_locally_owned())
       for (vertex=0...GeometryInfo<dim>::vertices_per_cell)
         vertices_on_locally_owned_cells
                .insert (cell->vertex_index(vertex));

   for (cell=...)
     if (cell->is_locally_owned() == false)
       for (vertex=0...GeometryInfo<dim>::vertices_per_cell)
         if (vertices_on_locally_owned_cells contains
                   cell->vertex_index(vertex))
           {
              mark cell as ghost layer;
              break;
           }
```
This way you only have to store a single std::set.

**Comment by davydden** [comment]
>I think this algorithm is storing too much information. How about this:
>```
>   std::set<unsigned int> vertices_on_locally_owned_cells;
>   for (cell=...)
>     if (cell->is_locally_owned())

i think it should be possible to write those if's more generally with some lambda-functions, i.e. 
`if (my_input_function(cell)==true)`

>       for (vertex=0...GeometryInfo<dim>::vertices_per_cell)
>         vertices_on_locally_owned_cells
>                .insert (cell->vertex_index(vertex));
>
>   for (cell=...)
>     if (cell->is_locally_owned() == false)

and `if (my_input_function(cell)==false)`

>       for (vertex=0...GeometryInfo<dim>::vertices_per_cell)
>         if (vertices_on_locally_owned_cells contains
>                   cell->vertex_index(vertex))
>           {
>              mark cell as ghost layer;

put it to an output set of cells.

>              break;
>           }

so that the function could be used to create a layer using arbitrary input condition function, provided by the user. 

The set of layer-cells would then be returned to do whatever, e.g. mark cells as ghost layer and do whatever else.

**Comment by bangerth** [comment]
Yes, obviously it should be easy to generalize as you suggest. I'm sure it would make for a nice function in `GridTools`. Maybe something like `GridTools::compute_vertex_halo_layer()` or similar?

**Comment by tjhei** [comment]
This is nearly identical to what we do to identify ghost cells in the p4est implementation, see mark_locally_active_vertices_on_level() in dof_handler_policy.cc

**Comment by jppelteret** [comment]
Great, thanks @bangerth and @tjhei . So no need to reinvent the wheel; we just need to generalise it. I'll try to get onto this today.

**Comment by davydden** [comment]
Going back to the original question, i am trying to recall how locally owned, ghost and artifical cells work. It seems I only need to get halo layer for each processor and then set `subdomain_id` of cells which 

* subdomain_id != this_mpi_process and
* they are not in the halo layer 

to `numbers::artificial_subdomain_id`. 
I suppose this should be done in numerous places, but certainly in constructor of shared triangulation class together with partitioning (which i don't do currently for whatever reason).

**Comment by bangerth** [comment]
Your algorithm is basically correct. I think the only place where you need to do this is right after all of the places where you do partitioning. This is where you currently set subdomain_ids (by copying the output of METIS to the cells) and you may simply have to add another loop over all cells doing as you suggest above.

**Comment by bangerth** [comment]
@davydden and @jppelteret -- did your previous patches implement what you had wanted here?

**Comment by davydden** [comment]
yes, i think it's done in the PR #1674 . I am closing this issue...
