### ISSUE TITLE
n_blocks in the constructor of FiniteElementData

### ISSUE THREAD

**Issue by davydden** [dealii/dealii#1378]
while diving into `FiniteElement` and `FiniteEelementData` classes i found out that the constructor of `FiniteElementData` recieves `n_blocks` as the last argument. However, it is not used anywhere:

```
template <int dim>
FiniteElementData<dim>::
FiniteElementData (const std::vector<unsigned int> &dofs_per_object,
                   const unsigned int n_components,
                   const unsigned int degree,
                   const Conformity conformity,
                   const unsigned int)
```
and inside it sets `block_indices_data(1, dofs_per_cell)`, leaving it to be modified in derived classes if needed.

Not sure whether one should remove `n_blocks` from the constructor, or somehow encapsulate `block_indices_data` so that the number of blocks is set up in constructor but number of DoFs in each block has to be set up in the derived classes without accessing `block_indices_data` directly. 
For a newcomer (like me) to this part of the library it is a bit confusing which class has to initialise or re-initialise what member variables. Perhaps, there is a way to improve it.

**Comment by bangerth** [comment]
Yes, poorly done. All of this was written in 1998 when we were much worse software designers :-(

The style we follow elsewhere these days is to pass everything down through the constructor of the base class and let that set its fields, if possible. This makes it clear who is in charge of initializing a field, and furthermore often makes it possible to make the field `const`.

Want to give this a try? If you initialize the field in the base constructor and mark it `const`, you should easily be able to find all of the places where it is currently set because these places are now writing into a `const` field.

**Comment by davydden** [comment]
i will give it a try a bit later, need to finish partition-of-unity quickly ;-)
