### ISSUE TITLE
[Tutorial step-1] part of the HTML is malformed.

### ISSUE THREAD

**Issue by willi-z** [dealii/dealii#13848]
Hi, 
I am new to dealii and I currently started to go through the dealii-tutorial.
In [step-1](https://www.dealii.org/current/doxygen/deal.II/step_1.html) the last paragraph seems to be malformed. 
As an outsider there seems to be an issue with ``@code`` and ``@endcode`` not being parsed correctly.
Also there are some wierdly intertwined ``<a href/>`` tags, that might not be the way the author originally intended.
Example:
```html
(see <a href= "
<a href="http://en.wikipedia.org/wiki/Iterator#C.2B.2B">
http://en.wikipedia.org/wiki/Iterator#C.2B.2B</a>
">wikipedia</a> for more information)
```
And because this also might just be an issue with my browser, here are my stats:
- Firefox Version 100
- Winsows 11

**Comment by tjhei** [comment]
Thank you for reporting this. We are aware of this and the fix for the 9.3 documentation should be online in the next few days. @tamiko will just need to regenerate the documentation.

Until then, you can take a look at https://www.dealii.org/developer/doxygen/deal.II/step_1.html (this is the development version of step-1, but there should be little to no changes to 9.3).

**Comment by tamiko** [comment]
@willi-z @tjhei I have regenerated the documentation with out doxygen fixes. Please have a look!
Let's close after you two have confirmed that all issues are resolved.
See, https://www.dealii.org/current/doxygen/deal.II/step_1.html

**Comment by tjhei** [comment]
Looks good to me.
