### ISSUE TITLE
Configuration: Checking for parallel HDF5 fails

### ISSUE THREAD

**Issue by jppelteret** [dealii/dealii#14065]
The check for parallel HDF5 (version 1.10.7, built through spack) is failing for my configuration. Specifically, [this line](https://github.com/dealii/dealii/blob/master/cmake/configure/configure_50_hdf5.cmake#L28) seems to be the culprit. Maybe this flag is not present in all versions of HDF5?

Here is the relevant part of the configuration output:
```
     596    --   HDF5_INCLUDE_DIRS: <PATH>/hdf5-1.10.7-dtklg2jrvt6qmxacwfp5bkpohggkt3bf/include;<PATH>/openmpi-4.1.4-eis7yrm5hdpkyjqewqdrdowk2664ujj4/include
     597    --   HDF5_USER_INCLUDE_DIRS: <PATH>/hdf5-1.10.7-dtklg2jrvt6qmxacwfp5bkpohggkt3bf/include;<PATH>/openmpi-4.1.4-eis7yrm5hdpkyjqewqdrdowk2664ujj4/include
     598    --   HDF5_LIBRARIES: <PATH>/hdf5-1.10.7-dtklg2jrvt6qmxacwfp5bkpohggkt3bf/lib/libhdf5.so;<PATH>/openmpi-4.1.4-eis7yrm5hdpkyjqewqdrdowk2664ujj4/lib/libmpi.so
     599    -- Found HDF5
     600    -- Insufficient hdf5 installation found: hdf5 has to be configured with MPI support.
     601    -- DEAL_II_WITH_HDF5 has unmet external dependencies.
```

I also attach two of the HDF5 configuration files that indicate that it is build with parallel capabilities. 
[libhdf5.settings.txt](https://github.com/dealii/dealii/files/8995585/libhdf5.settings.txt)
[hdf5-config.cmake.txt](https://github.com/dealii/dealii/files/8995589/hdf5-config.cmake.txt)

**Comment by tjhei** [comment]
I am not sure if it is related, but I had an issue before where ``HDF5_IS_PARALLEL`` sometimes (rarely) seem to have the wrong value if you run cmake again in an existing build directory as if is is not cached correctly. When I start from a fresh directory it always worked.

**Comment by tjhei** [comment]
1. Is this with a clean build directory?
2. What is your cmake version?

It could be related to https://gitlab.kitware.com/cmake/cmake/-/issues/16257 https://gitlab.kitware.com/cmake/cmake/-/merge_requests/83

**Comment by mathsen** [comment]
Hello,

I just wanted to open an issue with exactly this problem, that I have since [this commit](https://github.com/dealii/dealii/commit/b20e6e8d118d8256f07b82b6fafd84516777f32e). I normally use spack (as @jppelteret in the issue description) to install dealii with all dependencies. Since the spack hdf5 is definitely compiled with MPI support I first assumed an issue with spack or cmake and simply disabled the dealii check here to get a running library.
Nevertheless now I found some time to debug this problem and we actually have a concatenation of two problems. One is a dealii issue the other one a spack / cmake one. I just debugged the dealii one and think this should be fixed in the library.
In a nutshel: the dealii `macro_find_package.cmake` breaks cmakes `find_package()` function, on which dealii relies since [this commit](https://github.com/dealii/dealii/commit/b20e6e8d118d8256f07b82b6fafd84516777f32e).

Now in more detail:

[dealii overwrites](https://github.com/dealii/dealii/blob/master/cmake/macros/macro_find_package.cmake) cmakes `find_package()` with a simple macro. This [basically checks](https://github.com/dealii/dealii/blob/88f8ea7d54d1c59f60ea153805b10f979ef64264/cmake/macros/macro_find_package.cmake#L25) if `${_package_name_uppercase}_FOUND` and `${_package_name_uppercase}_FOUND` is not defined and if not it calls `_FIND_PACKAGE` - so cmakes builtin `find_package()` function.
So when `configure_50_hdf5.cmake` [calls](https://github.com/dealii/dealii/blob/88f8ea7d54d1c59f60ea153805b10f979ef64264/cmake/configure/configure_50_hdf5.cmake#L23)  `FIND_PACKAGE(HDF5)` the [dealii macro](https://github.com/dealii/dealii/blob/master/cmake/macros/macro_find_package.cmake) is executed which guards a call to cmakes `find_package()` function.

Let's have a brief look what happens when we call cmakes `find_package(HDF5)` function - we end up in the cmake [FindHDF5.cmake module](https://github.com/Kitware/CMake/blob/master/Modules/FindHDF5.cmake).
I want to highlight some crucial steps here:

1. In [line 163](https://github.com/Kitware/CMake/blob/251c1fc56c2c40c4a16b1e3dd1ffee5f1f38b3e8/Modules/FindHDF5.cmake#L163) the variable `HDF5_FOUND` is set to `off`.

2. Beginning in [line 500](https://github.com/Kitware/CMake/blob/251c1fc56c2c40c4a16b1e3dd1ffee5f1f38b3e8/Modules/FindHDF5.cmake#L500), cmake starts its first attempt to find HDF5 by using a cmake config file (that is normally packaged with hdf5, also spack ships it).

3. In [line 502](https://github.com/Kitware/CMake/blob/251c1fc56c2c40c4a16b1e3dd1ffee5f1f38b3e8/Modules/FindHDF5.cmake#L502) cmake calls again it's own `find_package()` function - which in the dealii library calls the [dealii macro](https://github.com/dealii/dealii/blob/master/cmake/macros/macro_find_package.cmake).
Here is the main problem: Since cmake set `HDF5_FOUND` in step 1, dealii does not call cmakes `find_package()` - we simply never reach [line 27](https://github.com/dealii/dealii/blob/88f8ea7d54d1c59f60ea153805b10f979ef64264/cmake/macros/macro_find_package.cmake#L27).
So this first CMAKE variant of looking for HDF5 simply fails because of the additional checks in the dealii macro.

4. Cmake then continues in [line 584](https://github.com/Kitware/CMake/blob/251c1fc56c2c40c4a16b1e3dd1ffee5f1f38b3e8/Modules/FindHDF5.cmake#L584) and tries to get the needed information of the HDF5 install using a fallback method: the hdf5 compiler wrapper. This fallback method works for me with my "system hdf5", but fails when I use spack to install dealii. So I assume we also have a spack issue here.

Nevertheless - normally in step 3 the call to `find_package()` should not be skipped. If it wouldn't, we would get a working configuration of HDF5.

To demonstrate the difference I have prepared a simple CMakeLists.txt, that simply calls directly cmakes `find_package()` function in a verbose way:
[CMakeLists.txt](https://github.com/dealii/dealii/files/9174183/CMakeLists.txt)
(if you don't use system hdf5 define the hdf5 path in line 5 or load a corresponding module). Simply putting this file in a directoy and running `cmake .` looks for hdf5. I highlight some parts of the output:

```
Found HDF5 at /home/user/apps/spack/opt/gcc-12.1.0/hdf5-1.12.2-mtqwo22utj4ywptot26bnadfuon3fwqw/share/cmake/hdf5 via NO_MODULE. Now trying to extract locations etc.
[...]
-- HDF5_FOUND: TRUE
-- HDF5_IS_PARALLEL: ON
```
We see cmake found HDF5 with the "[NO_MODULE](https://github.com/Kitware/CMake/blob/251c1fc56c2c40c4a16b1e3dd1ffee5f1f38b3e8/Modules/FindHDF5.cmake#L508)“ way, that is way number 1 of the explanation above.

In comparison here is a part of the dealii configure output:
```
-- HDF5: Using hdf5 compiler wrapper to determine C configuration
[...]
-- HDF5_FOUND: TRUE
-- HDF5_IS_PARALLEL: FALSE
```
One sees, that this time the [hdf5 compiler](https://github.com/Kitware/CMake/blob/251c1fc56c2c40c4a16b1e3dd1ffee5f1f38b3e8/Modules/FindHDF5.cmake#L646) version of cmake `find_package()` function is used - which fails at least for the spack install.

Of course this second way *should* also not fail - and this way works outside spack, so I assume that we have another issue on the spack side here.
Nevertheless I think that dealii should not break the first way of detecting the hdf5 library. 

I have a dirty workaround for this [problem here](https://github.com/mathsen/dealii/commit/0a593aeb2680aac293e1948f479fa241cd4a56b5), where I more or less disable the dealii if-checks in the `macro_find_package.cmake`. This fixes the problem for me.
Maybe anybody has an idea on how to cope with this?

**Comment by tjhei** [comment]
@tamiko Can you take a look?

**Comment by tamiko** [comment]
Fascinating. I'll have a look how to fix this.

**Comment by RichardYCJ** [comment]
Hi, @tamiko @jppelteret. Here's an extra supplementary to @mathsen's found.

I've also encounter this problem while trying to install from `spack` with `hdf5@1.12.2`. **Downgrading to `hdf5@1.10.7` could avoid this problem.**

## One sentence conclusion
It turns out the `FIND_PACKAGE(HDF5)` command also invokes `FIND_PACKAGE` inside itself and the dealii defined same-name macro does not expect this.

## Simple test of what `FIND_PACKAGE(HDF5)` does
An easy way is to print out every time `find_package` is invoked. Here's an example `CMakeLists.txt`:
```cmake
MACRO(FIND_PACKAGE _package_name)
  message("Invoke: _FIND_PACKAGE (${_package_name} ${ARGN})")
  _FIND_PACKAGE (${_package_name} ${ARGN})
ENDMACRO()

FIND_PACKAGE(HDF5)
message("HDF5 Found: ${HDF5_FOUND}")
message("HDF5 support MPI: ${HDF5_IS_PARALLEL}")
```

The output clearly shows two call one from `FIND_PACKAGE(HDF5)`, and one is from inside (QUIET;NO_MODULE;HINTS)
```log
Invoke: _FIND_PACKAGE (HDF5 )
Invoke: _FIND_PACKAGE (HDF5 QUIET;NO_MODULE;HINTS)
-- Found HDF5: hdf5-shared (found version "1.12.2")
HDF5 Found: TRUE
HDF5 support MPI: ON
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/test-hdf5
```

## Use deal.II defined `FIND_PACKAGE`
As a results, when applying dealii wrapper:
```cmake
MACRO(FIND_PACKAGE _package_name)
  STRING(TOUPPER ${_package_name} _package_name_uppercase)
  message("Invoke: _FIND_PACKAGE (${_package_name} ${ARGN})")
  IF( NOT DEFINED ${_package_name_uppercase}_FOUND AND
      NOT DEFINED ${_package_name_uppercase}_LIBRARIES )
    message("Enter first case.")
    _FIND_PACKAGE (${_package_name} ${ARGN})
  ELSE()
    message("Enter second case.")
    IF(NOT DEFINED ${_package_name_uppercase}_FOUND)
      SET(${_package_name_uppercase}_FOUND TRUE)
    ENDIF()
  ENDIF()
ENDMACRO()

FIND_PACKAGE(HDF5)

message("HDF5 found: ${HDF5_FOUND}")
message("HDF5 support MPI: ${HDF5_IS_PARALLEL}")
```

The **first** (last in log output) `find_package` will enter the first case to **only find HDF5 library** (set `HDF5_FOUND`) but **no module/flag is set**. And when a **second** call is ready to set flags, it will enter the second case and **exit** directly, no extra flags are set.
```log
Invoke: _FIND_PACKAGE (HDF5 )
Enter first case.
Invoke: _FIND_PACKAGE (HDF5 QUIET;NO_MODULE;HINTS)
Enter second case.
HDF5 found: TRUE
HDF5 support MPI: FALSE
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/test
```

IMO, overwriting `find_package` with self-defined macro is never a good idea, for it is intrusive and will pollute the global namespace. A fast work-around is to use an extra name like [previous commit](https://github.com/dealii/dealii/commit/853842c3ad113567c3996faf58a1cce2e4701037).
