### ISSUE TITLE
DataPostprocessor< dim >::compute_derived_quantities_vector still use Point<dim> as norms

### ISSUE THREAD

**Issue by QiaoLei-88** [dealii/dealii#1418]
Something missed in #1408

**Comment by bangerth** [comment]
This can't be done in a backward compatible way, unfortunately. But it is on the list of things to address for #391.

**Comment by QiaoLei-88** [comment]
How about overload the function ```compute_derived_quantities_vector``` to make it take ```Tensor<1,dim>``` as parameter and deprecate the old version with ```Point<dim>``` parameter?

**Comment by bangerth** [comment]
That's possible. We did this before, but I think I'm more interested in fixing the problem right this time, rather than another hack that doesn't address the underlying problem: that by passing everything as individual arguments, we can not expand the the list of things we pass without breaking backward compatibility.
