### ISSUE TITLE
Undefined behavior warning: `Triangulation::execute_refinement_isotropic/execute_coarsening`

### ISSUE THREAD

**Issue by mschreter** [dealii/dealii#14263]
With GCC 12.1.1 I get the following warning

```
/home/dealii/source/grid/tria.cc: In function ‘static typename dealii::Triangulation<3, spacedim>::DistortedCellList dealii::internal::TriangulationImplementation::Implementation::execute_refinement_isotropic(dealii::Triangulation<3, spacedim>&, bool) [with int spacedim = 3]’:
/home/dealii/source/grid/tria.cc:5697:43: warning: iteration 12 invokes undefined behavior [-Waggressive-loop-optimizations]
 5697 |                         raw_line_iterator line(&triangulation,
      |                                           ^~~~
/home/dealii/source/grid/tria.cc:5695:48: note: within this loop
 5695 |                     for (unsigned int l = 0; l < hex->n_lines(); ++l)
```
and 

```
/home/dealii/source/grid/tria.cc: In member function ‘void dealii::Triangulation<<anonymous>, <anonymous> >::execute_coarsening() [with int dim = 3; int spacedim = 3]’:
/home/dealii/source/grid/tria.cc:14809:32: warning: iteration 12 invokes undefined behavior [-Waggressive-loop-optimizations]
14809 |               ++line_cell_count[line_indices[l]];
      |                 ~~~~~~~~~~~~~~~^
/home/dealii/source/grid/tria.cc:14808:40: note: within this loop
14808 |             for (unsigned int l = 0; l < cell->n_lines(); ++l)
```
Could it be that an array access might be out of bounds in iteration 12? I quickly went through the code but unfortunately could not identify the issue. It might be related to https://github.com/dealii/dealii/pull/14221, so maybe @kronbichler you know immediately if it is relevant and what it might cause.

**Comment by kronbichler** [comment]
This should not actually be an out-of-bound access, because for all cell types we have `n_lines() <= 12`, hence there can never be a loop iteration 12. I don't know why the compiler won't see this: https://github.com/dealii/dealii/blob/ce01b6b551a06c3003d4a8edcea15134c46ced27/include/deal.II/grid/reference_cell.h#L989-L1008

Since I do not really feel like adding a separate statement `l < std::min(hex->n_lines(), 12u)`, I wonder if you also see the warning if you change the default return value in `ReferenceCell::n_lines()` from `numbers::invalid_unsigned_int` to `0`. Could you please try that? We should not reach that code, but I wonder if that is the origin or if the compiler is not inlining the function at all at the time it generates the warning and just assumes some generic integer value.

**Comment by mschreter** [comment]
Your guess is right: if we change the default value of `ReferenceCell::n_lines()` to 0, the warning is gone.

**Comment by kronbichler** [comment]
So do we want to proceed by letting the code return `0` in the undefined case, which is in fact unreachable for debug mode due to the `Assert` in the line above?

**Comment by peterrum** [comment]
> So do we want to proceed by letting the code return 0 in the undefined case, which is in fact unreachable for debug mode due to the Assert in the line above?

I guess so. 

But returning `numbers::invalid_unsigned_int` in the invalid case is what we normally do in deal.II. For instance in the same file, there are additional 14 instances of this usage...

**Comment by kronbichler** [comment]
How do we want to proceed here? I think it would be good to fix this warning in some way, as we generally strive for zero warnings when compiling deal.II with our main compilers.

**Comment by peterrum** [comment]
> How do we want to proceed here? I think it would be good to fix this warning in some way, as we generally strive for zero warnings when compiling deal.II with our main compilers.

Let's go with the `0` solution for now.

**Comment by mschreter** [comment]
Shall I take this one over since I am using GCC 12.1.1?

**Comment by kronbichler** [comment]
That would be great, thank you @mschreter!
