### ISSUE TITLE
Triangulation distributed without p4est

### ISSUE THREAD

**Issue by Wayne901** [dealii/dealii#14274]
Hi dealii community,
I'm new to dealii and attracted by its comprehensive tutorials, but I have one question. Thats is can mesh be distributed in parallel computation without p4est framework? I came to this question when reading [step-40](https://www.dealii.org/current/doxygen/deal.II/step_40.html#:~:text=for%20this%20to%20be%20moderately%20simple%20to%20implement%2C%20each%20MPI%20processor%20had%20to%20keep%20its%20own%20copy%20of%20the%20entire%20Triangulation%20and%20DoFHandler%20objects) and it says previous mpi tutotrial like step-17 based on METIS partition keep a global triangulation in every process, which is unwanted for large scale multi-process projects. However I'm not sure if orthogonal meshes suit problems with complex geometries.
More specifically, I plan to try matrix-free method with multigrid method for unorthogonal  quad/hex mesh (as in step1), and of course with parallelization. It's this possible in dealii? Thank you.

**Comment by drwells** [comment]
It sounds like `parallel::fullydistributed::Triangulation` might be the data structure you want.

> However I'm not sure if orthogonal meshes suit problems with complex geometries.

In general, yes, but fundamentally `p4est` works well with any mesh with a coarse grid of a few thousand cells which has been adaptively or uniformly refined - whether it comes from a cube or a mesh of some complex object isn't really relevant to `p4est` since it just manages topology.

If you still have questions, could you help us by posting them to the mailing list instead? There's a lot more people who subscribe to the mailing list than issue tracker and it's where we typically hold this kind of discussion. Thanks!

**Comment by Wayne901** [comment]
Hi Wells. 
Great to here p4est works for arbitrary quad/hex mesh. I'll post questions to mail the next time.
Thank you!
