### ISSUE TITLE
Generalized interface to collect CGAL intersections

### ISSUE THREAD

**Issue by jh66637** [dealii/dealii#14338]
I have been working with CGAL during the last weeks. During this time, I wrote a class that collects intersections between ```spacedim``` elements and ```spacedim-1``` elements on distributed triangulations. Currently, I have a class called ```ExactFaceIntersections``` for this purpose and I hand over the boundary_id on which ```spacedim-1``` elements are located and a ```marked_vertices``` function as it is done in ```RPE``` to be able to specify elements in which intersections are searched for. I have to put some more work into this, but it works in general.

Before I continue working on this and before filing a PR, I would like to discuss on this interface with you. I am pretty sure there are better solutions, such that the interface can be used to search for intersections between arbitrary element dimensions. 

One idea would be to hand over a vector of ```cell_iterators``` or ```face_iterators``` on which intersections are required and to provide the dimension of the elements that are tested for the intersection.

However, in that case, I would have to distinguish between iterating over faces or cells inside the function. Is there a way you typically deal with this kind of problems? Or do you have any other thoughts on an interface?

I hope the description is clear. If not, I'm happy to clarify things :)

**Comment by peterrum** [comment]
@jh66637 Thanks for working on this topic!

Before digging into a user-friendly interface, let's discuss what the class actually does (in comparison to RPE). 

To set up PRE, you give a list a points you want query some, e.g., solution, on a mesh. The points may come from the quadrature point of another mesh. The points are communicated and a communication is set up, which can be used in a second step.

> Generalized interface to collect CGAL intersections

I am not completely sure if you actually do what the title states. Do you actually need the intersections? What is the purpose of having the intersection? What is actually the data structure of an intersection? From what I know what you do, I would guess that you need the quadrature points on intersections. Maybe I am wrong and you actually create a surface mesh consisting of intersected elements. 

In the case that you only need the quadrature points, I would guess the high-level algorithm you have implemented looks as follows
- collect the bounding vertices of relevant geometric entities (structdim might be arbitrary) to be intersected
- send them around 
- for each geometric entity check if one of its vertices inside of a cell of the triangulation; if yes, create intersection and create on that the quadrature points
- this information can be used set up the same or similar data structures an the case of PRE (augmented by JxW)
 
The case of the auxiliary surface mesh sounds also very interesting; but my feeling there is that it is more complicated, since the communication has to be set up between the two tringulations and the auxiliary mesh.

Could you clarify what the result of your algorithm is?

**Comment by fdrmrc** [comment]
Hi,

I'd like to share here what we did so far to assemble interface terms with different intrinsic dimensions in the context of immersed methods. Unfortunately I am not a `RPE` user, so this surely affects my considerations.

In order to get the collection of quadratures on intersections of two trias, we start from two cached ones and return a vector of tuples `v` where each tuple consists of three elements:
1) Iterator to the first cell $T \in \mathcal{T}_h^0$
2) Iterator to the second cell $K \in \mathcal{T}_h^1$
3) `Quadrature` object to integrate over $T \cap K \ne \emptyset$ (computed using CGAL utilites)

So the signature I have in one of my branches is as follows:

```
  template <int dim0, int dim1, int spacedim>
  std::vector<std::tuple<typename Triangulation<dim0, spacedim>::cell_iterator,
                         typename Triangulation<dim1, spacedim>::cell_iterator,
                         Quadrature<spacedim>>>
  collect_quadratures_on_overlapped_grids(
    const GridTools::Cache<dim0, spacedim> &space_cache,
    const GridTools::Cache<dim1, spacedim> &immersed_cache,
    const unsigned int                      degree, //degree of quad rule
    const double                            tol = 1e-14); //discard if measure is lower than tol
```

**Comment by peterrum** [comment]
@jh66637 Question what are you communicating during setup? I guess the intersections are never communicated but only the geometric entities that might cut?

**Comment by jh66637** [comment]
@peterrum I am communicating all vertices of the cells or faces I want the intersections on (to the relevant ranks). After doing some work the vertices of the found intersection patches are sent back.

Regarding the interface I proposed in my last comment. I think it would be nice to be able to search 2D/2D intersections on 3D/3D triangulations. Proposed interface can't do that.

**Comment by peterrum** [comment]
Let me allow to shortly summarize the algorithm we talked about. For me a geometric entity is defined as a vector of vertices (2 points for a line, 3 points for a triangle, and 4 for a quad).

1) collect relevant geometric entities on master side and categorize them by processes that have - on the slave side - geometric entities that might cut them (a possible heuristic is using bounding boxes)
2) send the geometric entities to the slave side
3) perform cut on slave side, which generates new geometric entities (intersections)
4) collect for each geometric entity on the master side all generated new geometric entities
5) on the master side, use a quadrature rule on each intersection and plug in the generated quadrature points into RPE to setup the communication pattern

Alternatively, steps 4 and 5 could be merged if the slave side also knows about the quadrature rules. The advantage of this approach would be that one needs a communication step less and one can skip the expensive search algorithm within RPE.

**Comment by jh66637** [comment]
Thanks for the reminder. Regarding the interface:
The core of the algorithm is the same, independent on the dimensions (only relying on vertices). The interface is realized by overloading multiple functions that call the core functions internally. I think this is a good solution :) 

From my side, the Issue is resolved. I know what to do and will push a first attempt soon.

**Comment by peterrum** [comment]
With @jh66637, we agreed on following approach:

We write a function (lets call it `distributed_compute_intersection_locations`), which is similar to

https://github.com/dealii/dealii/blob/59a32f8eaf19dc8148db1bebedf363338eea8ae6/source/grid/grid_tools.cc#L5909

The function would take instead of a list of points a list of cells (`CellAccessor` or list of points) and would return a data structure similar to:

https://github.com/dealii/dealii/blob/85e854aec2535eb4ada3b613b896ca874e71dc6a/include/deal.II/grid/grid_tools.h#L1172-L1173

Lets call the new data structure `DistributedComputeIntersectionLocationsInternal`. In particular, it would contain relevant information regarding the communication.

The new struct would have a function that converts the information to `DistributedComputePointLocationsInternal` (by distributing a quadrature on each intersection), which can be used to fill `RemotePointEvalution` (communication free).

The motivation for splitting up the responsibilities is to be able to create later based on `DistributedComputeIntersectionLocationsInternal` an intersection triangulation.

**Comment by jh66637** [comment]
I will split the tasks into multiple PRs. 

- [ ]  Make it possible to ```reinit()``` ```RPE``` with ```DistributedComputePointLocationsInternal```
- [ ] introduce ```DistributedComputeIntersectionLocationsInternal``` which can construct ```DistributedComputePointLocationsInternal```
- [ ] introduce ```distributed_compute_point_locations```, which fills ```DistributedComputeIntersectionLocationsInternal```

After that, I will provide the Wrapper called ```FERemotePointEvaluation``` for ```RPE``` which can be used in combination with ```FEPointEvalution``` or ```FEEvaluation``` to access data in quadrature points on a different triangulation.

**Comment by jh66637** [comment]
All the needed PRs are in place :)
