### ISSUE TITLE
Fix compilation unit sizes

### ISSUE THREAD

**Issue by tamiko** [dealii/dealii#1444]
gcc got hungrier over the last releases... It is now a gamble whether 14-16GB of main memory are sufficient to compile on ~8 threads...

We should drastically decrease compilation unit sizes. And, ideally, also split the library into multiple parts [1].

[1] The issue with exception propagation on mac should be resolved, shouldn't it?

**Comment by bangerth** [comment]
What would help here is if we had a way to measure how long it takes each .cc file to compile. Is there a way to get this out of make or ninja?

**Comment by tamiko** [comment]
Yes, builtin!
```
cd build && awk '{ time = $2 - $1; print time "\t" $4}' < .ninja_log | sort -n
```

**Comment by tjhei** [comment]
Splitting the library into separate libraries would improve link times (and memory requirement there) but this is not the main issue here, so we can look at that separately.

Timing is also not very important in my opinion. Should we try to agree on a reasonable limit for memory usage for a single compilation unit? Maybe 1.5GB or 2GB of virtual memory?

One thing I am not a huge fan of is the manual splitting of .inst files (see the ugly thing I did in fe_values_inst2.cc). Are we doing something better anywhere else? I don't think it would be particularly difficult to split .inst files automatically based on a #define for the number of files during the .inst.in->.inst conversion. Does anybody know of other c++ libraries that do something like this?

**Comment by bangerth** [comment]
Yes, link time is negligible with #1492. We shouldn't make this the goal.

Memory consumption is an issue. I agree that the current approach for fe_values.*inst* is not particularly elegant :-(

**Comment by tjhei** [comment]
I think I have a much nicer solution. I will prepare a patch later/tomorrow.

**Comment by tjhei** [comment]
See #1516 for a suggestion. If you like this approach, I will go ahead and split the biggest offenders (I already have a list).

**Comment by kronbichler** [comment]
I like the solution in #1516 but I fear it is not enough:
- With the experience of splitting up the file vector_tools.templates two years ago into various categories (vector_tools_{boundary,constraints,integrate_difference,interpolate,mean_value,point_gradient,point_value,project,rhs}) for improving compile times, I would like to add that many of the difficult cases (and the culprits in terms of memory usage really are some of the vector_tools as well as dof_accessor files) do not really profit when split up in such a coarse-grained fashion, in particular the memory usage. The new approach is a bit better but it more or less randomly assigns tasks to different compilation units, even those where a smart compiler could reuse some info e.g. common internal functions.
- One of the main problems is that we have to instantiate the a lot of heavy code for a zillion of different vector and matrix types. Having one vector interface only (with a few 'Number' types, say float, double, long double, std::complex<double>) fed into these functions would probably help a lot in not only the dimension of compile times but also overall library size.
- I know way to little about how compilers work internally to make definite statements here, but it's not just about the shear size of the instantiated code, it's also a lot about the data structures and function names involved. I realized this was an issue when I worked on the parallelization of data movement and initialization of AlignedVector in early 2012, what eventually lead to parallel::ParallelForInteger (you find a comment about the issue in include/deal.II/base/parallel.h around line 450). Simply replacing **two** parallel::apply_to_subranges in aligned_vector.h by ParallelForInteger reduced memory usage for compiling matrix_free.cc from around 2.2G to 800M if I remember things correctly. What was surprising to me was that this actually seems like a side issue given that said class is used for initializing and resizing an aligned vector with some mapping data, representing only a tiny part of the functionality of matrix_free.cc. The culprit seemed to be std::bind that leads to awfully long argument lists/function names of many hundreds kB each (!). If you have a couple of hundred different of those, the compiler is screwed.

The lesson I learned was that keeping templates under control is quite important for memory usage. If anything, my experience does not really increase my appreciation of std::bind and friends in terms of resource usage during compilation, at least not in template heavy code. One more lesson: Taking the compilation time as a proxy for memory usage and looking at the five slowest files on my machine reveals interesting things:
```
165083  source/lac/CMakeFiles/obj_lac.release.dir/sparse_matrix.cc.o
177610  source/numerics/CMakeFiles/obj_numerics.release.dir/data_out_dof_data.cc.o
190140  source/numerics/CMakeFiles/obj_numerics.release.dir/vector_tools_interpolate.cc.o
196582  source/lac/CMakeFiles/obj_lac.debug.dir/trilinos_precondition.cc.o
502556  source/lac/CMakeFiles/obj_lac.release.dir/trilinos_precondition.cc.o
```
trilinos_precondition.cc time is 98% due to muelu.hpp that does some crazy things (involving hundreds of template instantiations into Kokkos; our code never uses those). So we're not the only ones suffering from these problems it seems (even though we use MueLu.hpp in another project where compilation is actually quite good, so I don't really know why we have those big problems here).

**Comment by tjhei** [comment]
Good points, Martin.

> One of the main problems is that we have to instantiate the a lot of heavy code for a zillion of different vector and matrix types.

Yes, and that will get worse in the transition period because we need one additional instantiation.

> trilinos_precondition.cc time is 98% due to muelu.hpp

Yes, while going through the files, this is one of the big offenders. Just compiling TrilinosPreconditionMueLu blows through more than 2gb of memory with gcc (removing all other preconditioners from that file). Any suggestion on how to get that under control?

**Comment by kronbichler** [comment]
> > trilinos_precondition.cc time is 98% due to muelu.hpp

> Any suggestion on how to get that under control?

I can have a look into why it blows up for deal.II but not the other codes I have seen, but I have to admit that I realistically won't be able to do that for at least a week.

**Comment by Rombur** [comment]
Like @kronbichler said, the problem with MueLu is due to Kokkos (so it will get worse with the Tpetra interface). The developers of Trilinos are aware of this (it is almost impossible to compile DTK, which at some point should be part of Trilinos, if you turn on the explicit instantiation). I don't know if they have a solution though :-(

**Comment by bangerth** [comment]
There are some ideas in this issue, but ultimately nobody seems to have a good plan on how to attack the problem. At least it seems as if splitting up the .inst.in files is not the biggest win, and it's also not particularly simple to implement. 

This is tagged for 8.4 with label "High priority", but I don't see how we can make *systematic* progress on this one (although we can split up the one or two worst offenders). Ideas anyone? Or have we done what can reasonably be done, and should close the issue?

**Comment by tjhei** [comment]
> At least it seems as if splitting up the .inst.in files is not the biggest win, and it's also not particularly simple to implement.

But we do this in #1516?

The only problem left is muelu and I don't think we can do anything about that. I think we can close this issue.

**Comment by bangerth** [comment]
Right, I meant that we don't seem to have any _further_ ideas beyond #1516.

Then yes, let's close it.
