### ISSUE TITLE
Let DoFHandler remember the index sorting strategy

### ISSUE THREAD

**Issue by jpthiele** [dealii/dealii#14518]
In my discussions with @searhein I learned that many algebraic preconditioners need to
make some assumption on how the finite element components are distributed throughout the matrix
i.e. cell-wise or component wise. 
To our (limited) knowledge of the MueLU implementation the assumption should be cell-wise there.
So a wrong ordering would result in a performance drop of the resulting preconditioner,
either in setup time or in the worst case in approximation of the inverse.
Therefore it would be good to be able to check if the dofs were ordered in a certain way to either warn or even except. 
Data-wise this information should not take up too much space as it is a global information of the DoFHandler,
for example as an enum. 
I'd be interested to hear what everyone else thinks about this.

**Comment by tjhei** [comment]
This is somewhat challenging to do, because you need to keep in mind that:
1. several renumberings can be applied consecutively (for example cell-wise then component-wise or the other way around).
2. I often use AMG on a subset of all DoFs (for example the velocity block of a Stokes system like step-32). As the linear algebra blocking is independent of the DoFHandler, how would you able to detect that the component-wise ordering is not relevant (where I keep dim velocity components together)?

**Comment by jpthiele** [comment]
On 1. when renumbering from cell-wise to component-wise and back would this not completely revert all changes as both renumberings should be uniquely defined by my understanding of the documentation. 
With the Cuthill-McKee algorithms all bets are off of course, but even then a call to renumbering cell-wise should revert to the original indexing. 
As for 2 I am not sure what point you are trying to make. Do you mean that the Stokes velocity matrix you are supplying to PreconditionAMG has to have component-wise numbering to construct the block system so it would break an assert on cell-wise renumbering?
Assertion would of course be a very hard barrier so a warning (in debug mode only) would be a better thing there. 
On the other algebraic preconditioners are somewhat black box but not magical and I have seen people somewhat blindly compare all preconditioners provided and then concluding "PreconditionSuperStar" not being a good preconditioner because it did not work for any of their problems when it could have been with proper information.

**Comment by bangerth** [comment]
There are infinitely many possible permutations of DoF indices. There is no way to store which one is used, much less describing this in some sort of "semantic" way. So I don't think that we can or should store this -- the information on how DoFs are renumbered is in the code and that should be the only place where that information is.

As for @tjhei 's example: Many of our renumbering schemes only provide a partial ordering, for example saying "all DoFs for component 1 should come after those for component 0", but do not reorder DoF indices belonging to the same vector component. What Timo is pointing out is that from a global perspective, you'd think that DoFs have been renumbered based on vector component, but if you only look at one block of the matrix, they have been ordered in whichever way you ordered them before you called `component_wise()`. Since the AMG is only applied to one block, the latter is what the AMG is interested in, not the component wise ordering even though that happened last.

Separately, we only give preconditioners a matrix. We do not provide a `DoFHandler`, nor do we say how `DoFHandler` and matrix are related -- the matrix could of course be a standard FE discretization, but it could also have been a nonlocal discretization or a boundary element method. So even if we did give the preconditioner a `DoFHandler` to inspect, it wouldn't know what to do with it.

As a consequence, if a preconditioner needs to know something, that should be an explicit piece of information to provide during construction. An example is how we describe the "null space" to AMG preconditioners.

**Comment by drwells** [comment]
It doesn't sound like we have a good way to make this information available - if we come up with something we can revisit this in the future but lets close for now.
