### ISSUE TITLE
cmake can't find existing BLAS/LAPACK installation

### ISSUE THREAD

**Issue by cruddybanana1102** [dealii/dealii#14579]
Trying to build dealii for my personal machine(Ubuntu 22.04 LTS) with Intel CORE(R) i7-9750H and NVIDIA GeForce GTX 1650. 

I am getting the following error when building with cmake. please see attached screenshot. 
![image](https://user-images.githubusercontent.com/57914003/208203163-8fe8b078-ee1d-44af-a47b-cd1df17591c3.png)
BLAS and LAPACK have been successfully built at /home/cruddybanana1102/Downloads/lapack-3.11.0/ 
but specifying that as file path while running cmake doesn't work. 

Details can be found in attached cmake output and error logs. 
[CMakeOutput.log](https://github.com/dealii/dealii/files/10249931/CMakeOutput.log)
[CMakeError.log](https://github.com/dealii/dealii/files/10249934/CMakeError.log)

**Comment by CodyGirl** [comment]
Hi @cruddybanana1102 ,

I could reproduce the issue, and currently looking into it.
Will provide you with a solution soon.

Best,
CodyGirl

**Comment by CodyGirl** [comment]
Hi @cruddybanana1102,

Try to follow the steps mentioned in the following document, [Resolve-#14579.md](https://github.com/dealii/dealii/files/10251961/Resolve-.14579.md)
I have also attached the build log for your reference, [detailed.log](https://github.com/dealii/dealii/files/10251966/detailed.log)

Let me know, if it solves the issue for you.

Best,
CodyGirl

**Comment by tamiko** [comment]
May I ask how you called `cmake` precisely? I am asking because your CMakeError.log contains:
```
gmake[1]: *** No rule to make target '/home/cruddyanana1102/Downloads/lapack-3.11.0', needed by 'cmTC_31925'.  Stop.
```
In this regard @CodyGirl 's recommendation is spot on: It is best to compile shared libraries and hint via `LAPACK_DIR` (or `CMAKE_PREFIX_PATH`).



A quick comment: If your goal is to simply install deal.II (and you're fine with using software packaged in Ubuntu) then it's not necessary to compile and install any dependency by hand. You can either
 - install the current version of  deal.II from a PPA [1] by running `apt install libdeal.ii-dev`
 - or install all build dependencies (with or without above PPA - but with PPA is recommended from my side): `apt build-dep libdeal.ii-dev`

[1] https://launchpad.net/~ginggs/+archive/ubuntu/deal.ii-9.4.0-backports
