### ISSUE TITLE
Check all_zero in (F)GMRES?

### ISSUE THREAD

**Issue by peterrum** [dealii/dealii#14619]
In GMRES

https://github.com/dealii/dealii/blob/f8bd841edc40111e41523d777adb13e9671cc386/include/deal.II/lac/solver_gmres.h#L1250-L1264

and FGMRES

https://github.com/dealii/dealii/blob/f8bd841edc40111e41523d777adb13e9671cc386/include/deal.II/lac/solver_gmres.h#L1617-L1618

there is no check if the source vector is zero. However, in the case of CG we have such a check with appropriate short cut:

https://github.com/dealii/dealii/blob/f8bd841edc40111e41523d777adb13e9671cc386/include/deal.II/lac/solver_cg.h#L552-L561

I am wondering if we could make it consistent. The shortcut might introduce more work, since checking if a vector is zero is not  just accessing a cached information but involves the read of the complete vector + global reduction. Any opinion? Is the most common use case to start with a zero initial guess?

**Comment by kronbichler** [comment]
I think the motivation to check for `all_zero()` is that it is still cheaper than a matrix-vector product. At least by a factor of 2. Here I ignore the global reduction, which is only relevant in the scaling limit, but then we're doing a considerable number of reductions later in the solver. Conversely, the work in the matrix-vector product can be a more measurable saving. Obviously, when we do 10 or more iterations, and when we have expensive preconditioners, then either way does not matter much.

I agree that we should have a consistent behavior. Intuitively, I would not make any check because it is the default behavior. I can see the need to catch the special cases of a zero vector say in finite difference approximations. These cases do not appear inside the iteration where many solvers work with the residual.

> Is the most common use case to start with a zero initial guess?

I think both cases are about equally common in real applications (not the more or less artificial setup of a tutorial program). On the one hand, one often uses extrapolations or similar means to create good initial guesses, so one naturally gets the case of a non-zero starting vector. On the other hand, when using an iterative solver inside a non-linear solver, one might typically want to solve for an increment, which starts from a zero state.

**Comment by kronbichler** [comment]
Thinking about this again, let us simply introduce the `all_zero()` after #16749 is merged, then we can close this issue.
