### ISSUE TITLE
Docu of VectorTools::interpolate_boundary_values() unclear

### ISSUE THREAD

**Issue by nfehn** [dealii/dealii#14871]
The documentation of `VectorTools::interpolate_boundary_values()` (https://www.dealii.org/current/doxygen/deal.II/group__constraints.html#gadb46ee8a7dbb0c1cafb1ff315afcd203), see function [1/4] to [4/4], is unclear to me. How to use these functions in case of multiple boundary IDs with different `ComponentMasks`? The first function seems to be ruled out for this purpose?

The docu of functions [2/4] to [4/4] says "The same comments apply as for the previous function, in particular about the use of the component mask and the requires size of the function object.", but I could not find such information for function [1/4]. Is it safe to call functions [2/4] (or [3/4]) subsequently for every boundary ID with a different `ComponentMasks`? What about the note in function [1/4] in this context?

It appears unclear to me why the first function takes a map of boundary ids and functions, but a single `ComponentMask`? Is this a somewhat inconsistent design or do I misunderstand something? It would be helpful if the docu was more detailed here.

As a minor comment, references like "see the function above", "same as above" are somewhat unclear in case of 4 functions. In this context, it would make more sense in my opinion to place function [4/4] immediately below function [1/4]. Also, we should avoid copy-pasting the same sentence 3 times, e.g. typos are copy-pasted as well. Suggestion: "see the first function with this name for more information."

Edit: I also do not understand "(dofs the entry is constrained to, inhomogeneities)" for function [1/4].

**Comment by kronbichler** [comment]
> How to use these functions [`VectorTools::interpolate_boundary_values`] in case of multiple boundary IDs with different ComponentMasks?

The general answer to that would be to call `interpolate_boundary_values` multiple times, once with every different `ComponentMask`. This is not very nice from a user perspective, because one could have many `boundary_id`s collected in an `std::map` with associated function, but only a few component masks. One solution that came up in exadg/exadg#376 would be to have the interface
```c++
  struct FunctionPlusMask
  {
    const Function<spacedim, number>* function;
    ComponentMask component_mask;
  };

  VectorTools::interpolate_boundary_values(
    const Mapping<dim, spacedim> &   mapping,
    const DoFHandler<dim, spacedim> &dof,
    const std::map<types::boundary_id, FunctionPlusMask>
      &                                        function_map,
    std::map<types::global_dof_index, number> &boundary_values);
```
This change indicates that the component mask and the prescribed function are both tied to a particular boundary id. I would like this function more than passing both the function and the component mask as two separate `std::map` arguments. More reasoning is that those two maps might contain different boundary ids, making it unclear which of the two aspects to consider. Either way, it feels like the current interface is a bit incomplete, suggesting that the addition of a component mask (appended to the original function without it) has left some new question marks. The reason against my proposed change is that we hide what a `FunctionPlusMask` (or any other name, this one is really just for illustration) actually is, requiring the user to learn yet another struct name.

One could argue that the current interface is a compromise to reflect these conflicting requirements, or we could argue that it would be better to group things that belong together (as all the information to interpolate on a particular boundary) to create smaller more intuitive interfaces.

Opinions on this topic?

**Comment by kronbichler** [comment]
Regarding the comments
> It would be helpful if the docu was more detailed here.

and
> As a minor comment, references like "see the function above", "same as above" are somewhat unclear in case of 4 functions. In this context, it would make more sense in my opinion to place function [4/4] immediately below function [1/4]. Also, we should avoid copy-pasting the same sentence 3 times, e.g. typos are copy-pasted as well. Suggestion: "see the first function with this name for more information."

I agree with you assessment, it would be great to extend the documentation. Would you mind opening a pull request that applies your suggestions, maybe combined with the comment regarding the component mask?

**Comment by kronbichler** [comment]
The functions (plus some additional ones that do not get grouped in the same way by doxygen) are here: https://github.com/dealii/dealii/blob/b5212ad975cda2f263a3126cdd881ecb6cc20780/include/deal.II/numerics/vector_tools_boundary.h#L139-L354

**Comment by bangerth** [comment]
They key problem with this function, as with many others, is that we already have multiple versions of it. We could, of course, add yet more versions but that does not fundamentally fix the problem. In the current case, I think a better solution would be to just improve the documentation -- I'll take care of that.

**Comment by bangerth** [comment]
@kronbichler and I must have been writing at about the same time. I would of course be very happy for you to write patches that improve the documentation :-)
