### ISSUE TITLE
Exceptions inside FEPointEvaluation - Index out of bounds 

### ISSUE THREAD

**Issue by gassmoeller** [dealii/dealii#14984]
Since a few days (<5) we are seeing test failures with deal.II master in ASPECT (e.g. [here](https://github.com/geodynamics/aspect/actions/runs/4533255063/jobs/7985813615?pr=5117#step:6:5401)) related to indices out of bounds inside FEPointEvaluation. At first glance it looks like a loop that runs one index too long (or deal.II triggering the assert on the last iteration of a loop that used to work before).
I saw that https://github.com/dealii/dealii/pull/14972#issuecomment-1484225106 already mentioned something about loop bounds so before debugging myself I just wanted to check if this is something that is already known and worked on. Maybe @bergbauer @kronbichler or @peterrum know more?

Affected deal.II version: 9c182271f7b1db53b11f1ed244487371cee4ee66
Unaffected deal.II version: 9bc3f89c18e161014493f0d1d5ecdcedb9f2ad73

Ideas are appreciated, before I start digging myself :-)

**Comment by bergbauer** [comment]
Sorry for that! It is probably related to this PR https://github.com/dealii/dealii/pull/14926

In what regard is your usage in ASPECT different from the tests
- https://github.com/dealii/dealii/blob/master/tests/matrix_free/point_evaluation_15.cc
- https://github.com/dealii/dealii/blob/master/tests/matrix_free/point_evaluation_16.cc
- https://github.com/dealii/dealii/blob/master/tests/matrix_free/point_evaluation_17.cc

?

**Comment by gassmoeller** [comment]
Thanks for the quick feedback, I will have some time later today to investigate, I will get back to you by tomorrow.

**Comment by gassmoeller** [comment]
Per your suggestion in #14926: Yes, calling `FEPointEvaluation::reinit(numbers::invalid_unsigned_int)` in addition (after) calling `MappingInfo::reinit()` fixes the problem. Is this supposed to be necessary?

I have compared our offending code (https://github.com/geodynamics/aspect/blob/a2d8beb3511d6548be4547fb203565719a04e91f/source/particle/world.cc#L618) to the deal.II tests. Our code is more complex, but the basic operations (`mapping_info.reinit()` then `evaluator.evaluate()`) remain the same. The only substantial difference I could see is that we do not have the same number of evaluation points for every cell, while the tests seem to have the same number for every cell (i.e. in our application not only the unit positions change, but the number of points at which to evaluate as well). Does that make a difference in the new version of the code? I can investigate further tomorrow.

**Comment by bergbauer** [comment]
> Is this supposed to be necessary?

No, but now we exactly know what the problem is. I have moved the responsibility to resize the values and gradients data fields from `evaluate()/integrate()` to `reinit()`. To support test cases 15-17 I introduced the bool `is_reinitialized` which triggers the `reinit()` call in `evaluate()/integrate()` internally (but only once), see https://github.com/dealii/dealii/blob/6a5df1fc493c96c35d52715a85e194175be0055b/include/deal.II/matrix_free/fe_point_evaluation.h#L980-L981

A question to code in ASPECT you referred to: Do you only use the `evaluate()` function of `FEPointEvaluation`?

I see two options how to solve this:
- We make it possible to call `FEPointEvaluation::reinit()` without arguments, this then would have to be called in user code after `NonMatching::MappingInfo::reinit()`. This would make it possible to get rid of the if statement at the beginning of `evaluate()/integrate()` and we would insert an assertion here instead.
- We adjust the if statement at the beginning of `evaluate()/integrate()` to catch the case where the number of unit points changes and call `reinit()` internally.

We should set up a test where the number of unit points changes so we do not break this with future changes. I will open a PR to address this issue.

**Comment by peterrum** [comment]
> We adjust the if statement at the beginning of evaluate()/integrate() to catch the case where the number of unit points changes and call reinit() internally.

I guess this is the backwards compatible approach? So I would be in favor if this.

**Comment by bergbauer** [comment]
@gassmoeller Can you try out  #14989 and confirm if it works for you?

**Comment by gassmoeller** [comment]
#14989 works, so once that is merged this issue can be closed.
