### ISSUE TITLE
FEInterfaceValues::reinit fails when neither element dominates

### ISSUE THREAD

**Issue by simonsticko** [dealii/dealii#15021]
As the title says. The following is an example (adapted from existing tests of FEInterfaceValues).
```c++

// Set up a two cells with different elements, such that neither element
// dominates. Create an FEInterfaceValues object and call reinit on it.

#include <deal.II/base/quadrature_lib.h>

#include <deal.II/fe/fe_interface_values.h>
#include <deal.II/fe/fe_q.h>
#include <deal.II/fe/fe_system.h>

#include <deal.II/grid/grid_generator.h>
#include <deal.II/grid/tria.h>

#include "../tests.h"

template <int dim>
void
make_2_cells(Triangulation<dim> &tria);

template <>
void
make_2_cells<2>(Triangulation<2> &tria)
{
  const unsigned int        dim         = 2;
  std::vector<unsigned int> repetitions = {2, 1};
  Point<dim>                p1;
  Point<dim>                p2(2.0, 1.0);

  GridGenerator::subdivided_hyper_rectangle(tria, repetitions, p1, p2);
}


template <int dim>
void
test()
{
  Triangulation<dim> tria;
  make_2_cells(tria);

  const unsigned      max_fe_degree = 2;
  const FESystem<dim> fe_left(FE_Q<dim>(1), FE_Q<dim>(2));
  const FESystem<dim> fe_right(FE_Q<dim>(2), FE_Q<dim>(1));

  hp::FECollection<dim> fe_collection;
  fe_collection.push_back(fe_left);
  fe_collection.push_back(fe_right);

  DoFHandler<dim> dofh(tria);
  dofh.distribute_dofs(fe_collection);

  const QGauss<dim - 1>          quadrature(max_fe_degree + 1);
  const hp::QCollection<dim - 1> q_collection(quadrature);


  const unsigned int face_index = 1;

  auto cell     = dofh.begin();
  auto neighbor = cell->neighbor(face_index);

  cell->set_active_fe_index(0);
  neighbor->set_active_fe_index(1);

  const UpdateFlags update_flags = update_values | update_gradients |
                                   update_quadrature_points | update_JxW_values;
  FEInterfaceValues<dim> fiv(fe_collection, q_collection, update_flags);
  fiv.reinit(cell,
             face_index,
             numbers::invalid_unsigned_int,
             neighbor,
             cell->neighbor_of_neighbor(face_index),
             numbers::invalid_unsigned_int);
}



int
main()
{
  initlog();
  test<2>();
}
```

Gives the error:
```
--------------------------------------------------------
An error occurred in line <456> of file </home/simon/workspace/dealii3/source/hp/fe_values.cc> in function
    void dealii::hp::FEFaceValues<dim, spacedim>::reinit(const dealii::TriaIterator<dealii::DoFCellAccessor<dim, spacedim, lda> >&, unsigned int, unsigned int, unsigned int, unsigned int) [with bool lda = false; int dim = 2; int spacedim = 2]
The violated condition was: 
    ::dealii::deal_II_exceptions::internals::compare_less_than(real_q_index, this->q_collections.size())
Additional information: 
    Index 65535 is not in the half-open range [0,1).
--------------------------------------------------------
```

The problem is on line 2494 in `fe_interface_values.h`. `find_dominated_fe` returns `numbers::invalid_fe_index` when neither element dominates.

```c++
const unsigned int dominated_fe_index =
        internal_hp_fe_face_values->get_fe_collection().find_dominated_fe(
          {cell->active_fe_index(), cell_neighbor->active_fe_index()});

      const unsigned int used_q_index =
        (q_index == numbers::invalid_unsigned_int ? dominated_fe_index :
                                                    q_index);
      const unsigned int used_mapping_index =
        (mapping_index == numbers::invalid_unsigned_int ? dominated_fe_index :
                                                          mapping_index);
```

How should we actually choose `q_index` and `mapping_index` when no element dominates? I could not figure it out by myself.

**Comment by marcfehling** [comment]
I missed this while preparing #14225. `find_dominated_fe()` now returns a `numbers::invalid_fe_index` instead of `numbers::invalid_unsigned_int`. You will need to adjust this in `fe_interface_values.h` and it should work. Can you also add your example as a test case?

**Comment by marcfehling** [comment]
We need to figure out what to do when `dominated_fe_index` is invalid. Is it critical in this case to find a dominated FE among the two? If not, we can simply pick one of the two FE indices as we do for example in [`dof_handler_policy.cc`](https://github.com/dealii/dealii/blob/982a52a150913752215d81d237d27b6a7e50fc0d/source/dofs/dof_handler_policy.cc#L504-L517), and we should pick the FE index of the current cell here. If yes, then I don't know how to deal with that. @fdrmrc, @jppelteret  -- Do you have an idea?

Also related to the decision in https://github.com/dealii/dealii/pull/14547#discussion_r1053319521.

**Comment by bangerth** [comment]
I don't see a good reason why we care about domination in this context. Domination only matters when computing constraints, but that's not what `FEInterfaceValues` does. What's the history for having this code block there? Was it there from the beginning of this file?

From looking at the code, the domination logic is only used to decide which quadrature formula and mapping to use if the user has not explicitly specified one for the given face. My guess is that we wanted to use this to determine which is the larger finite element space (the "dominated" one) and use the quadrature and mapping associated with that. If there is no dominating element at a face, it would not be unreasonable to say that the user needs to provide values for 7th to 9th argument, and to test this in an assertion.

**Comment by marcfehling** [comment]
The discussion got split among this issue and two PRs. Let's focus the discussion in this issue.

---

> I don't see a good reason why we care about domination in this context. Domination only matters when computing constraints, but that's not what `FEInterfaceValues` does. What's the history for having this code block there? Was it there from the beginning of this file?

This has been introduced after review in https://github.com/dealii/dealii/pull/14547#discussion_r1053319521, after it has been pointed out that `ScratchData` uses `FiniteElementDomination` across interfaces. I believe the reason is that it affects the calculation of jumps and averages of the solution at a face where two different DG elements meet.

@jppelteret -- Do you recall the importance of `FiniteElementDomination` in this context?

> If there is no dominating element at a face, it would not be unreasonable to say that the user needs to provide values for 7th to 9th argument, and to test this in an assertion.

That would be one way to deal with the problem if we want to stick to `FiniteElementDomination` here.

Then the question is whether we need to perform the change to `codim = 1` as we are only working on faces, which affects some tests with DG elements as in #15038 ([`meshworker/scratch_data_03_hp.cc`](https://github.com/dealii/dealii/blob/master/tests/meshworker/scratch_data_03_hp.cc), [`feinterface/fe_interface_values_11.cc`](https://github.com/dealii/dealii/blob/master/tests/feinterface/fe_interface_values_11.cc)). DG elements do not dominate over faces, so `find_dominated_fes` reports `no_requirements` and returns an invalid index.

It would help to understand the initial motivation for the choice of `FiniteElementDomination`.

---

Another option would be to get rid of the `FiniteElementDomination` logic and only use the active FE indices on the respective cells (if no indices have been provided by the user).

---

Parts of deal.II relevant for this discussion:
- https://github.com/dealii/dealii/pull/13181
- https://github.com/dealii/dealii/pull/14547#discussion_r1053319521
- https://github.com/dealii/dealii/blob/1eb854175b6ef54b3be930b115f0c8b5741b311b/include/deal.II/meshworker/scratch_data.h#L654-L660
- https://github.com/dealii/dealii/blob/1eb854175b6ef54b3be930b115f0c8b5741b311b/source/meshworker/scratch_data.cc#L315-L327
- https://github.com/dealii/dealii/blob/1eb854175b6ef54b3be930b115f0c8b5741b311b/include/deal.II/fe/fe_interface_values.h#L1482-L1496
- https://github.com/dealii/dealii/blob/1eb854175b6ef54b3be930b115f0c8b5741b311b/include/deal.II/fe/fe_interface_values.h#L2494-L2496

**Comment by bangerth** [comment]
#15099 will close this issue by providing a better error message, explained in great detail in #15098. I have some follow-ups that will actually make the test case herein work, but that's a second step.
