### ISSUE TITLE
Future direction of the different Vector classes in deal.II

### ISSUE THREAD

**Issue by Rombur** [dealii/dealii#15168]
The goal of this issue is to start a discussion on the future direction of the different Vector classes in deal.II. We have periodically made some efforts to converge the different Vector interfaces but we still cannot simply swap Vector classes . Before deciding on what a future API should look like, we need to decide on what's our goal: 

1. Do we want all the Vector types to have the exact same API so that we can easily swap Vector type? 
2. Do we want the Vector types to have similar API like we have now but offer an easy way to copy from one Vector type to another (for instance from a PETSc vector to a deal.II vector)?
3. Do we want to introduce a VectorView that doesn't own any data but implements a minimal interface shared by all the Vector types? All the deal.II functions would take this VectorView as input instead of a Vector which would significantly cut down on the number of template instantiations.

Each of these goals come with its own drawback:

1. While it sounds attractive to be able to switch from one Vector type to another without changing any code, we have to ask ourselves if it is desirable in practice. There is a price to pay to do it. We are restricted to the subset of functionalities that offered by all the libraries.
2. How different are we willing to let the interfaces and the behaviors of the Vector types be? Should every Vector type decide what's best given the underlying library?
3. We need to modify all the interfaces and the only gain compared to the current situation is to cut down the number of template instantiations.

Please feel free to share any thought you have on this issue.

**Comment by bangerth** [comment]
A relatively low-hanging fruit would be to introduce a `ReadWriteVectorView` (or simply `VectorView`) and switch everything in `namespace VectorTools` to use these instead of template arguments. These view classes would simply do type-erasure and forward to the underlying vector classes' member functions -- that incurs the cost of a virtual function call, but that would probably be a relatively minor cost compared to what these functions do. It would likely save substantial time and memory in a much reduced number of template instantiations.

This follows a similar model that we have used with `ArrayView`, which I think has generally been a useful class. The only difference is that the `ArrayView` model does not require dispatching to virtual functions.

**Comment by drwells** [comment]
We could get rid of the majority of our FEValues instantiations if we had a vector base class with a method `extract_subvector_to()`: in practice we just have static polymorphism explicitly covering Trilinos vectors in `dof_accessor.templates.h` and template member functions for the rest of the vector classes.

**Comment by bangerth** [comment]
That, too, could be done via a non-owning `VectorView` object.

**Comment by drwells** [comment]
I tried implementing `VectorView` in that way and ran into some issues. Passing in an object which has both a template argument and a converting constructor doesn't work because template resolution occurs before function overloading - i.e.,
```cpp
using namespace dealii;
template <typename T>
void foo(const ArrayView<const T> &v)
{
  std::cout << v.size() << std::endl;
}

int main()
{
  std::vector<int> v{1, 2, 3};
  foo(v);
}
```
cannot work.

One possibility would be to do extend the `ReadVector` draft to know how to create vector view classes. The present version of the class could provide batched access via virtual functions and direct access by creating a view:
```cpp
template <typename Number>
class ReadVector
{
public:
  // allow batched access in a standard way:
  void extract_entries(ArrayView<Number> &v, const ArrayView<const global_dof_index_type> &i) const;

  // use a proxy class for direct access:
  class VectorView
  {
  public:
    Number &local_element(const global_dof_index_type i)
    {
      return values[i];
    }

   Number &
   operator[](const global_dof_index_type i)
   {
      // implement this with perhaps this object owning an IndexSet for ghosts
   }

  protected:
    Number *values;
  };

  std::unique_ptr<VectorView<Number>> make_view();
}
```
We should make this class have a virtual dtor so that we can call `VecRestoreArrayRead()` etc. when they go out of scope, or other resource management.

**Comment by bangerth** [comment]
We've implemented `ReadVector`. Is there anything in here that isn't in #745? Or can we close this issue?
