### ISSUE TITLE
Bundled Kokkos + CUDA

### ISSUE THREAD

**Issue by drwells** [dealii/dealii#15432]
It looks like we can't configure our bundled copy of Kokkos to use CUDA - is this expected? I see the following message:

```
-- DEAL_II_WITH_KOKKOS has unmet external dependencies.
-- 
-- DEAL_II_WITH_KOKKOS successfully set up with bundled packages.
-- 
-- Include /home/drwells/Documents/Code/CPP/dealii/cmake/configure/configure_40_cuda.cmake
-- DEAL_II_WITH_CUDA has unmet external dependencies.
CMake Error at cmake/configure/configure_40_cuda.cmake:103 (message):
  

  Could not find any suitable cuda library!

  deal.II can only be compiled with Cuda support if Kokkos was built with
  Cuda support!
```

How hard would it be to build our own Kokkos with CUDA support? I would like to do this so I can test step-64.

**Comment by masterleinad** [comment]
We hardcode the Kokkos configuration to only provide the `Serial` backend for the bundled Kokkos copy so that we can avoid running `Kokkos` whole CMake configuration. It's not feasible to support building different backends if we don't commit to use `Kokkos`' build system.
If you want to test `step-64`, I would just use an external `Kokkos` installation (although `step-64` shouldn't really need `Cuda` support anymore anyway) like we do in our CI https://github.com/dealii/dealii/blob/a740622ea290243d8e44c28edb3bdb9230cd95bb/.github/workflows/linux.yml#L151-L169.

**Comment by drwells** [comment]
Thanks - I'll try that out and also see if I can put a better error message in the build system.
