### ISSUE TITLE
Transformations for FE_PolyTensor on non-affine grids

### ISSUE THREAD

**Issue by agrayver** [dealii/dealii#1548]
@maieneuro introduced missing terms to calculate gradients (and Hessian) for FE_PolyTensor in #1377 

This small program https://polybox.ethz.ch/public.php?service=files&t=28b6f0b0021707e88b8c8180dfb8cbea

constructs 2x2x2 mesh, creates Nedelec space and projects vector function (with divergence == 0). This is done for few global refinements. Here is output for rectangular mesh:
>DEAL::dim: 3	FE_Nedelec<3>(0)
>DEAL::DoFs	||u-u_h||	div(u_h)
>DEAL::300	1.13	0
>DEAL::1944	0.556	0
>DEAL::13872	0.278	0
>DEAL::104544	0.139	0

Note div = 0 as it should be.
By moving the central vertex a bit (change line 91 to Point<3> (0.2, 0., 0.)) we get:

>DEAL::dim: 3	FE_Nedelec<3>(0)
>DEAL::DoFs	||u-u_h||	div(u_h)
>DEAL::300	1.14	0.711
>DEAL::1944	0.558	0.815
>DEAL::13872	0.279	0.835
>DEAL::104544	0.139	0.839

Note that error decreases while divergence is not zero and even increases. This looks contradictory.

P. S. If you want to test on non-conforming meshes, call test function with the third argument = false
If you want to have non-standard faces (and various combinations of orientation/flip/rotate flags), (un-)comment lines 119-129.

**Comment by agrayver** [comment]
FWIW, here is output obtained with deal.II 8.2:
>DEAL::dim: 3	FE_Nedelec<3>(0)
>DEAL::DoFs	||u-u_h||	div(u_h)
>DEAL::300	1.14	0.704
>DEAL::1944	0.558	0.808
>DEAL::13872	0.279	0.831
>DEAL::104544	0.139	0.834

**Comment by maieneuro** [comment]
I may be missing something obvious, but is there a reason why we use a covariant mapping on the reference element shape functions to get the real cell shape functions for the nedelec element?

The reason I'm asking is that when I simply change the mapping type in FE_Nedelec to
```
this->mapping_type = mapping_piola;
```
The test submitted here passes for both the original mesh as well as the mesh with the moved central node. I get, respectively, the outputs:

DEAL::dim: 3	FE_Nedelec<3>(0)
DEAL::DoFs	||u-u_h||	div(u_h)
DEAL::300	1.15	0
DEAL::1944	0.565	0
DEAL::13872	0.283	0
DEAL::104544	0.143	0

and

DEAL::dim: 3	FE_Nedelec<3>(0)
DEAL::DoFs	||u-u_h||	div(u_h)
DEAL::300	1.13	0
DEAL::1944	0.556	0
DEAL::13872	0.278	0
DEAL::104544	0.139	0

**Comment by bangerth** [comment]
I don't understand the mathematics well enough to actually answer say why it is *not* doing as you suggest (and will therefore leave it to others). I can only contribute that I cannot say that I know the reason why it *is* doing what it is doing.

**Comment by rosskynch** [comment]
From the top of my head, I believe the Piola transformation is the one that should be used for curl-conforming elements, but the reasoning escapes me. I don't have time to look into it at the moment, but at least it matches with what Maien is seeing.

**Comment by agrayver** [comment]
By looking at [1] (it describes implementation of H(div) and H(curl) elements in FEniCS), it seems that covariant Piola mapping should be used for Nedelec elements to preserve continuity of the tangential traces.

[1] http://arxiv.org/pdf/1205.3085

**Comment by maieneuro** [comment]
That's a nice paper; I need to go through it in detail when I have the chance, thanks for the link. So the covariant mapping is the right one after all.

Just one thing, since FE_Nedelec is meant to be H(Curl) conforming, is the divergence test attached the right thing to look at? Shouldn't we be looking at something like
```
fe_values[vec].get_function_curls (v, curl_v);
```
instead of get_function_divergences? The element as it currently is gives sane values for the curls. I've modified the test (as in here https://drive.google.com/file/d/0B-7mnFLpdvqxalVxNy0zdnlYSmM/view?usp=sharing) and I'm getting the following results for the cartesian mesh and the moved-node mesh, respectively:

```
DEAL::dim: 3	FE_Nedelec<3>(0)
DEAL::DoFs	||u-u_h||	div(u_h)	curl(u_h)
DEAL::300	1.13	0	0
DEAL::1944	0.556	0	0
DEAL::8428	0.365	0	0
DEAL::26488	0.238	0	0
```
and
```
DEAL::dim: 3	FE_Nedelec<3>(0)
DEAL::DoFs	||u-u_h||	div(u_h)	curl(u_h)
DEAL::300	1.14	0.711	1.27e-12
DEAL::990	0.992	0.897	0
DEAL::2870	0.526	0.860	0
DEAL::9418	0.353	0.886	0
```

**Comment by agrayver** [comment]
In general, if we want to test new terms you've added we need something else than curl because they cancel there (curl(grad(u)) = 0 no matter what).
Alternatively, we can calculate curl(curl(u)) by using Hessians. Here is rectangular mesh:
>DEAL::dim: 3	FE_Nedelec<3>(0)
>DEAL::DoFs	||u-u_h||	curl(u_h)	curl(curl(u_h))
>DEAL::300	1.13	0	0
>DEAL::1944	0.556	0	0
>DEAL::13872	0.278	0	0
>DEAL::104544	0.139	0	0

and here is with the node moved:
>DEAL::dim: 3	FE_Nedelec<3>(0)
>DEAL::DoFs	||u-u_h||	curl(u_h)	curl(curl(u_h))
>DEAL::300	1.14	1.28e-12	1.49
>DEAL::1944	0.558	0	1.28
>DEAL::13872	0.279	0	1.23
>DEAL::104544	0.139	0	1.22

https://polybox.ethz.ch/public.php?service=files&t=6c26c0456d27f51df00522b489f3e678

**Comment by rosskynch** [comment]
Alexander asked me to try these tests with my new nedelec element which overcomes the orientation issue and also implements a different basis set based on gradients and non-gradients of the H1-conforming basis. I can't run the second (curl-curl) test with my element as I've not implemented the Hessians in it (I had no need for them). However, I have run the first test:

Rectangular:
DEAL::dim: 3	MyFE_Nedelec<3>(0)
DEAL::DoFs	||u-u_h||	div(u_h)
DEAL::300	1.13	0
DEAL::1944	0.556	0
DEAL::13872	0.278	0
DEAL::104544	0.139	0

Centre point moved:
DEAL::dim: 3	MyFE_Nedelec<3>(0)
DEAL::DoFs	||u-u_h||	div(u_h)
DEAL::300	1.15	        0.576
DEAL::1944	0.562	0.666
DEAL::13872	0.281	0.677
DEAL::104544	0.140	0.677

Note that I use the same mapping_type as was declared in the original FE_Nedelec element.

However, since these tests are being run at first order, I don't expect to see any difference - the basis set for p=0 is the same for both. I don't think I'd see any difference with the curl-curl test if I were to implement the hessians in my element either.

Surely this points to the transformation being the issue?

**Comment by maieneuro** [comment]
Is there a way to test continuity of the tangential traces with both transformations?

**Comment by rosskynch** [comment]
You could look at something like (for some domain \Omega with boundary \Gamma):

\int_{\Omega} curl(u)*v - u*curl(v) dV = \int_{\Gamma} (n \cross u)*v dS

where u, v are some functions in H(curl) and n is the normal vector. The RHS is the tangential trace.

I think the culprit is in the project function - I don't think it takes into account the residuals between edge and face-based shape functions when calculating the DoFS associated with the edges/faces of interior cells. E.g. see VectorTools::project_boundary_curl_conforming_l2 for details on how the projection should be handled on a boundary.

**Comment by agrayver** [comment]
@maieneuro regarding a proper space, I have tried H(div) conforming FE_RaviartThomas (this can easily be done by replacing the argument in the main function) and the problem remains. Here is rectangular mesh
>DEAL::dim: 3	FE_RaviartThomas<3>(0)
>DEAL::DoFs	||u-u_h||	curl(u_h)	curl(curl(u_h))	div(u_h)
>DEAL::240	1.45	0	0	0
>DEAL::1728	0.770	0	0	0
>DEAL::13056	0.391	0	0	0
>DEAL::101376	0.196	0	0	0

and node-moved mesh:
>DEAL::dim: 3	FE_RaviartThomas<3>(0)
>DEAL::DoFs	||u-u_h||	curl(u_h)	curl(curl(u_h))	div(u_h)
>DEAL::240	1.45	0	0.0130	0.00446
>DEAL::1728	0.774	0	0.00760	0.0120
>DEAL::13056	0.393	0	0.00653	0.0157
>DEAL::101376	0.197	0	0.00632	0.0176

Note the last column, div(u_h) != 0 and grows upon refinement. I guess if this was a numerical error, then div(u_h) would decrease upon refinement.

@rosskynch do you mean VectorTools::project? I do not think so because, in contrast to projection on boundary, this function works by inverting a volume mass matrix and since we see error decreasing this should be fine. Furthermore, solution is visually identical between two meshes.

**Comment by rosskynch** [comment]
@agrayver Having looked at the project code again, yes - I agree.

**Comment by maieneuro** [comment]
@agrayver Fair enough. A question that could help get to the bottom of this is the following: why is it true that these elements maintain the relevant property (e.g. being divergence free) after the transformation? And is that true even if the transformation is not affine? The assumptions used in proving this could perhaps give rise to specific tests to help better pinpoint the problem?

**Comment by agrayver** [comment]
@maieneuro fair point, some spaces do worse on non-affine meshes [1], but I'm not sure this explains problems we observe. 

To get a better view on the problem, I have further worked on the test to test seprately meshes with rectangular, parallelogram and non-affine cells in 2d and 3d: https://polybox.ethz.ch/public.php?service=files&t=1e19fc59a5fa63009312f139cd86ca0b

I have tested the following bases: FE_Nedelec, FE_RaviartThomas, FE_ABF (for 2d), FESystem(FE_Q, dim) by projecting function and integrating such quantifies as curl, curl(curl(u)) and divergence. 

The program output gets quite lenghty, so I just summarize here: 
1. In 2d everything works for all listed FEs on all types of grids (including non-affine case)
3. In 3d settings everything works except for non-affine case. In this case, curl(curl(u_h)) and div(u_h) give wrong results for all listed above FEs, whereas curl(u_h) is calculated correctly.

The most confusing part is that running this test in 3d with version 8.2 gives exactly the same result. It appears as if terms you've added have no effect on calculations. 

[1] http://umn.edu/~arnold/papers/vecquad.pdf

**Comment by rosskynch** [comment]
I put this to a colleague of mine... The transformations should work in the same way as the gradient of h1 conforming functions (since the functions are built from the gradient of the H1 basis). A special transformation for the curl (in the case of a Nedelec element) should be used which only requires computing derivatives with respect to the reference co-ordinate system. A similar transformation should be used for R-T elements when transforming the divergence.

A good place to look these up would be Peter Monk's book, Finite Element Methods for Maxwell's Equation.

So can we perhaps a test which makes use of the gradient of FE_Q would be a good idea?

Another thought: Given that curl(u_h) is working correctly... is the transformation used for the curl also being used for the other cases - could this be causing problems? perhaps they only differ for non-affine meshes?

Sorry that I can't look into this more closely myself, but I hope this helps.

**Comment by bangerth** [comment]
> I have tested the following bases: FE_Nedelec, FE_RaviartThomas, FE_ABF
> (for 2d), FESystem(FE_Q, dim) by projecting function and integrating
> such quantifies as curl, curl(curl(u)) and divergence.
>
> The program output gets quite lenghty, so I just summarize here:
> 1. In 2d everything works for all listed FEs on all types of grids
> (including non-affine case)

This is in itself a positive test that would actually be worthwhile 
having in the testsuite, just to make sure whatever changes we make in 
the future doesn't break tested and correct functionality. Would you 
mind adapting the 2d versions of your program into a test for the 
testsuite (or a set of tests, one for each tested element)?

**Comment by agrayver** [comment]
@bangerth sure, will do that.

**Comment by maieneuro** [comment]
@agrayver @rosskynch I've run a few tests and I think I've narrowed down the potential causes of the problem to two places: either there's a problem in combining the dofs_per_cell degrees of freedom in FEValues::get_function_*, or there's a discontinuity across cell boundaries in the function values.

The thinking process was as follows: we know that the divergence theorem-based tests work, and that FE_Nedelec elements pass them in a hyper_ball mesh which is rather general, so I've added to the test above an integration of the flux through the triangulation boundaries (https://drive.google.com/file/d/0B-7mnFLpdvqxNkJkTFBfanNuRFU/view?usp=sharing). For all the elements except FE_Nedelec in non rectangular meshes, the divergence integral over the bulk matched the flux integral over the boundaries. As a double check, I've also re-run the divergence-theorem-based test on FE_Nedelec on the meshes here (https://drive.google.com/file/d/0B-7mnFLpdvqxaWFpM29CQlJLZms/view?usp=sharing), and it passes for all cases.

So the divergence theorem test passes when run for each DoF on each cell separately, but it fails if it's run for a function over the entire triangulation. Unless I'm missing something, we can conclude from this that either combining the DoF's in get_function_divergences introduces an error, or there is a discontinuity across cell boundaries and so internal fluxes do not cancel out. Either of these could be related to what @rosskynch mentioned to some days ago?
>I think the culprit is in the project function - I don't think it takes into account the residuals between edge and face-based shape functions when calculating the DoFs associated with the edges/faces of interior cells. E.g. see VectorTools::project_boundary_curl_conforming_l2 for details on how the projection should be handled on a boundary.

In terms of the same behaviour being observed before and after adding the jacobian-inverse-derivative terms:

>The most confusing part is that running this test in 3d with version 8.2 gives exactly the same result. It appears as if terms you've added have no effect on calculations.

The rectangular and affine meshes should both give identical results because the jacobian is constant, and thus so is its inverse. For the non-affine mesh, are the numerical results also the same? In any case, the tests/fe/fe_nedelec_gradient_divergence_theorem fails in version 8.2 but passes in the version with the missing terms added, so they definitely come into play for a general transformation.

**Comment by bangerth** [comment]
Just for my own understanding: For the Nedelec element, all that is required is that the *tangential* component of the field is continuous across faces, but not the *normal* component. (And the other way around for the Raviart-Thomas element.) I believe that in your test you compare for a given field $u_h$ that
```
  \int_S  div u_h  =  \int_{dS}  n.u_h
```
where S is your integration domain and dS its boundary. This equality clearly holds for individual cells, because there the function is in C^infinity and so integration by parts works. But if you choose S to be the entire domain, I'm not sure. You could interpret the left side as the sum of the corresponding terms on each cell, do the integration by parts on each cell, and add up the integrals over the boundaries of all cells. But because the normal component `n.u_h` of the field is not continuous, the corresponding terms from both sides of interior faces do not necessarily cancel out. Or do I misunderstand what you are testing?

**Comment by bangerth** [comment]
By the way, I don't know whether that's going to help anything here, but a reasonable test would be to choose one of the basis functions defined on the reference cell (for which one can look up the definition), choose a non-parallelogram cell (e.g., the reference cell where one moves only one vertex), compute on a piece of paper how the shape function transforms to the real cell (using the transformation one can find in the literature for Nedelec elements), and then compare with this known correct answer what deal.II computes at a set of evaluation points.

This should clarify whether the problem is at the mapping/transformation stage, or elsewhere.

**Comment by maieneuro** [comment]
>For the Nedelec element, all that is required is that the tangential component of the field is continuous across faces, but not the normal component.

Thanks, that explains it. But in this case, shouldn't one account for discontinuities in the normal components across cell boundaries when assembling the divergence on the triangulation? Also, given the discontinuities, can we assume that the integral of the divergence exists in the first place? (One can ask these two questions for the curl_curl integral as well for all the elements tested, since the curl is not required to be continuous across element boundaries.)

For completeness sake, for each of the quantities, I've modified the test (https://drive.google.com/file/d/0B-7mnFLpdvqxdTJnRk94dUFZbzQ/view?usp=sharing) to also compute the corresponding surface integrals:

```
A_{tria}\int_{\Omega^e}  div u_h  =  A_{tria}\int_{\partial\Omega^e}  n \cdot u_h
A_{tria}\int_{\Omega^e}  curl u_h  =  A_{tria}\int_{\partial\Omega^e}  n \times u_h
A_{tria}\int_{\Omega^e}  curl (curl u_h)  =  A_{tria}\int_{\partial\Omega^e}  n \times curl (curl u_h)
```
(A_{tria} indicating assembly over the triangulation). By uncommenting line 365, the traces are assembled only on the triangulation boundary and discontinuities across internal element boundaries can be detected.

The results are lengthy as well, but the main points are:

1. The quantities computed by surface integrals including internal element boundaries match those computed by volume integrals for all elements on all meshes.
2. The quantities computed by a surface integral on the mesh boundary (and not accounting for internal element boundaries) match the volume integral ones on all meshes for all elements for which they are supposed to, but (as expected) differ in some instances where internal continuity is not enforced.

**Comment by agrayver** [comment]
@maieneuro I have slightly modified the program: https://polybox.ethz.ch/public.php?service=files&t=ae799ceed4de0c18a0f485230a047ed6

Most importantly we forgot to initialize some variables with zero, this precluded us from seeing actual numbers. I have also made the non-affine grid more non-affine to make difference more profound. 

Here is what we have for dim=3 on non-affine mesh:
>DEAL::
>Non-affine grid:
>dim: 3	FE_Nedelec<3>(1)
>DEAL::DoFs		||u-u_h||_1	curl(u_h)	tangentials	curl(curl(u_h))	curl_curl_traces	div(u_h)	boundary_flux
>DEAL::1944		0.800		0.00658		0.00658		0.988		0.988			-0.00763	-0.00763
>DEAL::13872		0.197		0.00203		0.00203		0.612		0.612			-0.00162	-0.00162
>DEAL::104544		0.0488		0.000334	0.000334	0.550		0.550			-0.000372	-0.000372
>DEAL::dim: 3	FE_RaviartThomas<3>(1)
>DEAL::DoFs		||u-u_h||_1	curl(u_h)	tangentials	curl(curl(u_h))	curl_curl_traces	div(u_h)	boundary_flux
>DEAL::1728		1.15		0.00429		0.00429		1.06		1.15			0.0168		0.0168
>DEAL::13056		0.272		0.000837	0.000837	0.886		0.969			0.00381		0.00381
>DEAL::101376		0.0673		0.000198	0.000198	0.867		0.950			0.000624	0.000624
>DEAL::dim: 3	FESystem<3>[FE_Q<3>(1)^3]
>DEAL::DoFs		||u-u_h||_1	curl(u_h)	tangentials	curl(curl(u_h))	curl_curl_traces	div(u_h)	boundary_flux
>DEAL::375		1.70		0.0383		0.0383		2.57		2.57			-0.00473	-0.00473
>DEAL::2187		0.342		0.00230		0.00230		2.13		2.13			-9.88e-05	-9.88e-05
>DEAL::14739		0.0797		0.000222	0.000222	2.05		2.05			-2.23e-06	-2.23e-06

We get all things right for all bases, except curl(curl(u)). It was also my mistake to say that there is no difference w.r.t. 8.2, on non-affine mesh there is a difference and indeed added terms make it right. 

The only thing that is is to be figured out is why curl curl does not converge to zero?

**Comment by maieneuro** [comment]
>Most importantly we forgot to initialize some variables with zero, this precluded us from seeing actual numbers.

oops. Nicely caught!

>The only thing that is to be figured out is why does not curl curl converge to zero?

Maybe it's because of the element order? Here are the outputs for the first two refinement cycles for a 2nd order element (the third cycle is taking a while, will add it in an edit when it's done).

DEAL::
Non-affine grid:
dim: 3	FE_Nedelec<3>(2)
DEAL::DoFs ||u-u_h||_1 curl(u_h) tangentials	curl(curl(u_h))	curl_curl_traces div(u_h)	boundary_flux
DEAL::6084 0.111 0.000693 0.000693	0.220	0.220 -0.00840	-0.00840
DEAL::45000 0.0129 0.000156 0.000156	0.0509	0.0509 -0.00167	-0.00167

For a 3rd order one:

DEAL::
Non-affine grid:
dim: 3	FE_Nedelec<3>(3)
DEAL::DoFs ||u-u_h||_1 curl(u_h) tangentials curl(curl(u_h)) curl_curl_traces div(u_h) boundary_flux
DEAL::13872 0.0121 0.000414 0.000414 0.0495 0.0495 0.000151 0.000151
DEAL::104544 0.000745	2.12e-05	2.12e-05	0.00928 0.00928 8.07e-06 8.07e-06

**Comment by maieneuro** [comment]
More importantly though is that the curls are not necessarily continuous across cell boundaries; and so if the integral of their derivatives within the domain (if it exists) is to be computed, one must take into account the traces in the internal cell boundaries. That means subtracting, from the bulk integral of the curl curls, the surface integral of the tangential components of the curls computed on internal cell boundaries. The same goes for the divergence integral in Nedelec elements, because the normal components of shape values are not necessarily continuous across cell boundaries. This is done by this slightly further modified version of the tests (https://drive.google.com/file/d/0B-7mnFLpdvqxeVduUklaNHdwelE/view?usp=sharing), which gives the following results for order 1 and order 2 elements:
```
DEAL::
Non-affine grid:
dim: 3	FE_Nedelec<3>(1)
DEAL::DoFs ||u-u_h||_1 curl(u_h) tangentials curl(curl(u_h)) curl_curl_traces div(u_h) boundary_flux
DEAL::1944 0.800 0.00658 0.00658 0.161 0.161 -0.0262 -0.0262
DEAL::13872 0.197 0.00203 0.00203 0.0650 0.0650 -0.00449 -0.00449
DEAL::104544 0.0488 0.000334 0.000334 0.0209 0.0209 -0.000629 -0.000629
```

```
DEAL::
Non-affine grid:
dim: 3	FE_Nedelec<3>(2)
DEAL::DoFs ||u-u_h||_1 curl(u_h) tangentials curl(curl(u_h)) curl_curl_traces div(u_h) boundary_flux
DEAL::6084 0.111 0.000693 0.000693 0.0406 0.0406 0.00359 0.00359
DEAL::45000 0.0129 0.000156 0.000156 0.0170 0.0170 0.000848 0.000848
```

**Comment by agrayver** [comment]
@maieneuro makes sense. This probably resolves this issue, does not it? I guess we can make a test out of this and also we can update documentation on FE_Nedelec page with regard to support on non-affine cells. I can construct a test. Would you be willing to update documentation to take the credit for really fixing it?

I also wanted to run a test on curved elements with high-order mappings, but there seems to be an unrelated issue #1646

**Comment by maieneuro** [comment]
@agrayver sounds good. I'll update the documentation shortly. Thanks for raising this issue and for the tests and discussion.

**Comment by bangerth** [comment]
>     For the Nedelec element, all that is required is that the tangential
>     component of the field is continuous across faces, but not the normal
>     component.
>
> Thanks, that explains it. But in this case, shouldn't one account for
> discontinuities in the normal components across cell boundaries when
> assembling the divergence on the triangulation?

Of course. Your question pertains to what equations one can use the Nedelec 
element for. There is no problem if you want to solve the equation
   (curl u_h, curl v_h) = (f,v_h)
i.e., the equation
   curl curl u = f
Here, the integral only ever contains curls, and so the discontinuity of the 
normal component does not matter. On the other hand, you cannot, for example, 
solve the Laplace equation with this element in any straightforward way, because
   \int_Omega  nabla u_h  cdot  nabla v_h
is not equal to the piecewise integral
  \sum_K \int_K nabla u_h cdot nabla v_h
which we typically compute: the gradient nabla u_h is singular on the 
interfaces between cells because the normal component of u_h is discontinuous. 
So if you wanted to solve the Laplace equation with Nedelec elements (which 
nobody would want to do, that's not what the Nedelec element was invented 
for), you'd have to add extra penalty terms to your formulation that penalize 
the jump of the normal component of u_h.

The same is true if, for example, you wanted to use the Raviart-Thomas element 
for the Laplace equation -- there you have to penalize the jump in the 
tangential component of u_h across interior faces.


> Also, given the
> discontinuities, can we assume that the integral of the divergence exists in
> the first place?

No. The divergence of an FE_Nedelec field contains delta functions along all 
interior interfaces. So, just like above, you will have that

   \int_Omega  div u_h
is not equal to the piecewise integral
   \sum_K \int_K  div u_h



> (One can ask these two questions for the curl_curl integral
> as well for all the elements tested, since the curl is not required to be
> continuous across element boundaries.)

Correct again. This is no different than asking whether the integral over 
second derivatives of a Q(p) element exist or converge -- the answer being no. 
This is actually easier to see here: think for example of a linear element in 
1d (or on triangles) where the second derivatives are all zero in the cell 
interiors, but since the gradient is discontinuous, the second derivatives of 
the field u_h *as a whole* simply consists only of delta functions on the 
interfaces. For p>1, there are nonzero second derivatives in the interior of 
the cells, but you do not have

   nabla^2 u_h   ->   nabla^2 u

in a pointwise sense, and you certainly also don't have convergence of

   sum_K \int_K  nabla^2 u_h    ->    \int_\Omega   nabla^2 u

because the former "forgets" about the contributions from interfaces. In fact, 
I wouldn't know that the former converges to anything at all.

The situation for the Nedelec element is similar, curl curl u_h simply being a 
subset of the full tensor of second derivatives.

**Comment by bangerth** [comment]
I haven't tried to completely understand your data, but do I understand correctly that you two have convinced yourself that the results you get are in fact correct?

If so, as always, if anything of this could be turned into more tests then that would be greatly appreciated!

**Comment by agrayver** [comment]
@bangerth yes, if one thinks carefully through peculiarities of each space and accounts for them accordingly, then results make sense. At least, I do not see any inconsistency anymore. I will construct a test.
