### ISSUE TITLE
Performance analysis of step-68 performance test

### ISSUE THREAD

**Issue by kronbichler** [dealii/dealii#15650]
I quickly looked into the new `timing_step_68` performance test. I would like to collect some ideas for possible improvement. Not all will benefit the real applications, but I think they are nonetheless interesting for us:
- I see that `VectorTools::interpolate` comes with a relatively high cost (25% of total instruction count in this program with 2 MPI ranks). Inside that function, we do `convert_generalized_support_points_values_to_dof_values` and various related things that are necessary in the general case, but not for `FE_Q`. We could think about re-assessing that setup.
- `euler_step_interpolated` calls https://github.com/dealii/dealii/blob/8aa0f4d35b3243b7094b4987399a83a15e503d0b/tests/performance/timing_step_68.cc#L363-L364 for every particle, this should be called once and use the stored value.
- At least in 2D and for linear polynomials, `NonMatching::MappingInfo::reinit()` takes too much time. We call `Subscriptor::subscribe` for every call, we use `dynamic_cast` twice inside `compute_mapping_data_for_quadrature`, and several similar things that should be possible to avoid to call for every point (the total cost is around 7%, and we should get that below 3-4%)
- We currently use https://github.com/dealii/dealii/blob/8aa0f4d35b3243b7094b4987399a83a15e503d0b/tests/performance/timing_step_68.cc#L342-L344 that allocates a new vector on every cell. We should move `std::vector` out of the loop over the particle handler, call `particle_positions.clear()` on the cell and then fill the data. This will only do a few allocations.
- Inside `ParticleHandler::sort_particles_into_subdomains_and_cells`, I see a rather high cost in `GridTools::Cache::get_vertex_to_cell_map` that seems to be re-created for every call. Maybe we can store that somewhere, I did not check carefully.

When we have addressed some of those (or refuted the initial measurements), we should have another look. Of course, we might also accept some inefficiencies here because this is not the final application.

**Comment by tamiko** [comment]
@blaisb *ping*

**Comment by blaisb** [comment]
@tamiko  and @kronbichler . Ouhh, very good suggestions. I will look into them. Some of these are artificially linked to step-68 and don't mean much in terms of performance. However, the information regarding the mapping and the sort_particles_into_subdomain_and_cells is general to every cases. I will look more into this in the following week :).

**Comment by blaisb** [comment]
@kronbichler Another thing I am wondering is the following:
https://github.com/dealii/dealii/blob/master/source/particles/particle_handler.cc#L1374

When we sort particles into subdomain and cells, we first identify the closest vertex, then search the cells in the vicinity of that vertex. Should that fail, we proceed with searching the other cells (for which the comments could definitely be improved).

I think this premise is a bit flawed. It inherently assumes that the particle CFL number would be significantly below 1. I wonder if we could get better performance by removing the distance calculation and testing right away with all neighbouring cells all at once?

**Comment by masterleinad** [comment]
> I think this premise is a bit flawed. It inherently assumes that the particle CFL number would be significantly below 1. I wonder if we could get better performance by removing the distance calculation and testing right away with all neighbouring cells all at once?

That heavily depends on the use case, right? How expensive is this first search compared to the other ones anyway?

**Comment by blaisb** [comment]
Well the current code does actually something different. It uses Boost::rtree to search for the closest vertex in the entire domain, and then searches in the neighbouring of that vertex.

But I agree, most likely right now the cell is generally always identified in the first loop. I could try to cook up a small performance analysis to see where we actually end-up in most cases.

**Comment by masterleinad** [comment]
How expensive is `sort_particles_into_subdomains_and_cells` in the benchmark and which of its parts is critical? Would it make sense to parallelize some of the loops using `OpenMP`/`Kokkos` or similar?

**Comment by blaisb** [comment]
> How expensive is `sort_particles_into_subdomains_and_cells` in the benchmark and which of its parts is critical? Would it make sense to parallelize some of the loops using `OpenMP`/`Kokkos` or similar?

It depends a lot on the application. For us it is an expensive part of the DEM (say 30%), but that depends on the density of the flow. The more "free flowing" the particles are, the more expensive this step is.

**Comment by blaisb** [comment]
@kronbichler . Fixing the MPI issue you pointed out (the call to getting the proc id) changed the performance significantly enough to be captured by the tester:
https://dealii.org/performance_tests/graphs/whistler-bullseye-gcc-10/timing-step_68.png

btw @tamiko  this performance benchmark thing is just freaking awesome to have.

**Comment by bangerth** [comment]
We should get @gassmoeller 's input on this. He spent a large amount of time on figuring out which of several strategies works best!

**Comment by gassmoeller** [comment]
I am at a workshop right now and on vacation for two weeks afterwards, so substantial input might take a while, but here are some thoughts: I am sure there is a lot of optimization potential in step-68 and as long as we do not make the code too specific or hard to read we should probably make sure to make it efficient enough to be used as a template for users. 

 Regarding your points @kronbichler:
- Curious that `GridTools::Cache::get_vertex_to_cell_map` takes so much time, the cache is intended to prevent the recreation, something must go wrong there. Should be worth looking into.
- Regarding avoiding the `push_back` memory allocation that is definitely a change that should be made (and is easy)
- `VectorTools::interpolate` is mostly necessary because we interpolate from a function into a finite element space. For this example we could also just evaluate the function directly. However, that would not be the most common use case for users. I would think that most user codes would not run into this performance bottleneck though, because they acquire their velocity from a finite element solution, which does not need to be interpolated.

In our experience the relative cost of different parts of the particle algorithm can change quite a bit depending on the application, in particular depending on:
- how many particles per cell? 
- how expensive are cell operation vs particle operations? 
- how often is mesh refinement happening
So whether the performance optimizations in step-68 actually translate into user codes may depend on the application, but of course we can make reasonable optimizations to help them set up efficient applications.

**Comment by gassmoeller** [comment]
I looked a bit into a few of the suggestions. #15832 takes care of one.

> Inside ParticleHandler::sort_particles_into_subdomains_and_cells, I see a rather high cost in GridTools::Cache::get_vertex_to_cell_map that seems to be re-created for every call. Maybe we can store that somewhere, I did not check carefully.

I looked into that, but I only see ~100 recreations of `get_vertex_to_cell_map` for 500 time steps, which is necessary, because we repartition the mesh every 5 timesteps. So the cache seems to work correctly, but the creation of the map is somewhat expensive at the moment. The most expensive part is that for every cell and every vertex we insert that vertex into a small set to filter out duplicates. This insertion into the set seems slow, but I dont know if a manual filtering would be faster (e.g. by searching through a vector and appending if the vertex is new). I think this part mostly shows up, because we have somewhat few particles for quite many cells in this example.

In regard to another topic @blaisb wrote earlier:

> I think this premise is a bit flawed. It inherently assumes that the particle CFL number would be significantly below 1. I wonder if we could get better performance by removing the distance calculation and testing right away with all neighbouring cells all at once?

I have tested different algorithms when I implemented this part and at least for cells with higher order mappings it is always the inversion of the mapping that dominates the cost. In other words minimizing the number of cells to try (and therefore mappings to invert) is the most important function of that algorithm. I could see that in some cases for MappingEulerian a different approach where we simply test all neighbors may be faster (although in these cases the total cost of the current algorithm is likely still not much higher). In fact I see that the comment in the code is slightly out of date, the algorithm does not simply test all cells around the closest vertex, it also orders them so that it encounters the likeliest cells first (see Figure 1 in https://agupubs.onlinelibrary.wiley.com/doi/full/10.1029/2018GC007508 for an explanation).

**Comment by kronbichler** [comment]
The issue with `VectorTools::interpolate` has been addressed by #16843, the call to `Subscriptor`. Other issues were fixed by @gassmoeller and @blaisb as discussed in the performance section. I think the final topic left in my initial post for this issue is `NonMatching::MappingInfo`, which I hope to tackle soon. That means we can schedule this for the 9.6 release.
