### ISSUE TITLE
Step-12 Solver should use SolverGMRES

### ISSUE THREAD

**Issue by nils-schween** [dealii/dealii#15984]
When talking with @bangerth during the deal.ii workshop we noticed that a Richardson Solver is used in Step-12. Wolfgang suggested that a GMRES solver was a better choice. Maybe it could be changed?

Thanks. 
Nils

**Comment by tamiko** [comment]
@nils-schween Yes, absolutely. 

I just tested this: when increasing the number of refinement cycles to 9/10 then the Richardson iteration will fail (for any number of iterations).

Would you mind to open a pull request that changes `SolverRichardson` over to `SolverGMRES`?
It would be good to also tune the GMRES parameters mildly so that the number of iterations for small refinement levels (say for refinement cycles 4-8) between Richardson and GMRES is comparable.

**Comment by bangerth** [comment]
For context, I believe that step-12 comes from a time when we used things in tutorials _because we could_, not necessarily because it was the right thing. We tried to show as many things as we could, but in hindsight, I think we all know that that was not always the best choice.

**Comment by nils-schween** [comment]
I am sorry that it took so long to create the PR. I was very busy. I increased the size of the Arnoldi basis to 100 to keep the number of iterations comparable to the Richardson Solver. Using the GMRES Solver I cannot naively increase the number of refinement cycles above 7. Keeping the number of allowed iterations 1000 and the basis size 100, the GMRES solver does not converge in cycle 7. Whereas the Richardson Solver does not converge in cycle 9. My general impression is that the RichardsonSolver works quite well in the case of the tutorial. Nonetheless with the increased size of the basis both solvers work well for the number of refinement cycles used in the actual tutorial, i.e. 12. You can decide if you would like to change the solver.

You should check how I adapted the tutorial.
