### ISSUE TITLE
deal.ii vector and block_vector interaction

### ISSUE THREAD

**Issue by taojinllnl** [dealii/dealii#16366]
Dear all,

I am writing a BFGS solver for a nonlinear problem. In this process, I need to perform some routine vector operations for the BFGS matrix update. For instance, I define a BlockVector and a Vector: 

    BlockVector<double> BFGS_update(m_dofs_per_block);
    Vector<double> BFGS_r_vector(m_dof_handler.n_dofs());
where *BFGS_update* has a block structure that are related to two different fields, and *BFGS_r_vector* is just a regular Vector for BFGS matrix update.

Inside deal.ii "block_vector.h" and "vector.h", there are "operator=" defined to convert a BlockVector into a Vector and vise versa. For instance, both codes below are legal:
    `BFGS_update = BFGS_r_vector;`
or
    `BFGS_r_vector = BFGS_update;`

However, there are no definition of "operator+=" to add a BlockVector to a Vector. For instance, the following code is illegal:
    `BFGS_r_vector += BFGS_update;`

In order to perform the add-on operation, I need to first define a temporary Vector, assign the BlockVector to this temporary Vector, and then perform the += operation:

   `Vector<double> BFGS_temp_vector(m_dof_handler.n_dofs());`
    `BFGS_temp_vector = BFGS_update; // BFGS_update is a BlockVector`
    `BFGS_r_vector += BFGS_temp_vector;`

This seems rather awkward. Can we just define operator+= that is able to take either a Vector or a BlockVector?

Best,

Tao Jin

**Comment by bangerth** [comment]
I am not in favor of this. The vector API is large enough, and if we were to add these sorts of operations, we'd have to add these functions to the deal.II vectors, the Trilinos wrappers, the PETSc wrappers, the parallel vector classes, etc. Then it would of course be awkward to have `operator+=` but not `operator-=`. Let's not go there -- my recommendation is to settle either on vectors or block vectors, rather than try to mix and match them all.
