### ISSUE TITLE
Make sure all generic template definitions are in *.templates.h files

### ISSUE THREAD

**Issue by tamiko** [dealii/dealii#16484]
This is something that annoys me.

We generally do a good job of putting all template definitions of generic into `*.templates.h` header files. But there is the occasional outlier. This is highly frustrating when trying to work around or debug instantiation issues without modifying or recompiling deal.Ii itself. This is particularly true for the case when deal.II is installed via package manager or via the mac bundle.

TODO:
 - [ ] `dof_tools.cc` -> `dof_tools.templates.h`
 - [ ] ...

**Comment by drwells** [comment]
I don't have strong feelings either way about this - if it helps some debugging cases then we should do it.

To the best of my knowledge, our rule is (right now) that we only put things which users might want to instantiate themselves (e.g. `Vector<long double>`) in the `.templates.h` file; everything else should be in the `.cc` file. That's probably written down somewhere in our documentation or style guide. We should update it to clarify our expectation if we consistently make this switch.

**Comment by bangerth** [comment]
The rule we used  in the past (which I think is good) is that only those functions should be in a `.templates.h` file that have template arguments users might reasonably provide that we cannot foresee. On the other hand, functions that only depend on `dim,spacedim` need not be in such files because we *know* what values these could possibly have, and so they go into a `.cc` file.

**Comment by tamiko** [comment]
Nevermind.

**Comment by tamiko** [comment]
Superseded by #16493
