### ISSUE TITLE
fe/fe_project_3d regularly times out

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#1700]
This test is too expensive. We either need to break it into multiple tests that each run shorter, or figure out where it spends its time.

(As a general rule, constructing higher order Nedelec elements is dog slow. I'd love to learn which function is responsible for this.)

**Comment by bangerth** [comment]
For reference, the test runs 36 seconds in release mode. It times out after 600 seconds on an otherwise pretty empty system.

**Comment by agrayver** [comment]
Construction of elements should not be the problem here. In particular,  0199c41 addressed the issue with FE_Nedelec by moving expensive stuff out of constructor. Further, this test uses p=1, this wasn't that expensive anyway. 

I have profiled the test and by far the longest time is spent in this loop https://github.com/dealii/dealii/blob/master/tests/fe/fe_project_3d.cc#L317

Where 80% of the time is spent because of calculating curl-curl (which requires update_hessians).

Should it be removed?

Also, RT is twice slower than Nedelec.

**Comment by bangerth** [comment]
Do you happen to know which part of this loop is the culprit? Only `reinit()` really looks expensive...

**Comment by kronbichler** [comment]
I can confirm that most time is spent in FEValues::reinit. Here is a callgrind profile for release mode:
![image](https://cloud.githubusercontent.com/assets/8276200/10229682/b224006a-6879-11e5-9599-7d2441c34166.png)

Since this test is supposed to test second derivatives, the only simple possibility (except for speeding up the code of course) is to reduce the number of refinements. I guess that the test is sensitive enough already for 2 cycles (i.e. 64 cells instead of 512).

As to code optimizations: I will have a look at FE_PolyTensor::fill_fe_values and MappingQGeneric::transform (rank 3 tensor version) to see if there are obvious improvements.

**Comment by Rombur** [comment]
In debug mode more than 50% is spent in dealii::(anonymous)::transform_hessian. That's where all the time in MappingQGeneric::transform is spent. 

One of the reason the debug mode is so much slower than the release mode is because of the asserts when accessing elements. About 42% of the time is spent in include/deal.II/base/tensor.h at line 851 and another 10% in include/deal.II/base/derivative_form.h line 246 
transform_hessian is the only non-trivial function that takes time in debug mode (it takes 15% by itself).

PS: I just killed valgrind after two hours so it's possible that the accessing of elements takes even more time.

**Comment by tjhei** [comment]
> already for 2 cycles

so let's just do 2 cycles in 3d and call it a day...

**Comment by bangerth** [comment]
Thanks, Martin. It's of course sad that computing *anything* on 13k cells takes any kind of time at all. But that's for another time to fix.

**Comment by bangerth** [comment]
For the record, the test ran for 20m30s in debug mode on my machine, compared to 36 seconds in release mode :-(
