### ISSUE TITLE
Error in `multigrid-global-coarsening/multigrid_util.h`

### ISSUE THREAD

**Issue by tamiko** [dealii/dealii#17118]
As mentioned by @bangerth in #17117:
```
/scratch/dealii/tests/multigrid-global-coarsening/multigrid_util.h(223): error: no instance of overloaded function "dealii::FEEvaluation<dim, fe_degree, n_q_points_1d, n_components_, Number, VectorizedArrayType>::submit_value [with dim=2, fe_degree=-1, n_q_points_1d=0, n_components_=1, Number=double, VectorizedArrayType=dealii::VectorizedArray<double, 1UL>]" matches the argument list
            argument types are: (dealii::Tensor<1, 1, dealii::VectorizedArray<double, 1UL>>, unsigned int)
            object type is: dealii::FEEvaluation<2, -1, 0, 1, double, dealii::VectorizedArray<double, 1UL>>
          detected during:
            instantiation of "void Operator<dim_, n_components, Number>::rhs(Operator<dim_, n_components, Number>::VectorType &) const [with dim_=2, n_components=1, Number=double]" 
/scratch/dealii/tests/multigrid-global-coarsening/events_non_nested.cc(126): here
            instantiation of "void test<dim,Number>(unsigned int, unsigned int, __nv_bool) [with dim=2, Number=double]" 
/scratch/dealii/tests/multigrid-global-coarsening/events_non_nested.cc(152): here
```
@kronbichler @peterrum

**Comment by kronbichler** [comment]
Which compiler is this @bangerth? I did not immediately find it. My point is that there should not be the argument list `(dealii::Tensor<1, 1, dealii::VectorizedArray<double, 1UL>>, unsigned int)` for `n_components==1` because the test contains `if constexpr` to filter that case away: https://github.com/dealii/dealii/blob/5a49ec4209422ce316589dcf0a5de4666bbd724c/tests/multigrid-global-coarsening/multigrid_util.h#L209-L224
We might want to allow additional types in `submit_value` in terms of `submit_value`, i.e., extending https://github.com/dealii/dealii/blob/5a49ec4209422ce316589dcf0a5de4666bbd724c/include/deal.II/matrix_free/fe_evaluation.h#L364-L368 to `n_components == 1` instead, but for this I would need a compiler to check against.

**Comment by bangerth** [comment]
I must admit that I didn't write it down. I got there by following the links in #17117, but I don't recall which it was :-(

**Comment by kronbichler** [comment]
As this bug has not been observed again, let me close the issue. We can always open a new issue in case something similar happens again.
