### ISSUE TITLE
get_manifold() policy

### ISSUE THREAD

**Issue by nicola-giuliani** [dealii/dealii#17810]
Hi all, i think there is an inconsistency between thè implementazione and the public documentation of get_manifold() .

From the documentation (9.6 and dev) It seems that if no manifold is found the default flat manifold should be returned. From the source code an assert is throw if the manifold is not found. 

From the changelog of release 9.6 it seems that an assert should be thrown of a non existing manifold_id is passed but not that it is thrown if no manifold is set. From the documentation I can set manifold ids without setting a manifold and I expect flat manifold by default. 

What should be the expected behavior?

**Comment by bangerth** [comment]
Yes, I'm sure we're inconsistent in these places because historically we allowed setting manifold ids that did not correspond to already set manifolds. What we found is that that leads to all sorts of difficult to find bugs.

I think the expected behavior should be to use a system that is maximally useful for finding bugs. So, "It seems that if no manifold is found the default flat manifold should be returned [by get_manifold()]. From the source code an assert is throw if the manifold is not found." Here, the implementation seems right to me and the documentation wrong. You shouldn't be able to ask for something that doesn't exist.

Does this make sense from a *conceptual* perspective? We would of course love to take patches to address these inconsistencies!

**Comment by peterrum** [comment]
@nicola-giuliani Is this the only sentence, you are referring to:

https://github.com/dealii/dealii/blob/d9582acac8f4e368122610388d85424a0b18ef23/include/deal.II/grid/tria.h#L1962

? If yes, you could change that to state that an exception is thrown.
