### ISSUE TITLE
Time the effect of #1841

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#1842]
#1841 undoes some parallelization work in `FESystem::fill_fe_values`. I'm curious about the impact this has, for example on assembly in a program like step-22. It seemed to me that the work done in `fill_fe_values` is substantial enough to allow for multiple threads to work together. As @kronbichler pointed out, this has large detrimental effects on performance in `WorkStream`. I'm curious, though, what it means for single-threaded programs, mostly out of curiosity.

**Comment by kronbichler** [comment]
I just made a quick test on my laptop (2 cores/4 threads Broadwell i7) in the assemble part of step-22, going through cycles 0 to 5 in 2D; since only 2 tasks are generated in FESystem::compute_fill_one_base it should be representative also for systems with more parallelism:
```
  tasks  |  no_tasks
0.001894 |  0.001015
0.004797 |  0.002558
0.011777 |  0.008626
0.018732 |  0.014982
0.043870 |  0.033516
0.116135 |  0.073282
```
Interestingly, despite using workers the code gets slower. The impact is actually quite substantial since FEValues::reinit should take less time than the actual computation of matrices, I'd assume 0.01 to 0.02 seconds for the last data row.

**Comment by kronbichler** [comment]
Note that these numbers are without NUMA. It might get worse on a NUMA machine (but probably not very much when running only with a single thread where non-local memory initialization only increases latency; in the fully threaded case one would also expect data traffic between NUMA domains that could hurt unless the non-data can remain in the L1/L2 cache of the worker).

So I guess it is rather that we are looking at a thread overhead problem here.

**Comment by kronbichler** [comment]
I ran the same step-22 in 3D:
```
tasks    | no_tasks
0.024005 | 0.021294
0.107698 | 0.092989
0.520431 | 0.500591
2.34575  | 2.22813
8.54464  | 7.40178
32.1209  | 31.3125
```
Despite larger tasks and possibly less overhead, using tasks slows things down.

**Comment by bangerth** [comment]
Ah, great, thanks for doing these experiments. I didn't mean to imply that someone else should do it when I opened this issue, but I gladly take any help I can get :-)

**Comment by kronbichler** [comment]
I know, but I was curious enough myself... :-)
