### ISSUE TITLE
Doxygen error in Schur Complement linear operator

### ISSUE THREAD

**Issue by jppelteret** [dealii/dealii#2049]
In the online documentation, there's a equation thats not rendered due to `\textnormal` being undefined in math mode. However, it builds fine locally (doxygen v1.8.10). If someone can suggest what the correct syntax then I'll correct the issue.

**Comment by bangerth** [comment]
For reference, this is https://www.dealii.org/developer/doxygen/deal.II/group__LAOperators.html#ga1cb1a9bb9e30355214718b66ac71d107

**Comment by bangerth** [comment]
I think the correct command (used elsewhere) is to simply use `\text`. A patch would be welcome!

**Comment by bangerth** [comment]
(By the way, the online website linked to above creates this error because the MathML representation of this formula uses `\textnormal`. It may be that your local installation just runs latex to convert formulas into images, where `\textnormal` is not a problem, where MathML doesn't appear to understand it.)

**Comment by jppelteret** [comment]
Thanks @bangerth for providing the correct command and for the explanation! Sorry it took more effort to present the distinction between the online and locally rendered formulas than it did to fix the problem :-)

**Comment by bangerth** [comment]
For completeness, the website seems to show the correct formula now.

**Comment by jppelteret** [comment]
Great, thanks a lot!
