### ISSUE TITLE
FE_Nedelec constructor fails for degree=8

### ISSUE THREAD

**Issue by jppelteret** [dealii/dealii#2176]
As the title says, the FE_Nedelec constructor fails for degree=8 (and possibly > 8 as well).

Git revision: `22044ff0c183976bfdd66ff9e5d9b17dc93d02cd`

Testcase:
```c++
#include <deal.ii/fe/fe_nedelec.h>
#include <iostream>

int main ()
{
  for (unsigned int d=1; d<10; ++d)
  {
    std::cout << "degree: " << d << std::endl;
    dealii::FE_Nedelec<2> fe (d);
  }
}
```
Output:
```bash
degree: 1
degree: 2
degree: 3
degree: 4
degree: 5
degree: 6
degree: 7
degree: 8

--------------------------------------------------------
An error occurred in line <1090> of file <XYZ/dealii/source/fe/fe_tools.cc> in function
    void dealii::FETools::compute_face_embedding_matrices(const FiniteElement<dim, spacedim> &, FullMatrix<number> (&)[GeometryInfo<dim>::max_children_per_face], const unsigned int, const unsigned int, const double) [dim = 2, number = double, spacedim = 2]
The violated condition was:
    result <= threshold
The name and call sequence of the exception was:
    ExcLeastSquaresError(result)
Additional Information:
Least squares fit leaves a gap of 1.33911e-12

Stacktrace:
-----------
#0  2   libdeal_II.g.8.5.0-pre.dylib        0x0000000103bba6ef _ZN6dealii7FETools31compute_face_embedding_matricesILi2EdLi2EEEvRKNS_13FiniteElementIXT_EXT1_EEERAsr12GeometryInfoIXT_EEE21max_children_per_face_NS_10FullMatrixIT0_EEjjd + 6095: 2   libdeal_II.g.8.5.0-pre.dylib        0x0000000103bba6ef _ZN6dealii7FETools31compute_face_embedding_matricesILi2EdLi2EEEvRKNS_13FiniteElementIXT_EXT1_EEERAsr12GeometryInfoIXT_EEE21max_children_per_face_NS_10FullMatrixIT0_EEjjd
#1  3   libdeal_II.g.8.5.0-pre.dylib        0x0000000103523cef _ZN6dealii10FE_NedelecILi2EEC2Ej + 1503: 3   libdeal_II.g.8.5.0-pre.dylib        0x0000000103523cef _ZN6dealii10FE_NedelecILi2EEC2Ej
#2  4   libdeal_II.g.8.5.0-pre.dylib        0x000000010352410b _ZN6dealii10FE_NedelecILi2EEC1Ej + 27: 4   libdeal_II.g.8.5.0-pre.dylib        0x000000010352410b _ZN6dealii10FE_NedelecILi2EEC1Ej
```

**Comment by bangerth** [comment]
Most classes make thresholds such as the one involved here dependent on the polynomial degree. In this case, the `FE_Nedelec` constructor calls `compute_face_embedding_matrices()` with the default value 1e-12 for the threshold. I think the right approach is to pass something like `1e-13*degree*degree` or similar for the threshold. The point of the threshold is simply that it should be small enough to ensure a basic smell test, but large enough to allow things that are supposed to work, to work.

**Comment by jppelteret** [comment]
Thanks @bangerth, setting the tolerance as `1e-12*degree*degree` works for `degree <= 10` but it still fails for higher polynomial orders. Personally I don't need anywhere near that high - this was just a bug I found by accident. Besides, it works in release mode. I will set up a PR when I'm done running tests.

I see that there are calls to `compute_embedding_matrix` in `get_restriction_matrix` and `get_prolongation_matrix` that also require a tolerance. However, I don't know if they have similar issues. I will attend to them if necessary.

**Comment by bangerth** [comment]
On 02/12/2016 01:38 PM, jppelteret wrote:
> Thanks @bangerth <https://github.com/bangerth>, setting the tolerance as
> |1e-12*degree*degree| works for |degree <= 10| but it still fails for
> higher polynomial orders. Personally I don't need anywhere near that
> high - this was just a bug I found by accident. Besides, it works in
> release mode. I will set up a PR when I'm done running tests.

Take out the assertion and instead print what the value is for different 
degrees. You'll see a pattern that you then want to mimic at the calling 
site (e.g., if the residual grows cubically, then that's what the 
calling site needs to put in as well).


> I see that there are calls to |compute_embedding_matrix| in
> |get_restriction_matrix| and |get_prolongation_matrix| that also require
> a tolerance. However, I don't know if they have similar issues. I will
> attend to them if necessary.

Great, thanks. Same principle as above.

**Comment by jppelteret** [comment]
@bangerth So what would you call this limit of ridiculousness here? The growth is exponential but is "closely" bounded until degree 12 by `1E-14 + 1.5E-018 x p^8`. The constant gives some wiggle room at low order. Can this be reliably computed (my knowledge of floating point arithmetic is not fantastic)? At degree 12 the error is already on the order of `2.5e-10`. If you're comfortable with this then can I make its computation a private function in the class?

**Comment by bangerth** [comment]
This is reasonable -- I don't think any sensible person would use more than 12th order Nedelec elements.

Why a private function? Why not
```
  1e-14+1.5e-18*std::pow(1.*degree, 8)
```
?

**Comment by jppelteret** [comment]
Sorry, the question was more about adding a class member function since the computation for the prolongation and restriction matrices (presumably) should use the same tolerance. I realised afterwards that this was not the best idea and that I should just put this function in an anonymous namespace. This is my final implementation which bounds the error better:
```c++
namespace internal
{
  namespace
  {
    double
    get_embedding_computation_tolerance(const unsigned int p)
    {
      return 1.e-15*std::exp(std::pow(p,1.075));
    }
  }
}
```
Full disclosure: After my modifications the following tests fail
```bash
	1293 - fe/nedelec_non_rect_2d.debug (Failed)
	1294 - fe/nedelec_non_rect_2d.release (Failed)
	1295 - fe/nedelec_non_rect_face.debug (Failed)
	1296 - fe/nedelec_non_rect_face.release (Failed)
```
but it appears that (on my machine) they did not pass before the changes either. I'll set up a PR now.

**Comment by bangerth** [comment]
On 02/12/2016 04:07 PM, jppelteret wrote:
> Sorry, the question was more about adding a class member function since
> the computation for the prolongation and restriction matrices
> (presumably) should use the same tolerance. I realised afterwards that
> this was not the best idea and that I should just put this function in
> an anonymous namespace. This is my final implementation which bounds the
> error better:

Yes, looks good.

**Comment by kronbichler** [comment]
I know I'm late to the party, but I would like to add the following comment: It seems the condition number grows exponentially with the polynomial degree. This is a strong indication that the basis is ill-conditioned and should not be used. Even though you can fix the constructor with the chosen approach, you are very likely to get problems to converge iterative solvers and the like down the road (essentially, everything except direct solvers and explicit time stepping with direct inversion of the mass matrix will be problematic long before the constructor fails). The same thing happens for FE_Q on equidistant points which one should **never** use when going **beyond degree 4-6** or so. I have not checked the polynomials of the Nedelec element but it seems very likely that there is some equidistant or monomial character in them that causes this behavior. Rather than curing the symptoms, we should at some point fix the polynomials. @jppelteret do you happen to know more? The documentation says we use Q_k polynomials, so it should be easy to change them to polynomials based on Gauss-Lobatto points.

**Comment by jppelteret** [comment]
Hi @kronbichler . Thanks for your insights into this issue. From what you've stated here I think that we've taken the wrong approach in (not) dealing with the problem and I'm comfortable with this PR being reverted. I'm sure that @bangerth would agree. I came across this issue by chance as part of my first look into the Nedelec ecosystem in deal.ii. At this point I'm only trying to determine if I can use them to solve a coupled problem with a complex mesh (given the documentation in the [FE class](https://www.dealii.org/developer/doxygen/deal.II/classFE__Nedelec.html) itself and the implementation of some of the tools for [applying boundary values](https://www.dealii.org/developer/doxygen/deal.II/group__constraints.html#ga6fca3672ae63b249402460a6ed4538b4) I think that this is not possible at the moment). So, no, as of yet I am completely unfamiliar with how they work and much of the detailed theory behind them.

With regard to the construction of the polynomials, I think that these are the two relevant functions from `base/polynomials_nedelec.cc` for this discussion:
```c++
template<int dim>
PolynomialsNedelec<dim>::PolynomialsNedelec (const unsigned int k) :
  my_degree (k), polynomial_space (create_polynomials (k)),
  n_pols (compute_n_pols (k))
{
}

template<int dim>
std::vector<std::vector< Polynomials::Polynomial<double> > >
PolynomialsNedelec<dim>::create_polynomials (const unsigned int k)
{
  std::vector<std::vector< Polynomials::Polynomial<double> > > pols (dim);

  pols[0] = Polynomials::Legendre::generate_complete_basis (k);

  for (unsigned int i = 1; i < dim; ++i)
    pols[i] = Polynomials::Lobatto::generate_complete_basis (k + 1);

  return pols;
}
```
Would your suggestion effectively entail replacing the `Legendre` basis for `pol[0]` with the `Lobotto` basis of order `k` and dealing with whatever knock-on issues arise from this?

**Comment by kronbichler** [comment]
@jppelteret No, the polynomials 'Legendre' should be fine and this constructor seems appropriate. My idea of using Gauss-Lobatto support points was more related to a finite element with a nodal basis. The polynomials used in `PolynomialsNedelec` are different from that. In particular, the choice of basis looks alright at first sight. I guess the problem is rather that the polynomial coefficients (both Legendre and Lobatto) are of a bad shape so that the Horner scheme evaluates them poorly. In the nodal case, we switched from the monomial coefficients to something I call 'product form' which means that we evaluate polynomials in terms of the factors `(x-x_0)(x-x_1)...` rather than in terms of monomials `a_0 + a_1 x + x_2 x^2 + ...`. The problem is that the Legendre and Lobatto polynomials use the latter because you cannot simply write them down as a product. You can check whether this is the reason for the problem by looking at the coefficient array at a polynomial degree around 10. If the coefficients are 'osciallating' and very large (larger than `1e6`), then we have the reason.

Literature contains special evaluation routines for Jacobi polynomials (including the Legendre and Lobatto case). One example is the book on Nodal discontinuous Galerkin methods by Hesthaven and Warburton. The problem I see with this approach is that the routine recursively evaluates the polynomial at given locations, which does not directly fit into our framework: We cannot overload the `Polynomials::value` method, so we would need to introduce a third path alongside the Horner evaluation and the Lagrange polynomial evaluation. Or make the method virtual nonetheless - but I don't know how much that would cost and one would have a look if it does not slow down any interesting case. Unless you are very keen in trying this because you want really high order (say larger than 10), I would vote for keeping things as they are and merely add a note (both in the class documentation of the Legendre and Lobatto polynomials and FE_Nedelec). It should mention the deficiency of bad polynomial evaluation and how it could be addressed at the point when one wants to do serious computations on those very high order polynomials.

**Comment by jppelteret** [comment]
Thanks again @kronbichler for the detailed and insightful comment. I really appreciate it! As you've inferred at the end, this is definitely out of the scope of what I am interested in (and probably best left to someone with more knowledge on numerical methods applied to FEM). Hopefully what you've mentioned here will be useful for the person who chooses to take on this task! In the mean time I'm all for a note being put into the documentation. I'm about to hop on a plane but I can put one together in a couple of days time. Would you suggest that I put a link to your comment in the documentation?

**Comment by davydden** [comment]
i think it's better to discuss the issues in documentation directly. Github might not exist tomorrow.

**Comment by kronbichler** [comment]
@davydden is right. I would vote for putting the long comments comments alongside the respective implementation of `create_polynomials` of `polynomials_nedelec.cc` (my comment seems too ad-hoc for making it straight into the user-visible documentation). The short version according to `Warning: The evaluation of Legendre/Lobatto polynomials becomes inaccurate at polynomial degrees larger than 10.` would then be visible in doxygen.
