### ISSUE TITLE
FE_Bernstein lacks proper get_interpolation_matrix() implementation

### ISSUE THREAD

**Issue by kronbichler** [dealii/dealii#2237]
As reported on the mailing list, FE_Bernstein fails to interpolate data between different meshes. The reason for this is that FE_Bernstein::get_interpolation_matrix() is not implemented in the class itself but inherited from FE_Q_Base which in turn access the unit point support points. FE_Bernstein does not define support points afaik, so there is no such data and thus an invalid access is done. The solution would be to create a new get_interpolation_matrix function for FE_Bernstein that uses the correct points for interpolation, similarly to what is done for FE_Bernstein::get_subface_interpolation_matrix. @mtezzele @luca-heltai you wrote the original implementation: Would you mind having a look?

**Comment by lambe** [comment]
Here's a test case:
[Bernstein_refine_test.zip](https://github.com/dealii/dealii/files/143111/Bernstein_refine_test.zip)


The code runs without issue if we set fe_density in the elasticProblem class to be of type FE_Q<dim>, but we really want it to be FE_Bernstein<dim>. The error lies in the VectorTools::interpolate_to_different_mesh() function.

(Compiling the example can be done with the standard CMakeLists.txt file used in the early tutorial examples.)

**Comment by luca-heltai** [comment]
`VectorTools::interpolate_to_different_mesh` should not work on non-interpolatory finite elements. In this specific case, I think it could be made to work following the same principles implemented in `VectorTools::get_position_vector`, but this would be a hack. Our definition of "interpolation" in the deal.II library is not compatible with FE_Bernstein (it assumes that u(xi) = u_i for some support points xi. this is false in FE_Bernstein). 

Face interpolation *can* work (and it does, in terms of hanging nodes, and that is way those matrices are inplemented) because Bernstein FE *are* interpolatory **only** on the faces. Not on the interior. Interpolation is therefore not well posed in the interior.

What do you want to achieve, exactly, @lambe?

**Comment by bangerth** [comment]
But aren't we trying to interpolate *off* a Bernstein FE and *onto* an FE_Q? That should work. The other way around may not.

**Comment by lambe** [comment]
@luca-heltai, @bangerth,  I'm basically trying to define some material properties that are location-dependent and using the deal.ii machinery to do a continuous interpolation of these properties over the domain of interest. The Bernstein FEs are necessary in this application because the polynomials stay strictly between zero and one, so I don't have to worry about unrealistic values of these properties. 

As long as I use the same triangulation for both the material properties (with FE_Bernstein) and the PDE solution (with regular FE_Q), everything is fine. But now I want to try dissimilar meshes. I was thinking that I could use a coarse mesh of FE_Bernstein elements to define how the properties vary, and a fine mesh of FE_Q for the PDE solution. 

The problem comes with how to evaluate those properties for quadrature and setting up the linear system. I thought the fastest approach would be to map the coarse mesh to a fine mesh of FE_Bernstein elements and use an appropriate FEValues object to compute the properties at the quadrature points. Based on what you are saying to me now, this is not possible. If that's the case, what is the workaround?

**Comment by luca-heltai** [comment]
I think `FEFieldFunction` will work as a first attempt. It will be slower than performing the interpolation using `VectorTools` functions. In the mean time (next week) I can look into this with Wolfgang.

**Comment by lambe** [comment]
I've devised a workaround for my specific problem. I use the FEFieldFunction to interpolate the FE_Bernstein mesh data onto an identical FE_Q mesh, then just interpolate between FE_Q meshes in the refinement stage. This is fast enough for my specific problem, so there's no time pressure to solving this issue.

**Comment by kronbichler** [comment]
@luca-heltai Do you still plan to do anything on this? Since there seems to be no pressing need, I'd be fine with just adding a separate `get_interpolation_matrix()` method to FE_Bernstein that throws an exception.

**Comment by luca-heltai** [comment]
Yes, I think adding a method that throws an exception is a good starting point. We'll be looking into this at some point, but it is not very high on the priority list right now...
