### ISSUE TITLE
Parmetis in CMake config (is it actually used?)

### ISSUE THREAD

**Issue by davydden** [dealii/dealii#2434]
I looked at the https://github.com/dealii/dealii/blob/master/cmake/modules/FindMETIS.cmake. It seems that ParMetis is actually not used at all in deal.ii (I grepped for `metis` and have not seen any parmetis functions). Moreover, CMake searches only for `metis.h` and never for `parmetis.h`.

Also I think this
> Only search the parmetis library in the same directory as the metis library.

should be changed. A lot of packagins systems (`MacPorts`, `Homebrew/Linuxbrew`, `Spack`) and also Petsc build `Parmetis` against a separately compiled `Metis` instead of using the one, provided within `Parmetis` sources. But if parmetis is not used, perhaps the whole search should be dropped completely.

**Comment by davydden** [comment]
also `$ ag --cpp DEAL_II_WITH_PARMETIS` does not return anything.

**Comment by bangerth** [comment]
Correct -- we don't use parmetis.

**Comment by davydden** [comment]
shall we remove these parts of the config and also do not print `DEAL_II_WITH_PARMETIS` at the end of the config?

**Comment by bangerth** [comment]
I think that would probably make sense.

**Comment by tamiko** [comment]
Just to shed a bit of light to this very issue:

For certain versions of bundled metis provided by parmetis it was necessary to also include ```libparmetis.a``` into the link interface, otherwise linkage of statically build metis would fail.

Unfortunately, I do not recall the specifics of this any more, so I cannot tell whether it is still relevant. :-/
(If I had to guess I'd say that metis support on some old debian or gentoo version is now broken, but this might be irrelevant nowadays.) 

@davydden The parmetis library the lines of code you removed looked for were just included into the link interface of metis - at no point a ```DEAL_II_WITH_PARMETIS``` variable was set up.

**Comment by davydden** [comment]
> For certain versions of bundled metis provided by parmetis it was necessary to also include libparmetis.a into the link interface, otherwise linkage of statically build metis would fail.

that sounds strange. Even for bundled metins within parmetis, metis is build first (from it's sources) and then parmetis. How could they be screwed up that way :open_mouth:
