### ISSUE TITLE
What are the post-conditions of move construction?

### ISSUE THREAD

**Issue by danshapero** [dealii/dealii#2490]
I recently added a move constructor for `SparseMatrix` and `Subscriptor`, and there already is one for `Vector`. I would like to add move constructors for several more classes in deal.II, which dovetails with #1519 and would also clean up a lot of my own code. However, there are some subtle issues that would be nice to clear up first.

The C++ standard is vague about what the post-conditions of a move constructor should be, stating only that the moved object is in some "unspecified state". In some libraries, the moved object is restored to what its state would be after default initialization; in others, the two objects are swapped, as is the case with `Vector`.

The behavior of the default move constructor is a member-wise move, which sounds ok but some of the defaults do unexpected things. For a class like `Quadrature`, which contains `std::vector` members that have a move constructor defined already, the default will work just fine. For a class like `dealii::Vector`, `std::vector` or `SparseMatrix` which directly manages heap memory, using the default move constructor would result in memory errors. This is because the default move for a pointer is to copy it; the moved-from pointer is not nullified. If one were to use this behavior with, say, `SparseMatrix`, then the member `number * val` of the moved-from object would be non-null, and the memory would be freed upon its destruction, even though the moved-to matrix is still pointing to that memory.

There is the additional complication that it's not always obvious if move construction will be used. If a local variable is returned from a function, the compiler can avoid copying by using the object's move constructor, or it may instead use return-value optimization to directly construct the object where it will be returned to. A class with a deleted copy constructor, e.g. `FEValues`, cannot be returned from a function without a move constructor, even if RVO will be used every time.

Finally, the destructor of a moved-from object is not invoked until end of scope, which could occur much later than the actual move. For example, `dealii::Vector` is currently implemented using `swap`. If one were to write

    Vector<double> x = /* magic happens */;
    Vector<double> y = /* more magic */;
    y = std::move(x);
    /* Do a bunch of things with x */

then this code would work just fine, even though one might be led to believe that `x` is null after being moved.

I think the easiest behavior to reason about is to make sure that any object which manages heap memory is put into a null state after being moved. That said, I'd like to see what others think before I go and add a bunch of stuff using this convention; I only know some of the code base and there's surely an edge case somewhere that I haven't considered.

**Comment by bangerth** [comment]
The common case for a move constructor is to move from a temporary object (which is what one typically has as the source of the rvalue reference argument to the move constructor, although that may also come from a call to `std::move()`). In other words, the "unspecified state" comment in the standard simply wants to indicate that whether the object being moved from represents anything useful or not is not of actual concern.

However, what is important is that the object will still be able to run its destructor, and that typically implies that it is internally consistent. For example, for the `Vector` class, this would mean, in my view, the following:
* The pointer to the data has been reset to zero; because, if it hasn't, the destructor of the moved-from object will try to delete the memory pointed to -- which at this point in time is already used by another object.
* The variables that store the length and maximal length of the vector have been reset to zero, because someone may think that the following is a useful debugging tool:
```
  Vector::~Vector ()
  {
    // overwrite the memory of the vector with NaNs to help debug memory corruption
    for (i=0...size())
      val[i] = std::numeric_limits<number>::signaling_nan();
  }
```
Here, the problem appears because even if the `val` pointer is set to zero, the size has not been set to zero and we will get a segmentation fault because the two are no longer consistent in what they declare.

The internal consistency argument is also a useful guideline for cases (such as the one you provide at the end of your post above) where the moved-from object is not immediately destroyed, but could live on for a while longer.
