### ISSUE TITLE
Route to LA::VectorSpaceVector for parallel::distributed::Vector

### ISSUE THREAD

**Issue by kronbichler** [dealii/dealii#2535]
This is related to #745 but I would like to discuss the issues for the new parallel distributed vector in a separate issue and before implementation.

The simple thing about this task is that `parallel::distributed::Vector` should derive from `LA::VectorSpaceVector`. It cannot derive from `ReadWriteVector` because we would need to synchronize ghost values before using them. @Rombur should I move the implementation to the LA namespace (and later create a derived class for backward compatibility)?

As outlined in #745, I would like to be able to create a light-weight `ReadWriteVector` that can avoid a deep copy of the locally owned entries in the parallel distributed vector. So the idea would be that those two share the data array and the ReadWriteVector would additionally call what now is `update_ghost_values()` upon import. The operation back to a `VectorSpaceVector` would involve what is now `compress()`. This would be possible if we make `Utilities::MPI::Partitioner` derive from the CommunicationPattern (or call it some communication pattern name and link the old file to that one). This would check whether the same underlying IndexSet is present for doing it cheaply, otherwise go the expensive way.

The issue that I would like to discuss here is how much flexibility we want to add to the ReadWriteVector. Remember that part of the design of ReadWriteVector is a `local_element()` method (and the associated `begin()` and `end()` pointers which have the same underlying index representation). Whenever you depend on fast access to the vector, you need those direct access methods. I've seen an example from the Trilinos community where people got a >100x improvement in speed when going from Epetra to Tpetra on a force computation of a potential. The issue was not threading, but solely that Tpetra and the underlying Kokkos algorithm managed to provide direct array access under the hood rather than index conversion (through Epetra_BlockMap::LID). The question is where we would like to have fast access. I definitely need them for fast matrix-free algorithms, and also the various get_dof_values calls would profit. This requires local index storage in DoFHandler (see #2000 for that).

The tricky thing with local indices is that you can have different sets depending on what you like to do. For many algorithms, the locally active indices (i.e., those related to locally owned cells). But if you compute jump terms (error estimation, DG), you need also some additional indices from the ghost layer. If you do multigrid transfer, you need to access again a few indices from the ghost layer. You could address them all if the only numbering we provided were the locally relevant dofs. At the end of the day, that is exactly the set indices that we **understand** locally. However, I would not want to have them all in a performance-critical algorithm because it could easily quadruple the amount of data you have to communicate in a typical setting. I have measured that for the relevant set the manipulation work necessary in `parallel::distributed::Vector` is no longer negligible compared to other operations - a matrix-free product on the Laplacian slows down by 20-40% on a few hundred cores. (It's partly the MPI send operation, but not only.)

If we do not use local indices in a centralized place (DoFHandler), their use will be quite limited and everyone trying to be smart would have to copy the whole chunk and re-compute as necessary. My idea would be to introduce a smarter index set that represents data in layers:

```
class LayeredIndexSet
{
  // ...
  void add_layer (const IndexSet &next_index_set); // adds another layer
  std::vector<IndexSet> index_sets; // keeps a list of IndexSets
};
```

The local numbering of the index set would start with all the indices in the first index set. A typical DoFHandler numbering would have the following four layers:
1. locally owned dofs
2. locally active dofs without 1, i.e., the indices on the locally owned cells that are not owned
3. remaining dofs on cells that sit behind faces that we consider 'ours'
4. remaining dofs in the ghost layer

This way, you have a unique numbering of dofs on the DoFHandler part when coming in with a vector that only has 1+2, but also one with 1+2+3+4. Of course, the read operations on the cell iterator would have to decide whether the vector has the appropriate layer, but that is not too many lines of code.

Obviously, the LayeredIndexSet would need to be chosen in the ReadWriteVector (and the DoFHandler would natively know the layered index set consisting of 1-4 which we would use for initialization of ReadWriteVector). Or rather, it would hold a shared pointer of that index set that allows for sharing between different vectors and the DoFHandler as a way to check whether we speak about the same index set without global MPI synchronization. We can allow vectors to be constructed differently but in that case we need global communication or at least go through the global indices.

This concept sounds a bit complicated I admit but I see this as a viable way forward to unify the index part from the MatrixFree class in the main DoFHandler and additionally speed up common operations that are not related to matrix-free (vector access on cells). But of course it is open to discussion: I don't want to create a solution that comes from a bit of a niche, make it a first-class citizen in DoFHandler/ReadWriteVector and then creates major headache five years ahead.

**Comment by Rombur** [comment]
@kronbichler I think moving the implementation to the LA namespace is the right way to do it.

I like the idea of the ```LayeredIndexSet``` as long as it doesn't contaminate ```ReadWriteVector```. ```ReadWriteVector``` is not supposed to know who owns the dofs. I think that it would be fine if a ```ReadWriteVector``` could use a ```LayeredIndexSet``` or an ```IndexSet``` and that the underlying storage format would depends on if we are using a ```LayeredIndexSet``` or an ```IndexSet```. However, I don't think that you should be able to ask directly the ```ReadWriteVector``` to get only the locally owned dofs for example.

**Comment by kronbichler** [comment]
@Rombur I would not put anything about `ownership` into the `ReadWriteVector`. While there will be such a relation to the first index set for the fast path from a distribued vector, it will neither be assumed implicitly nor exposed to the outside. Thus, we will not (and cannot) put a function for the locally owned dofs. We might have a method that returns the `LayeredIndexSet` for initialization purposes but not put any meaning into it.

**Comment by Rombur** [comment]
Great. I like the possibility of having this kind of fine control on the IndexSet :+1:

**Comment by kronbichler** [comment]
We will not change this for 8.5. Regarding the extension of `IndexSet` I'm not completely sure what approach we may take. In the DG extension of `MatrixFree` (it is 95% done and we will start open PRs after 8.5 has been branched) there is some logic that bypasses the vector data exchange and we will discuss it there. This change will also need synchronization with #2000.

**Comment by bangerth** [comment]
Here is a short note about a separate topic: Eventually, we want to base the Trilinos interfaces on the newer Tpetra package (https://trilinos.org/packages/tpetra/). I had some conversations about the stability of Tpetra APIs at this point with Mark Hoemmen -- the main Tpetra developer -- and these were his answers:

.....................................
> We're looking forward to using Tpetra for deal.II. Do you think it's at a 
> point where there is largely API stability so we don't have to write and 
> rewrite our code multiple times?

The interface for thread-parallel sparse graph and matrix construction and modification – what I call the “fill interface” – will continue to evolve.  However, other parts of the interface will not change much. 

Let me elaborate on the fill interface.  Tpetra’s current fill interface has only limited support for thread safety and scalability.  For example, CrsMatrix::sumInto*Values is thread safe and scalable (in so far as hardware atomic += thread-scales), but only on the CPU, not on the GPU.  CrsGraph and CrsMatrix methods that change the graph structure are NOT thread safe.

If you want thread-parallel sparse graph and matrix construction and modification, here is the most efficient thing you could do:

1. Split up “local” (per MPI process) and “global” (across MPI processes) assembly
2. Do local work using Kokkos data structures (e.g., KokkosSparse::CrsMatrix, which has sumIntoValues and replaceValues methods)
3. Pass them off to Tpetra data structures and do global work, e.g., using doExport for global assembly

Kokkos has examples, esp. the “FENL” (finite-element assembly and solve) example, that illustrate thread-parallel local graph construction and local assembly.

Our plan is to deprecate and remove the fill interface in Tpetra::CrsGraph and Tpetra::CrsMatrix.  Local things are local; global things are global.  We will continue to support the interface for a while.

I will be happy to work with you and/or your folks in order to make thread-parallel fill better ☺

> On a different note, given that Kokkos has all of these placement and policy 
> parameters, how do you deal with these in Tpetra? Do you run them all the way 
> through the user interface and let Tpetra users choose them? Or do you make 
> educated guesses and hide this choice from the user?

Tpetra asks users to specify the Kokkos execution space.  It uses that execution space’s default memory space as its memory space.  Tpetra objects will eventually all behave like Kokkos::DualView (MultiVector and Vector already do now); this will help gradual porting to use GPUs, and will also let users decide whether to run in HBM or main memory on KNL.  Otherwise, Kokkos developers’ view is that special placement and policy parameters, like texture fetch (RandomRead), belong only at the entry point of computational kernels.  Use mostly undecorated Views wherever possible, and only decorate on entry to a computational kernel, like sparse matrix-vector multiply.  The point is to avoid building kernels and code for too many different template parameter combinations.  We have taken this approach in the design of KokkosKernels.  I would be happy to walk you through examples if you like.
........................

**Comment by drwells** [comment]
This morning we agreed that `VectorSpaceVector` should become a concept rather than a base class. Given that and that this class already inherits from `VectorSpaceVector` I think that we can close this - thoughts?

**Comment by kronbichler** [comment]
I agree, we have a good concept for the vectors overall, including the use of non-templated interfaces to as large extent as possible. Furthermore, the application side of our `LinearAlgebra::distributed::Vector` is such that optimizations rather belong to the user side, as e.g. for `MatrixFree` expressed in the issues #15224 or #14098. In other words, the vector interface on its own does not need to be further considered.
