### ISSUE TITLE
Can we complie and use dealii-8.4.1 using codeblcoks with gcc ?

### ISSUE THREAD

**Issue by wangenli** [dealii/dealii#2597]
thanks a lot !

**Comment by drwells** [comment]
@wangenli I see no reason why not, but most of the library's users prefer Eclipse, so it is a bit better supported. In particular, if you go to the wiki page, we have a nice tutorial on how to set up Eclipse with deal.II.

For usage questions like this you will probably find better responses by posting to the mailing list
https://groups.google.com/forum/#!forum/dealii
than here because many more people are active on the mailing list than here.

**Comment by wangenli** [comment]
Thanks for your help. I will try.
