### ISSUE TITLE
Question about do_tensor_product argument in new FETools function

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#2628]
#2614 introduces a new function `do_tensor_product` to a bunch of functions that build composed elements from individual elements. I've edited their description in #2627, but I'm actually not quite clear what it means. Here is what the description, in essence, says:
```
   * If @p do_tensor_product is true, the number of components
   * returned in the FiniteElementData object is the sum over the
   * product of the number of components in each of the finite
   * elements times the corresponding multiplicity.  Otherwise the
   * number of components is taken from the first finite element with
   * non-zero multiplicity.
```
I *think* what you are doing in the implementation is essentially this: if `do_tensor_product=true`, you really just do the tensor product of the elements, adding up the vector components. Whereas if you use `do_tensor_product=false`, then you throw all of the shape functions of a base element into the *same* vector component of the resulting element. In other words, you form the *set sum* of the shape functions of each of the base elements.

So, questions:
- Is this correct?
- What would happen if you had a multiplicity larger than one. In that case, you'd have the exact same shape function more than once. Wouldn't this lead to a non-unisolvent element?

**Comment by bangerth** [comment]
Oh, and one more question:
- Shouldn't one assume that either all base elements have the same number of vector components, or instead take the number of components equal to the *maximum* number of components of the base elements, not the first one?

**Comment by davydden** [comment]
The mentioned PR is a preparatory step for partition of unity method (Melenk and Babuska 1996, Babuska and Melenk 1997) and the corresponding enriched finite element where the FE space is indeed a sum (instead of a tensor product), but enriched with real-space scalar valued functions:
```
u(x) = \sum_i u_i N_i(x) + sum_k f_k(x) \sum_j u_{jk} N_{jk}(x).                  (1)
```
Of course this underlying usage was not obvious from that PR, out of the context, but I also did not want to have a PR which changes to many things.

> Is this correct?

yes.

> What would happen if you had a multiplicity larger than one. In that case, you'd have the exact same shape function more than once. Wouldn't this lead to a non-unisolvent element?

In general yes, but in the context of partition of unity method -- no. Of course, there are cases when the resulting basis `(1)` can end up linearly dependent if the choice of the enrichment functions is careless. 

> Shouldn't one assume that either all base elements have the same number of vector components, or instead take the number of components equal to the maximum number of components of the base elements, not the first one?

I have asserts in those extended functions to make sure that the number of components is the same for `do_tensor_product=false`.

**Comment by bangerth** [comment]
Thanks for the confirmation. I've updated #2627 accordingly.

As for `do_tensor_product=false` and multiplicities greater than 1: In this case, you end up with the *same* shape function *multiple* times. Unless you treat different shape functions differently in the assembly (e.g., by multiplying *some but not all* shape functions with weights), then you get the unisolvency wrong. I suppose you do multiply with weights, though.
