### ISSUE TITLE
Failing test with MappingManifold + sphere

### ISSUE THREAD

**Issue by ESeNonFossiIo** [dealii/dealii#2629]
@cpraveen noticed that MappingManifold has some problems with integrals on a sphere. 
I am trying to find a solution together with @luca-heltai .

This is a test that shows that the integral using a MappingQ has a small relative error (1.31252e-07) while MappingManifold is bigger (0.0477574).
[test.zip](https://github.com/dealii/dealii/files/279794/test.zip)

**Comment by cpraveen** [comment]
@ESeNonFossiIo Just checking if there is any progress on this issue. Is #2676 related to this ?

**Comment by ESeNonFossiIo** [comment]
Yup. We are trying to rewrite the MappingManifold in a different way and find the bug.

**Comment by bangerth** [comment]
See also #2810.

**Comment by cpraveen** [comment]
Is this issue fixed by #2810 ? From the documentation, it seems that I should use PolarManifold together with MappingManifold ?

**Comment by drwells** [comment]
The documentation of SphericalManifold states that it should not be used with MappingManifold. I must admit that I do not know enough about manifolds to really understand why this is true, but this seems like a reasonable explanation for why the errors are so high.

Since the answer is (unfortunately) just "don't do it that way" I think that we can close this issue.

**Comment by drwells** [comment]
#3038 duplicates the warning about SphericalManifold in MappingManifold. Since both classes now warn not to do this (due to mathematical, not implementation, reasons) I think that we can close this.
