### ISSUE TITLE
Recent changes - link does not work

### ISSUE THREAD

**Issue by kbzowski** [dealii/dealii#2653]
Link to "Recent changes" on the deal.ii main site does not work.
https://www.dealii.org/developer/doxygen/deal.II/changes_after_8_4.html

404 error.

**Comment by drwells** [comment]
Thanks for catching this. I spent a few minutes clicking through all the other links and found some other dead links:

1. link to UMFPACK on dealii.org/license.html
2. link to TBB on dealii.org/license.html

Additionally, the survey link still shows up under the downloads page.

(I do not have access to the web site source, otherwise I would handle these myself).

**Comment by bangerth** [comment]
I left the survey link in on purpose -- we still got a couple of replies a week, and that's still useful.

The other links clearly ought to be fixed, though, of course.

**Comment by bangerth** [comment]
The proper link to the changelog is https://www.dealii.org/developer/doxygen/deal.II/changes_after_8_4_1.html

**Comment by tjhei** [comment]
The links on the website are now fixed.
