### ISSUE TITLE
step-56 question

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#2664]
@tjhei and @rrgrove6 -- while looking through step-56, I realize that the timing table in the results section has columns for "Set-up" and "Assemble", but these contain no numbers. Do you have these numbers lying around somewhere? If so, please add. Otherwise, maybe just delete the columns?

**Comment by bangerth** [comment]
Also, the text below the table states that the number of outer iterations is the same between the ILU and GMG columns, but it isn't. What's going on?

**Comment by rrgrove6** [comment]
We do not have the set-up and assemble results at the moment but we were plannng on adding them in once we redo the Results documentation. I believe we were waiting for comments from everyone else regarding what we did and anything else they'd like to see before we recomputed the numbers.

I'm not sure about this line "Because we are using inner solvers for $A$ and $S$, ILU and GMG require the same number of outer iterations."  I believe Timo added it in recently but he may have just meant similar instead of same?

**Comment by tjhei** [comment]
> I believe we were waiting for comments from everyone

Yeah, but the tutorial is now online.

> I'm not sure about this line "Because we are using inner solvers for $A$ and $S$, ILU and GMG require the same number of outer iterations." I believe Timo added it in recently but he may have just meant similar instead of same?

I wrote this and I thought that this was the case, oops.

I should probably rerun everything and update the tables...
