### ISSUE TITLE
step-25 based on the method described in step-40 (MPI)

### ISSUE THREAD

**Issue by Esfahani120** [dealii/dealii#2670]
Dear Deal-ii Users,

Greetings. I am trying to change step-25 for MPI based on the method described in step-40. Unfortunately, I got stuck with an error :( 

**> Time step #1; advancing to t = 0.2.
> [0]PETSC ERROR: --------------------- Error Message --------------------------------------------------------------
> [0]PETSC ERROR: Argument out of range
> [0]PETSC ERROR: Inserting a new nonzero at global row/column (0, 0) into matrix
> [0]PETSC ERROR: See http://www.mcs.anl.gov/petsc/documentation/faq.html for trouble shooting.
> [0]PETSC ERROR: Petsc Release Version 3.6.3, Dec, 03, 2015 
> [0]PETSC ERROR: /home/ehsan/apps/candi/deal.II-toolchain/deal.II-v8.4.0/examples/step-25 (mine)/step-25 on a arch-linux2-c-opt named levitasgrad01.me.iastate.edu by ehsan Mon Jun  6 13:06:02 2016
> [0]PETSC ERROR: Configure options --prefix=/home/ehsan/apps/candi/deal.II-toolchain/petsc-3.6.3 --with-debugging=0 --with-shared-libraries=1 --with-mpi=1 --with-x=0 --download-hypre=1 CC=mpicc CXX=mpicxx FC=mpif90
> [0]PETSC ERROR: #1 MatSetValues_MPIAIJ() line 582 in /home/ehsan/apps/candi/deal.II-toolchain-build/petsc-3.6.3/src/mat/impls/aij/mpi/mpiaij.c
> [0]PETSC ERROR: #2 MatSetValues() line 1173 in /home/ehsan/apps/candi/deal.II-toolchain-build/petsc-3.6.3/src/mat/interface/matrix.c
> 
> 
> +---------------------------------------------+------------+------------+
> | Total wallclock time elapsed since start    |     0.732s |            |
> |                                             |            |            |
> | Section                         | no. calls |  wall time | % of total |
> +---------------------------------+-----------+------------+------------+
> | RHS                             |         1 |     0.122s |        17% |
> | assembly                        |         1 |     0.113s |        15% |
> | setup_GridGen                   |         1 |     0.353s |        48% |
> +---------------------------------+-----------+------------+------------+
> 
> ERROR: Uncaught exception in MPI_InitFinalize on proc 0. Skipping MPI_Finalize() to avoid a deadlock.
> 
> 
> ----------------------------------------------------
> Exception on processing: 
> 
> --------------------------------------------------------
> An error occurred in line <1424> of file </home/ehsan/apps/candi/deal.II-toolchain/deal.II-v8.4.0/include/deal.II/lac/petsc_matrix_base.h> in function
>     void dealii::PETScWrappers::MatrixBase::add(dealii::PETScWrappers::MatrixBase::size_type, dealii::PETScWrappers::MatrixBase::size_type, const size_type*, const PetscScalar*, bool, bool)
> The violated condition was: 
>     ierr == 0
> The name and call sequence of the exception was:
>     ExcPETScError(ierr)
> Additional Information: 
> An error with error number 63 occurred while calling a PETSc function
> --------------------------------------------------------
> 
> Aborting!
> ----------------------------------------------------**

I've attached the code ([step-25.TXT](https://github.com/dealii/dealii/files/301039/step-25.TXT)) if you like to see a full description of the error. I cannot understand why I'm getting this error because I'm just trying to change step-25 based on step-40. I was thinking it would be easy but it seems I was mistaken. Do you have any suggestion about this error? I find out that I am inserting a new nonzero component in a sparse matrix and it violates the sparsitypattern but I cannot find out where I'm doing this because the code is aborting and I cannot debug it correctly in Eclipse-Mars II.
Also, is it really possible to change step-25 for MPI by using step-40 or I'm completely on a wrong road?
Thanks for your help in advance.

Best Regards,
Ehsan

**Comment by jppelteret** [comment]
Hi Ehsan,

I see that this is the second issue that you've raised related to a "user" issue with deal.II. I'm not sure if you're aware, there's a [google groups forum](https://groups.google.com/forum/#!forum/dealii) that it specifically aimed at answering user's questions related to deal.II. If you visit the website, you'll see numerous questions that have the same "flavour" as yours. 

You don't even need to join the group to use it - you can simply [email](dealii@groups.google.com) your question to the [mailing list](https://dealii.org/mail.html). In this way your question gets the exposure it deserves (more people are active on the forum, and the developers and regular contributors are too) and the solution to your problem gets seen by the community as well. In this way, if someone else has a similar problem then they can find your thread and use the information in it to try to solve their own issue. Right now, when you or one of the developers close your issue, the responses will effectively be lost unless someone digs deep to find them! See [this post](https://groups.google.com/forum/#!topic/dealii/uFi56KMx1h0) for more information as to how we use the group and why I think that its a more appropriate platform for these sorts of questions.

Regards,
J-P

P.S. Although I don't think I'm out of line for mentioning this, any of the devs are free to rebuke me if they disagree. My understanding is that the GitHub issues are to raise issues that pertain directly to the deal.II library itself, rather than user code that utilises it.

**Comment by drwells** [comment]
The most important thing is that we help users :)

Either way, more people (a superset of the people on github) check the mailing list so I think you will find a better answer to your question if you head there. The user group is also set up so that other people can easily search for common problems, so posting there may help someone with a similar problem in the future too.

**Comment by Esfahani120** [comment]
@jppelteret @drwells 
Thanks for your comments. I've posted the issue in the mailing box and still waiting for an answer there. Sorry for raising the issue here. 

Best,
Ehsan

**Comment by davydden** [comment]
I am closing this one then. p.s. here's a link to Google group thread https://groups.google.com/forum/?fromgroups#!topic/dealii/ik7Y_oQ02Oo

**Comment by jppelteret** [comment]
@drwells 100% agreed! That's priority number 1.

@Esfahani120 Absolutely no apologies necessary. I'm just trying to maintain some order and help ensure that you get a solution to your problem ASAP :-)
