### ISSUE TITLE
`contract3` for symmetric tensors

### ISSUE THREAD

**Issue by danshapero** [dealii/dealii#2691]
Currently, the `contract3` function which computes the product of 3 tensors is only defined for `Tensor`, not for `SymmetricTensor`. Adding this function would make general and symmetric tensors more consistent. It might also be a performance gain over computing the product using the overloaded `*` operator, which will create a temporary value.

**Comment by bangerth** [comment]
Correct. Though one needs to pay attention to the fact that even if A,B are symmetric, the product `AB` is not in general. What would be useful, though, is a function that computes `A^T B A`, which is always guaranteed to be symmetric. We ran into this in ASPECT recently.

**Comment by tamiko** [comment]
@danshapero Can you give the low level ```TensorAccessors::contract3``` a try? It should work out of the box.

**Comment by danshapero** [comment]
@tamiko I'll give that a shot -- might be a few days before I get to it.

**Comment by jppelteret** [comment]
@tamiko I'm busy working on adding this functionality using the suggestion you made. I've hit a snag that within `TensorAccessors::contract3` one needs to retrieve a tensor row with `operator[]`. However, this does not seem to work for `SymmetricTensor`s:
```
485: .../deal.II/base/tensor_accessors.h:745:92: error: no viable overloaded operator[] for type 'const dealii::internal::SymmetricTensorAccessors::Accessor<2, 3, true, 1, double>'
485:           result += Contract3<0, rank_2 - 1, dim>::template contract3<T1>(left, middle[i], right[i]);
```
This is understandable as the data structures for the `Tensor` and `Symmetric` tensor classes are different. I could write a function like `extract_subtensor(right,i)` that calls `operator[]` for a `Tensor` object but builds the necessary data for the `SymmetricTensor` object, but this seems a bit wasteful since it'll mean creating a temporary `Tensor<1,dim>` when `right` is a `SymmetricTensor<2,dim>`.

Do you perhaps have any other suggestions?

**Comment by jppelteret** [comment]
@tamiko Nevermind - I think I've worked out what's actually going wrong here. The problem turns out not to be what I thought it was :-)
