### ISSUE TITLE
Bugday/Bugweeks and Milestones

### ISSUE THREAD

**Issue by tamiko** [dealii/dealii#2703]
Hi all,

is it just me or is our list of 166 open issues slowly growing above one's head?

What about we (a) try to reassign bugs to Milestones, for example
 - bugs that should be fixed for the next release
 - bugs that should be fixed for version 9.0

and maybe nominate some for specific "bug fixing" weeks/days?

Personally, I would like to stay in the maybe ~100-150 open issues range in the long run.

**Comment by bangerth** [comment]
Totally correct. We also need to take a look at the current failing tests at http://cdash.kyomu.43-1.org/index.php?project=deal.II&display=project to make sure we don't have an overly hard time running the testsuite every time.

**Comment by drwells** [comment]
I agree. I considered opening a 'too many issues' issue for a long time but I did not due to psychological problems with making the list even longer.

To throw it out there: we open issues that don't really have a clear path towards resolving them. I am in favor of moving these somewhere else (like the list of projects we have on the website). These are good ideas but they don't really seem like 'problems with the library':
1. #1338
2. #302
3. #335

I admit that this is a subjective list based on how clear I consider the resolution to be.

**Comment by bangerth** [comment]
#1338 actually has something that can be done and that would make for a nice starter project for a hackathon. I agree about the other two, in particular about #302 which has nothing concrete that can be implemented. #335 might at least serve as a meta bug in the spirit of #1198, but it could also disappear and nobody would be sad.

**Comment by tamiko** [comment]
OK. I will close this issue now in order to reduce the total number of issues. :-]
It turns out that the LABEL overview page https://github.com/dealii/dealii/labels is quite neat.

Maybe we should simply require that all issues are labeled.

**Comment by bangerth** [comment]
Yes for labeling. That's useful. In ASPECT we just introduced another label "Starter project" for small projects people can take a stab at. I think that's useful, so I'll create that here as well. I might have to one day go through our issue data base and label issues with this new tag.
