### ISSUE TITLE
parallel::shared::Triangulation: Partition information lost after copy_triangualtion and load.

### ISSUE THREAD

**Issue by adamqc** [dealii/dealii#2798]
The partition information is lost after calling to `copy_triangualtion` and `load`, hence the triangulation is on an invalid state.

This could be easily fixed by reimplementing the `copy_triangualtion` function in `shared::Triangulation` that do the partition operation after `::Triangulation::copy_triangulation`. But since the `load` function in `::Triangulation` is not virtual, I think that simply reimplementing it is not wise (see: [redefining-nonvirtuals](https://isocpp.org/wiki/faq/strange-inheritance#redefining-nonvirtuals)). Shall we declare the ::Triangulation::load as virtual?

**Comment by drwells** [comment]
@adamqc Yes, unfortunately this part of the library has some problems. It looks like both the parallel and shared versions have similar issues.

I am not very familiar with the Triangulation classes but this fix sounds reasonable (and I see no problem in making `load` virtual; we will probably need that for #2796 anyway). Would you be willing to give this a try?

**Comment by adamqc** [comment]
I will make a pull request as soon as possible.

**Comment by bangerth** [comment]
There is no point in making the function `virtual` because then the base class would declare it as
```
  class Triangulation {
    [...]
    virtual void copy_triangulation (const Triangulation &source);   // note: ::Triangulation argument!
    [...]
  };
```
and the derived class would have to override it with exactly the same argument, i.e., a `::Triangulation`). But what you want here is to actually have an overload that takes `parallel::shared::Triangulation` as argument for `parallel::shared::Triangulation::copy_triangulation`, and `parallel::distributed::Triangulation` as argument for `parallel::distributed::Triangulation::copy_triangulation`. It's a bit the same as making `operator=` virtual: possible, but not often very useful.
