### ISSUE TITLE
GSL creates trouble

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#2881]
On my new desktop (stock Centos 6), the deal.II configure detects that the GSL is installed, but then, much later, we conk out with this error:
```
1075: /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libgsl.so: undefined reference to `cblas_dtrsm'                                     
```

I think someone else saw this as well as few days ago, so maybe it's a problem worth addressing more systematically. The reason is that libgsl does not record that it relies on CBLAS -- don't ask me how this happened :-( !@#$%^&*()
```
$ ldd /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../lib64/libgsl.so
        linux-vdso.so.1 =>  (0x00007ffefcff2000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f51ded7e000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f51de9ea000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f51df424000)
```
Also don't ask me why exactly it is that GSL is compiled in such a way that it links against the CBLAS, rather than the system BLAS...

Either way, can we add a link check to the GSL detection to kick out those GSL installations that create this kind of trouble?

**Comment by davydden** [comment]
here is same issue https://github.com/dealii/dealii/issues/2757

Indeed on Linux distros it seems GSL is distributed in a very funny way. For an ease of discussion, a copy-paste of another post of mine:

looking at https://www.gnu.org/software/gsl/

> GSL requires a BLAS library for vector and matrix operations. The default CBLAS library supplied with GSL can be replaced by the tuned ATLAS library for better performance,

so it looks like on Linux distros cblas is not withint gsl, but in a separate lib, like libgslcblas. What is worse is that indeed this requirement is not stated in the shared lib.

This is not the case when gsl is compiled with package managers like [Homebrew](https://github.com/Homebrew/homebrew-core/blob/master/Formula/gsl.rb) or [Spack](https://github.com/LLNL/spack/blob/develop/var/spack/repos/builtin/packages/gsl/package.py), where default cblas is used.

p.s. CBLAS is a C interface to BLAS routines.

**Comment by davydden** [comment]
One could probably check if `cblas_dasum` is contained within `libgsl` (i.e. cblas is inside). If this is not the case, then probably check if this symbol is in Blas libs found by CMake. If so, we add link dependency. Otherwise i don't think we can guess where `cblas` could be found and we need to disable GSL interface.

**Comment by bangerth** [comment]
Yes, the fundamental problem is indeed that the shared lib does not record its dependencies :-( What moron set up the makefiles for this?

**Comment by tamiko** [comment]
@bangerth 
> Also don't ask me why exactly it is that GSL is compiled in such a way that it links against the CBLAS, rather than the system BLAS...

This is pretty much a bug found on CentOS (and a few other distributions). The gsl installations I have on Gentoo and Debian behave just fine. This is by the way not the first time we have such an issue (I remember at least 5 different bugs of this kind.)

@davydden 
>  so it looks like on Linux distros cblas is not withint gsl, but in a separate lib, like libgslcblas. What is worse is that indeed this requirement is not stated in the shared lib.

Just for the record: Relying on an _external_ ```libcblas``` is the correct way to go. Bundling cblas is just plain wrong.

@davydden 
> One could probably check if cblas_dasum is contained within libgsl (i.e. cblas is inside). If this is not the case, then probably check if this symbol is in Blas libs found by CMake. If so, we add link dependency.

@bangerth  
> Either way, can we add a link check to the GSL detection to kick out those GSL installations that create this kind of trouble?

The easiest way to resolve this issue is to add (optional) known link interface libraries to ```FindGSL.cmake``` [1, 2]. I will make a pull request. With that we will resolve the issue for current (bfd-)ld. (Extra fun might be provided by some gold linker variants that might plainly refuse to link libraries with incorrect stated shared object dependencies.)


[1] With every single instance of a broken external library installation we find, I am more and more tempted to kill the whole auto-enabling of external interfaces. It is incredibly frustrating that we have to increase the footprint of our cmake configuration to work around countless distribution problems.

[2] It is always very tempting to cook up an over-engineered solution that tries to be smart (e.g. looking at defined symbols, etc.). This has the simple problem that (a) it is not platform independent and (b) doesn't help anyway. For example, it is pretty safe to just add cblas to the link interface unconditionally. Because if this leads to problems due to symbol clashes we're dead anyway: deal.II's  transitive link interface is gigantic - there is a fair chance that cblas already entered the link interface due to another library:
```
tamiko@jackdaw ~ % ldd /usr/lib/libdeal_II.so | grep cblas
        librefcblas.so.20110218 => /usr/lib64/librefcblas.so.20110218 (0x00007fb8d3446000)
```

**Comment by tamiko** [comment]
> Yes, the fundamental problem is indeed that the shared lib does not record its dependencies :-( What moron set up the makefiles for this?

Welcome to the world of build systems for scientific software.

**Comment by tamiko** [comment]
@davydden The cblas story is even more popcorn than I have imagined. [1,2,3]

[1] https://github.com/gentoo/gentoo/blob/master/sci-libs/gsl/gsl-2.1.ebuild
[2] https://github.com/gentoo/gentoo/blob/master/sci-libs/gsl/files/gsl-2.1-cblas.patch
[3] https://bugs.launchpad.net/ubuntu/+source/gsl

**Comment by davydden** [comment]
@tamiko from the patch i have an impression that GSL makefiles are broke w.r.t. external blas, are they?

**Comment by davydden** [comment]
from GSL manual  https://www.gnu.org/software/gsl/manual/gsl-ref.pdf

> To link against the library you need to specify both the main library and a supporting cblas library, which provides standard basic linear algebra subroutines. A suitable cblas implementation is provided in the library libgslcblas.a if your system does not provide one. The following example shows how to link an application with the library,
$ gcc -L/usr/local/lib example.o -lgsl -lgslcblas -lm

and

> The following command line shows how you would link the same application with an alter- native cblas library libcblas.a,
$ gcc example.o -lgsl -lcblas -lm

so it appears that developers intentionally don't include dependency on Blas.

**Comment by bangerth** [comment]
@davydden -- I think that statement just shows that they have no idea how to write portable software...
@tamiko -- thanks for thinking about how to patch this. I wanted to say that, rather than making it overly complicated, I'm also ok with just adding a link test to FindGSL.cmake. That would kick out the GSL detection and the user would be out of luck which was going to be ok with me because I thought that we really only use the GSL in unimportant places. But we've recently started using it for cspline geometries, and that is a more relevant case now.

**Comment by tamiko** [comment]
@bangerth 
>  I'm also ok with just adding a link test to FindGSL.cmake

I would like to avoid this because it adds a configure time penalty of several seconds. So I think the easiest task is to always form the full link line that upstream envisions.

Further, we might actually link successfully as long as we happen to not use the wrong symbols in ```libgsl.so``` (due to ```-Wl,-as-needed```, etc.). :-)

**Comment by bangerth** [comment]
OK, good plan. Let me know if you want me to test something.
