### ISSUE TITLE
dealii 4.8.1 Linker error LNK2005 while compiling Step-1 example under VisualStudio 2013 

### ISSUE THREAD

**Issue by loylick** [dealii/dealii#2929]
Hi!
When I compile Step-1 example (actually noy only Step-1 but all the examples which require an output into eps files) I get this error: 
deal_II.g.lib(data_out_base.obj) : error LNK2005: "public: static unsigned int const dealii::DataOutBase::Deal_II_IntermediateFlags::format_version" 
(?format_version@Deal_II_IntermediateFlags@DataOutBase@dealii@@2IB) is already defined in step-1.obj
The reason for the error is rather obvious. You have declaration and definition of the format_version variable in the header data_out_base.h: 
` struct Deal_II_IntermediateFlags : public OutputFlagsBase<Deal_II_IntermediateFlags>
  {
   static const unsigned int format_version = 3;
  };`
 data_out_base.h included in step-1.cc through grid_out.h file once comliled generates format_version instance in step-1.obj. Also the same variable format_version presents in dealii.lib itself. So we get the error. To solve the issiue I had to declare the variable in the header as follows:
`struct Deal_II_IntermediateFlags : public OutputFlagsBase<Deal_II_IntermediateFlags>
  {
   static unsigned int format_version;
  };`
And I defined it in data_out_base.cc line 1505:  
`unsigned int Deal_II_IntermediateFlags::format_version = 3;`
After that I rebult dealii.lib and step-1 compiled well. Maybe you'll find another wayout. However in libraries it is not common to define variables in headers just because of the above mentionned error one gets including such headers in code. IMHO it is always better to move definition from header to cpp file.
Alex

**Comment by drwells** [comment]
Yes, that is definitely a mistake for the reasons you mentioned (and the fix is what we do for most non-templated statically allocated objects in the library).

Would you like to turn your fix into a PR?

**Comment by loylick** [comment]
I'm new to this PR kitchen, so I'd prefer you fix it by yourself. It is just a line of code to fix, not much.

**Comment by davydden** [comment]
@loylick 

it's actually quite easy:
1) fork deal.II GitHub repo to your account
2) checkout a new branch locally
3) do changes and commit
4) push to your GitHub account
5) open a PR
see for details https://github.com/dealii/dealii/blob/master/CONTRIBUTING.md

Since you fix is especially easy, it is actually a good chance to start. Once you know how to do it, it will be easy for your to propose fixes later if you will find further bugs. deal.II is a community project that lives by the participation of its members — i.e., including you. So it would be best if you give a quick try.

ps. The procedure also the same for any project hosted on GitHub, should you contribute to other projects or use Git as VCS for your own research.

**Comment by loylick** [comment]
Sounds to be quite easy. But doing so I would fix the current development version of dealii. How about fixing 4.8.1 version?

**Comment by davydden** [comment]
@loylick AFAIR test suite is removed from releases. As for the 8.4.1., let's first fix it in the `master` branch, which you will be able to use straight away. Then we can all discuss if there is a need for `8.4.2.` which would contain this fix.

**Comment by bangerth** [comment]
(As for @davydden 's description of the procedure -- if you're into interactive demonstrations, see lecture 32.8 here: http://www.math.tamu.edu/~bangerth/videos.html .)

**Comment by bangerth** [comment]
I'm going to note for completeness that the standard actually only says that the `=3` at the variable is not a *definition*, just an initializer that is used wherever a definition is found. So, strictly speaking, you could have
```
  struct Deal_II_IntermediateFlags : public OutputFlagsBase<Deal_II_IntermediateFlags>
  {
    static const unsigned int format_version = 3;
  };
```
in the header file and
```
unsigned int Deal_II_IntermediateFlags::format_version;   // automatically initialized to 3
```
in the `.cc` file. This should have the same effect as your patch. That Visual Studio has trouble with it is, really, a problem with Visual Studio, not C++.

Of course, in reality that makes no difference at all since we want to get stuff to work.

**Comment by davydden** [comment]
fixed by https://github.com/dealii/dealii/pull/2933
