### ISSUE TITLE
TrilinosWrappers::MPI::Vector reports wrong locally_owned_elements

### ISSUE THREAD

**Issue by masterleinad** [dealii/dealii#2955]
Using the attached test at 
[https://gist.github.com/masterleinad/66e2bdbf5127e62f403d600474b960a5](https://gist.github.com/masterleinad/66e2bdbf5127e62f403d600474b960a5)
I observe that the locally_owned_elements are not the same
for a ghosted and a distributed vector initialized with the same set of locally_owned_dofs.
In particular, the output is:

>DEAL:0::locally_owned_elements_distributed: {[0,9]}
>DEAL:0::locally_owned_elements_ghosted: {[0,19]}
>DEAL:0::local_range_begin_ghosted: 0
>DEAL:0::local_range_end_ghosted: 20
>DEAL:0::local_range_begin_distributed: 0
>DEAL:0::local_range_end_distributed: 10

**Comment by tjhei** [comment]
Yes, this is a problem. I guess this happens because Trilinos doesn't really make a difference between those two types, because it supports overlapping ranges for "locally owned" entries. Further, we need to pay close attention to the ``vector_writable`` flag, because that uses a different code path.
Sorry, I am not sure what the best approach to fix this is.

**Comment by masterleinad** [comment]
Fixed by #2972
