### ISSUE TITLE
Output of map_dofs_to_support_points has changed

### ISSUE THREAD

**Issue by cpraveen** [dealii/dealii#3013]
I have included below an example code which converges with 
```
commit ed1bdc6fc1931a664bc30920f66f054907a49cce
```
but fails to converge with the next commit which is
```
commit d1e3ffcaf6733e7d8509d93785b1f9e2b16a977e
```
In this code, I solve the Winslow equations using continuous finite elements. I am using curved boundaries and I could reproduce the failure only with a complicated manifold.

The manifold I use is a NACA0012 airfoil for which I have implemented a **project_to_manifold** function, see **winslow/parallel/naca.h**. I project the candidate point onto the true boundary in the normal direction to the boundary edge.

The code is here

https://bitbucket.org/cpraveen/deal_ii/src/master/winslow/parallel/?at=master

To get the code
```
git clone https://cpraveen@bitbucket.org/cpraveen/deal_ii.git
```
The code is in 
```
deal_ii/winslow/parallel
```
Steps to run the code
```
cd deal_ii/winslow/parallel
cmake .
make
cd ../run
gmsh -2 naca_struct.geo
../parallel/main 3
```
I realise that this is a bit complicated example but I dont know what to remove to simplify it. Any tips will be useful so that I can narrow down the problem.

Also see https://groups.google.com/forum/#!topic/dealii/8lVs367Sq0s

**Comment by cpraveen** [comment]
I point out some info that might help.

The code takes a Q1 mesh and deforms it to a Qk mesh by solving the Winslow equations. The solution of the Winslow equation gives me the euler vector that can be used in MappingFEField.

In the example, I attach a NACA0012 manifold to the airfoil, then use DoFTools::map_dofs_to_support_points to obtain the initial condition for the euler vector, which also contains boundary vertices lying on the true airfoil surface.

After this step, the manifold descriptions are removed and then the PDE is solved on the Q1 mesh to get the euler vector.

So my guess is that DoFTools::map_dofs_to_support_points together with my own manifold is causing the problem. 

For my NACA0012 manifold, I have implemented the project_to_manifold function only, see

https://bitbucket.org/cpraveen/deal_ii/src/master/winslow/parallel/naca.h?at=master

I dont have any problem if I use one of the in built manifolds like SphericalManifold.

**Comment by bangerth** [comment]
It would take a good amount of debugging in a code we don't know to find out what exactly is going on. So I think it's more productive to delineate the steps that I usually use to narrow down where the problem is.

Let's say you have checked out the two offending versions of deal.II into separate source directories `dealii-good` and `dealii-bad`, and that you compiled them both separately and installed them into directories `install-good` and `install-bad`. Let's also say that you have a directory `application` in which you have your own code.

Now create two directories, `app-good`, `app-bad` parallel to `application`. Then do
```
  cd application
  for i in * ; do
    ln -s $i ../app-good/$i
    ln -s $i ../app-bad/$i
  done
```
This way you have two directories in which you can configure, compile, and run the exact same version of your application (exact same because they both contain links to the exact same source files), just compiled against the good and bad versions of the library, respectively.

So you do
```
  cd app-good
  cmake . -DDEAL_II_DIR=.../install-good
  make

  cd ../app-bad
  cmake . -DDEAL_II_DIR=.../install-bad
  make
```
If you run in these two directories, e.g., in two separate xterm windows, you will get one working and one failing run. Now start modifying the source files in `application` to figure out where the first point in the program is where there are differences. For example, after assembly, you could do insert a statement of the form
```
  std::cout << "Linear system: " << system_matrix.l1_norm() << ' ' << system_rhs.l2_norm() << std::endl;
```
I would suspect (though that doesn't have to be true -- but just assume for the moment) that if you compile and run this modification in your two windows that you will get different results. At this point, you can remove everything that is executed after this point from your program -- likely a few hundred lines of code. Or, if you're too lazy, just put `abort()` after that statement because everything that comes after it clearly only shows symptoms but not the cause of the problem.

Now that you know that the problem exists at the end of assembly, make your way further forward in the program. For example, is the local matrix on the first cell on which you assemble the same between the two programs? If it is, the problem is on a later cell. If it isn't the same, try to think about what the cause may be. Is the mesh the same? You can test that by putting output into an earlier spot of the program; if that output is different between the two programs, you can again delete everything that happens after that point.

The whole exercise is designed to find the first place in the program where you can unambiguously say that something has changed. Non-convergence is just such a non-specific problem that it is not helpful in finding what exactly is going on. It also happens rather late in typical programs that there are too many possibilities for where the root cause may be.

**Comment by davydden** [comment]
@bangerth maybe this advices/workflow should be in WiKi or homepage or sticky on google forums?

**Comment by cpraveen** [comment]
@bangerth Thanks for the detailed instructions.

I am comparing these two commits.

[1] commit ed1bdc6fc1931a664bc30920f66f054907a49cce
[2] commit d1e3ffcaf6733e7d8509d93785b1f9e2b16a977e

I have started to compare the two commits. I suspect there is some change in DoFTools::map_dofs_to_support_points. So I save the output "support_points" from this function using the two versions of deal.II and I see they are very different. It looks like I get the same values but they come in different order.

Has something changed in [2] relative to [1] that accounts for this difference ?

**Comment by bangerth** [comment]
That patch certainly could have had an effect, although I don't think that it should have. Can you create a small testcase that only generates the mesh, distributes DoFs, and calls that function?

I don't know what it would mean thta the values come in different order because I don't know how you output the data.

**Comment by bangerth** [comment]
@davydden -- good suggestion. See here: https://github.com/dealii/dealii/wiki/Frequently-Asked-Questions#user-content-my-code-converges-with-one-version-of-dealii-but-not-with-another

**Comment by drwells** [comment]
Thank you for updating the table of contents too :)

**Comment by cpraveen** [comment]
Ignore my comment about "different order". That was not correct.

To run attached code

```
cmake .
make
gmsh -2 naca_struct.geo
./main 3
```

The code sets naca airfoil as a manifold, does some setup, calls map_dofs_to_support_points and saves the support points into map.dat

The output in map.dat has changed between the two commits. The change is only in the cells adjacent to the airfoil. You can plot in gnuplot

```
gnuplot> plot 'map.dat' w p
```
[dealii_test.zip](https://github.com/dealii/dealii/files/442896/dealii_test.zip)

**Comment by cpraveen** [comment]
I have attached the output files map.dat that I get from the two versions of deal.II

Plot them together
```
gnuplot> set size ratio -1
gnuplot> p 'map_good.dat' w l,'map_bad.dat' w p
```
and zoom near airfoil to see they are different.

[maps.zip](https://github.com/dealii/dealii/files/442907/maps.zip)

**Comment by bangerth** [comment]
So these points seem similar but not the same.

Next step: the different order surprises me. If you do
```
  for (cell=...)
    {
        cell->get_dof_indices (local_dof_indices);
        for (i=...)
          std::cout << local_dof_indices[i] << std::endl;
```
do you get the same order? In other words, if you loop over all cells and look at the global indices of the degrees of freedom of all cells, are they the same?

**Comment by cpraveen** [comment]
@bangerth The dof indices are same in the two versions. 

The problem is not in the order in which support points are listed but in the value of the support points for cells adjacent to the curved boundary. These values come out different with the two deal.II versions.

If I use SphericalManifold, then I get same support points.

The difference comes with my own manifold which is a naca0012 airfoil and is implemented in naca.h via the project_to_manifold function.

**Comment by cpraveen** [comment]
I have changed the title to reflect the actual change I observe b/w the two versions of deal.II

If I use my own manifold in naca.h the output from map_dofs_to_support_points differs b/w the two deal.II versions.

But if I use some builtin manifold like SphericalManifold, the output from this functions is same in the two versions.

**Comment by cpraveen** [comment]
@luca-heltai  I try to explain the difference I observe. Below I show dof index and corresponding support point coordinates on the airfoil.

With ed1bdc6fc1931a664bc30920f66f054907a49cce
```
2  0.00413789  0.0110918
3  0  0
13  0.00292179  0.00936369
14  0.00113689  0.00589362
15  0.000145406  0.00212757
565  -49.7846  4.6366
566  -50  0
573  -49.8218  3.83599
574  -49.8923  2.3183
575  -49.9628  0.800617
```

With d1e3ffcaf6733e7d8509d93785b1f9e2b16a977e
```
2  0.00413789  0.0110918
3  0  0
13  0.000145406  0.00212757
14  0.00113689  0.00589362
15  0.00292179  0.00936369
565  -49.7846  4.6366
566  -50  0
573  -49.8218  3.83599
574  -49.8923  2.3183
575  -49.9628  0.800617
```

These are different. E.g., support points of 13 and 15 have been interchanged.

Note that I am using FE_Q<dim>(QGaussLobatto<1>(degree+1)).

**Comment by bangerth** [comment]
What do you know about dofs 13 and 15? Are these located on the same line? In the same cell?

**Comment by cpraveen** [comment]
@bangerth yes, they are on same line of same cell.

**Comment by cpraveen** [comment]
@luca-heltai @bangerth I think there is a bug introduced in get_new_point. In this line

https://github.com/dealii/dealii/blob/master/source/grid/manifold.cc#L125

the last argument should be `weight`. Making this change, my code works properly.

**Comment by cpraveen** [comment]
@luca-heltai @bangerth Changing `1 - weight` to `weight` works fine in 2-d but not for 3-d. I changed this function to an older version as follows

```
  // Now loop over points in the order of their associated weight
  double w = weights[permutation[0]];
  Point<spacedim> p = w * surrounding_points[permutation[0]];

  for (unsigned int i=1; i<n_points; ++i)
    {
      p += weights[permutation[i]] * surrounding_points[permutation[i]];
    }

  return project_to_manifold(surrounding_points, p );
}
```

With this, another issue I had is also resolved. See here

https://gist.github.com/cpraveen/6c50ca2594aa0ead9ea2e95dc1e4c6a9

Surface area of sphere had too much error and was not converging with increasing polynomial order. If I use above code in get_new_point, I now get good convergence of error to machine precision
```
$ ./surface_quad 
Testing the surface computation of a sphere
exact area : 12.5664
1 1536 0.00821636 
2 3456 1.19955e-05 
3 6144 7.39117e-09 
4 9600 7.36149e-11 
5 13824 9.79611e-14 
6 18816 1.11673e-14 
7 24576 1.00364e-14 
8 31104 3.39259e-15 
9 38400 9.18827e-15 
10 46464 8.48148e-15 
11 55296 5.65432e-15 
12 64896 4.52346e-15 
13 75264 6.60142e-14 
14 86400 5.3292e-14 
```

**Comment by luca-heltai** [comment]
This does not make any sense to me... The change was introduced by @ESeNonFossiIo, on the basis that 
~~~
get_new_point(quad({a,b}, {w0, 1-w0})
~~~
would return an intermediate point between `a` and `b` defined as `p = w0*a + (1-w0)*b`.

However, if I want a point which is at distance `s` from `a`, between `a` and `b`, I need to do `p=a+s(b-a) = (1-s)*a + s*b`. That's what the `1-w` is doing there, i.e., `get_intermediate_point(a,b,0) = a` and `get_intermediate_point(a,b,1) = b` by definition, and these would be obtained by `get_new_point({a,b}, {1,0})` and `get_new_point({a,b}, {0,1})` respectively.

The code you pointed to, makes pairwise simplifications of quadrature points, by only using the primitive `get_intermediate_point`, which in turns calls the `project_to_manifold` (in its default implementation).

I think the issue is not in `1-w` but deeper down in 

https://github.com/dealii/dealii/blob/master/source/grid/manifold.cc#L73

where the default implementation does not work correctly because 

~~~

template <int dim, int spacedim>
Point<spacedim>
Manifold<dim, spacedim>::
get_intermediate_point (const Point<spacedim> &p1,
                        const Point<spacedim> &p2,
                        const double w) const
{
  std::vector<Point<spacedim> > vertices;
  vertices.push_back(p1);
  vertices.push_back(p2);
  return project_to_manifold(vertices, w * p1 + (1-w)*p2 );
}
~~~

should really be

~~~
  ...
  return project_to_manifold(vertices,  (1-w)*p1+ w * p2);
  ...
~~~

Can you try to change this line, instead of the other, and check again if things work?

**Comment by luca-heltai** [comment]
I'm running the testsuite with the new change. I'll be submitting a patch soon if things work. I'm now convinced, after having spoken with Mauro (@ESeNonFossiIo) that the default implementation of `get_intermediate_point` is wrong. We didn't see this, because most of our classes reimplement this function instead of using `project_to_manifold`.

**Comment by bangerth** [comment]
Good detective work, @cpraveen ! Thanks for tracking this down to a level of complexity where the problem became obvious to @luca-heltai .

**Comment by cpraveen** [comment]
@luca-heltai yes, your change to get_intermediate_point also solves my problem. I have to still test it for my sphere problem. Thanks a lot for looking into this.

@bangerth Thanks a lot for the hand-holding. It helped me to keep looking for the issue.
