### ISSUE TITLE
 GridGenerator::extract_boundary_mesh for parallel::distributed::Triangulation

### ISSUE THREAD

**Issue by andreabonito** [dealii/dealii#3020]
Is  GridGenerator::extract_boundary_mesh working  for distributed triangulations?
Attached is a simple code attempting to create a surface mesh out of a half-ball volume mesh. 
It works fine when running with one proc but crashes with two:

--------------------------------------------------------
An error occurred in line <1361> of file </w/bonito/opt/dealii/include/deal.II/grid/tria_accessor.templates.h> in function
    int dealii::TriaAccessor<<anonymous>, <anonymous>, <anonymous> >::child_index(unsigned int) const [with int structdim = 2, int dim = 3, int spacedim = 3]
The violated condition was: 
    has_children()
The name and call sequence of the exception was:
    TriaAccessorExceptions::ExcCellHasNoChildren()
Additional Information: 
(none)
-----------------------------------------------

[step-1.cc.txt](https://github.com/dealii/dealii/files/439598/step-1.cc.txt)

**Comment by bangerth** [comment]
I would be surprised if it worked. We should probably provide a better error message.

The thing is that `p::d::Triangulation` objects automatically partition themselves across processors, and I don't think we can make any kinds of guarantees right that would place the cells of the surface mesh on the same processors as the cells of the volume mesh to which they are adjacent.

**Comment by andreabonito** [comment]
Maybe a "not implemented" would be more insightful. Unfortunately, this means some implementation is required...  Notice that a way around would be to re-partition the extracted mesh but I am not sure it is feasible.

**Comment by bangerth** [comment]
Yes, that's the exception that's required.

The first step of any implementation is simple: create the coarse grid of the surface mesh. That's simple because every processor knows about the coarse grid of the volume mesh. So that can be done locally. The problem is then to refine this coarse mesh the same way the volume mesh was, because we don't have the co-location of the mesh. It should not be impossible to write a function that does that, but require a bit of work and communication. The bigger question then becomes what you're going to do with this distributed surface mesh, because the correspondence between the two meshes is simply not there.

**Comment by bangerth** [comment]
#3022 adds the necessary assertion.

**Comment by bangerth** [comment]
I don't think there is much of a point keeping this one open for now -- we can always re-open it if someone is interested and willing to implement this feature. For the moment, at least the assertion is in place.
