### ISSUE TITLE
Macros undefined when using nvcc

### ISSUE THREAD

**Issue by Rombur** [dealii/dealii#3029]
From @kalj in #3005: 
I now found the problem with the DEBUG macro not being defined. Several macro definitions are eventually appended to COMPILE_DEFINITIONS, which are then used internally by CMake to create definitions for a given target. The problem is that for CUDA, where we e.g. use CUDA_ADD_EXECUTABLE instead of ADD_EXECUTABLE, these are not at all picked up. I've mailed the cmake mailing list about this, but I have not had any luck with help from there before. Maybe we have to make yet another hack ourselves...

**Comment by kalj** [comment]
Being discussed in this thread on the CMake mailing list: https://cmake.org/pipermail/cmake/2016-August/064146.html

**Comment by tamiko** [comment]
@kalj I now have a cuda toolchain on my computer. I.e., i will have a look into this. Please ping me if you don't hear back from me by the end of this week.

**Comment by tamiko** [comment]
That said, I get less impressed by the mechanics in  CMake's ```FindCUDA.cmake``` module by the minute.

**Comment by kalj** [comment]
Thank you. Yeah, it's not great to say the least.

**Comment by Rombur** [comment]
@tamiko ping (since you asked for it...)

**Comment by kalj** [comment]
@tamiko Let's make an effort on this. I think the possible solutions here are:

- Change FindCUDA / implement our own macro instead of `CUDA_WRAP_SRC`, so that properties can be set.
- Add something hacky to `DEAL_II_SETUP_TARGET` which manages to setup include directories, definitions, etc in some other way.
- Change deal.II to setup things before calling `DEAL_II_SETUP_TARGET`. Then we can use `INCLUDE_DIRECTORIES` etc which do work with CUDA.

What is your take on this?

**Comment by kalj** [comment]
I have now filed a bug for this: https://gitlab.kitware.com/cmake/cmake/issues/16401

**Comment by tamiko** [comment]
See also #3743

**Comment by tamiko** [comment]
With CMake-3.7* and #3782 applied I get the following nvcc invocation:
```
/opt/cuda/bin/nvcc -M -D__CUDACC__ ...cu -o ...cu.o.NVCC-depend
  -ccbin /usr/bin/cc -m64 -Dobj_lac.debug_EXPORTS
  -DDEBUG
  -Xcompiler ,\"-fPIC\" -arch=sm_35 -std=c++11 -DNVCC -I...
```

So at least macros get passed down.
