### ISSUE TITLE
Require sm=35 or higher when using CUDA

### ISSUE THREAD

**Issue by Rombur** [dealii/dealii#3037]
We require `sm=35` or higher when compiling the library but we don't check that the device supports `sm=35` and the user has to set `-D CUDA_NVCC_FLAGS="-arch=sm_xx"` himself at configure time.

**Comment by bangerth** [comment]
That may be what you're trying to say, but I imagine that we want to check this in cmake and set the appropriate flag ourselves, right?

**Comment by Rombur** [comment]
Yes.

**Comment by kalj** [comment]
I think the reasonable solution is to disable CUDA by default, since, as pointed out in #3229, only a fraction of the users actually are going to want it. Regarding checking if the capability of the GPU automatically, I don't think this is without problems as the build machine might not be identical to the one used for execution. I think we should require sm=35 or higher and then put in a runtime check to print something sensible if it is being executed on non-compatible hardware. How about that?

**Comment by Rombur** [comment]
@kalj So if I understand correctly, you want to set the flag to sm=35 unless the user provides the flag himself and if the hardware doesn't support sm=35 then we throw an error at runtime. I think that would be fine, as long as the behavior is documented.

**Comment by kalj** [comment]
In #2631 this was brought up, but we decided to not disable it eventually since it was a different issue. I believe we can revise that now. I will create a PR.

**Comment by kalj** [comment]
@Rombur Yes. The second half is more tricky I suspect, but also more okay to leave as-is for now, since it only affects op-in users. :)

I did some lay mans printing of error messages. I suspect that I did not follow the standard practice for how to squeal in case of errors. :) Also, maybe it is time to create a module for CUDA to put this in. Ping @tamiko.

**Comment by Rombur** [comment]
Kokkos has an init function where they do some nice checks. For example, when I run one of their tutorial I get:
`Kokkos::Cuda::initialize WARNING: running kernels compiled for compute capability 3.0 on device with compute capability 5.0 , this will likely reduce potential performance.`
Here is the function they use to check the hardware at runtime https://github.com/kokkos/kokkos/blob/9c698c86ac48dbdedd2029f5a978d87d06c1fc80/core/src/Cuda/Kokkos_Cuda_Impl.cpp#L94
