### ISSUE TITLE
Problem with ghosted elements using Trilinos:MPI::Vector

### ISSUE THREAD

**Issue by PascalKraft** [dealii/dealii#3110]
Scenario: Parallel computation yields a solution vector for a distributed triangulation and dof_handler. The parts of the triangulation per processor only have interfaces to the neighboring processes (0 only to 1, 1 to 1&3, etc.). Computation runs fine. The numbering numbering of dofs is contiguous like 

| process | n_owned_dofs | min_dof | max_dof |
| ---------- | ------------------- | ----------- | ------------ |
|0| 10800|0|10799|
|1| 10272|10800|21071|
|2| 10272|21072|31343|
|3| 10272|31344|41615|
|4| 10272|41616|51887|
|5| 10272|51888|62159|
|6| 10272|62160|72431|
|7| 10272|72432|82703|

Now I want to write the data to a vtu using data_out. Originally I did something like
```
solution.reinit(locally_owned_dofs, MPI_COMM_WORLD);
...
solution.compress(VectorOperation::insert);
...
data_out.add_data_vector (solution, "solution",dealii::DataOut_DoFData<dealii::DoFHandler<3>, 3, 3>::DataVectorType::type_dof_data);
...
data_out.build_patches ();
```

where solution is _TrilinosWrappers::MPI::Vector_ and the last line throws the following error:
for every process except 0 (because 0 owns the interface dofs to process 1)

`You tried to access element 53678 of a distributed vector, but this element is not stored on the current processor. Note: There are 10272 elements stored on the current processor from within the range 62160 through 72431 but Trilinos vectors need not store contiguous ranges on each processor, and not every element in this range may in fact be stored locally.`

The same happened for 
`solution.reinit(locally_owned_dofs, locally_relevant_dofs, MPI_COMM_WORLD, true);`
which in my oppinion should fix the problem since I have a writable (so I can use it in a solver) parallel Vector with ghost elements. However this threw the same error.
If I do something like 

```
TrilinosWrappers::MPI::Vector solution_copy(locally_relevant_dofs, solution, MPI_COMM_WORLD);
data_out.add_data_vector (solution_copy, "solution",dealii::DataOut_DoFData<dealii::DoFHandler<3>, 3, 3>::DataVectorType::type_dof_data);
```

where I copy the gosted elements to a locally owned one it works fine. Is this behaviour wanted? The data_out should only need the value to be available so it being ghosted or not should not have an impact in my oppinion or am I misunderstanding the role of ghosted elements or my own code?

**Comment by davydden** [comment]
did you have a look at step 40 https://www.dealii.org/developer/doxygen/deal.II/step_40.html#LaplaceProblemoutput_results ?
The workflow is as follows:
```
TrilinosWrappers::MPI::Vector completely_distributed_solution (locally_owned_dofs, mpi_communicator);
...// solve the system of equations
constraints.distribute (completely_distributed_solution);
locally_relevant_solution = completely_distributed_solution;
```
with
```
locally_relevant_solution.reinit (locally_owned_dofs,
                                  locally_relevant_dofs, mpi_communicator);
```
In other words you need to have **two** vectors: one without ghost elements `completely_distributed_solution` (used in SLAE) and one with -- `locally_relevant_solution` (used for output, error estimators and alike).

**Comment by PascalKraft** [comment]
Thank you for your very fast response!
The thing I'm not clear about is the following: For _Trilinos::MPI::Vector_ I have the option to make ghosted vectors writable which I did by 

`solution.reinit(locally_owned_dofs, locally_relevant_dofs, MPI_COMM_WORLD, true);`

so if the only reason to use a Vector without ghosted elements is to be able to use it in a solver for then I don't need it because the vector I initialize above does that just fine (this part works). Also it should have the ghosted elements available. So I currently don't see why I need a new vector. I have seen that it works - I was simply wondering if for this specific kind of vector the behavior shouldn't be different.

**Comment by Rombur** [comment]
@PascalKraft When you are solving the system, you probably are doing some matrix-vector multiplications inside your Krylov solver. You do not want the ghosted values here, otherwise some elements would appear multiple times. When you want to output the results, you loop over the cells and output for each cells the values at the vertices. So  you need to know the ghost values, otherwise you wouldn't be able to output the result cellwise.

**Comment by kronbichler** [comment]
> For Trilinos::MPI::Vector I have the option to make ghosted vectors writable

You can make a vector writable with the constructor/reinit method using two index set arguments, but the vector will not ghosted. Ghosted is a property for vectors we read from.

To be more precise, the reinit method with two index set arguments is used for assembly where you accumulate some integrals for remote degrees of freedom that *later* need to be shipped to the owner.

This is logically a different operation from what you need when reading from the vector as in the output function because it needs to get data from somewhere else *before* accessing the vector entries.

In the implementation of the wrapper, we have chosen the model advocated by the Trilinos developers. You are right that it is a bit wasteful to copy a vector while most of the data is available, the locally owned dofs. But not *all* data is. Ghosts are not known at that point.

**Comment by PascalKraft** [comment]
Thank you @kronbichler  and  @Rombur for your detailed explanation.
