### ISSUE TITLE
Improve inverse mapping approaches

### ISSUE THREAD

**Issue by luca-heltai** [dealii/dealii#314]
_From [bange...@gmail.com](https://code.google.com/u/111126369971033778052/) on February 19, 2014 04:45:39_

We have a number of places where we compute the inverse of the mapping F(hat x)=x for a point x in real space, finding the reference coordinates hat x. One of the places is the function that returns whether a point is inside a cell.

We do this in a sort of ad-hoc way that occasionally fails. We should take a look at Damien Lebrun-Grandie's PhD thesis (Texas A&M University, 2014) for some ideas to implement. In particular, I like the rotated bounding box (section 6.2.3) and the good initial guess (section 6.2.2) for the inversion. 

This may make for a simple project for a starting student, if anyone wants to get a student started.

_Original issue: http://code.google.com/p/dealii/issues/detail?id=186_

**Comment by bangerth** [comment]
See also #866

**Comment by drwells** [comment]
As part of #2703: while it has been about a year since I looked at this I do not recall seeing multiple implementations that could be refactored. For example, MappingFEField and MappingQGeneric don't really overlap. Does anyone know what we could do to improve this further.

My impression from a year ago was that the Newton algorithm with a line search was very robust: it took a lot of work to make the exact formula as accurate as this solver, so I would consider the default algorithm fairly robust.

**Comment by bangerth** [comment]
@drwells You looked at this in more detail than anyone else. Feel free to close.

Do you have a comment for what happens if one tries to map a point into the coordinate system of a cell, if the original point lies far outside the cell?

**Comment by drwells** [comment]
This question seems to come up frequently; I should add something to the FAQ about it.

In 1D, for better or for worse, since the transformation is affine it can always be computed (and always succeeds).

In 2D the transformation switches to Newton iteration if the exact formula fails or produces a point not in the unit cell, so in this case we would always switch to the iterative algorithm. I don't think the behavior of the Newton solver is well defined when the answer is outside the unit cell (it might converge but the answer probably has no meaning).

In 3D we only use Newton iteration so the same result holds: the algorithm will probably fail, but might succeed, for points outside the cell.
