### ISSUE TITLE
Surface area of sphere fails to converge

### ISSUE THREAD

**Issue by cpraveen** [dealii/dealii#3144]
I was testing surface area computation using

SphericalManifold<2,3>
FE_DGQArbitraryNodes(QGaussLobatto<dim>(degree+1))
MappingQ(degree)
QGaussLobatto(degree+1) for quadrature

see code here

https://gist.github.com/cpraveen/6c50ca2594aa0ead9ea2e95dc1e4c6a9

As I increase degree, I get
```
$ ./surface_quad 
Testing the surface computation of a sphere
exact area : 12.5664
1 1536 0.00823725 
2 3456 1.21078e-05 
3 6144 3.48582e-08 
4 9600 8.77328e-09 
5 13824 9.8126e-09 
6 18816 9.66812e-09 
7 24576 1.27884e-08 
8 31104 1.12567e-08 
9 38400 1.28967e-08 
10 46464 1.24116e-08 
11 55296 1.36827e-08 
12 64896 1.05048e-08 
13 75264 1.4113e-08 
14 86400 1.37372e-08
```
With simple averaging in `get_new_point`
```
  // Now loop over points in the order of their associated weight
  Point<spacedim> p;

  for (unsigned int i=0; i<n_points; ++i)
    {
      p += weights[permutation[i]] * surrounding_points[permutation[i]];
    }

  return project_to_manifold(surrounding_points, p);
}
```

gives better convergence

```
$ ./surface_quad 
Testing the surface computation of a sphere
exact area : 12.5664
1 1536 0.00821636 
2 3456 1.19955e-05 
3 6144 7.39117e-09 
4 9600 7.36149e-11 
5 13824 9.79611e-14 
6 18816 1.11673e-14 
7 24576 1.00364e-14 
8 31104 3.39259e-15 
9 38400 9.18827e-15 
10 46464 8.48148e-15 
11 55296 5.65432e-15 
12 64896 4.52346e-15 
13 75264 6.60142e-14 
14 86400 5.3292e-14
```

@luca-heltai I am not getting notifications on gist, so I am opening this issue.

**Comment by luca-heltai** [comment]
Using your changes, I still get some errors with FE_DGQ_ArbitraryNodes and QGaussLobatto:

~~~
Testing the surface computation of a sphere
exact area : 12.5664
1 1536 ERROR!!! : 0.00819939
0.00830965 
2 3456 ERROR!!! : 3.41479e-06
4.81765e-06 
3 6144 ERROR!!! : 7.56506e-06
1.98853e-08 
4 9600 ERROR!!! : 2.32763e-09
2.66224e-11 
5 13824 ERROR!!! : 7.74104e-09
2.81302e-14 
6 18816 4.24074e-15 
7 24576 1.41358e-14 
8 31104 1.5408e-14 
9 38400 2.64339e-14 
~~~

This indicates better convergence, as in your case, but there is still an issue somewhere, that I was not able to identify. I think your approach is only mitigating the problem, but the real problem is still there (and I cannot find it).

The "ERROR!!!" string above is complaining that the support points and the quadrature points are different. This should not be the case when we select FEQ with QGaussLobatto and QGaussLobatto. When refinement increases, the problem disappears, but still this does not indicate a solution... 

I think your solution makes things better for the wrong reason. I'm still looking for the real bug. I have little time, but I'll try my best...

**Comment by cpraveen** [comment]
@luca-heltai I am yet to try your fix from #3148 

I observed problem with normal vectors. I have updated the gist

https://gist.github.com/cpraveen/6c50ca2594aa0ead9ea2e95dc1e4c6a9

It compares quadrature weights and normal vectors from two sides of the face. With simple averaging in `get_new_point`, I get this
```
$ surface_quad
Testing the surface computation of a sphere
exact area : 12.5664
deg=1 ndofs=1536 , area error =0.00821636
max dweight =4.34442e-16  max dnormal=0.263919

deg=2 ndofs=3456 , area error =1.19955e-05
max dweight =4.81059e-16  max dnormal=0.000508612

deg=3 ndofs=6144 , area error =7.39117e-09
max dweight =4.36451e-16  max dnormal=0.00115419

deg=4 ndofs=9600 , area error =7.36149e-11
max dweight =4.5275e-16  max dnormal=1.6166e-06

deg=5 ndofs=13824 , area error =9.79611e-14
max dweight =5.76918e-16  max dnormal=4.43429e-06

deg=6 ndofs=18816 , area error =1.11673e-14
max dweight =3.63582e-14  max dnormal=4.90207e-09

deg=7 ndofs=24576 , area error =1.00364e-14
max dweight =5.71894e-16  max dnormal=1.48081e-08

deg=8 ndofs=31104 , area error =3.39259e-15
max dweight =5.27286e-16  max dnormal=1.88443e-11

deg=9 ndofs=38400 , area error =9.18827e-15
max dweight =7.15377e-16  max dnormal=4.57403e-11

deg=10 ndofs=46464 , area error =8.48148e-15
max dweight =6.43105e-16  max dnormal=1.1563e-12

deg=11 ndofs=55296 , area error =5.65432e-15
max dweight =6.0012e-16  max dnormal=9.27598e-13

deg=12 ndofs=64896 , area error =4.52346e-15
max dweight =6.5473e-16  max dnormal=7.02044e-13

deg=13 ndofs=75264 , area error =6.60142e-14
max dweight =6.00451e-16  max dnormal=3.2492e-12

deg=14 ndofs=86400 , area error =5.3292e-14
max dweight =6.83336e-16  max dnormal=2.2175e-12
```
The weights are almost equal, but the normal vector from two sides do not add up to zero, see value of "max dnormal".

I would like to look into the code to see if I can spot something. What parts of the code should I read ?

**Comment by luca-heltai** [comment]
The computation of the normal should not have been touched by #3148. Normals are computed using the base Manifold class, that first compute two tangent vectors and then it takes the cross product of these. 

The function in question is get_tangent_vector. The two neighboring faces should return, on the common edge, the same tangent vector. If this is not the case, then the normal may be different. I'd start by trying to write some tests in this direction.

Ps: instead of writing gists, could you make a PR by creating a new test for the library? 

(https://www.dealii.org/developer/developers/testsuite.html#layoutaddtests) 

This would be much more useful, and it would make sure that codes we change in the future won't have the same bug you are observing now...

**Comment by bangerth** [comment]
Yes, indeed. Each one of your little programs should be a separate test that we can add to the testsuite. If we end up with 20 different tests, then that much better!

**Comment by cpraveen** [comment]
Yes, I will create a test.

For sphere surface, what are the two tangent vectors ?

One tangent vector to cell edge that lies on the sphere, and the second tangent vector is along the radial direction ? Is this how it is done ?

**Comment by cpraveen** [comment]
I dont see any function like `Manifold<2,3>::normal_vector` or `SphericalManifold<2,3>::normal_vector`. I wrote this 
```
template <>
Tensor<1,3>
SphericalManifold<2, 3>::
normal_vector (const Triangulation<2, 3>::face_iterator &face,
               const Point<3> &p) const
{
   const int spacedim=3;
   
   Tensor<1,spacedim> tangent = ((p-face->vertex(0)).norm_square() > (p-face->vertex(1)).norm_square() ?
                                 -get_tangent_vector(p, face->vertex(0)) :
                                 get_tangent_vector(p, face->vertex(1)));
   Tensor<1,spacedim> radial_unit_vector = p - center;
   radial_unit_vector /= radial_unit_vector.norm();
   Tensor<1,spacedim> normal = cross_product_3d(tangent,radial_unit_vector);
   return normal/normal.norm();
}
```
but during linking, it complains of other missing functions.

**Comment by cpraveen** [comment]
I compiled with these additional functions
```
template <int dim, int spacedim>
Tensor<1,spacedim>
SphericalManifold<dim, spacedim>::
normal_vector (const typename Triangulation<dim, spacedim>::face_iterator &face,
               const Point<spacedim> &p) const
{
   std::cout << "normal2\n";
   return Manifold<dim, spacedim>::normal_vector(face, p);
}

template <>
Tensor<1,3>
SphericalManifold<2, 3>::
normal_vector (const Triangulation<2, 3>::face_iterator &face,
               const Point<3> &p) const
{
   std::cout << "normal1\n";
   const int spacedim=3;
   
   Tensor<1,spacedim> tangent = ((p-face->vertex(0)).norm_square() > (p-face->vertex(1)).norm_square() ?
                                 -get_tangent_vector(p, face->vertex(0)) :
                                 get_tangent_vector(p, face->vertex(1)));
   Tensor<1,spacedim> radial_unit_vector = p - center;
   radial_unit_vector /= radial_unit_vector.norm();
   Tensor<1,spacedim> normal = cross_product_3d(tangent,radial_unit_vector);
   return normal/normal.norm();
}
```
But when I run the test code as in the gist, the function `SphericalManifold<2,3>::normal_vector` is never invoked, which I have checked by adding some cout statements.

**Comment by cpraveen** [comment]
Also, when FEFaceValues<2,3> computes normal vectors, the function SphericalManifold<2,3>::get_tangent_vector is never invoked.

**Comment by cpraveen** [comment]
From the little I could understand by reading some code, it looks like FEFaceValues gets its normal vector from MappingQGeneric, which computes an approximate tangent vector (doesnt use Manifold I think). It then takes cross product with cell normal to get face normal.

On sphere surface, due to curvature, the cell normal would be slightly different for the two cells adjacent to a face. So the face normal you get from the two sides would not exactly sum to zero.

**Comment by luca-heltai** [comment]
So, you hit a "feature", not a bug. I thought you were using a MappingManifold object, and complained about the normals not being exact when using the Manifold. If you are using a MappingQ/MappingQGeneric, then the two normals should *not* be the same. 
With MappingQGeneric you are approximating the surface in each cell with a polynomial approximation. The normals are *not* the same. They are normals to the polynomial surface, not to the Manifold itself...

**Comment by cpraveen** [comment]
@luca-heltai yes, I can see they would be different in this case. Unfortunately, I cannot use MappingManifold with SphericalManifold.

Even if normals are approximate, it would be nice to get a unique normal on either side of the face. Otherwise, bad things can happen with DG schemes. Is it not possible that MappingQ can use Manifold::normal_vector ?

**Comment by cpraveen** [comment]
@luca-heltai What about JxW values given by FEFaceValues using MappingQ ? Will they not be exactly identical from two sides of face ?

**Comment by kronbichler** [comment]
> Even if normals are approximate, it would be nice to get a unique normal on either side of the face. Otherwise, bad things can happen with DG schemes. Is it not possible that MappingQ can use Manifold::normal_vector ?

Can you explain how you think that `MappingQ` would be problematic with DG? With `MappingQ` the normal vectors as seen from both sides of a face are the same because they rely on transforming the tangential vectors inside the face to the real space, which obviously use the same transformation. The problem arises between two faces that share a common edge (or two lines that share a point in 2D). At this position, the normal vectors are discontinuous because the representation from both sides is different as @luca-heltai points out. But the usual form of DG schemes does **not** involve normals on **two different faces**, rather the **same face** on **two different cells**.

**Comment by cpraveen** [comment]
@kronbichler I am comparing normal to common face of two cells for Triangulation<2,3> + SphericalManifold<2,3> + MappingQ. In this case, it looks like the normal computed from the two cells is not equal and opposite on the common face.

We are in case of dim < spacedim and dim=2. In this case there is only one tangent vector on the face (an edge really) and second tangent vector is taken to be a "cell_normal", see around here

https://github.com/dealii/dealii/blob/master/source/fe/mapping_q_generic.cc#L2813

This cell_normal, which is perpendicular to sphere surface, would be slightly different on the two cells since the cells have curvature. Hence the normal to common face computed from the two cells are not the same. Atleast, this is what I think is happening.

**Comment by kronbichler** [comment]
@cpraveen You are right about how the normals in `dim<spacedim`, where things work slightly differently than in the more familiar `dim=spacedim` setting.

**Comment by cpraveen** [comment]
I think this is not a serious problem. I make sure to take the normal from same side of face, so that both cells "see" a common normal vector to their common face. This way, conservation is still satisfied in DG scheme.

**Comment by bangerth** [comment]
@cpraveen -- the problem is that even if you have a C^1 surface, its approximation by `MappingQ` is only C^0. That means that both the cell normals and the tangent vectors *to the Q_p approximation will not be continuous across cell interfaces. Think of approximating a smooth curve with a chain of line segments and what that means for the normals and tangents of the original curve and the approximation.

**Comment by cpraveen** [comment]
@bangerth The normals from the two sides of face do converge to a common value as polynomial degree increases, but the convergence is very slow. See above where I show "max dnormal" When degree=5, relative error in surface area is at machine zero, but error in normal is O(1e-6). I compute normal error as

max dnormal = Max (normal_left + normal_right).norm()

where Max is taken over all faces and their quadrature points. 

Also, the error stalls at O(1e-12).

This problem is peculiar to `dim < spacedim` case. I can use `SphericalManifold::normal_vector` as I wrote above, instead of asking `FEFaceValues` for the face normal vectors. Would you consider adding these functions ? They are already present in the base `Manifold` class.

But I dont know how to get "outward normal" to the cell boundary.

**Comment by bangerth** [comment]
I am not surprised that the difference converges very slowly. If you look at numerical analysis textbooks, you'll find that polynomials of higher and higher order approximate a given function in the L2 norm, but not necessarily in the Linfty norm. (At least not for equidistant points; the situation may be different for Gauss-Lobatto points.) What you are trying to do, though, is to use the *derivative* of the polynomial approximation at the end points of your intervals, i.e., you expect convergence in the W^{1,\infty} norm. I do not know for sure, but my gut feeling is that polynomial approximation as a function of polynomial degree does not converge in this norm.

Regarding normal vector -- @luca-heltai , what do you think? I see no good reason not to do this in the manifold classes, though the mapping classes should of course continue doing what they are doing. @cpraveen , why does the default implementation of that function not work in your case?

**Comment by cpraveen** [comment]
@wolfgang `Manifold` class provides `normal_vector` function only for the case `dim==spacedim`. Hence adding `SphericalManifold<2,3>::normal_vector` would be useful for solving pde on sphere.

If such a function is available, how can I figure out the orientation of the normal vector ? When I am on `cell` and `cell->face(f)`, I need outward normal wrt `cell` on `cell->face(f)`.

**Comment by bangerth** [comment]
@cpraveen -- I can't figure out whether you are arguing for or against the addition of a `normal_vector()` function :-) 

I've updated the description of `normal_vector()` in #3198, which among other things gives my interpretation why that function should only exist for `dim==spacedim`.

**Comment by cpraveen** [comment]
Hello Wolfgang

I wanted to add such a function for SphericalManifold<2,3> but now I dont
need it.

I have implemented a cubed sphere manifold that is a simple radial
projection of a point on cube to sphere. This is commonly used
in atmospheric sciences community. See

https://www.image.ucar.edu/staff/rnair/mwr05_dg_adv.pdf

With this manifold I am able to use MappingManifold !!!

I am still doing some tests and I can contribute this manifold to deal.ii
if you think its useful.

One drawback is that cells are not of uniform size. They are smaller near
the cube edges. I think its possible to improve this.

Best
Praveen

**Comment by bangerth** [comment]
We take all contributions :-)

Do I understand you right that this is a manifold that can work with the surface for a sphere without the difficulties of a singularity in the coordinate system? That would be very cool, but I had thought we already have that in one of the two existing classes where the only problem existed with the *origin* of the coordinate system (which you don't care about because you only work on the *surface* of the sphere).

**Comment by cpraveen** [comment]
What is available in deal.II to describe surface of sphere is SphericalManifold but this cannot be used with MappingManifold.

The manifold I wrote has no problem with coordinate singularity and it can be used with MappingManifold. But it is only for describing the surface, not the interior or exterior of the sphere.

**Comment by bangerth** [comment]
I thought that `SphericalManifold` should be usable with `MappingManifold` as long as it's only used on the surface of the sphere, but not the interior. But I may be wrong.

**Comment by cpraveen** [comment]
@bangerth @luca-heltai I have added the code for the manifold here

https://bitbucket.org/cpraveen/deal_ii/src/master/cubed_sphere/?at=master

The grid from this manifold is very similar to that obtained using `SphericalManifold`, as the picture shows.
