### ISSUE TITLE
Silent failure in GridTools::collect_periodic_faces

### ISSUE THREAD

**Issue by jppelteret** [dealii/dealii#3280]
Sample code in [this gist](https://gist.github.com/jppelteret/83847fb1c542ff0386eb0b35f52950b3).

In the case that boundary ID's are set only after a grid is refined, `GridTools::collect_periodic_faces` fails to pick up periodic face pairs. This is sensible as the coarsest level faces have no colourisation, but leads to a hard to find bug if one's not vigilant in the way that one sets up the grid.

A few suggestions, both of which I'm happy to implement if they make sense:
1.  Provide an assertion that the collection process must always increase the number of matched cell/face pairs.
2. Offer the user the opportunity to set the starting cell level for the face matching process (with a default at level 0).
3. If not (2), then provide a more visible warning in [the documentation](http://www.dealii.org/developer/doxygen/deal.II/namespaceGridTools.html#aaeadfc0053429f542fbfd48d192b94f0).

**Comment by bangerth** [comment]
Yes, this is confusing behavior. It should at least be documented.

Couldn't we just keep walking hierarchically down pairs of faces even if the current pair of faces does not have "interesting" boundary indicators? It is at most `O(#faces)` in complexity, whereas right now the algorithm only walks face pairs on the coarsest level, i.e., `O(#faces on coarsest level)`. This should make relatively little difference in practice. I know this has the potential to create trouble if a processor does not own "opposite" faces, but it will work in sequential cases at least.

I suppose you want to do what you're doing because you have matching periodic boundaries that are only *subsets* of the faces of a coarse mesh? We may also just forbid this in the documentation.

**Comment by jppelteret** [comment]
No, mine was a simple case of a mixed order of operations. In my workflow I typically find need to do refinement before setting boundary indicators, so the same applied here. Ultimately periodicity does apply on the coarsest level too. I've been scratching my head to think of a situation where this would not be the case, but can't come up with one.

Ok, I'll open a PR to update the documentation. But I still think that a standard `Assert` would be handy because in effect one's calling function that ends up doing nothing, which is probably not what one's were aiming for!

I can see the problem in both the sequential/parallel case where one might have pre-refinement that leads to the finer cells being mismatched at periodic boundaries. I suspect that is why the child face traversal happens in the `make_periodicity_constraints` function as opposed to here. Thats why I suggested point (2), because they'd know a little more about their geometry. There's is however the possibility though that one later coarsens beyond the starting level...

**Comment by bangerth** [comment]
That all sounds good. I think it makes sense to require that a periodic boundary consists of COMPLETE faces of the coarse mesh, and then the assertion is useful as well. Thanks for pushing this along!
