### ISSUE TITLE
coding conventions: document the usage of .templates.h 

### ISSUE THREAD

**Issue by davydden** [dealii/dealii#3291]
I have not seen it documented anywhere, but my understanding is the following:

1. if a templated function is **not** to be instantiated, its definition is placed at the bottom of `.h` with guards against doxygen (e.g. [quadrature_point_data.h](https://www.dealii.org/developer/doxygen/deal.II/quadrature__point__data_8h_source.html) )

2. If a templated function is to be instantiated, its definition can go both to `.cc` or `.templates.h` included from `.cc` (preferences?) and then it will be instantiated based on instructions in `.inst.in`, which is processed by Cmake (?).  Examples: `source/numerics/vector_tools_project.inst.in`, `include/deal.II/numerics/vector_tools.h`, `source/numerics/vector_tools_project.cc`.

3. `.templates.h` are not to be used by users. Probably it's more of a backup plan in case a function is not instantiated during deal.II build for what the user need, then user can include `.templates.h` and hope that his combination of template parameter is also ok.

Probably the right place for that is [Coding conventions](https://www.dealii.org/developer/doxygen/deal.II/CodingConventions.html).

**Comment by drwells** [comment]
I agree that this should be mentioned somewhere explicitly. 

1. I think that we do this consistently. If there is a file where we don't do this then we should fix that (doxygen should not see template definitions).

2. One of the first things CMake does is compile an executable that reads the `.inst.in` files and generates files that are `#include`ed at the end of the corresponding `.cc` files (the `.inst` files). We have templates in both places depending on whether or not someone else might want to use the template again (then it goes in `.templates.h`): see 3.

3. I think that we do support this use case (for things like, e.g., `Vector<long double>`) but I am not aware of anyone who utilizes this (at some point I might want to run things in quad precision, so I think this feature is useful). I think that we assume that users might access these.

In a sense the `.templates.h` files are mostly redundant because there is only one place in the library where we `#include` a given `.templates.h` file in more than one source file (some of the multigrid code). I really like this convention of putting common template definitions in (labeled) header files so I do not endorse merging things :)

**Comment by bangerth** [comment]
The idea of these files is as follows:
* If we can enumerate all possible template arguments (e.g., the dimension can only be 1, 2, or 3), then a function template goes into the `.cc` file and we explicitly instantiate all possibilities. Users will not have any need to ever see these function templates because they will not want to instantiate these functions for any other template arguments anyway.
* If we can *not* enumerate all possible template arguments (e.g., vector types -- because users might want to define their own vector kinds), then the function is put into a `.templates.h` file. We `#include` it into the `.cc` file and instantiate the functions for all of the common arguments. For almost all users, this will be just fine -- they only use the (vector, matrix, ...) types we already instantiate, and for them the `.templates.h` file will not be of any interest. It will also not slow down their compilations because nothing they see will `#include` the `.templates.h` file. But users who define their own (vector, matrix, ...) types can instantiate the template functions with their own user-defined types by `#include`ing the `.templates.h` files.

Does this make sense?

**Comment by davydden** [comment]
> Does this make sense?

makes perfect sense, thanks for clarifying it. Do you mind copy-pasting this explanation to `Coding convention` ?

**Comment by bangerth** [comment]
I can try to do it on the weekend, but I'm otherwise quite overwhelmed with stuff until then. If you want to beat me to it, I'm not going to complain.

**Comment by davydden** [comment]
@bangerth sure, i will do that...

**Comment by bangerth** [comment]
Thanks, @davydden !
