### ISSUE TITLE
linear_operator and LA::distributed::Vector<> with MatrixFree 

### ISSUE THREAD

**Issue by davydden** [dealii/dealii#3295]
looks like the two can not be combined at the moment due to specifics of initialization by ``MatrixFree::initialize_dof_vector()` instead of `vector.initialize(locally_owned_dofs, mpi_communicator`:

```
The violated condition was:
   dst.partitioners_are_globally_compatible(*data->get_dof_info(0).vector_partitioner)
```

Can we overcome this limitation somehow?

**Comment by kronbichler** [comment]
Short answer: No.
We need to initialize the vectors that go into and come out of `MatrixFree` with a ghost set because we need read/write access to some ghosts and this is controlled by the indices in MatrixFree. On the other hand, the vector is initialized with `locally_owned_dofs` only.

Longer answer: We could of course modify the vectors that come into the `MatrixFreeOperators::Base` operator and do not have a globally compatible partitioner by reinitializing the vector again to the right size. It would be a bit dangerous because we change a const vector `src` but technically speaking we do these changes in a `mutable` section so it's not completely against the API.

The second option would definitely make life easier because right now the user has to be really careful with initializing all vectors through `MatrixFree::initialize_dof_vector` or from another vector with the right layout. But it slightly changes vectors in places where we do not expect them to change.

**Comment by davydden** [comment]
Thanks for explanation @kronbichler. I will keep it open just in case there are further ideas or a need for discussion, but I also assign `Low priority` tag.

**Comment by kronbichler** [comment]
I'm just rewriting the step-37 tutorial program and came to think that modifying the vector partitioner inside `MatrixFreeOperators::Base` would indeed be neat. If that were in place, I think I would be able to avoid the separate class `MGTransferMF` that I use in tests/matrix_free/parallel_multigrid_adaptive_01.cc, lines 372-404. I will try if I can make that work without trouble somewhere else...
