### ISSUE TITLE
cuda unit tests

### ISSUE THREAD

**Issue by Rombur** [dealii/dealii#3331]
@tamiko and @kalj I have a problem to add tests that use cuda. I am implementing Tensor for the GPU (@kalj this is very similar to your GpuArray) but the problem is that the header file contains some CUDA codes. I can compile the library without any problem. However when I write a test, because of the cuda code inside the header, the test needs to be compiled by nvcc instead of gcc. So I have called my test tensor.cu and try to modify the cmake code but I don't know what to do. First, I added .cu as a suitable target in macro_dealii_add_test.cmake. This gives me the error:

CMake Error at /home/bt2/Documents/dealii/build_gpu/share/deal.II/macros/macro_deal_ii_add_test.cmake:236 (ADD_EXECUTABLE):
  Cannot find source file:

    cuda_tensor_01.cc

So I excluded .cu from the ADD_EXECUTABLE, similar to what is done for the .cc. Unfortunately, this doesn't work either. I get lots of errors like the one below: 

CMake Error at /home/bt2/Documents/dealii/build_gpu/share/deal.II/macros/macro_deal_ii_add_test.cmake:236 (ADD_EXECUTABLE):
  Cannot find source file:

    complex_vector_equality_7.cu

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx
Call Stack (most recent call first):
  /home/bt2/Documents/dealii/build_gpu/share/deal.II/macros/macro_deal_ii_pickup_tests.cmake:237 (DEAL_II_ADD_TEST)
  CMakeLists.txt:4 (DEAL_II_PICKUP_TESTS)

I am not sure if there is a way to have some tests compiled with nvcc or if I need to rethink the interface.

**Comment by Rombur** [comment]
Just to explain a little bit more, I need to include this file https://github.com/Rombur/dealii/blob/matrixfree_gpu/include/deal.II/base/cuda_tensor.h in the test but when I do, I get an error because `cuda_runtime_api.h` is unknown.

**Comment by kalj** [comment]
Did you accidentally rename the file from .cuh to .h? I think we should follow that standard practice, with .cuh for all headers with explicit CUDA code inside them. I.e. .cuh can only be included from .cu, which should be compiled using nvcc.

Based on this, we should definitely make the test have a .cu ending, and fix the cmake system to accept this. I can look into that.

**Comment by Rombur** [comment]
@kalj yes, my bad. I did use `dealii__cuda_tensor_cuh` to guard the file but I guess I am just to used to `.h` :-)

**Comment by kalj** [comment]
@Rombur No worries. :D 

I thought of something while looking at your test code -- you're testing the CPU version of the code (the __host__ version), since your putting it directly in the main function. Was this on purpose? I guess it is actually not a bad idea for this kind of code which is not all that CUDA centric. In that case, you can do what I did i my code and put in a macro which removes the __host__ __device__ if included in a non-CUDA context. That would definitely be the most straightforward way, but in the long term we should really do what we suggest above.

**Comment by kalj** [comment]
I created a branch where I enable .cu tests: https://github.com/kalj/dealii/tree/cuda-tests
This works, but it is really hacky so we need something more permanent.

To set off in the right direction here, I think we need to take a step back and review how we want to design the CUDA build system in the long term. In essence, what we want to be able to do is 

- (A) set up CUDA
- (B) set up targets

for compilation of 

- (i) deal.II itself
- (ii) tests
- (iii) user applications (#2594)

(A) is quite straightforward, but for (B) it is harder since we're again affected by something we also saw in #3029; FindCUDA does not work with `ADD_PROPERTY`, meaning `DEAL_II_SETUP_TARGET` also doesn't fly. The long term solution is to fix the behavior of FindCUDA but we at least need some partial fix, or we will have to have dirty hacks all over Deal.II. I suggest we continue the discussion in #3029.

BTW, should we add this to the CUDA checklist?

**Comment by Rombur** [comment]
There is a project here https://github.com/dealii/dealii/projects/2 to keep track of what needs to be done and the progress of CUDA.

**Comment by kalj** [comment]
@Rombur Good, I believe there are some further issues related to this, but it seems I can't add stuff to the project. E.g. #2382, #2594, #2595 & #2596.

**Comment by Rombur** [comment]
@kalj Thanks, I'll add them.

**Comment by davydden** [comment]
@Rombur where you figure it out, you could also add a quick test for CUDA in `make test` (maybe a copy-paste of one of the most representative unit tests), see this issue https://github.com/dealii/dealii/issues/3230.
