### ISSUE TITLE
inst.in not processed for .cu

### ISSUE THREAD

**Issue by Rombur** [dealii/dealii#3668]
I have this file `cuda_tensor.cu` where I include `cuda_tensor.inst`. The problem is that `cuda_tensor.inst` is not generated from `cuda_tensor.inst.in`. However, if I add an empty file `cuda_tensor.cc`, then everything works. I had to put `cuda_tensor.cc` before `cuda_tensor.cu` in the CMakeLists.txt for it to work (not sure if it matters or not though).

**Comment by bangerth** [comment]
On 12/08/2016 02:09 PM, Bruno Turcksin wrote:
> I have this file |cuda_tensor.cu| where I include |cuda_tensor.inst|. The
> problem is that |cuda_tensor.inst| is not generated from
> |cuda_tensor.inst.in|. However, if I add an empty file |cuda_tensor.cc|, then
> everything works. I had to put |cuda_tensor.cc| before |cuda_tensor.cu| in the
> CMakeLists.txt for it to work (not sure if it matters or not though).

Let me speculate: cmake doesn't know how to get dependencies right 
automatically. For our .inst.in files, cmake calls a basic version of the 
compiler on each `.cc` file that "sees" that we have a `#include` directive 
for the `.inst` file, and so knows that the `.inst` file needs to be generated 
before the `.cc` file can be compiled. If cmake can't figure out that the 
`.cu` file requires the `.inst` file, then it will simply never create the 
`.inst` file because nothing seems to depend on it.

To fix this, you might have to add this dependency by hand. This probably 
requires a bit of hand-written cmake magic to figure out which `.inst` files a 
`.cu` file depends on, but will otherwise just work using the `ADD_DEPENDENCY` 
command.
