### ISSUE TITLE
-Og does not work at all with GCC 6.2

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#3737]
Having just upgraded to GCC 6.2, I'm having the hardest time debugging anything because most local variables have been optimized out. Very bad.

It turns out that we compile in debug mode with `-Og`. Replacing this with `-O0` (minus oh zero) fixes the problem. Does anyone recall why exactly we used `-Og` to begin with?

If there is no great opposition to going back to `-O0`, then I will propose a patch (already ready on my SSD).

**Comment by kronbichler** [comment]
The motivation for that change was that `-Og` promises most of the debugging experience of `-O0` but at a moderate performance hit. I do not think we checked the debug experience properly and I indeed find `-Og` unattractive for real debugging. I have a separate built which manually adds the debug flags `-O0` for exactly that reason.

Having said that, as a developer I would clearly be in favor of going back to `-O0`. Of course, performance takes a big hit, depending on what exactly you are doing. For my codes, `-Og` turns out to be 1.5-3 times slower than the release built, whereas `-O0` is 10-50 times slower. The reason is that `-Og` optimizes out function calls with access functionality and does not immediately write back and re-load temporary register values from/to memory. But performance is rarely critical when using debug mode and if it were, I'd rather manually add `-Og`.

I don't know what a typical user might experience. Debug mode at `-O0` is really slow and my students wondered several times how slow deal.II was when they were looking at the debug mode rather than release...

**Comment by davydden** [comment]
To weight in a different perspective: for user libraries/codes I would prefer to keep `-Og` to go through all asserts in debug unit tests but still keep things fast enough. Whereas if one really wants to debug something, one would manually add `-O0`. I have not tried, but it's possible that some of the deal.II's unit tests may time out with `-Og`.

**Comment by bangerth** [comment]
My concern is purely practical: Debugging is not possible at all with `-Og`. Since I spend a fair share of my time debugging internals of deal.II, this is bothersome. But I suspect that the same will be true for anyone debugging their own codes.

This all worked without any problem at all with gcc 4.8. It is completely broken with gcc 6.2 :-(

**Comment by davydden** [comment]
maybe to make everyone happy we shall add a `cmake` flag which will trigger `-O0` instead of `-Og` (default)?

**Comment by Rombur** [comment]
I agree with @davydden, we should have two different flags. I usually use the debug mode just to enable the asserts, not for debugging.

**Comment by drwells** [comment]
I am also in favor of making this conditional and keeping `-Og` as the default for performance reasons (running the test suite at `-O0` is usually unnecessary).

**Comment by bangerth** [comment]
OK, let's leave it at that then -- I'm looking forward to hearing others report on their experiences with gcc 6.2, I can't be the only one using gdb all the time :-)

**Comment by tamiko** [comment]
Two comments on the CMake part:
 - The check in question is `DEAL_II_HAVE_FLAG_Og` - so one can simply configure with
   ```
   $ cmake -DDEAL_II_HAVE_FLAG_Og=false ...
   ```
 - Alternatively,
   ```
   $ cmake -DDEAL_II_CXX_FLAGS_DEBUG="-O0" ...
   ```

**Comment by drwells** [comment]
@bangerth It is annoying for exactly the reason you gave (important things are optimized out) but I need to do that so infrequently that I have just gotten by without it.

**Comment by davydden** [comment]
so it looks like `cmake -DDEAL_II_HAVE_FLAG_Og=false` enables `-O0`, right? @bangerth : would it be amicable solution for your problem?

**Comment by davydden** [comment]
p.s. maybe we should document it somewhere (add a note in https://www.dealii.org/developer/users/cmake.html?)

**Comment by bangerth** [comment]
On 01/06/2017 11:19 AM, Denis Davydov wrote:
> so it looks like |cmake -DDEAL_II_HAVE_FLAG_Og=false| enables |-O0|, right?
> @bangerth <https://github.com/bangerth> : would it be amicable solution for
> your problem?

Yes, that's fine by me!
