### ISSUE TITLE
doxygen: tensor friend functions

### ISSUE THREAD

**Issue by tjhei** [dealii/dealii#3756]
It looks like doxygen gets really confused by the friend functions ``deviator_tensor``, ``identity_tensor``, etc. in ``symmetric_tensor.h``: https://www.dealii.org/developer/doxygen/deal.II/classSymmetricTensor.html#a0d40eac7f1138a9018c41564f5712ee1

It looks like it sees the friend declaration and picks up the template arguments ``dim2`` and ``Number2`` from there and then groups the two overloaded functions (for ``Number`` and ``double``) into one.

Any better ideas than wrapping the friend declaration and the ``double`` cases in ``#ifndef DOXYGEN``? I tried it just for the friend declaration but that didn't help.

**Comment by bangerth** [comment]
The problem might go away in C++11 since we can delete the `double` specialization and simply give the other function a default template argument.

Because the description appears twice, my suspicion is that it just merges the two specializations. What happens if you enclose the specialization in `#ifndef DOXYGEN`? That of course has the distinct disadvantage that we no longer document a function we want people to use...

**Comment by tjhei** [comment]
> my suspicion is that it just merges the two specializations

Yes, it merges the two overloads. It is not a template specialization but two overloaded functions, right? 

> What happens if you enclose the specialization in #ifndef DOXYGEN?

That should work but removes the second function from doxygen (including the documentation that might be different, see [unit_symmetric_tensor](https://www.dealii.org/developer/doxygen/deal.II/classSymmetricTensor.html#a9b919d70d4c4c5c0dfc06435b0482621) for example).

> That of course has the distinct disadvantage that we no longer document a function we want people to use...

Yes. Let's see if anybody has a better idea.

**Comment by davydden** [comment]
@dealii/dealii what do we do with this issue?

**Comment by drwells** [comment]
The release happened without this fix, so I think that it is fair to remove the milestone.
