### ISSUE TITLE
fe_abf_02 fails on Sierra with clang 8.0.0

### ISSUE THREAD

**Issue by davydden** [dealii/dealii#3935]
```
        2828 - fe/abf_02.debug (Failed)
	2829 - fe/abf_02.release (Failed)
```
diffs look big:
```
----------------
##9       #:5   <== 3.76386
##9       #:5   ==> 2.64943
@ Absolute error = 1.1144300000e+0, Relative error = 4.2063009779e-1
----------------
##10      #:5   <== 16
##10      #:5   ==> 9
@ Absolute error = 7.0000000000e+0, Relative error = 7.7777777778e-1
----------------
##12      #:8   <== 2.50000
##12      #:8   ==> -0.618870
@ Absolute error = 3.1188700000e+0, Relative error = 5.0396205988e+0
```

**Comment by bangerth** [comment]
This is the starting value for a CG solver, i.e., the norm of the rhs. It really should be predictable.

When fixing up the ABF element over the last couple of months, I have had on occasion non-reproducible runs. Something in the element depends on uninitialized memory, or triggers a race condition. I get different results once every dozen or so run. I don't recall if that was an issue with this particular element order used in the test, but I do recall that it was with higher degrees and in 3d. I never found where exactly the problem is.

If you delete the output file or just run the test executable by hand a second time, do you reproducibly get the output you show?

**Comment by davydden** [comment]
@bangerth you are right -- I run it again and the result is different!

Sometimes I even have
```
--------------------------------------------------------
An error occurred in line <1792> of file </Users/davydden/spack/var/spack/stage/dealii-develop-yfqypqhbak6tfj2t5zlz7t55otkc32pm/dealii/include/deal.II/lac/full_matrix.templates.h> in function
    void dealii::FullMatrix<double>::gauss_jordan() [number = double]
The violated condition was:
    max > 1.e-16*typical_diagonal_element
Additional information:
    The maximal pivot is 1, which is below the threshold. The matrix may be singular.
--------------------------------------------------------
```

**Comment by bangerth** [comment]
Yes, I have that error intermittently as well. Never figured out where the issue is. I thought it may have been #3457, but that is fixed now. I also checked that the class has no mutable member variables. 

Can you close this pull request (because it doesn't address the underlying issue) and instead open a github issue about the non-reproducible output of the ABF element (with a link to here)?

**Comment by davydden** [comment]
> Can you close this pull request 

hm, this is an issue :smile:

> github issue about the non-reproducible output of the ABF element

will do.

**Comment by bangerth** [comment]
Ah, yes, my mistake. Regardless, the new one is more on point. Thanks!
