### ISSUE TITLE
detailed.log in the test folder for an already installed lib shows wrong compiler

### ISSUE THREAD

**Issue by davydden** [dealii/dealii#3973]
subj.

In the build folder I have `GNU 6.3.0` whereas in the test folder for an already installed library detailed log has a single entry corresponding to the system-provided compiler `GNU 5.4.0`

**Comment by tamiko** [comment]
@davydden How do you run the testsuite? Can you post the full command line invocation please.

**Comment by davydden** [comment]
@tamiko 

> How do you run the testsuite? Can you post the full command line invocation please.

from an **empty** folder within the dealii source root:

```
$ echo $DEAL_II_DIR
/home/davydden/spack/opt/spack/linux-ubuntu16.04-x86_64/gcc-7.2.0/dealii-develop-om6ju7ginrgr3qpvulc6gohbwmieigky
$ cmake ../tests/
$ make -j8 setup_tests
$ ctest -j8
$ ctest -j8 -DDESCRIPTION=Spack -V -S ../tests/run_testsuite.cmake
```

native GCC is
```
$ gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.5) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
which gets mixed in logs with `7.2.0` I used to compile everything.

That clearly has to do with `run_testssuite.cmake` only, which creates `detailed.log`.

So it looks like instead of taking configure options from the installed dealii, `run_testssuite.cmake` looks for a compiler in path and writes down its version, which is not correct.

**Comment by tamiko** [comment]
The problem is the `run_testsuite.cmake` invocation.
 
The minimal `detailed.log` file gets created in `run_testsuite.cmake` [1]. Normally, the configure step will override the file. Now, this doesn't happen because you only configure the testsuite (not the whole project.)

The only feasible workaround I see at the moment would be to simply set the environment variable CXX when you run `ctest ... run_testsuite.cmake`. Everything else gets very ugly.

[1] Purely for being able to append a compiler name to the build id - even in case the configuration fails.

**Comment by bangerth** [comment]
Could you put `run_testsuite.cmake` into the build directory and have it be a configured file you create in the original `cmake` run? Then you can stick the correct compiler in there.

**Comment by tamiko** [comment]
@bangerth Yes, one can also retain the `detailed.log` file from the original compilation and installation and simply copy it to the test binary directory. But this is nothing that I can automate in `run_testsuite.cmake`.
