### ISSUE TITLE
ParameterHandler::print_parameters() and friends should be const

### ISSUE THREAD

**Issue by davydden** [dealii/dealii#3989]
subj. I did not dig into the code, but I see no reason why they should not be declared as `const`.

**Comment by bangerth** [comment]
The problem is that when printing, the function calls `enter_subsection()` and `leave_subsection()`, which alters the state of the object temporarily. The function, however, leaves the state of the object the same after it exits.

I agree that this could probably be done differently by just walking the data structure directly, rather than using the two functions above.

**Comment by davydden** [comment]
maybe if `enter_subsection()` and `leave_subsection()` are harmless, some private variable can be made `mutable`?

**Comment by bangerth** [comment]
But that seems like the wrong approach as well: `mutable` variables are ones that can be changed without altering the *externally visible state* of an object. Think of scratch arrays, for example. But the variable that stores where in the "directory tree" we are do yield externally visible effects.

**Comment by davydden** [comment]
agreed.
