### ISSUE TITLE
matrix free MSVC issues

### ISSUE THREAD

**Issue by tjhei** [dealii/dealii#3997]
This has been introduced in the last couple of days. I don't have time to look at them right now, but this needs to be fixed. See https://jenkins.tjhei.info/job/dealii-windows-compile/CC=msvc2015,label=win/lastBuild/console for details:
```
E:\jenkins\workspace\workspace\dealii-windows-compile\CC\msvc2015\label\win\source\multigrid\mg_transfer_matrix_free.cc(314): warning C4307: '*': integral constant overflow [E:\jenkins\workspace\workspace\dealii-windows-compile\CC\msvc2015\label\win\build\source\multigrid\obj_multigrid_debug.vcxproj]
```
followed by
```
    54>e:\jenkins\workspace\workspace\dealii-windows-compile\cc\msvc2015\label\win\include\deal.ii\matrix_free\fe_evaluation.h(5698): fatal error C1001: An internal error has occurred in the compiler. [E:\jenkins\workspace\workspace\dealii-windows-compile\CC\msvc2015\label\win\build\source\numerics\obj_numerics_release.vcxproj]
```

**Comment by bangerth** [comment]
I appreciate the verbosity of the error message -- not... Line 314 is this one:
```
        if (prolongate)
          {
            t0 += Eval::dofs_per_cell;                   // ****** here
            t2 += Eval::n_q_points;
          }
        else
          {
            t0 += Eval::n_q_points;
            t2 += Eval::dofs_per_cell;
          }
```
`t0` and `t2` are of type `VectorizedArray<Number> *`. It's unclear to me what the `'*'` refers to in the error message...

**Comment by bangerth** [comment]
Here's the explanation of the warning: https://msdn.microsoft.com/en-us/library/4kze989h.aspx

**Comment by bangerth** [comment]
I can only imagine that the compiler transforms the expression `t0 += Eval::dofs_per_cell;` into
```
  (char *)t0 += sizeof(*t0) * Eval::dofs_per_cell;
```
It would be interesting to see what data type `Eval::dofs_per_cell` has, and how large the compiler thinks `*t0` is. But neither can be a problem...

**Comment by kronbichler** [comment]
@tjhei If I read the error message correctly, there must not be an immediate relation between the warnings and the internal errors. For the former, MSVC sees bad accesses because I compute offsets of the form `ptr + temp_size` with `temp_size = numbers::invalid_unsigned_int`. It is wrapped into `if (temp_size < 100)`, though, so I do not see it immediately. I can probably work around that one.

As for the internal compiler error, I do not really see what is going on there: It values in line `5698` which is `EvaluatorTensorProduct<evaluate_symmetric,dim,fe_degree,n_q_points_1d,Number>
  ::gradients`, i.e., a function that should not be called.

I have no Windows system available, but I can try to fix the warnings. Shall we try to go that route and see if it also cures the compiler error?

**Comment by tjhei** [comment]
> If I read the error message correctly, there must not be an immediate relation between the warnings and the internal errors

That might be, but both of them recently appeared.

> I have no Windows system available, but I can try to fix the warnings.

I can take a look, but not in the next two weeks, I think. If you have an idea nad create a pull request, I can trigger a build and see if it fixes it.
