### ISSUE TITLE
Bug/Design flaw: FEFieldFunction: _list function in parallel

### ISSUE THREAD

**Issue by tjhei** [dealii/dealii#4081]
Discovered while working on #4080. The function ``compute_point_locations`` throws ``ExcPointNotAvailableHere`` if one of the points is not available locally. This of course doesn't make much sense because you can hand in several points where some of them are available locally, while some are not. 

Of course the problem is that the current API doesn't really allow you to return a few points. We can't really change the interface because it comes from ``Function``.

Any suggestions besides documenting this fact?

**Comment by bangerth** [comment]
You could fill the returned values for points that are not locally owned with NaNs, instead of throwing an exception.

But I'll note that the intent of the class (originally) was probably to evaluate the solution at quadrature points on the same cell. In hindsight, this is probably the points on one cell of a mesh that is not related to the mesh on which the function is defined, so your problem does seem to be germane. 

I tend to think that the right solution from user code would be to try all points at once, and if the operation fails try them individually. This is how I would also document it.

**Comment by kronbichler** [comment]
We have accumulated a number of newer facilities to evaluate multiple points, including improvements in `compute_point_locations`. Closing this, as new questions/requests should be tackled for those interfaces in my opinion.
