### ISSUE TITLE
FEEvaluation::submit_value() and integrate_value() on irregular cells

### ISSUE THREAD

**Issue by davydden** [dealii/dealii#4421]
i noticed that in the code like
```
        fe_eval.reinit(cell);
        for (unsigned int q=0; q<n_q_points; ++q)
          {
            vec_f_q = some_function(fe_eval.quadrature_point(q)); // set full SIMD vector regardless of the cell
            fe_eval.submit_value(vec_f_q,q);
          }
        vec_integral += fe_eval.integrate_value();
```
gives result which is different from that obtained by explictly zeroing elements of the `VectorizedArray` on irregular cells
```
for (unsigned int v = fine_level_data->n_components_filled(cell); v < VectorizedArray<double>::n_array_elements; v++)
      vec_f_q[v] = 0.;
```
before calling `submit_value()`. 

I would have expected that `JxW(q)`, that are eventually used in `integrate_value()`, should have part of SIMD vector zero for irregular cells. But this does not appear to be the case.

If so, is it a bug or an expected behaviour?

**Comment by kronbichler** [comment]
The scheme applied in the SIMD vectors within FEEvaluation is that all geometry-related data (`inverse_jacobian`, `JxW`, etc.) is copied from the last valid SIMD component. This is done in order to avoid division by zero or other operations on singular data. It is only the `read_dof_values` and `distribute_local_to_global` functions that ignore the invalid entries in order not to affect the solution vectors.

Does that make sense? Do you have suggestions for improvement, like augmenting the documentation? Your observation is right in the sense that one needs to take care with those entries at some point, either by sending a zero entry (like you did) or by ignoring the result after the computation.

**Comment by davydden** [comment]
> The scheme applied in the SIMD vectors within FEEvaluation is that all geometry-related data (inverse_jacobian, JxW, etc.) is copied from the last valid SIMD component. This is done in order to avoid division by zero or other operations on singular data. It is only the read_dof_values and distribute_local_to_global functions that ignore the invalid entries in order not to affect the solution vectors.

can we not set `JxW` to zero for those entries (which is kind of setting quadrature weights to zero and  let the rest follow automatically)? I don't think we ever need to divide by `JxW[q]`. 

> Does that make sense?

for `inverse_jacobian` it certainly does. For `JxW` i don't immediately see where you would need its inverse.

> Do you have suggestions for improvement, like augmenting the documentation? 

if the above is not possible, i would certainly add a discussion about it in `FEEvaluation`. Essentially, copy-pasting what you wrote above.

**Comment by davydden** [comment]
> can we not set JxW to zero for those entries 

i guess we can not, indeed, as someone may want to calculate the cell's volume and divide by it.

**Comment by davydden** [comment]
> i guess we can not, indeed, as someone may want to calculate the cell's volume and divide by it.

@kronbichler on another hand, if we set `JxW` to zero, then if someone tries to divide by the cell of volume, it will immediately see the error. Whereas in the code above you would still get some values, just wrong values. This is much harder to notice/debug. So i still believe we should set `JxW` to zero so that in those (rare?) cases when users do `1./sum_q JxW[q]`, the error is apparent and it's a matter of setting unused part of the SIMD vector to something nonzero.

**Comment by kronbichler** [comment]
> I don't think we ever need to divide by JxW[q].

That depends on the application. My codes do it quite often because the inverse mass matrix involves the inverse of the JxW (see `CellwiseInverseMassMatrix`).

> if we set JxW to zero, then if someone tries to divide by the cell's volume, he/she will immediately see the error.

But it is not an error to divide by the cell's volume. Put more generally, the vectorization approach in `FEEvaluation` should behave as if the empty SIMD lanes were not there. The basic property we agree upon is that it should not add any contribution to vectors when computing integrals, which is of course fulfilled. But it also should be transparent when doing other operations. Divisions for example because you compute a cell-wise stabilization parameter that gets weighted by the cell volume, as you point out. Divisions by zero can invoke a floating point exception, and you don't want to trigger them on artificial data. (You also want to avoid working with subnormals or NaNs for performance reasons, but that is more of a corollary to the previous two approaches.)

On the other hand, I admit that this can cause a problem: You compute a local integral (where you wouldn't care about the content in the artificially filled up lanes) but you then sum this into a global result (where it gives wrong results). So we are really looking at conflicting requirements here.

What we could do is make the result of `integrate_value` zero the non-filled lanes at the end, as opposed to making the `JxW` zero which would be a pain in a number of contexts.

More generally, we would need some kind of contract of how the unused lanes behave. My point of view is that one should not make any assumptions on the local content inside a cell loop - except for minimizing the risk for floating point exceptions and other unexpected slowdown. This approach was used and the only failure I see is when you try to accumulate results over several cells from within a `VectorizedArray` that does not go through a `distribute_local_to_global` or `set_dof_values` call.

**Comment by davydden** [comment]
> What we could do is make the result of integrate_value zero the non-filled lanes at the end, as opposed to making the JxW zero which would be a pain in a number of contexts.

Let's just document this behaviour. In other places I don't use `integrate_value` but actually integrate manually via `JxW` as I need to integrate several scalar valued fields stored in SIMD quadrature data. So if we only make it right in `integrate_value`, users can still be surprised when using `JxW` directly.

**Comment by kronbichler** [comment]
Alright, I will add this documentation during the next days.

**Comment by davydden** [comment]
>  So we are really looking at conflicting requirements here.

that i agree.

**Comment by kronbichler** [comment]
Yes, the problem is that the behavior is fine as long as you do not cross the lanes of the SIMD vector, i.e., mix the results from different cells. But one has to be really careful once that happens.
