### ISSUE TITLE
Deprecate ParameterHandler::print_parameters_section()

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#4473]
#3989 is about making `ParameterHandler::print_parameters()` a `const` function, as it probably ought to be. The problem is that it calls `ParameterHandler::print_parameters_section()` which goes into each subsection, prints parameters, and then out -- but going into and out is a non-`const` operation because it changes the current state of the object. That is the original sin of this function.

I suspect that the function is not widely used, and indeed its documentation says this:
```
   * In most cases, you will not want to use this function directly, but have
   * it called recursively by the previous function.
```
(The previous function being `print_parameters()`.) I believe that the right solution to the conundrum is:
* To deprecate the function
* To introduce a separate function that is `const`; there is no reason for this function to be `public`.
* To have `ParameterHandler::print_parameters()` call the new internal function.

**Comment by drwells** [comment]
None of the projects I track use this function, so I think no one will notice if it is deprecated.

**Comment by davydden** [comment]
i played around with `print_parameters()` but decided not to use it as it prints **all** parameters, whereas in order to be able to easily reproduce some calculations it's enough to output input file to a log so that one could copy-paste it. The input parameter file might contain only a few non-default values which makes it much smaller than printing all the options.

For the reason above, I am in favour of

> To deprecate the function
