### ISSUE TITLE
ZeroFunction and ConstantFunction minor issues

### ISSUE THREAD

**Issue by davydden** [dealii/dealii#4478]
both lack default value for `component` in `value()` method. Also they are in `dealii` namespace, whereas all the other functions are in `dealii::Functions` namespace. I think we should move them for consistency, but i am not quite sure how to depricate it properly.

**Comment by bangerth** [comment]
For the default argument: do you mean that the `value()` function does not declare a default value for the `component` argument, whereas the base class does? That should be easy to fix, but because most people call the function through a reference to the base class, it does not matter much in practice.

Regarding moving: move it to the new namespace, then put a `using` declaration into the old namespace that is marked as `DEAL_II_DEPRECATED`.
