### ISSUE TITLE
.png file links broken in http://dealii.org/8.2.1/doxygen/deal.II/classFE__Q.html

### ISSUE THREAD

**Issue by hovey** [dealii/dealii#463]
In the file http://dealii.org/8.2.1/doxygen/deal.II/classFE__Q.html, 
think links to .png files are broken and show only placeholders, e.g. ![broken image](https://www.dealii.org/images/shape-%20%20functions/lagrange/Q2/Q2_shape0000.png)

The beginning of the errors starts at:
```html
    <p>In 2d, these shape functions look as follows (the black plane corresponds to zero; negative shape function values may not be visible): </p>
    <table class="doxtable">
    <tr>
    <td align="center"><div class="image">
    <img src="http://www.dealii.org/images/shape-
      functions/lagrange/Q2/Q2_shape0000.png" />
    </div>
```
Thank you.  
- Chad Hovey

**Comment by bangerth** [comment]
Chad -- yes, a change just before the release broke the links :-( There is little we can do at this point (this is part of the release) other than actually fixing the file on the server by hand (which I can't do because I don't have access to the machine).

On the other hand, the developer version is fixed:
  http://dealii.org/developer/doxygen/deal.II/classFE__Q.html
