### ISSUE TITLE
Fix rotation matrix as described in step-18

### ISSUE THREAD

**Issue by kuberry** [dealii/dealii#468]
In step 18, the rotation matrix is defined as

 const double rotation[3][3]
= {{
t *axis[0] *axis[0]+c,
t *axis[0] *axis[1]+s *axis[2],
t *axis[0] *axis[2]-s *axis[1]
},
{
t *axis[0] *axis[1]-s *axis[2],
t *axis[1] *axis[1]+c,
t *axis[1] *axis[2]+s *axis[0]
},
{
t *axis[0] *axis[2]+s *axis[1],
t *axis[1] *axis[1]-s *axis[0],
t *axis[2] *axis[2]+c
}
};

However, entry (3,2) should be:
t *axis[1] *axis[2]-s *axis[0],
rather than:
t *axis[1] *axis[1]-s *axis[0],

as can be seen in http://www.gamedev.net/page/resources/_/technical/math-and-physics/do-we-really-need-quaternions-r1199

You may notice that entry (1,3) disagrees also between step-18 and http://www.gamedev.net/page/resources/_/technical/math-and-physics/do-we-really-need-quaternions-r1199, however there is a typo in that entry in http://www.gamedev.net/page/resources/_/technical/math-and-physics/do-we-really-need-quaternions-r1199 and step-18 is correct (as can be verified by checking the previous set of equations preceding the rotation matrix at http://www.gamedev.net/page/resources/_/technical/math-and-physics/do-we-really-need-quaternions-r1199).

**Comment by jppelteret** [comment]
@bangerth I'm sorry to report that once the rotation matrix in step-18 is corrected, the solution no longer appears to exhibit a buckling instability. 
![step-18-fixed_rotation_matrix](https://cloud.githubusercontent.com/assets/10460610/21774384/9bebaa40-d692-11e6-9a55-0e881a0b1788.png)

**Comment by jppelteret** [comment]
Well, at least not for the refinement level etc. that I've created a test-case for...

**Comment by tjhei** [comment]
Well, that is certainly interesting. Would it make sense to introduce an instability using an initial condition or something?

**Comment by jppelteret** [comment]
One could perturb the geometry slightly. That would probably do the trick.

**Comment by jppelteret** [comment]
However, it would probably be best for me to try to recreate the conditions under which the original results were created in order to confirm this result. Maybe the conditions are too "simple" to generate significant numerical errors that could lead to this result (as I think was an observation made in the conclusions in step-18).

**Comment by jppelteret** [comment]
I've just confirmed that if there is a real geometry-induced instability then it doesn't naturally appear for the given loading conditions. In this picture the red is the original result and the grey is the new result. I've tried to indicate where the cylinder's original axis is. You can see that the new result remains more-or-less symmetric about the z-axis. Not entirely surprising because the original stress tensor was probably not azimuthally constant.
 ![step-18-fixed_rotation_matrix-comparison](https://cloud.githubusercontent.com/assets/10460610/21776914/0f191b1a-d69d-11e6-91f6-77f8814e6d7c.png)

**Comment by bangerth** [comment]
Thanks, @jppelteret, for finally getting this fixed! I'm ok with just updating the outputs to show the new version, even if it's symmetric -- it's still interesting behavior, with or without the collapse to one side.

**Comment by jppelteret** [comment]
Thanks to @kuberry for pointing out that there was indeed an issue in the first place!
