### ISSUE TITLE
run CUDA build on Travis and run tests on tester

### ISSUE THREAD

**Issue by davydden** [dealii/dealii#4786]
we should certainly run CUDA build on Travis to make sure existing functionality is not broken. It would be also good to have a tester to run CUDA tests.

**Comment by Rombur** [comment]
I don't think that Travis has gpus that we can use. My plan for today is to have a nightly tester for cuda but I won't be able to send the results to cdash (the machine is behind Oak Ridge's firewall). Instead, I will report the results [here](https://cloud.cees.ornl.gov/jenkins-ci/).

**Comment by Rombur** [comment]
I have setup the tester. It will run nightly. You can see the results [here](https://cloud.cees.ornl.gov/jenkins-ci/job/deal.II/lastBuild/compiler=GCC54,slave=fetnat01/console) 99% of the error are due to one error (this [include](https://github.com/dealii/dealii/blob/master/include/deal.II/base/numbers.h#L28) cannot be found). Basically the problem is now almost everything needs to be compiled through `nvcc` when you use cuda.

**Comment by Rombur** [comment]
Apparently this can be fixed if we are smarter in our cmake. We just need to include the right directory when we use gcc and cuda is enable.

**Comment by Rombur** [comment]
@davydden I think this can be closed. I checked and we cannot run CUDA code on Travis. The CUDA server is set up and report to cdash.

**Comment by davydden** [comment]
Thanks!
