### ISSUE TITLE
Step-36 problem

### ISSUE THREAD

**Issue by BEMfreshman** [dealii/dealii#5017]
Hi,
I want to use deal.ii to solve eigenvalue problem. And I notice that step-36 in tutorial is exactly what I want.So I build deal.ii on Archlinux via yaourt with Petsc.
But when I test, the system report that there is no file or directory named libmpi.so.12 which can be opened and used by executable file.

Is there anyone can tell me how to solve it?
Thanks in advance.

**Comment by davydden** [comment]
Hi, most likely you did not use the same MPI when compile deal.II as the one used in `petsc`. If you are not sure how to address this, it might be easier to try automated options, see "Source-based Installers" among [Installers and Packages](https://www.dealii.org/download.html). In general, such questions fit better into the [user forum](https://groups.google.com/forum/?fromgroups#!forum/dealii).

**Comment by drwells** [comment]
@BEMfreshman Like Denis mentioned the mailing list is usually a better place for asking these types of questions. Nevertheless I suspect that this is easy to fix; you probably updated your system copy of openmpi and petsc is now linked with a file that has since been removed (the latest version on Arch Linux is `/usr/lib/openmpi.so.20.10.1`). You should recompile PETSc from scratch and then recompile deal.II and everything should work. If not, please either post to the mailing list or (if that is not possible) email me.

**Comment by BEMfreshman** [comment]
Thanks for your information.
Now,I have build deal.ii with petsc using the script from candi-dealii, and it works well.
Thank you for your excellent FEM package.
