### ISSUE TITLE
More SUNDIALS interfaces.

### ISSUE THREAD

**Issue by luca-heltai** [dealii/dealii#5027]
Sundials provides several interfaces that should be included in deal.II. 

In particular we should provide interfaces to

- [ ] CVODE
- [ ] CVODEs
- [x] ARKODE
- [x] IDA
- [ ] IDAs
- [x] KINSOL

In https://github.com/mathlab/deal2lkit we cover `IDA`, `ARKODE`, and `KINSOL`, but the general idea is simple enough to extend to all other solvers as well.

**Comment by luca-heltai** [comment]
#4852 Implements IDA

**Comment by bangerth** [comment]
#5044 adds ARKODE

**Comment by juan42** [comment]
Since we had a really pleasant experience with the the library and existing IDA interface and our final goal is time dependent adjoint sensitivities, i'd like to implement the IDAs interface.

Before i really start though, i'd like to know if there is already work going on.
My initial steps would be

1. Mostly copy/paste work from existing IDA wrapper
2. Test IDAS for an IVP (which is exactly what IDA is doing right now)
3. Test IDAS for FSA (forward sensitivity analysis)
4. Test IDAS for ASA (adjoint sensitivity analysis)

I'd appreciate any suggestions on how to tackle this. I'd also like to know if there is an opinion on having IDA and IDAs coexist.

**Comment by drwells** [comment]
We've made a lot of independent progress on SUNDIALS recently that is tracked elsewhere.
