### ISSUE TITLE
Remove second argument of type Point<dim,Number>?

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#526]
When `Tensor<rank,dim,Number>` got its type argument `Number`, `Point<dim>` also got such an argument. But I can't really see why given how we use it, and I would like to propose to get rid of it again.

There are currently only a handful of instances where this type is anything other than `double`:
- `Function<dim,Number>` takes `Point<dim,Number>` as arguments. I think this is actually a mistake and I don't really see why
- There are a couple of instances in the matrix_free framework:

```
include/deal.II/matrix_free/mapping_data_on_the_fly.h:      const AlignedVector<Point<dim,VectorizedArray<Number> > > &
include/deal.II/matrix_free/mapping_data_on_the_fly.h:      AlignedVector<Point<dim,VectorizedArray<Number> > > quadrature_points;
include/deal.II/matrix_free/mapping_data_on_the_fly.h:    const AlignedVector<Point<dim,VectorizedArray<Number> > > &
include/deal.II/matrix_free/mapping_info.h:        AlignedVector<Point<dim,VectorizedArray<Number> > > quadrature_points;
include/deal.II/matrix_free/fe_evaluation.h:  const Point<dim,VectorizedArray<Number> > *quadrature_points;
include/deal.II/matrix_free/fe_evaluation.h:  Point<dim,VectorizedArray<Number> >
include/deal.II/matrix_free/fe_evaluation.h:Point<dim,VectorizedArray<Number> >
include/deal.II/matrix_free/fe_evaluation.h:      Point<dim,VectorizedArray<Number> > point (false);
```

These are also the only uses in the tutorial programs (step-37) and the corresponding tests. I don't know whether these places of "Point of Array" could be replaced by "Array of Points" somehow -- it certainly seems awkward/unintuitive the way it is. I don't intend to change anything about the Tensor class, so maybe one could also replace these places by "Tensor of Array". @kronbichler ?

**Comment by bangerth** [comment]
To be clear about the use in `Function`, I think this actually makes it rather impossible to use the `Function` class for anything other than `double`. It does make sense to have a `Function<dim,std::complex<double> >` for example, which would describe a complex-valued field on the domain. But for that to work, the interface would have to be
```
  virtual Number value (const Point<dim>   &p,
                        const unsigned int  component = 0) const;
  virtual void vector_value (const Point<dim>   &p,
                             Vector<Number>     &values) const;
```
and not as currently
```
  virtual Number value (const Point<dim, Number>   &p,
                        const unsigned int  component = 0) const;
  virtual void vector_value (const Point<dim, Number>   &p,
                             Vector<Number>     &values) const;
```

**Comment by tjhei** [comment]
I agree that the main usage of ```Point<dim>``` is a position in space for FE computations, so restricting to double sounds reasonable.

> whether these places of "Point of Array" could be replaced by "Array of Points" somehow

Martin probably has a good reason to pack the data that way for performance reasons.

**Comment by kronbichler** [comment]
Regarding Point<dim,VectorizedArray<double> >: This order is intentional and cannot easily be changed.  If it is packed the other way around, the explicit vectorization is destroyed. Due to the construction of VectorizedArray, VectorizedArray<Point<dim> > contains just one single entry. Performance-wise, it also means that you need to convert from one type to the other when you intend to work on 'several' cells, which people usually call cross-lane permutations.

The use of Point<dim,VectorizedArray<double> > is legitimate in one sense because where it is used it really does store the location of points, quadrature points in that case. On the other hand, I see the confusion the template might provide, in particular with respect to what you describe for the function interface.

I would not be opposed to replace the Point<dim,VectorizedArray<double> > by Tensor<1,dim,VectorizedArray<double> >, though. That keeps the data structures 'in-lane' with respect to performance. It does not help in making the use case of vectorized data in MatrixFree clearer, but not much worse either because Point<dim,VectorizedArray<double> > is awkward anyway and one must go through sequentially the data. One might even want to get a new access method in FEEvaluation to pick out one component of the data that then is a point. That last thing could wait till a later patch, whereas the change to Tensor could happen straight away.

**Comment by bangerth** [comment]
OK, thanks for the explanation. Would you be willing to make the conversion to `Tensor`, or would you prefer I do it?

**Comment by kronbichler** [comment]
Yes, I will add a patch this afternoon. I can actually also remove the template argument of Point as well (and fix the case in Function<dim,Number>), or are we expecting user errors when changing the signature of the virtual functions?

**Comment by bangerth** [comment]
I already have a patch for `Function` that I tested overnight, to be submitted in a few minutes. If you want to do the rest for `Point`, that would be fantastic!

**Comment by luca-heltai** [comment]
I know I'm late for the party, but removing the Number template argument from `Point<dim, Number>` broke half of my codes which use heavily Sacado... 

I'll work around it, but I'd like to raise this issue here. Having also a template parameter in `Point<dim>` allowed pretty nice tricks...

**Comment by kronbichler** [comment]
I see your point regarding Sacado and automatic differentiation of Function objects because those do specifically take points as arguments. Apart from the Function interface, is there anything else where Point is mandatory and not the more flexible Tensor variant that still supports the templated number types? Just to make the picture more complete.

Basically, the problem with this issue is that we would need to treat std::complex<double> (as the range space of the function) and things like variables for automatic differentiation differently.

**Comment by luca-heltai** [comment]
I'm not suggesting to put the argument back, since I also agree with @bangerth that having the parameter as before meant not being able to create complex valued functions, unless we introduce **two** parameters for functions, i.e., 

~~~C++
template<int dim, type FunctionNumber=double, type PointNumber=double> 
class Function;
...
virtual FunctionNumber value (const Point<dim, PointNumber>   &p,
                                                 const unsigned int  component = 0) const;
~~~

This seems overly complex to me...

**Comment by luca-heltai** [comment]
The other possibility would be to set directly `Point` as a templated type. This would also partially answer @tjhei requirements of having more complicated schemes for functions of points/parameters... 

Something like
~~~C++
template<type Point, type Number> 
class Function;
...
virtual Number value (const Point &p,
                              const unsigned int  component = 0) const;
~~~

With this, one could have `Point` to be any of`Point<dim>`, `std::vector<double>`, `Tensor<1,dim,SacadoDouble>`, etc.

**Comment by bangerth** [comment]
I think you have a good point there (no pun intended). I had not considered the issue of Sacado types.

My preference would be to separate the underlying type for the domain and the range. Having both be the same type clearly makes no sense, and I think we agree on that. So if we want to support what you suggest, then
```
template <int dim, typename RangeScalar=double, typename DomainScalar=double>
class Function {...};
```
clearly seems like the right way to go.

**Comment by bangerth** [comment]
Rather than undoing the previous patch(es), I think it would be useful to first find out which of our function classes (other than the base class) really need this second argument. I assume `ZeroFunction`, `ConstantFunction`, etc, are probably quite happy with a regular `Point<dim>`.

**Comment by tamiko** [comment]
I think there is not much to discuss here any more. Closing.
