### ISSUE TITLE
SphericalManifold give different results than HyperBallBoundary. Same with CylindricalManifold

### ISSUE THREAD

**Issue by davydden** [dealii/dealii#5298]
I noticed that `HyperBallBoundary` and alike are deprecated now. So I switched to manifolds. However, the two give different results. Below is a simple matrix-vector product with (matrix-free) mass and Laplace operators. Those differences can not be attributed to round-off errors:

```
$ ./manifold
====== 2D without manifold =======
Mass operator:
l2_norm:       6.00853
l1_norm:       78.6242
linfty_norm:   1.33757
Laplace operator:
l2_norm:       83.7086
l1_norm:       1278.3
linfty_norm:   10.7009
====== 2D with manifold =======
Mass operator:
l2_norm:       6.00925
l1_norm:       78.6258
linfty_norm:   1.33838
Laplace operator:
l2_norm:       83.7183
l1_norm:       1278.15
linfty_norm:   10.7068
====== 3D without manifold =======
Mass operator:
l2_norm:       16.0041
l1_norm:       532.201
linfty_norm:   1.97697
Laplace operator:
l2_norm:       144.315
l1_norm:       6640.93
linfty_norm:   8.97991
====== 3D with manifold =======
Mass operator:
l2_norm:       16.0124
l1_norm:       532.209
linfty_norm:   1.97971
Laplace operator:
l2_norm:       144.385
l1_norm:       6642.93
linfty_norm:   9.00505

```

obtained from [manifold.cc.zip](https://github.com/dealii/dealii/files/1404300/manifold.cc.zip)

the core switch is:

```
  Point<dim> center;
  const double R = 5.;
  GridGenerator::hyper_ball (triangulation,
                             center,
                             R);

  static const HyperBallBoundary<dim> boundary_ball(center, R);

  const types::manifold_id sphere_id = 0;
  static const SphericalManifold<dim> manifold_ball(center);

  if (manifold)
    {
      triangulation.set_all_manifold_ids_on_boundary(sphere_id);
      triangulation.set_manifold (sphere_id, manifold_ball);
    }
  else
    {
      triangulation.set_boundary (0, boundary_ball);
    }

  triangulation.refine_global(2);
```

So the main question is: which result is correct? If both are, then there must be a bug in one of them.

**Comment by drwells** [comment]
I believe that the `Boundary` result is correct. If you switch to `PolarManifold` then the results agree in 2D up to the last bit (I hit `pcout` with `std::setprecision(16)` too)

```
====== 2D without manifold =======
Mass operator:
l2_norm:       6.008528815971319
l1_norm:       78.62423284718567
linfty_norm:   1.337572458417233
Laplace operator:
l2_norm:       83.70864274540949
l1_norm:       1278.299490965862
linfty_norm:   10.70094905248165
====== 2D with manifold =======
Mass operator:
l2_norm:       6.008528815971318
l1_norm:       78.62423284718565
linfty_norm:   1.337572458417229
Laplace operator:
l2_norm:       83.70864274540949
l1_norm:       1278.299490965863
linfty_norm:   10.70094905248164
====== 3D without manifold =======
Mass operator:
l2_norm:       16.00414412661237
l1_norm:       532.2010470191047
linfty_norm:   1.97696747701304
Laplace operator:
l2_norm:       144.3151778519309
l1_norm:       6640.933928392355
linfty_norm:   8.979905865239106
====== 3D with manifold =======
Mass operator:
l2_norm:       13.80925996284911
l1_norm:       417.5376200264976
linfty_norm:   3.393183203933932
Laplace operator:
l2_norm:       8442.750560726356
l1_norm:       67184.94264153304
linfty_norm:   3943.242511238712
```

of course, if we do this then the 3D results are nonsensical for `PolarManifold` (even the plot of the triangulation is wrong): ignore that part. This implies that `SphericalManifold` is squirrelly.

**Comment by drwells** [comment]
Here is a terse example:

```cppa
#include <deal.II/grid/manifold_lib.h>
#include <iostream>

int main()
{
  using namespace dealii;

  PolarManifold<2> polar_manifold;
  SphericalManifold<2> spherical_manifold;

  {
    const Point<2> p0(-3.5355339059327373, -3.5355339059327373);
    const Point<2> p1(0.0, -5.0);
    const std::array<Point<2>, 2> points {{p0, p1}};

    const double w0 = 0.72360679774997894;
    const double w1 = 0.27639320225002106;
    const std::array<double, 2> weights {{w0, w1}};

    std::cout << "polar_manifold.get_new_point:"
              << polar_manifold.get_new_point(make_array_view(points.begin(), points.end()),
                                              make_array_view(weights.begin(), weights.end()))
              << '\n';

    std::cout << "spherical_manifold.get_new_point:"
              << spherical_manifold.get_new_point(make_array_view(points.begin(), points.end()),
                                                  make_array_view(weights.begin(), weights.end()))
              << '\n';
  }
}
```
output:
```
polar_manifold.get_new_point:-2.69108 -4.21403
spherical_manifold.get_new_point:-2.7228 -4.19361
```

These should match, no?

**Comment by davydden** [comment]
> These should match

i would say so.

**Comment by davydden** [comment]
Actually, there are problems with `CylindricalManifold` as well (updated test
[manifold.cc.zip](https://github.com/dealii/dealii/files/1404969/manifold.cc.zip)):


```
== 3D cylinder without manifold ===
Number of active cells:       640
Number of degrees of freedom: 5729
Mass operator:
l2_norm:       31.76
l1_norm:       1580.65
linfty_norm:   2.55864
Laplace operator:
l2_norm:       330.735
l1_norm:       19160.8
linfty_norm:   16.7309
== 3D cylinder with manifold ===
Number of active cells:       640
Number of degrees of freedom: 5729
Mass operator:
l2_norm:       31.7571
l1_norm:       1580.67
linfty_norm:   2.5578
Laplace operator:
l2_norm:       330.584
l1_norm:       19155
linfty_norm:   16.7309
```

**Comment by kronbichler** [comment]
> These should match, no?

No, they will not. `SphericalManifold` uses geodesics and will not be "transitive": If you create an intermediate point with weights {0.5, 0.5} and then another one with weights {0.5, 0.5} on one of the original points and the middle point, then that's a different point than using weights {0.75, 0.25}. That's why I've complained about `CylindricalManifold` in #4451 and the reason I don't like `SphericalManifold`, at least not in 2D.

> Actually, there are problems with `CylindricalManifold` as well.

Here I'd say that `CylinderBoundary` is the bad guy, since @masterleinad fixed `CylindricalManifold` in #4483 and I can confirm that it works well.

**Comment by davydden** [comment]
> I can confirm that it works well.

good to hear! But you agree that there is something wrong with `SphericalManifold`?

**Comment by kronbichler** [comment]
The problem in `SphericalManifold` is due to the mathematical formulation, not due to the way that particular formula is implemented. I'd really like to have something like `PolarManifold` for the ball that is transitive in the sense as described in my previous post - of course, you'd need to do that for an atlas of 6 charts and not a single bidirectional map. I'm sure that there is literature about how to best represent coordinate transforms of a sphere, but I'm certainly not the right person to ask.

**Comment by drwells** [comment]
I have to admit that I did not really understand the algorithm employed by `SphericalManifold`. The reason I expected them to agree was that we say

```cpp
/*
 * [...]
 * weighted average of the starting radii. This Manifold is identical
 * to PolarManifold in dimension two, while for dimension three it
 * returns points that are more uniformly distributed on the sphere,
 * and it is invariant with respect to rotations of the coordinate
 * system, therefore avoiding the problems that PolarManifold has at
 * the poles. Notice, in particular, that computing tangent vectors at
 * [...]
 */
 ```

so we should, at least, update this.

**Comment by kronbichler** [comment]
Yes, we should update this if we can't come up with something else. But I'm still curious if the two formulations can be made equivalent in 2D: `SphericalManifold` claims to connect two points by a geodesic, i.e.,
```
s(t)=x_1 cos(α(t))+κ×x_1 sin(α(t))+κ(κ⋅x_1)(1−cos(α(t)))
κ=x_1×x_2 ∥x_1×x_2∥ and α(t)=t⋅arccos(x_1⋅x_2)
```
However, I don't see this formula implemented in `SphericalManifold::get_new_point()` but only in `SphericalManifold::get_intermediate_point`. The `get_new_point` takes the intermediate steps in a non-curved description which is clearly not correct.

@drwells can you test what happens with your test program https://github.com/dealii/dealii/issues/5298#issuecomment-338434430 when you use `get_intermediate_point` with the respective weights instead of `get_new_point`? I guess we should have the correct answer. If that's the case, what I suspect, we *only* need to figure out how to generalize this correct formula to more than 2 points.

**Comment by drwells** [comment]
@kronbichler We don't implement `PolarManifold::get_intermediate_point` (I suppose that this really means that we don't implement `ChartManifold::get_intermediate_point`) so we cannot compare these :)

**Comment by drwells** [comment]
I am surprised that we don't have that function... I suppose that this is another thing to fix.

**Comment by kronbichler** [comment]
I meant to only call `spherical_manifold.get_intermediate_point(p0, p1, w0);` which should be equivalent to `polar_manifold.get_new_point(points, weights)`

**Comment by kronbichler** [comment]
I checked with `get_intermediate_point` and results are as I suspected:
```
polar_manifold.get_new_point:-2.691082153338 -4.2140333226
spherical_manifold.get_new_point:-2.722801469799 -4.193608488648
spherical_manifold.get_intermediate_point:-2.691082153338 -4.2140333226
```
Thus, the interesting question is how to generalize the formula of `get_intermediate_point` (geodesics) to the general `get_new_point` setting. @luca-heltai I remember we once discussed the issue of doing some concatenated operations: Did we come to a conclusion? Can we construct the middle point of the two points with the largest weight, get an intermediate point, and then use that point with the next one? The current implementation goes back to d1e3ffc as far as I can see.

**Comment by kronbichler** [comment]
I spent some thought about the unsatisfactory behavior of `SphericalManifold` and how we could go forward. The following figure shows the problem
![ball_spherical_manifold](https://user-images.githubusercontent.com/8276200/32105957-9e6c5bf2-bb2a-11e7-84de-8c16781b4607.png)

The picture displays a ball that is meshed with 7 elements and a fourth-degree `MappingQGeneric`. Then I output the mesh with `DataOut::build_patches(mapping, 10)`, i.e., 10 subrefinements get plotted in the figure. We clearly see that the points are more densely distributed towards the "patch points" of the outer 6 cells, which is due to the formula used in `SphericalManifold` that computes new points in `get_new_point` as averages on a projection of the given points onto a planar coordinate system, ignoring the curvature of the sphere or circle in 2D that does not get distances right. It is different to the `get_intermediate_point` that uses geodesics. 

So how should we solve this? The correct approach would be to generalize the concept of the geodesics to more than two points. As I said in a previous post: I'm not an expert on spherical coordinate systems or cartography, but so much I know that there cannot be a single global chart of the 3D sphere that satisfies the demands of equi-distribution of points (even after taking into account periodicity). Instead, the correct approach would be to compute the averages in two steps: First we convert the given points to spherical coordinates. Instead of assuming a straight coordinate system in the spherical coordinates as is done in `PolarManifold` (that degenerates in the north and south poles), we assume a curved system (now in 2D) that connects the points via geodesics. As long as all given points contain less than half of the sphere (i.e., not north and south pole at the same time), we should be able find a unique answer to the new points in those systems that generalizes geodesics.

I hope someone can follow these ideas, and I'm sure than an expert on the geometry would be able to cast this in much more precise words, but I definitely think we should make it a priority to fix `SphericalManifold` in this regard.

**Comment by kronbichler** [comment]
I'm working on a fix right now...

**Comment by masterleinad** [comment]
I just had a look too. In particular, I have an implementation following http://www.cs.utah.edu/~lavanyat/pdfs/spherica_interp.pdf

**Comment by masterleinad** [comment]
I will create a branch soon, so we can have a look which approach is better.

**Comment by kronbichler** [comment]
Very good @masterleinad I'm happy to look into your code once you have uploaded it.

**Comment by masterleinad** [comment]
An initial version is in #5368.

**Comment by kronbichler** [comment]
Just for reference, the same setting as in the picture above (7 cells of ball, 10 sub-refinements in `DataOut::build_patches`) but now with the proposed method from #5368:
![ball_spherical_manifold_new](https://user-images.githubusercontent.com/8276200/32293629-0ade8b80-bf44-11e7-8f39-f2935de0b776.png)

Now everything is nice and equidistant.

**Comment by kronbichler** [comment]
@davydden Can you check if the behavior is correct now? #5368 should have fixed this.

**Comment by davydden** [comment]
@kronbichler it got better, we don't have any noticeable difference in 2D but in 2D spherical manifold is different:

```
$ ./manifold
== 2D sphere without manifold ===
Number of active cells:       80
Number of degrees of freedom: 337
Mass operator:
l2_norm:       6.00853
l1_norm:       78.6242
linfty_norm:   1.33757
Laplace operator:
l2_norm:       83.7086
l1_norm:       1278.3
linfty_norm:   10.7009
== 2D sphere with manifold ===
Number of active cells:       80
Number of degrees of freedom: 337
Mass operator:
l2_norm:       6.00853
l1_norm:       78.6242
linfty_norm:   1.33757
Laplace operator:
l2_norm:       83.7086
l1_norm:       1278.3
linfty_norm:   10.7009
== 3D sphere without manifold ===
Number of active cells:       448
Number of degrees of freedom: 3817
Mass operator:
l2_norm:       16.0041
l1_norm:       532.201
linfty_norm:   1.97697
Laplace operator:
l2_norm:       144.315
l1_norm:       6640.93
linfty_norm:   8.97991
== 3D sphere with manifold ===
Number of active cells:       448
Number of degrees of freedom: 3817
Mass operator:
l2_norm:       16.0034
l1_norm:       532.209
linfty_norm:   1.97452
Laplace operator:
l2_norm:       144.327
l1_norm:       6641.21
linfty_norm:   8.98513
```

Frankly, i do't have any idea on how to measure the quality of either and, for example, for certain say that yes, the new implementation is in some sense better so that we have this _incompatible_ change (deprecation) in the library and users are expected to get slightly different results.

**Comment by kronbichler** [comment]
I agree, one cannot really do that based on the result of a matrix-vector product. Since we have not used the *best approximation* on points of the 3D sphere before, I'm pretty sure the new implementation is better. In all changes in tests that I looked into yesterday the new manifold was producing better results, sometimes significantly better results (e.g. the computation of `4/3 pi` as the ball's volume in 3D through a polynomial approximation). So I'd completely agree with this statement:

> yes, the new implementation is in some sense better so that we have this *incompatible* change (deprecation) in the library and users are expected to get slightly different results.

**Comment by davydden** [comment]
@kronbichler :

>  the computation of 4/3 pi as the ball's volume

good point. That's indeed one of the tests which confirms that the new guy should be better.

github's `blame` tells me that @drwells deprecated boundary classes in https://github.com/dealii/dealii/pull/5222. I am thinking where should be leave a note about these incompatibilities? One one hand, _deprecation_ is already an invitation to switch to other means and so we should make suers aware that there are differences. On another, it does probably fit into _incompatibilities_ section as we do not remove those classes yet. 

Would you be willing to extend those `@deprecated` doxygen notes for `HyperBallBoundary` and `Cylinder` by saying that manifold classes are expected to behave differently ... but better. And then I say we close this issue?

**Comment by davydden** [comment]
p.s. after `9.0` is out and we actually remove those classes, we can copy-paste these notes into the /incompatabilities/changelog.
