### ISSUE TITLE
failing tests matrix-free

### ISSUE THREAD

**Issue by davydden** [dealii/dealii#5354]
`matrix_free/fe_evaluation_dofs_per_cell`

see https://cdash.kyomu.43-1.org/viewTest.php?onlydelta&buildid=12687

related to https://github.com/dealii/dealii/pull/5348

@kronbichler can you please have a look?

**Comment by davydden** [comment]
@tjhei maybe add `matrix_free/` to `tjhei-alpha` and `tjhei-gcc-serial`? There are not that many tests, should not take too much time.

**Comment by tjhei** [comment]
> and specify exactly what
> runs a subset of the testsuite
> is?

it currently is set to:
```
TESTREGEX=\'all-headers|multigrid/transfer\'
```
but I didn't want to document this because it is a moving target (and is basically just "all-headers").

> maybe add matrix_free/ to tjhei-alpha

I could, but it is 100+ tests and many of them parallel, so this increases the turn-around quite a bit. Ideally we would test everything, but for that I would need a spare machine... ;-(

> Looks like gcc-serial is a subset as well as opposed to

No. This is all serial tests and if you search for "matrix_free/" in http://www.math.clemson.edu/~heister/cib/dealii-tjhei-gcc-serial/a5ff2f8ce79210a3cdd6362943f858272a304236/log-gcc for example, you see that those tests are indeed run.

**Comment by davydden** [comment]
Thanks for explaining, @tjhei 

> I didn't want to document this because it is a moving target (and is basically just "all-headers").

fair enough

> you see that those tests are indeed run.

ah, i see
