### ISSUE TITLE
Make TriaAccessor::vertex_index faster

### ISSUE THREAD

**Issue by kronbichler** [dealii/dealii#5437]
In lots of my profiles I see `TriaAccessor<structdim, dim, spacedim>::vertex_index` to take an appreciable amount of time. (E.g. in the optimizations done in #5410.) It is used in a lot of functions, in particular all calls to `TriaAccessor::vertex`. The problem is that the implementation is somewhat nested. To get the vertex index of a cell, we ask all the faces for their vertex index (which in 3D then further goes to the lines). I'd wish to have a single index lookup at least for the cell case (`structdim==dim`). This small increase in storage would be definitely worth it in my opinion. I'm not sure where exactly we'd want to apply it. We have a few complications because this is effectively a number cache that needs to be filled and kept up to date. Not sure if this could be attached to the number cache already present... Any opinions?

**Comment by bangerth** [comment]
Ah, glad you asked before you implemented! :-)

The right way to do this is the same we do for the cell dof indices. Take a look at the `DoFLevel::cell_dof_indices_cache` member variable. It is accessed by `DoFCellAccessor::get_dof_indices()` function:
```
template <typename DoFHandlerType, bool level_dof_access>
inline
void
DoFCellAccessor<DoFHandlerType,level_dof_access>::get_dof_indices
(std::vector<types::global_dof_index> &dof_indices) const
{
  Assert (this->active(), ExcMessage ("get_dof_indices() only works on active cells."));
  Assert (this->is_artificial() == false,
          ExcMessage ("Can't ask for DoF indices on artificial cells."));
  AssertDimension (dof_indices.size(), this->get_fe().dofs_per_cell);

  const types::global_dof_index *cache
    = this->dof_handler->levels[this->present_level]
      ->get_cell_cache_start (this->present_index, this->get_fe().dofs_per_cell);
  for (unsigned int i=0; i<this->get_fe().dofs_per_cell; ++i, ++cache)
    dof_indices[i] = *cache;
}
```

After enumerating DoFs, we call `DoFCellAccessor::update_cell_dof_indices_cache()` which has an internal implementation in `dof_accessor.templates.h`, around line 2657 and following, where we go over all of the sub-objects and get DoF indices that we then store in the cache. 

In your case, I'd add a similar array to class `TriaLevel`. You won't need the `get_cell_cache_start()` function (which exists in the DoF case because the logic is more complicated for the hp case, but here you'd just index on the cell index times `GeometryInfo<dim>::vertices_per_cell`) and then you need to move what's currently in the `TriaAccessor::vertex_index()` function into a `update_vertex_index_cache()` function and in the now empty `vertex_index()` function you'd just index into the cache.

**Comment by kronbichler** [comment]
That sounds reasonable. I don't have time now to fix it but I set it on my list.

**Comment by kronbichler** [comment]
Given the increased flexibility of the triangulation with calls to `ReferenceCell::internal::info::get_cell()`, we should indeed implement a cache at least for `cell->vertex_index` for the 9.3 release.

**Comment by peterrum** [comment]
This shouldn't be to difficult.

**Comment by peterrum** [comment]
I will try to do this during the workshop.
