### ISSUE TITLE
unexpected DoF numbering at hanging node in 3D (probably not an issue)

### ISSUE THREAD

**Issue by davydden** [dealii/dealii#5450]
below is a small cut-off from a reasonably big mesh of `4096` elements with quadratic `FE_Q`. 

![screen shot 2017-11-13 at 12 00 42](https://user-images.githubusercontent.com/8023934/32722622-c1fbcbc8-c86a-11e7-9548-cb501d8627c6.png)

What I was surprised about is that the marked with the ball node has two DoFs attached, `38304` and `32`, obviously with constraint `u(38304)=u(32)`. And the `38304` DoF does not belong to either of the faces visible in the image. So it must be one of those which are hidden. 

I was expecting that `distribute_dofs()` ends up with a single DoF at this support point, but that's clearly not the case.

**Comment by tjhei** [comment]
This is how we do hanging nodes. Here is an even simpler 2d example with a Q2 element:
![q2hangingnode](https://user-images.githubusercontent.com/1531285/32728763-906f4136-c84f-11e7-8481-dd19ec44aff5.png)

The reason is that on the coarser cell the DoF is a face DoF, while it is a vertex DoF for the finer cells. Identifying this during the DoF distribution is difficult, so we just create constraints for it.

**Comment by davydden** [comment]
> This is how we do hanging nodes

you are right, I mistakenly though that DoF `32` in my case belongs to one of the invisible on the picture refined faces. But actually it should indeed belong to the coarse cell behind.
And then the numbering is exactly the same as the one in 2D case, of which I am aware of.

**Comment by bangerth** [comment]
For reference, in the hp DoFHandler we would actually unify DoFs 4 and 18. But it's a bit of work to find these opportunities.
