### ISSUE TITLE
Inline some hot functions of GeometryInfo

### ISSUE THREAD

**Issue by kronbichler** [dealii/dealii#5469]
In several PRs regarding manifolds, in particular #5410 and #5374, we found that some of the functions in `GeometryInfo` take a long time. Here is a list of items to address:
- [ ] the lookup of `face_to_cell_vertices` for the standard orientation
- [ ] `face_to_cell_lines` for the standard orientation case
- [x] evaluation of d-linear shape functions could profit from some common infrastructure, for example by providing new functions that evaluate all shape functions in a point

In case someone wants to address further issues, feel free to add them to this list.

**Comment by bangerth** [comment]
`face_to_cell_vertices` calls `child_cell_on_face`, which is long in the 3d case but seems to be an excellent candidate for constant propagation in compilers because it is almost entirely table lookup based. I'll have a patch tomorrow or so.

I'm almost tempted to just inline essentially everything from the .cc file into the .h file -- it's another 1000 lines or so, but that surely pales to the overall amount of inlines that we have, and these are heavily used. I'll have to think about what to do with the static arrays, but I think C++11 now allows me to put their values right into the class declaration. Will have to play with this.

**Comment by bangerth** [comment]
Hm, this isn't so easy after all. We have all of these static members like
```
template <int dim>
struct GeometryInfo
{
  static const unsigned int faces_per_cell = 2 * dim;
  static const int unit_normal_orientation[faces_per_cell];
```
We provide explicit instantiations for the definitions of these:
```
template <>
const int
GeometryInfo<1>::unit_normal_orientation[faces_per_cell]
  = { -1, 1 };

template <>
const int
GeometryInfo<2>::unit_normal_orientation[faces_per_cell]
  = { -1, 1, -1, 1 };

template <>
const int
GeometryInfo<3>::unit_normal_orientation[faces_per_cell]
  = { -1, 1, -1, 1, -1, 1 };

template <>
const int
GeometryInfo<4>::unit_normal_orientation[faces_per_cell]
  = { -1, 1, -1, 1, -1, 1, -1, 1 };
```
I can't seem to find a C++11 conforming way to move these initializers into the class declaration in a way that seems to make sense and allows the constructor to look through them to do constant propagation. And because variable definitions can't be inline, I also can't see how these arrays can be moved to the .h file out-of-class without causing linker errors. That leaves us with the possibility of moving the *functions* into the .h file as inlines, but they reference the arrays that we can't move, and that's surely going to defeat the purpose.

Ideas?

**Comment by masterleinad** [comment]
I would think that we can use `constexpr` functions to initialize the `constexpr` (or `static const`) arrays. Let me try if this works.

**Comment by bangerth** [comment]
The problem is that I couldn't figure out a way to do the initialization in a `dim`-dependent way. Or can you do a `constexpr` variable out-of-line in the .h file without violating the ODR rule?

**Comment by masterleinad** [comment]
Yes, if you immediately initialize with a `constexpr` function this should work. To get this dimension-independent we have to declare a templated struct for each of the variables that contains such a function. Give me some minutes to build a PR.

**Comment by drwells** [comment]
I believe that C++17 supports inline variables; we could move things conditionally into the header.

**Comment by tjhei** [comment]
Not backwards compatible but one could replace the public arrays by inline constexpr functions (after checking that the generated code is as efficient).

**Comment by kronbichler** [comment]
I have had a look at the profiles and the situation seems to have improved quite a bit indeed. Now the compiler still decides to not inline some of the functions due to the large number of `if/else` cases in some of the calls, and then fails to propagate the simple lookup through the function say for the constant orientation case. But overall I consider that #5748 a success. I will keep the issue open a bit more until I have checked how much propagation the compiler does in the standard orientation case (first two items in the list of the original post), but I guess this is fine and subject to the compiler to do well.

**Comment by kronbichler** [comment]
Since I did not see problematic parts in my profiles again, I'm closing this issue. If we later see problems again we can always look for more specific solutions.
