### ISSUE TITLE
simplify usage of p::d::Tria::register_data_attach() and notify_ready_to_unpack() ?

### ISSUE THREAD

**Issue by davydden** [dealii/dealii#5567]
I was wondering if we can simplify usage of those functions by providing some base class `parallel::distributed::CellDataTransfer` with already implemented `prepare_for_coarsening_and_refinement()` and `transfer()`. The idea is to have a general class to simplify transfer of some cell data upon refinement. 

In https://github.com/dealii/dealii/pull/5500 @luca-heltai factored our `pack/unpack` for an arbitrary serializable class into a `std::vector<char>`. So I think everything a user should do: 

1. have an arbitrary per cell data in a class which is boost-serializable
2. on receive, figure out what to do on refinement/coarsening.

The rest can be done by `dealii`. [ContinuousQuadratureDataTransfer](https://www.dealii.org/developer/doxygen/deal.II/classparallel_1_1distributed_1_1ContinuousQuadratureDataTransfer.html) can be derived from this new class as the former is tailored to quadrature data, whereas the later is a general one for some cell data, not necessarily quadrature related.

The complication is that we need to figure out the maximum size of data we may eventually send and provided it to `register_data_attach()`, see as an example https://github.com/dealii/dealii/blob/master/include/deal.II/base/quadrature_point_data.h#L704-L741

One may of course call `pack` for each cell just to figure out the maximum size, but it would be good to avoid this as we may need to exchange info for a handful of cells only and calling `pack` for each cell only for the sake of getting the size is not ideal.

Without looking into `register_data_attach` and `notify_ready_to_unpack`, maybe @tjhei can comment on the issue above.

**Comment by tjhei** [comment]
There is now functionality in p4est to transfer variable amount of data: https://github.com/cburstedde/p4est/issues/15

I think this would be a better approach than packing everything and finding the maximum size.

Finally, while I don't think it makes things a lot easier, I wouldn't mind a thin wrapper in form of a class that provides the same functionality that ``register.../notify...`` does.

**Comment by davydden** [comment]
> There is now functionality in p4est to transfer variable amount of data: cburstedde/p4est#15

nice, thanks for the link. So this is in p4est 2.0, i suppose and we don't use it yet in dealii?

> I think this would be a better approach than packing everything and finding the maximum size.

absolutely.

> Finally, while I don't think it makes things a lot easier, I wouldn't mind a thin wrapper in form of a class that provides the same functionality that register.../notify... does.

you mean for the one mentioned in p4est issue? I agree. But since I know nothing about p4est, I would prefer to leave this to someone else to implement. Once we have wrappers to use this functionality, implementation of the class discussed in OP is straight forward.

**Comment by davydden** [comment]
@gassmoeller was about try the new functionality out 😸

**Comment by tjhei** [comment]
> i suppose and we don't use it yet in dealii?

correct. 

> you mean for the one mentioned in p4est issue?

No, I mean wrapping the current deal.II functions ``register_data_.../notify_...`` in a helper class like you propose in the first paragraph of this issue.

Oh, by the way: if anybody wants to look at all this stuff there is also serialization (Triangulation::read/write) to consider.

**Comment by bangerth** [comment]
@marcfehling and I are thinking about how to do this as well.

Here's what I've been thinking about. Currently, we require classes that want to send data to (i) register a function via
```
      unsigned int
      register_data_attach (const std::size_t size,
                            const std::function<void (const cell_iterator &,
                                                      const CellStatus,
                                                      void *)> &pack_callback);
```
where you have to say how many bytes you want to attach and you get back an offset that you need to store, and then (ii) the function object you provided as second argument will be called on each cell. There is a corresponding mechanism for unpacking data.

It would be much nicer if all you'd have to do is attach a function object of the form
```
  std::vector<char> pack_cell_data (const cell_iterator &,
                                                         const CellStatus);
```
to a signal that just lets user classes pack up everything on a cell, and then let the internals deal with the details such as variable data sizes returned on different cells..

Would such a plan find all y'all's favor? We'd be working on this then.

**Comment by davydden** [comment]
> Would such a plan find all y'all's favor?

sounds good to me. 

Should the return be `boost::optional`, in case this specific cell has nothing to send?

**Comment by bangerth** [comment]
That seems unnecessarily complicated -- an empty `std::vector<char>` has the same semantic content.

**Comment by davydden** [comment]
ah, right, of course.

**Comment by marcfehling** [comment]
@bangerth and I recently discussed about attaching the pack functions to signals and are kind of skeptical about how this would work out, since 'gluing' together the packed vectors via combiners is potentially slow, and the 'unpacking' process is only triggered by calling a corresponding function, not directly after refinement.

I came up with another idea and want to know what you think about it before I give it a try.
- We register <code>SolutionTransfer*</code> objects in the <code>Triangulation</code> object (e.g. in a vector).
- With each call of <code>attach_mesh_data</code>, we introduce a map <code>map<cell_iterator, vector< char>></code> that will contain each cell's transfer buffer.
- During <code>attach_mesh_data_recursively</code>, a function <code>pack_callback</code> of each registered <code>SolutionTransfer</code> object will be called, that returns the packed data (like @bangerth introduced). We append it to the transfer buffer and store its size. After all data is packed, we create an offset vector (<code>unsigned int</code>), pack it and attach it (in front of) the transfer buffer. Now, we can transfer the data to p4est.
- We transfer the data back from p4est with <code>post_mesh_data_recursively</code>. Since we know how many <code>SolutionTransfer</code> objects are registered, we can deduce the length of the offset vector and split the buffer accordingly. Then we can assign each <code>SolutionTransfer</code> object its fraction of the buffer and use it to call their specific <code>unpack_callback</code> function.

Now memory handling is completely detached from the <code>SolutionTransfer</code> class. One only needs to pay attention on the association of buffer fractions to <code>SolutionTransfer</code> objects. If we use the order with which the <code>SolutionTransfer</code> objects were registered, we are on the safe side.

Reading this now, this feels kind of complicated. What do you think about that approach?

**Comment by davydden** [comment]
> What do you think about that approach?

If I understand correctly, you would introduce another `SolutionTransfer`-like class to do manage transfer of per-cell serializable data? If so, that sounds good to me. 

@dealii/dealii thoughts?

**Comment by marcfehling** [comment]
I would introduce some pure abstract <code>SerializableInterface</code> class that would just provide virtual functions for <code>pack_cell_data</code> and <code>unpack_cell_data</code>. All objects that want to attach data would need to inherit from that.

**Comment by marcfehling** [comment]
I guess I'll stick to the current implementation using the callback functions, and replace the <code>memcpy</code> calls with <code>Utilities::pack/unpack</code>. The <code>Triangulation</code> object will forward the respective memory to the callback functions, on which they will write. No vtable required.

I think that's the way to go. I'll give that one a try! :)

**Comment by bangerth** [comment]
On 04/10/2018 03:16 PM, marcfehling wrote:
> I guess I'll stick to the current implementation using the callback functions, 
> and replace the |memcpy| calls with |Utilities::pack/unpack|. The 
> |Triangulation| object will forward the respective memory to the callback 
> functions, on which they will write. No vtable required.
> 
> I think that's the way to go. I'll give that one a try! :)

Yes, I agree!

**Comment by marcfehling** [comment]
Is this still an issue, or does the variable size transfer introduced in https://github.com/dealii/dealii/pull/6920 close this issue?

**Comment by davydden** [comment]
To be frank, the issue is more than 2 years old and all motivation faded away from me, but I believe it can indeed be closed.
