### ISSUE TITLE
Multiplying of DynamicSparsityPattern

### ISSUE THREAD

**Issue by ExtremOPS** [dealii/dealii#5598]
Hi all,

at one point in my thesis I had to know where entries in a sparse matrix are. This matrix was composed of a multiplication of three matrices. To get this information I wrote a function which multiplies two DynamicSparsityPattern with each other to construct the resulting DynamicSparsityPattern exactly.

As far as I know, does this functionality not exist for the Class DynamicSparsityPattern. Do you think that this is a useful function to have? (Or was this an unnecessary extra effort because the solution is much easier?)

**Comment by bangerth** [comment]
I don't think the function exists. It is generally expensive, both to compute the sparsity pattern and later to store the memory of products of sparse matrices, so it is generally not done. Instead, one computes the product $ABx$ as $A(Bx)$ (rather than computing $(AB)x$) as the former only requires two matrix-vector products.

But there are situations where one genuinely wants the product of the matrix. So I think your function is useful. Feel like contributing it? (Hint, hint! :-) )

**Comment by ExtremOPS** [comment]
I tried it first with SparsityPattern and then the reinit(...) followed by an compress() after assigning the values into the matrix but this did not work out for me. Therefore the detour over DynamicSparsityPattern and .copy_from (const SparsityPatternType &dsp)...

I would not open the issue and take your time if I am not willing to share :-)

**Comment by kronbichler** [comment]
I like this idea and it would be great to use it. I wrote something like this many years ago, it must have been 2009 or 2010, but it is hidden in a bad place inside the `SparseMatrix::mmult` function implementation:
https://github.com/dealii/dealii/blob/master/include/deal.II/lac/sparse_matrix.templates.h#L1017-L1041

So it would be great if you could share your code, maybe templated on the input since it would be both useful for a `DynamicSparsityPattern` object and a `SparsityPattern` object as input, and always `DynamicSparsityPattern` as output. This way, we could also replace the code above in `SparseMatrix`.

**Comment by ExtremOPS** [comment]
I was thinking of following code outline like

`template <typename SparsityPatternType>
void DynamicSparsityPattern::mult(DynamicSparsityPattern &dst, const SparsityPatternType &src) const`

In the block itself I would suggest following steps

1. Check first if columns and rows of input are matching; otherwise throw error message
2. Set the size of the `dst`
3. Do multiplying

@kronbichler, would this do what you suggested?

And to all others, how should I name the function so it fits properly into the deal.II wording?

**Comment by kronbichler** [comment]
@ExtremOPS Yes this looks like a plan. (The only thing I'm not 100% sure about now is whether our generic interfaces that are available to both `SparsityPattern` and `DynamicSparsityPattern`, i.e., the iterators, are efficient enough for doing that, but I'd say it's fine until someone complains.

As for the name: My favorite would be the `compute_mmult_pattern` to be verbose with the name and still reflect the `mmult` name of matrix-matrix multiplication used in the `FullMatrix` and `SparseMatrix` contexts. Any other suggestions?

**Comment by bangerth** [comment]
@ExtremOPS: Is this fixed by your two patches? If so, can we close this issue?

**Comment by kronbichler** [comment]
I would say yes, so I will close.

**Comment by ExtremOPS** [comment]
Sorry to all, that I did not respond to this... But the notifications ended somehow in the JunkMail folder...
