### ISSUE TITLE
VectorView is deprecated but ArrayView does not provide the same functionality

### ISSUE THREAD

**Issue by davydden** [dealii/dealii#5627]
[VectorView](https://www.dealii.org/developer/doxygen/deal.II/classVectorView.html) is currently deprecated, but [ArrayView](https://www.dealii.org/developer/doxygen/deal.II/classArrayView.html) does not provide the same functionality. It looks like you can't really do much with that view, for example you can't use it in matrix-vector products with `FullMatrix` or `LAPACKFullMatrix`, neither can you add it to a `Vector<double>`, or do some simple operations with it, like multiply by a scalar. 

I think we shall not deprecate classes unless a comparable set of functionality is provided elsewhere.

**Comment by drwells** [comment]
ArrayView is supposed to replace `VectorSlice`, not `VectorView`. I do not think that we have any replacement in the pipeline for `VectorView`.

**Comment by davydden** [comment]
that's not what documentation states:

> Deprecated:
> Use ArrayView instead.

**Comment by kronbichler** [comment]
I think that it would be interesting indeed to have interfaces for small ("serial") operations in the full matrix classes by means of `ArrayView`.

**Comment by tamiko** [comment]
> I think that it would be interesting indeed to have interfaces for
> small ("serial") operations in the full matrix classes by means of
> `ArrayView`.

That's a good point.

Another idea would be to ensure that everything is also compatible with
LinearOperator - did someone already test that?
PackagedOperation/LinearOperator might actually be more in line 
with the very idea behind ArrayView, namely not copying data.

**Comment by davydden** [comment]
@bangerth was in favour deprecating `VectorVew` in https://github.com/dealii/dealii/issues/5278 . The class was deprecated by @masterleinad in https://github.com/dealii/dealii/pull/5447 .

**Comment by davydden** [comment]
> Another idea would be to ensure that everything is also compatible with
LinearOperator 

my angle here is that when I work with Lapack matrices, it's convenient to treat columns as vectors and do some operations with them, i.e. add to some other real vector.

**Comment by drwells** [comment]
There are a few places in user codes where this sort of functionality is useful: see, e.g., 

https://github.com/kronbichler/adaflo/blob/master/source/navier_stokes_preconditioner.cc#L287
or
https://github.com/mathLab/WaveBEM/blob/master/source/free_surface.cc#L1160

The first case is a pretty good example of what we want to do: it would be nice to have a linear operator variant that can take vector views as arguments.

**Comment by bangerth** [comment]
I'm still in favor of getting rid of this class. Its design is just fundamentally broken.

I can imagine that it makes sense to add a few functions in `FullMatrix` that work on `ArrayView`. In general, however, I like the idea that our vector classes represent elements of vector spaces and matrices operators on that, and that the dimensionality of both is encoded in the corresponding objects. `ArrayView` does have a length argument, but it fundamentally is intended to represent a view into something that has a different length. So semantically, I don't see that as a particularly good match.

What kind of operation, specifically, are you going to miss if we got rid of `VectorView`?

**Comment by davydden** [comment]
> What kind of operation, specifically, are you going to miss if we got rid of VectorView?

take column of a LAPACKFullMatrix and use it as a vector in some additions with other vectors.
Also see links above to user codes which use `VectorVew`.

**Comment by bangerth** [comment]
I recognize that there are occasions where `VectorView` makes some operations briefer, but I detest the implementation of that class so much that I'd be willing to advise people to rather copy data into a regularly created `Vector` object. The way `VectorView` is implemented is practically asking for someone to make a change to the data structures of `Vector` that completely breaks `VectorView`. It is also incredibly easy to create completely bogus code with this class -- for example, this incorrectly frees memory and creates a memory leak:
```
{
  Vector<double> x;
  ... do something with x...
  VectorView<double> y (10, x.begin());
  y.reinit (12);     // deletes x's memory (even though x may still want to use it)
                          // also allocates new memory in x that will never be released
  x(42) = 3.141; // now writes into invalid memory
} // x goes out of scope; releases x's memory *a second time*
```

But if we are looking for a replacement of this functionality, then I think the right thing to do would be to incorporate the functionality into `Vector` itself -- i.e., create a constructor that takes a pointer to externally managed memory, that remembers that that memory is not ours, and that then prohibits any operation that may change the memory allocation (such as `reinit`).

**Comment by davydden** [comment]
> create a constructor that takes a pointer to externally managed memory, that remembers that that memory is not ours, and that then prohibits any operation that may change the memory allocation

that's good idea.

Would that functionality cover all we use `ArrayView` for?

**Comment by drwells** [comment]
For what its worth that particular `reinit` function is `virtual`; `VectorView` does not allocate or free anything. The other ones are most likely broken, though.

**Comment by drwells** [comment]
I am also in favor of getting rid of this class: @bangerth's enumeration of problems has convinced me. Copying is so cheap compared to all of the other operations we support that this is not a huge performance problem. Here are possible fixes for the two links I provided:

1. In the first case (adaflo) `VectorView` is just used to copy the local part of a Trilinos vector into the local part of a `parallel::distributed::Vector`. I think that we could solve that by making sure that, if parallel vectors have contiguous storage for local parts, then we offer an iterator interface and can use `std::copy` or something fancier.
2. In the WaveBEM solver it looks like the main solution vector is contiguous but has logical blocks. Since copying is much cheaper than doing something like the Kelly error estimator this won't alter the performance much.

I am not so happy about the second one because this deprecation will necessitate a lot of work on a code that uses `VectorView` in a reasonable way.

One complicated way to fix this would be to manage blocks of memory with some sort of sub-Vector object (call it `Buffer<T>`). This could inherit from subscriptor and use slots to signal views that the block of memory had changed. I don't think any of us would be willing to go to the work of essentially rewriting all memory allocation in the library to support this.

Another not-great alternative is that we recommend that third parties write their own `VectorView` classes in case they really, really need them, but we don't provide it in deal.II proper.

**Comment by bangerth** [comment]
@davydden : I think of `ArrayView' as an entirely separate class. It provides a view into an array (stored consecutively in memory, but otherwise arbitrary) but it does not carry the notion of a vector space with which you can do things like addition, subtractions, multiplication, etc. 

That's why I proposed to merge the functionality of `VectorView` into `Vector`, not `ArrayView`.

**Comment by drwells** [comment]
I don't support adding linear algebra functionality to `ArrayView` (it is just a container class) but it is worth noting that we already treat it as a vector in some places, e.g.,
https://github.com/dealii/dealii/blob/master/include/deal.II/lac/tensor_product_matrix.h#L90

**Comment by drwells** [comment]
`VectorView` is now gone and this issue has not, since that point, received any traffic. Hence there does not seem to be a lot of interest in solving this issue.

Since we have gone 2.5 years without comments on it I will close this - if someone is interested in resurrecting it then go ahead.
