### ISSUE TITLE
GMSH dependency is not documented in installation instructions

### ISSUE THREAD

**Issue by davydden** [dealii/dealii#5643]
subj.

related to https://github.com/dealii/dealii/pull/5583

**Comment by luca-heltai** [comment]
I have a function sitting on my pc that would generate a mesh using gmsh and an iges curve. This plus the one we added some time ago that generates an iges curve from the boundary makes a very nice inclusion to have. It is one single function. It may go in 9.0. I never really pushed hard, because I had the impression most of you guys were against having gmsh as an executable, and I was waiting to have the time to explore the api in gmsh.

**Comment by bangerth** [comment]
On 04/27/2018 12:00 PM, Luca Heltai wrote:
> I never really pushed hard, because I had the impression most of you 
> guys were against having gmsh as an executable, and I was waiting to 
> have the time to explore the api in gmsh.

I like the idea of communicating with Gmsh. I'm agnostic whether it's 
via the API or the executable -- whatever makes it work is fine by me!

**Comment by drwells** [comment]
This has been closed by #6544 and #6541: we clearly say what we need Gmsh to support and how to enable it.
