### ISSUE TITLE
FlatManifold as replacement of StraightBoundary doesn't treat normals the same way

### ISSUE THREAD

**Issue by masterleinad** [dealii/dealii#5681]
The computation of normals in `FlatManifold` and `StraightBoundary` differ in that the first one really assumes flat faces while the latter one also works with curved faces described by a Q1-Mapping.
Since we want to use `FlatManifold` as a replacement for `StraightBoundary`, we should deal with this imbalance in one way or the other. Some options:

1. Simply document the difference.
2. Always use (steal) the implementation of `normal_vector` and `get_normals_at_vertices` from `StraightBoundary`.
3. Have a flag in the constructor to decide if the class should be able to treat Q1-mapped curved faces.
4. ~~Implement a new `Manifold` class that treats curved faces correctly.~~

I am currently in favor of 2. if this doesn't turn out to be too expensive. What do you think?

Related to #4921.

**Comment by kronbichler** [comment]
Can you give an example? I must admit I do not really understand what should go wrong with the current implementation of `normal_vector`. As far as I can see, all manifold classes go to the base class method `Manifold::normal_vector` that is based on the ability of a manifold to compute tangent vectors. On a flat manifold that gets a face that is indeed curved due to the positions of the vertices, the computation of tangents should take that into account, or doesn't it? Or is the problem that a particular point we might pass to `normal_vector` is not really on the face in that case, and thus gives incorrect normals?

Note that I would also prefer solution 2 that you sketch. How would you implement it? Overload the normal vector function for `FlatManifold`, because the other manifolds cannot use that kind of Newton iteration.

**Comment by masterleinad** [comment]
I noticed that for example in `tests/grid/normal_vector_01.cc` which fails in the second case were a vertex is moved when `StraightBoundary` is replaced by `FlatManifold`.

**Comment by bangerth** [comment]
I think option 2 is the way to go.

Is my interpretation of the current state correct? IIRC, we take the point at which we want to compute the normal, find two of the vertices, look at the geodesic that connects the point with these vertices (which are of course straight lines), and then take the cross product of these two directions to get the normal vector? If this is correct, then there are going to multiple regions on a curved 2d face in 3d space, with discontinuities in the normal vector between these regions.

**Comment by masterleinad** [comment]
> Is my interpretation of the current state correct? IIRC, we take the point at which we want to compute the normal, find two of the vertices, look at the geodesic that connects the point with these vertices (which are of course straight lines), and then take the cross product of these two directions to get the normal vector?

Yes, exactly. In particular, the computations call `get_tangent_vector` which doesn't know about the face but just about the point where to compute the tangent and the direction. For `FlatManifold` this just assumes a flat face. Unfortunately, I don't see a way to fix this function without changing the interface for `FlatManifold`.
