### ISSUE TITLE
Make LAPACK required

### ISSUE THREAD

**Issue by masterleinad** [dealii/dealii#5901]
In #5879, @kronbichler suggests to make `LAPACK` a required dependence. 
Since there are at least @kronbichler and @davydden in favor, let's put the discussion here to not forget about it.

**Comment by drwells** [comment]
My primary concern with this is that requiring these will make supporting Windows (with MSVC) even harder. Is there an easy way to get these libraries on Windows?

This might also be hard on macOS. I guess that ultimately I am concerned that we are raising the bar to entry for complete novices who do not have access to a cluster or some os with a package manager (including Windows 10, I suppose, at this point).

**Comment by Rombur** [comment]
Please let's not do that. I can already see the emails on the mailing list from people who can't install deal because their package manager doesn't have `Blas` and`Lapack` but only `openblas` or `atlas`.

**Comment by bangerth** [comment]
I'm not in love with the idea of more mandatory external dependencies. It would be different if we had a bundled backup we could go to.

What is the functionality we would gain if we made LAPACK mandatory? I know that there are some classes that one could always make available. But is there core functionality that we could start using everywhere? If you think about the other mandatory dependencies -- TBB, and BOOST --, they are used everywhere and enable code functionality that would be difficult to provide otherwise. Would requiring LAPACK enable similarly widely usable functionality, or would it only allow us to make available classes  that are "nice to have" but not "enabling"?

**Comment by jppelteret** [comment]
I agree with the opinions expressed here, and also do not think that this should be made a mandatory dependency unless absolutely necessary.

**Comment by davydden** [comment]
These are all valid reasons and I agree that it make sense to keep Lapack as optional dependency.

**Comment by kronbichler** [comment]
I agree that the installation issues are probably not worth the gain in other aspects.

> What is the functionality we would gain if we made LAPACK mandatory?

It depends a bit on the things you are using. I for myself consider LAPACK higher on the priority list than both BOOST and TBB when measured in the amount of time I would need to spend to create an adequate alternative solution (at least now that we have C++11). That's simply because I would hardly be able to run any of my simulations without the ability to solve eigenvalue problems in several contexts. The reason why I raised it was that given my circumstances, I've added a series of features that require LAPACK, the latest being #5879, but the more annoying one was #4587 where we had to duplicate code - fortunately that could go away again with the work of #5386. That said, I had the feeling that the need for LAPACK starts to spread, not the least due to my contributions. Now that's of course my personal priorities, and I try to keep it limited, so I agree that more weight should be on keeping the bar low for newcomers and non-experts.

Since this issue was brought up by me, I'll close it again.

**Comment by bangerth** [comment]
@kronbichler -- I appreciate your perspective, and that you're willing to let us go with keeping things optional. As I mentioned, I think the balance would look different if we could bundle BLAS/LAPACK. I think we probably could do that if we wanted to, for some generic old CBLAS or so. Would that be an option?

**Comment by kronbichler** [comment]
We could think about some old generic BLAS that we can bundle. But as I said, I'd do it when it gets annoying given that bundling is also quite some time. I keep an eye on it, so it won't get forgotten... :smile:

**Comment by tamiko** [comment]
We should also keep in mind that bundling BLAS/LAPACK will very likely
require a fortran compiler.

That won't work with the ninja generator (ninja does not support
implicit compile dependencies that are necessary for fortran
targets). Further, not every user has a fortran compiler installed.
