### ISSUE TITLE
Fix GridTools documentation

### ISSUE THREAD

**Issue by jppelteret** [dealii/dealii#5986]
If possible, we should find a way to fix the layout of the documentation in GridTools. The return type of some of the functions is extremely long, leading to terrible formatting. Perhaps introducing some typedefs would be the easiest way to correct the issue.

![screen shot 2018-03-02 at 10 27 38](https://user-images.githubusercontent.com/10460610/36892261-7dc84bda-1e04-11e8-8ce8-83025de39ab5.png)

**Comment by davydden** [comment]
Yes, it’s very ugly now :-(

**Comment by masterleinad** [comment]
We could also define a struct similar to [PeriodicFacePair](https://www.dealii.org/developer/doxygen/deal.II/structGridTools_1_1PeriodicFacePair.html) and use it instead of the tuple. Since this is not in the latest release we should be allowed to do so and increase readability of the return type as well.
On the other hand, I didn't check if we rely on any special `std::tuple` functions that would make this problematic.

**Comment by davydden** [comment]
does this work:
```
#ifndef DOXYGEN
std::tuple<a,b,c,d>
#else
std::tuple<a, <br> b, <br>, c <br>, d <br> >
#endif
function_name()
```
?

**Comment by Rombur** [comment]
I am reopening this because doxygen still looks horrible on the website. I guess @bangerth's PR only fixes the problem if the documentation is built locally.

![grid_tools](https://user-images.githubusercontent.com/368538/40846245-0a95ccf8-6587-11e8-8d28-beeb0c8f0e57.png)

**Comment by bangerth** [comment]
Confirmed. Quite ugly.

**Comment by bangerth** [comment]
`distributed_compute_point_locations` is the worst offender...

**Comment by bangerth** [comment]
I see the problem. We need to do the same in the .cc file as what I did in #6040 to the .h file. See #6952.

**Comment by drwells** [comment]
We have since shortened the worst offenders so lets close.
