### ISSUE TITLE
MPI communications in p::d::BlockVector can be smarter for 1k blocks

### ISSUE THREAD

**Issue by davydden** [dealii/dealii#6015]
currently, in places like `update_ghost_values()` we simply loop over all blocks and [call the corresponding method](https://github.com/dealii/dealii/blob/master/include/deal.II/lac/la_parallel_block_vector.templates.h#L257-L268) of each block. This is ok for 2-3 blocks, but not ideal in case we use this class as a multi-vector with 100-1k blocks. 

One could instead get all the data to be sent for each block and do this in one go. 
Same applies to `compress()`.

**Comment by kronbichler** [comment]
The question is what the typical size of messages is. The vectors typically send packages of a few kB over the network. We do indeed hide the latency of MPI because we use `update_ghost_values_start()` and `update_ghost_values_finish()`. If we're missing that somewhere we should definitely add it. What we should be left with is the general MPI overhead. Unless the data of each P2P communication call is really small (up to 100 doubles, not more), I think copying the data out into an additional data structure that holds the data is probably more expensive. But it really depends on the quality of the MPI implementation and the use case.

**Comment by kronbichler** [comment]
One thing we might want to add is to not send too many messages in the `_start()` parts because MPI might get overloaded by thousands of pending communications. So we might want to aggregate say 20 or 50 steps in a loop blocking approach.
