### ISSUE TITLE
-march=native as compile flag?

### ISSUE THREAD

**Issue by asartori86** [dealii/dealii#6061]
Just a curiosity: why we do not include `-march=native` in our list of compile flags?

**Comment by davydden** [comment]
IIRC it not always the right way in HPC context (but i don't remember why).

You can always add it manually (what I do).

**Comment by kronbichler** [comment]
We do so in case the variable `DEAL_II_ALLOW_PLATFORM_INTROSPECTION` is enabled.

**Comment by kronbichler** [comment]
> IIRC it not always the right way in HPC context.

One reason is when cross-compiling (but there is an additional variable `CMAKE_CROSSCOMPILING` for that). The other is that a login-node where one does the compilation is of a different architecture than the node where the job gets run. As far as I remember, we opted for the safe way of using the minimum instruction set and let the knowledgeable user do explicitly enable the advanced stuff, rather than the other way around.

**Comment by asartori86** [comment]
thanks @kronbichler  and @davydden for the comments!
