### ISSUE TITLE
p::d::Vector treats local_element() and operator() differently w.r.t. ghost indices

### ISSUE THREAD

**Issue by davydden** [dealii/dealii#6086]
i noticed that `p::d::Vector` does not prevent accessing ghost elements regardless of its state via `operator()`:

https://github.com/dealii/dealii/blob/master/include/deal.II/lac/la_parallel_vector.h#L1366-L1370

whereas `local_element()` requires the vector to be in the `vector_is_ghosted` state: 

https://github.com/dealii/dealii/blob/master/include/deal.II/lac/la_parallel_vector.h#L1411-L1413

that seems inconsistent to me as I would expect `local_element()` to be a `O(1)` alternative to `operator()`.

@kronbichler ping.

**Comment by davydden** [comment]
ah, i see now that the behaviour is different for `const` and non-`const` versions of accessors. Supposedly it has to do with `read` and `write` into ghosts?

**Comment by kronbichler** [comment]
I have looked through the four functions and they seem to be consistent as far as the access goes: The `const` functions do only allow reading the ghosts if you are in `vector_is_ghosted` state, whereas the non-const versions do not check that because we want to be able to write into a non-ghosted vector: That's exactly according to the notion of a non-ghosted vector where we accumulate data also for remotely owned indices after all.

**Comment by davydden** [comment]
ah, yes, it's for writing purposes. Ok, now it's all good in my head ;-)
