### ISSUE TITLE
Possible regression in `GridGenerator`

### ISSUE THREAD

**Issue by Jie-Cheng** [dealii/dealii#6307]
I use [this piece of code](https://github.com/kronbichler/adaflo/blob/master/tests/flow_past_cylinder.cc#L185) to create a standard flow around cylinder grid in 2D, which at least works fine at SHA 304c018c0c7. After updating dealii to the latest master, it fails. I have attached the code (please rename it to `test.cc`) to reproduce the issue, as well as the grids generated from two different builds.

[test.txt](https://github.com/dealii/dealii/files/1940676/test.txt)
![grid-new](https://user-images.githubusercontent.com/12647461/39163484-b42c17b6-4748-11e8-9578-905f3e569ccd.png)
![grid-old](https://user-images.githubusercontent.com/12647461/39163530-f094ab1e-4748-11e8-8e26-83f5c057d861.png)

**Comment by kronbichler** [comment]
This is due to #6233 and expected. Can you please try to call `triangulation.reset_all_manifolds()` or `triangulation.reset_manifold(0)` after you create the hyper shell in the `middle` triangulation, and then manually go through the mesh before the first refinement and set the curved manifold only at the inner rim, not the full manifold? (I still need to update that code at some point, but that has to wait until after the release.)

**Comment by Jie-Cheng** [comment]
Your suggestion fixes this code, thank you! BTW, if you have easy access to a grid generator that creates better grid for the flow around cylinder problem, can you please share it?

**Comment by drwells** [comment]
I suggest using the procedure in step-49: use `GridGenerator::hyper_cube_with_cylindrical_hole()` and `GridGenerator::subdivided_hyper_rectangle` to generate this mesh.
