### ISSUE TITLE
Explain operator| and update_* better

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#637]
I see students struggle with sequences like
```
  update_values | update_gradients | update_JxW_values
```
pretty much every time. This is an obvious statement to C programmers, but not to people who are not used to think in terms of binary operations etc.

I think we should find a way to hide what exactly it is we're doing here. For example, it uses the fact that each element of this list has only one bit set, but that's not clear to a reader. Can we come up with a better syntax? Maybe something like
```
  update_flags_list(update_values, update_gradients, update_JxW_values)
```
? Any other suggestions?

**Comment by QiaoLei-88** [comment]
I think it is OK to keep the form like

    update_values | update_gradients | update_JxW_values
.

Because "binary or" is  not a deprecated operator in C++ language. The C++ standard library also employ this convention:

    std::cout << std::setiosflags (std::ios::showbase | std::ios::uppercase);


And, hiding up things not necessarily make them clear. I believe you have to explain what 

	update_flags_list(update_values, update_gradients, update_JxW_values)

does someday later.

If you want make the statement consistent to natural language, there will be a paradox: a 'binary or’ between A and B means do A ‘and' B. I don't think we can address this conflict eventually. Then I prefer to follow the programming language for it is less ambiguous than natural language.

Maybe the best solution is a comment: "search Google for 'binary or' and you will know what happens".

**Comment by bangerth** [comment]
It's true that it's not deprecated, nor wrong. It's just hard to understand to all who are not as good programmers as @QiaoLei-88  :-)

**Comment by QiaoLei-88** [comment]
I think I can understand their feeling -- it should just like what I feel when reading math books.

I don’t mean to ignore their confusing. Just leave explanation to comment and keep executable code in a efficiency and elegant shape.

Or, one can change 
  update_values | update_gradients
into 
  update_values + update_gradients
This would more like to say “update values and update gradients”, even more than turn it into a function call like
  update_flags_list(update_values, update_gradients, update_JxW_values)
The cost is that the add operator is not safe to insert one flag more than once while there is no guarantee that nobody will confuse on this kind of statement.

Or, a function name “ accumulate_update_flags” is more self-explanatory.

No matter how I still prefer binary operations most. Let’s save those who confusing on binary operations by comment.

**Comment by tamiko** [comment]
I completely agree with @QiaoLei-88 at this point.

I do not see any syntactical benefit of using
```
FEValues<dim> fe_values([...], update_flags_list(update_values, update_gradients, update_JxW_values));
```
or any similar construct, instead of the current syntax
```
FEValues<dim> fe_values([...], update_values | update_gradients | update_JxW_values);
```

Contrary, and as was already rightfully mentioned, the latter is actually a common idiom used throughout different C++/C projects and not that hard to grasp. [1]

I think that we shouldn't try too hard to hide such implementational details if this means to introduce significantly more complexity.

[1] and I think that an explanation like "put in a list of what should be updated and separate the entries with an '|'" is no way worse than an explanation like "use the update-flags_list contructor to create [...]".

**Comment by bangerth** [comment]
I hear y'all. 

I come from a pragmatic point of view that if I have to explain something to 5 out of 20 students every time I teach deal.II, then it's either poorly explained or just genuinely difficult to understand. I think the latter is the case here given that (i) today's students, and (ii) high-level C++ programmers are just not used thinking in bit patterns any more.

But be that as it may, I've added a lengthy discussion to step-3 (the first place where we use this).
