### ISSUE TITLE
9.0 post mortem

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#6618]
Let's do a retrospective on what worked well in the 9.0 release process, and what did not. Here are things that I think did work well:
* We have a pretty good checklist now that lists all of the tasks that need to be worked through.
* We seemed to have sufficient capacity to really put the release through its paces with lots of different platforms and compilers.
* Overall all of the testing did not turn up anything major -- our code base seems to be in pretty good shape, with failing tests on various platforms essentially just do to round off and compiler optimizations, not actual bugs.
* We have enough people: Even if a couple of us are out for some reason or traveling, as a collective I think this worked pretty well.

And here what I see as not having worked well and where we should discuss how we can do better in the future:
* Testing uncovered a lot of warnings with brand new compilers, and trying to work around them took a significant effort and churn with patches that were not always trivial. (Examples: #6475 which at the last minute required introduction of C++17 elements. #6461/#6469/#6480 about `memmove`. #6546 about MPI tags.)
* We had some very last minute patches that were of the "nice to have" but not of the "critical" kind. These patches introduced the risk of breaking stuff since their impact was not always entirely obvious (I'm thinking of obscure Perl regular expressions) and discussions associated with these patches took up a significant amount of time and brain power. (Example: #6567, which changed the script that generates doxygen input for the tutorials.)
* At least for myself and @tjhei (and @gassmoeller), managing both the deal.II and the ASPECT release at the same time was bad timing (I ended up not doing my share of work with the ASPECT release).

My preference for the process would have been:
* We become more accepting of warnings in compilers that are brand new or uncommon. Sure, warnings are annoying, but if we only uncover them days before a release, then (i) they have not bothered a great number of people before, (ii) they are apparently not critical. We should fix them in the normal development process, but maybe accept some warnings we had never seen before as we get close to the release date.
* We become tougher with saying "enough is enough" for patches that are not critical, even if they would be nice to have. For example, #6567 garnered 50 comments, some of which certainly delayed someone going to bed at a reasonable time, and will collectively have cost us 10 hours of work (or sleep). 

My concern about these things is that the process of making a release binds so much time for so many people that we just shy away from doing it more often. It took us more than a year to get 9.0 out, and I'm sure a good part of the reason was that nobody really felt like doing it. If we burn ourselves out by endless late night sessions chasing down every little issue, then that's not motivating us to do it more frequently.

Opinions?

**Comment by davydden** [comment]
I agree with all you said. On the "enough is enough" i think next time we should really freeze the main branch for 2 weeks and do only testing  and bug-fixes. Yes, we can cherry-pick PRs / commits into release branch, but that costs extra effort / time and thus slows down everyone. I don't recall what happened last release, but for 9.0 I had a feeling that we were taking over a lot of PRs. In other words, I suggest we branch-off at a later stage compared to this release.

**Comment by kronbichler** [comment]
I also agree with most points. Two points I would like to add:
- Our release timing in the March/April time frame makes it very tempting to look our for new gcc versions (that have their yearly release in April) and clang versions (that have one of their two yearly releases in March). I would be in favor of either targeting the second half of May or beginning of June or January/February right away, just to avoid this implicit pressure.
- @bangerth you seem to suggest that we should have releases more often. While I do see some value in it, I believe that the current frequency of one release per year is pretty goo. On the one hand, I feel that many of our active users use the master branch on github already, so we include many people under the way already. (Also, ever since we are on github, I believe that the master branch is more visible than the release files.) On the other hand, I also believe that writing one release paper per year is a pretty optimal pace - it takes a reasonable share of time from all of us and we keep a good signal to noise ratio in that we actually have something exciting to tell.

**Comment by tjhei** [comment]
> In order to stabilize the codebase for a release we should branch off and increment in release candidates (this is what we did this time). I think the rapid release candidate increment worked out reasonably well.

I agree and I don't think that it is an issue that we take over many commits. I would prefer that we have a longer time frame for RCs.

**Comment by tamiko** [comment]
@drwells 
> I think that we were a bit too cavalier in merging commits without letting the tester run. This probably caused more problems than it solved (it did help us move faster, but we had more to ultimately fix).

I would say, yes and no.
 - Most of the problems we encountered weren't spotted by the CI configurations but only become apparent when run on the full testsuite.
 - I made sure that I had at least one full testsuite run for everything we merged. Unfortunately, just checking everything for gcc-7 with standard configuration isn't a guarantee for a smooth ride as it turned out  :confused: 
 - Another thought on the CI versus testsuite: We have to find an alternative mode, or a different procedure for coding sprints. At some point we had 20 PRs for the release to master and to the release branch within a time-frame of about 3 hours. Testing all of these would have taken the CI quite a significant amount of time.

For the latter, I plan to modify the testing site that I control to support also a submission based testing. @tjhei may I ask you to send me your CI control script for that purpose? :-)

**Comment by bangerth** [comment]
Looks like we got some consensus here. Good discussion. Let's read all of this again when we get to the next release!

I think the point about one release per year is reasonable since that gives us time to write meaningful release papers.
