### ISSUE TITLE
Don't use rand_r

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#674]
rand_r doesn't seem to be available readily with cygwin, and it's not a good solution anyway. It's also not C99. We should replace it by one of the BOOST random number generators.

Occurrences:
```
source/base/utilities.cc:390:    // context. thus, use rand_r. this does not produce reproducible results
source/base/utilities.cc:396:    const double y = 1.0*rand_r(&seed)/RAND_MAX;
```

**Comment by Ampaduj** [comment]
Thanks for the information. I am new to FEM as well as dealii. Today, March 29, 2015, I tried installing deal on windows using the cygwin interface and after about 40% of installation I had the same error:
/cygdrive/f/computation/dealii-8.2.1/source/base/utilities.cc: In function ‘double dealii::Utilities::generate_normal_random_number(double, double)’:
/cygdrive/f/computation/dealii-8.2.1/source/base/utilities.cc:421:38: error: ‘rand_r’ was not declared in this scope
     const double y = 1.0*rand_r(&seed)/RAND_MAX;

I implemented the advice you put up as a response at:
http://comments.gmane.org/gmane.comp.science.mathematics.dealii/5757

And the installation was completely finished.
I hope to learn, understand, implement and improve deallii as a software platform for Engineering applications.
Thank you.

**Comment by drwells** [comment]
@Ampaduj: what a coincidence. I had been writing this comment and digging through headers for about an hour when you posted.

I spent some time looking at this and it is surprisingly complicated to replace `rand_r` with one of the nice BOOST random number generators without running into the static initialization problem. We could do something like (this is C++11, but BOOST has all of this too)
```
std::normal_distribution<double> distribution(a, sigma);
std::random_device device;
return distribution(device);
```
Since
1. that is not much code to ask a user to write
2. calling `random_device` is a lot of IO for one function call (at least when `/dev/urandom` is present)
3. as far as I can tell, this function is not used in deal.II or aspect

perhaps this function should just be deprecated?

**Comment by Ampaduj** [comment]
@drwells: Thanks for information provided. Although you insist that the function is not really necessary, I think the information provided is very important at least for a beginner like me for the sake of learning!!
Thanks.

**Comment by tjhei** [comment]
@bangerth one work-around would be to modify the function ```rand``` in tests/tests.h to make it thread-safe (by making the static variables thread local): 
```
// Cygwin has a different implementation for rand() which causes many tests to fail.
// This here is a reimplementation that gives the same sequence of numbers as a 
program
// that uses rand() on a typical linux machine.

```

**Comment by bangerth** [comment]
Yes, I think that would be one way. Another option would be something of this kind:
```
  ThreadLocalData<boost::mt19937> random_number_generator;    // or some other type
  return boost::normal_distribution<>(0,1)(random_number_generator.get());
```

**Comment by Ampaduj** [comment]
@bangerth 
I am having some sort of difficulty in making a test run. I had successfully installed via:
make prefix=c:/cygwin64/usr/local install

Now I try the following command and it takes forever (more than 4 hours now):

make prefix=c:/cygwin64/usr/local test

The only output that appeared on the screen was:

Test project /cygdrive/f/computation/dealii-8.2.1/tests/quick_tests
    Start 1: step.debug

is this due to the specs of my core i3 windows 8.1 PC? My installed memory capacity is 6 GB and the processor speed is 2.4 GHz. Thanks.

**Comment by bangerth** [comment]
No, it shouldn't take 4 hours to run a single test, regardless of your machine :-) This should take a couple of seconds at most. Can you see in your process monitor whether the program is really still running?

(This issue is really unrelated to the `rand_r` problem discussed here. Please take your question to the mailing list or forum.)

**Comment by Ampaduj** [comment]
Okay, advice well noted.
I have put the question on the dealii google mail list.

At the processes tab of my task manager, I do not explicitly see Cygwin terminal.
However I do see the following processes names:
make, cmake, ctest, sh, as well as step.debug

Thanks.
