### ISSUE TITLE
Simplify vector-vector operation interfaces

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#684]
Our vector classes have all of these `equ`, `add` and `sadd` functions that do vector-vector operations, but I would venture the guess that fewer than half of these are actually used anywhere. On the other hand, they produce a very significant maintenance burden every time we write or update one of the many linear algebra interfaces we have.

I would favor us deprecating all of those functions that we don't use in the Krylov-space solvers.

**Comment by bangerth** [comment]
@Rombur was going to look into this at one point or other.

**Comment by tjhei** [comment]
Agreed. My idea would be to make a clean cut before we implement the TPetra interfaces and define a new minimal interface for vectors and matrices.

**Comment by tjhei** [comment]
Anyone starting to work on this: please keep me in the loop.

**Comment by bangerth** [comment]
Yes, that was the idea: identify which functions we need, deprecate the rest, and in new interfaces only implement those that are not deprecated in the other vector classes.

**Comment by Rombur** [comment]
Since changing the vector interface is a pretty big change, I want to talk about it here before I start doing changes everywhere. We can talk about the details when I create the pull request but I would rather not deprecate your favorite function ;-) .

Right now, I have looked at the serial vector and my first question is, do we need to have a serial implementation for petsc and trilinos vectors? I could see that some people want to use some packages in trilinos that require a Epetra_MultiVector but you can use a vector to create a Epetra_MultiVector. The division between serial and distributed is not very clear (all the serial vectors need to implement ```compress()```...) We may want to keep the serial implementation if we just want to work on a node that has an accelerator (I'm thinking about Tpetra or another library with similar capabilities) but if we just do plain multithreading we can just use dealii vector.  The way I see it, we can either keep the serial vector and use it when there is an accelerator or have a new interface when we have an accelerator (we would probably have things like move to/from the accelerator) and get ride of the serial petsc and epetra interface.

If we want to keep petsc and trilinos, here is the interface modification I was thinking of:

DEALII_VECTOR:
  to deprecate:
    ```add(const Number s)	Vector< number >```   (this is used in several tests)
    ```add(const Vector< Number > &V)```	   (only keep +=)
    ```begin()```
    ```begin() const```
    ```end()```
    ```end() const ```
    ```equ(const Number a, const Vector< Number > &u, const Number b, const Vector< Number > v, const Number c, const Vector< Number > &w)```
    ```print(const char *format=0) const ```
    ```sadd(const Number s, const Number a, const Vector< Number > &V, const Number b, const Vector< Number > &W, const Number c, const Vector< Number > &X)```
  to add:
    ```set(const std::vector< size_type > &indices, const std::vector< Number > &values)```

PETSC_VECTOR:
  to deprecate:
     ```abs()```
     ```add(const size_type n_elements, const size_type *indices, const PetscScalar *values)```
     ```add(const PetscScalar s)```  (use in several tests)
     ```add(const VectorBase &V)``` (only keep +=)
     ```conjugate()```
     ```get_mpi_communicator() const```
     ```has_ghost_elements() const```
     ```local_range() const```
     ```local_size() const```
     ```max() const```
     ```min() const```
     ```mult()```
     ```mult(const VectorBase &v)```
     ```mult(const VectorBase &u, const VectorBase &v)```
     ```normalize() const```
     ```sadd(const PetscScalar s, const PetscScalar a, const VectorBase &V, const PetscScalar b, const VectorBase &W, const PetscScalar c, const VectorBase &X)```
     ```write_ascii(const PetscViewerFormat format=PETSC_VIEWER_DEFAULT)```
I would like to replace  ```operator const Vec &() const``` used to get the underlying petsc_vector by something like ```petsc_vector() const``` It's similar to what we do for trilinos and it is easier to find in the documentation

TRILINOS_VECTOR:
  to deprecate:
     ```add(const size_type n_elements, const size_type *indices, const TrilinosScalar *values)```
     ```add(const TrilinosScalar s)```   (use in several tests)
     ```add(const VectorBase &V, const bool allow_different_maps=false)``` (only keep +=)
     ```begin()```
     ```begin() const```
     ```clear()```
     ```el(const size_type index) const```
     ```end()```
     ```end() const```
     ```get_mpi_communicator() const```
     ```has_ghost_elements() const```
     ```is_compressed() const```
     ```local_range() const```
     ```local_size() const```
     ```minimal_value() const```
     ```print(const char *format=0) const```
     ```reinit(const Epetra_Map &input_map, const bool fast=false)```
     ```sadd(const TrilinosScalar s, const TrilinosScalar a, const VectorBase &V, const TrilinosScalar b, const VectorBase &W, const TrilinosScalar c, const VectorBase &X)```
     ```set(const std::vector< size_type > &indices, const ::Vector< TrilinosScalar > &values)```
     ```set(const size_type n_elements, const size_type *indices, const TrilinosScalar *values)```

**Comment by tamiko** [comment]
I agree with almost all of it - with one notable exception. I would opt to keep the iterator interfaces <code>begin(), end()</code> etc. (and even add <code>rbegin/rend/cbegin/cend/crbegin/crend</code>) when appropriate. Otherwise we lose all of the nice C++11 features for operating with sequencing containers....

**Comment by Rombur** [comment]
I removed them because they don't exist for the petsc interface but it should be easy to add them.

**Comment by tjhei** [comment]
> do we need to have a serial implementation for petsc and trilinos vectors? 

I don't think so, but I am not sure if the SLEPc stuff is only available in serial.

> add(const size_type n_elements, const size_type *indices, const PetscScalar *values)

These are kind of nice because they are more flexible than the std::vector<> variant.

> has_ghost_elements()

We should keep some functionality to known if the vector is a ghosted vector or not.

Other thoughts:
1. We might need to change assembly (which is currently ended with ```compress``), to be wrapped in something like:
```
   x.begin_assembly();
   x[i]+=5.0;
   x.end_assembly(VectorOperation::Add); // or keep calling it compress(...)
```
so that we can allow multithreaded access to PETSc vectors.

2. We need to discuss if we want to stay with the current notion of read-only ghosted vectors or not. It might be worth representing them with a separate vector type as in ```LA::PETSc::Vector``` vs ```LA::PETSc::GhostedVector```.

**Comment by kronbichler** [comment]
I agree with @Rombur that having separate serial and MPI vectors in PETSc and Trilinos is redundant. Especially for the Trilinos interface which I know well. It makes sense to have the distinction for the deal.II vectors (Vector vs parallel::distributed::Vector) because the former can do direct array access upon operator() whereas the latter cannot, but the implementation for PETSc/Trilinos is the same.

Regarding begin_assembly(): If it helps PETSc, I would definitely introduce this in all classes.

Regarding set/add(const size_type n_elements, const size_type *indices, const TrilinosScalar *values):
This is the method closest to implementation because currently the other methods forward to this. If we don't use it anywhere, I'd have nothing against deprecating it. Adding several entries to vectors is not used frequently anyway and at least in Trilinos it gives you little performance benefit because we can directly access into the data arrays anyway. I did not check PETSc but guess we could have something similar when allowing for begin_assembly().

**Comment by bangerth** [comment]
I agree with @Rombur 's list for deprecation except the `begin/end` pair which I think I would like to keep -- we use iterators throughout, so let's keep them here as well if only for consistency. It's the C++ way of doing things.

About `has_ghost_elements()` -- do we not use this in all sorts of places?

About `Vector` vs `GhostedVector` -- I feel that that would make things unnecessarily complicated. `Vector` has a superset of operations to `GhostedVector`, so the natural way to implement it would be to derive from `GhostedVector`. Yet, this is not an is-a relationship, so a better way of implementation would be to have them be parallel classes, but then there would be a lot of duplication. I don't see a major benefit to it.

About `begin/end_assembly()` -- I really don't like this. It exposes an implementation detail to the user and it's so easy to forget. What would be the benefit to it?

**Comment by Rombur** [comment]
@tjhei according to our documentation SLEPc works in parallel.

I don't want to have to deal with Trilinos and PETSc in serial because like @kronbichler pointed out things like operator() don't exist in parallel. It's was not easy to do with Epetra but it's worse with Tpetra: you need to create a view every time you want to access an element and I can image people using it to copy vector... That's why I want to deprecate a lot more functions for the parallel vector. Right now, we try to make it easy to go from petsc/trilinos serial to petsc/trilinos parallel but I don't think that we gain a lot from it and worse we encourage user to write bad parallel code.

**Comment by bangerth** [comment]
The issue with creating a view is the same in PETSc. It's incredibly inefficient. It's also not possible to make this efficient in a multithreaded context.

**Comment by Rombur** [comment]
I have to think more about it but I feel that, for parallel vector, we could force people to fill a Vector or a std::vector and then, use it to fill the petsc/trilinos vector. 

Anyway, I think we agree on the serial interface. I will start working on a pull request and we can discuss the detail there. The only question left is: Do we want to keep the serial petsc and trilinos interfaces? @kronbichler and I want to drop it, is someone against it?

**Comment by bangerth** [comment]
I do like `operator()`. There are many cases where not having it would certainly make code much more awkward. I believe, for example, that step-42 pokes into Trilinos vectors all the time to figure out whether a Lagrange multiplier is larger or smaller than zero. There is no real alternative to doing this, so not having `operator()` would just lead to code obfuscation.

As for the removal of the serial vectors -- I'm ok with it. Is there a way to add constructors to the parallel vectors in such a way that they can be created without an MPI communicator object (which in that case would just default to MPI_COMM_SELF)?

**Comment by Rombur** [comment]
My problem with ```operator()``` is what do you do once you have created the view ? If you are using ```operator ()``` in a loop, you want to keep the view but if you need access to only one element, there is no point in keeping the view around. I would prefer to let the user get the view and decide what to do with it.
