### ISSUE TITLE
Output and visualization of high-order solutions/meshes

### ISSUE THREAD

**Issue by agrayver** [dealii/dealii#6931]
The current workflow for storing high-order element solutions and high-order meshes (with attached manifolds) is by subdividing them. I find this approach rather limiting: it takes up a lot of space/memory and one does not see the actual mesh in the end. 

Recently, both VTK and ParaView have added [support ](https://www.paraview.org/Wiki/ParaView_Release_Notes#Arbitrary-order_Lagrange_finite_element_support)for arbitrary-order Lagrange elements. 

Below is a somewhat exaggerated, but motivating example: it shows a single 9th order element with a 4th order polynomial solution and six times subdivided linear mesh (64x64x64 cells). At the bottom, you can see how wastly different their memory footprint is (a factor of 743!). Even more so on the disk, even though both were saved as zipped vtu. 

The other remarkably convenient feature is that one can adjust the accuracy of interpolation within paraview, thereby controlling both memory consumption and rendering time. 

![paraview](https://user-images.githubusercontent.com/8438035/42936397-3e79c1a6-8b4c-11e8-87d7-fc55908c7eb5.png)

Does anyone of @dealii/dealii devs see any reason this should not be supported? Are there any technical problems envisaged?

**Comment by tjhei** [comment]
> Does anyone of @dealii/dealii devs see any reason this should not supported?

This would be great to have. Do you know where we can find a specification for these elements in the vtu format?

> Are there any technical problems envisaged?

It looks like it would only work for Lagrange elements and I am not sure if there are other restrictions (curved geometry? vector-valued elements?)...

**Comment by drwells** [comment]
The workaround I use is to write the grid with `GridOut` and no patches and then write solutions with `DataOut` and *lots* of patches. It would be great to have this feature for our output so that these hacks are no longer needed.

My main concerns are:
1. Most peoples' workstations have older copies of paraview and visit (it seems like I am usually 3-4 years behind). When was this feature added?
2. The `Patch` (see `deal.II/base/data_out_base.h` circa line 240) data structure assumes that everything is a nodal interpolant. Fortunately, since all data is placed in a dynamically allocated object (a `Table<2, float>`), we can probably just reuse most of the existing infrastructure by encoding some scheme for putting higher-order interpolants (i.e., with our standard `FE_Q` ordering) in that object, but we will still have to update our entire output pipeline to understand the new patch data format.
3. As @tjhei pointed out we might need to add an additional inter-finite element interpolation step. Chances are paraview has not yet learned how to plot `FE_RaviartThomas`. (I would be pleasantly surprised if they support isoparametric elements; we may still have to build patches to fake that).

**Comment by agrayver** [comment]
> Most peoples' workstations have older copies of paraview and visit (it seems like I am usually 3-4 years behind). When was this feature added?

It is in ParaView since 5.5 and it was introduced to VTK a year ago or so. 

> As @tjhei pointed out we might need to add an additional inter-finite element interpolation step. Chances are paraview has not yet learned how to plot FE_RaviartThomas. (I would be pleasantly surprised if they support isoparametric elements; we may still have to build patches to fake that).

Of course, for non-Lagrange elements you will need to get quantities at the Lagrange points, but you already do so when subdivison happens anyway, don't you? The physical locations of the VTK Lagrange points are then requested from the given mapping (same as for subdivided elements).

**Comment by bangerth** [comment]
I gave this some thought, and I think the least intrusive way would be this: Right now, even if you have called `DataOut::build_patches(n)` with `n>1`, all of the output from one cell ends up in one `Patch` object. Currently, the writers interpret this as the user wanting the output to be created in a way where the patch is split up into what I'll call "output-cells" (as opposed to "source-cells").

All current producers of these `Patch` objects know how to create patches, and all current consumers (namely, output writers) of these `Patch` objects know how to interpret them. Keeping the `Patch` data structure as is is therefore a useful approach.

What I would suggest is to add a flag to the `VtkFlags` structure that instructs the VTK/VTU writers to *interpret* patches with subdivision differently. Namely, rather than trying to output each patch with subdivision as multiple output-cells, output it only as a single cell and interpret the subdivided data as point evaluations of a higher order polynomial. If we do this, we can:
* output higher order polynomials with no changes anywhere other than in the VTU/VTK writers
* all other producers and consumers of `Patch` objects remain unchanged
* it also works for any finite element: if you have an RT(2) element where some of the shape functions are cubic in at least some of the variables, just call `DataOut::build_patches(3)` and set the flag in `VtkFlags`, and you will get to see a cubic (Q_3) interpolation of the solution. Because Q_3 is a superspace of RT(2), you see the exact solution.

Anyone who would like to think about how to implement this?

**Comment by agrayver** [comment]
Since we already figured out how to write these elements (connectivity patterns, etc), I could help with the actual VTK/VTU output, but it would be good if someone more experienced made the initial attempt to adjust the DataOut internals.

**Comment by bangerth** [comment]
If you went with the idea I outlined above, you wouldn't have to make any changes at all to `DataOut` and friends. They just put their data on uniformly subdivided subcells into the `Patch` object, and it would be up to the output generator to decide (based on a user-provided flag) whether they interpret that `Patch` as consisting of multiple d-linear sub-cells, or as the support point values of a single higher-degree cell.

**Comment by agrayver** [comment]
Ok, I figured out all details on how to write these cells (had to dig into VTK a bit). I also had a look at DataOut::write_vtk and I think I know how to implement this. Will try to come up with a PR.

**Comment by kronbichler** [comment]
Thanks to the contributions in #6994 and #7015 I think this can be closed. @agrayver is there anything more you want to address or want to be addressed?

**Comment by agrayver** [comment]
Yes, this is resolved. I hope to get +1 to me karma for each GB saved in our disks ;)

**Comment by bangerth** [comment]
Definitely lots of karma points for you!

**Comment by bangerth** [comment]
Now, if only Visit started to support this too...
