### ISSUE TITLE
"Features" tab on the website

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#6947]
There are other libraries that do a really nice job at listing features -- like here, for example: http://mfem.org/features/

We ought to do the same.

**Comment by icojb25** [comment]
hi, i can do these - where is the website source?

**Comment by drwells** [comment]
@icojb25 the website source is not publicly available. However, if you would like to get started, I think it would be reasonable to just draft a page similar to https://dealii.org/about.html that highlights our feature set.

**Comment by icojb25** [comment]
> 
> 
> @icojb25 the website source is not publicly available. However, if you would like to get started, I think it would be reasonable to just draft a page similar to https://dealii.org/about.html that highlights our feature set.

hi David, thanks for the reply. ok cool. at least i was not not finding it because i was doing something silly! i will have a crack at that, is there anywhere i can solicit stuff which people would like to be highlighted? the mailing list?

how do you want to go through the process if i cannot share my revisions as a PR?

**Comment by bangerth** [comment]
If you have a mock-up HTML page, I (or any of the others) can commit it to the repository!

**Comment by icojb25** [comment]
[deal2.zip](https://github.com/dealii/dealii/files/3125675/deal2.zip)

hi @drwells @bangerth i've attached a first draft above.
