### ISSUE TITLE
Don't throw exceptions by reference

### ISSUE THREAD

**Issue by drwells** [dealii/dealii#7048]
Throwing exceptions by ~value~ reference doesn't make sense: the exception itself has to be copied somewhere, which cannot be done without slicing if we have a reference.

The real impact of this is that trying to catch things that are thrown after `disable_abort_on_exception` doesn't work: those exceptions are always sliced down to ExceptionBase.

We can probably fix this by moving things in `exceptions.cc` into `exceptions.h` and declaring them as templates on the type of the exception.

**Comment by bangerth** [comment]
I don't think I understand. Throwing by-value is totally common and supported, after all you can do
```
  throw 1;    // int
```
and later do
```
  catch (int i)  // triggers
```
What is happening in practice is that the runtime system allocates the exception on the heap, stores the pointer somewhere along with a pointer to the typeid of the object that's being thrown, and no copy happens.

Can you give an example of something you want to do but think doesn't work correctly right now?

**Comment by drwells** [comment]
I made a huge typo when I wrote this out (probably because I had been debugging for several hours): I meant to write *reference* everywhere. Of course throwing by value works.

**Comment by drwells** [comment]
Here is an example:
```cpp
    [[noreturn]] void
    abort(const ExceptionBase &exc) {
      if (dealii::deal_II_exceptions::abort_on_exception)
        internal_abort(exc);
      else
        {
          // We are not allowed to abort, so just throw the error:
          throw exc;
        }
    }
```

This will always slice down to `ExceptionBase` (unless, of course, we throw an `ExceptionBase`).

**Comment by masterleinad** [comment]
The problem here is not that `abort` takes its argument by reference, but that `throw exc;` creates a copy of type `ExceptionBase` (and slices `exc`). That is probably also what you meant.
It seems that we really need to templatize these functions to avoid slicing.

**Comment by drwells** [comment]
This would be a good opportunity to clean these functions up a bit. I have always found the `dealii::deal_II_exceptions` namespace to be very strangely named.

**Comment by bangerth** [comment]
Yes, @masterleinad is correct: a `throw` expression copies the object referenced in the expression using its static type, which in the example given is `ExceptionBase`. 

If this is the only place this happens, then we could rearrange things in such a way that the base class stores the information in the form of a string, rather than the derived class generating it at the time the string is output. But that's likely inefficient.

It's a shame that the `throw;` statement without argument can only be used in a `catch` block, because that's probably exactly what you want. Here's a trick that we could do, though: Instead of directly calling
```
  MyException exc (...);
  dealii::abort (exc);   // dynamic type is lost
```
we can do
```
  MyException exc;
  try {
    throw exc;
  } catch {
    dealii::abort();
  }
```
because then, in `dealii::abort` we can call all of the functions listed here: https://en.cppreference.com/w/cpp/error
In particular, we can capture the exception using `std::exception_ptr` and throw it again using `std::rethrow_exception`.
