### ISSUE TITLE
Bug in Particle::load()?

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#7093]
`Particle::load()` current looks like this:
```
  template <int dim, int spacedim>
  template <class Archive>
  void
  Particle<dim, spacedim>::load(Archive &ar, const unsigned int)
  {
    unsigned int n_properties = 0;

    ar &location &reference_location &id &n_properties;

    if (n_properties > 0)
      {
        properties = new double[n_properties];                  // ***********************************
        ar &boost::serialization::make_array(properties, n_properties);
      }
  }
```
The marked line bypasses the property pool.

@gassmoeller -- is this a bug?

**Comment by gassmoeller** [comment]
Not sure if I would call it a bug, it worked with the current version of the property pool. I think the problem here was that the particle at the time when `load` is called does not have a property pool assigned (it as default constructed), so it does not know where to ask for a space to load its properties into. That is why it creates its own space. This might lead to problems if the property pool at some point does more than just creating a handle as a pointer to a `new double`. This should probably be documented here though.

But thinking about it, I am not sure this function is actually called anywhere at the moment. The `ParticleHandler` uses the `store_particles` and `load_particles` functions to serialize and deserialize the data during a checkpoint (it is stored as serialized data together with the triangulation), and thus particles itself are serialized/deserialized with the `Particle::write_data` function, and the `Particle::Particle(const void *&begin_data, PropertyPool &property_pool)` constructor. The `load` function might just be a remnant of an earlier version of serialization.

**Comment by bangerth** [comment]
You're correct -- it's not called anywhere right now. But I want to do so while addressing https://github.com/geodynamics/aspect/issues/2602 -- it's just so much more convenient to serialize these particles using these functions than to go through the `store()` and `load()` interfaces because there you have to know how big the buffer is going to be.

Let me think about this some more. I think bypassing the `PropertyPool` is awkward and is both going to lead to performance issues with fragmented memory and with potentially later releasing the memory allocated with `new` through the `PropertyPool` that thought that it had allocated that memory itself.

**Comment by drwells** [comment]
We have since rewritten the binary representation of particles - lets close unless there is another report.
