### ISSUE TITLE
Surprising result from hp_unify_dof_indices_02

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#7179]
@marcfehling , here's a question for you: `hp_unify_dof_indices_02` with 2 processors in 2d uses a 2x2 grid in which the bottom two cells belong to process 0 and the top two belong to process 1. It distributes DoFs as follows (all cells have Q2 elements):
```
DEAL:0:2d::Processor: 0
DEAL:0:2d::  Cell: 0.0
DEAL:0:2d::    0 1 2 3 4 5 6 7 8 
DEAL:0:2d::  Cell: 0.1
DEAL:0:2d::    1 9 3 19 5 10 11 12 13 
DEAL:0:2d::  Cell: 0.2
DEAL:0:2d::    2 3 14 20 15 16 7 17 18 
DEAL:0:2d::  Cell: 0.3
DEAL:0:2d::    3 19 20 21 16 22 12 23 24 
DEAL:0:2d::  n_locally_owned_dofs: 14
DEAL:0:2d::  n_global_dofs: 25
```

One can argue that the DoF index 19 at the right end vertex of the subdomain boundary is a bit surprising (I would have expected it belong to process zero), but that's not wrong -- just surprising. 

What does seem a bit wrong is that the numbering indicates that that vertex DoF *belongs* to process 1. That's visible also in the fact that process 0 only claims to own 14 DoFs, not the 15 one would naively expect. 

Is this expected?

**Comment by marcfehling** [comment]
I looked over the results and think they are in agreement with the current desired behavior. Let me try to be more precise with the following sketch:

```
|----------|----------|
| fe_idx=2 | fe_idx=0 | <-- CPU 1
|----------|-----+----*
| fe_idx=0 | fe_idx=1 | <-- CPU 0
|----------|----------|
```
Ownership of vertex DoFs is specified by the active FE index, whereas ownership on lines and quads is clarified via face domination.

DoF 19 (marked with a `*` here) is shared by both cells on the right, but is owned by the upper cell with the lower active FE index that belongs to processor 1.

DoF 14 (marked with a `+` here) is also shared by both cells, and both FE objects are of equal order. Thus, we choose the first active FE index assigned to this line, which would be the `fe_idx=1` (at least I assume that this happens).

We should discuss if we want to consider a common criterion for all objects, i.e. vertices, lines and quads, so that we do have unique ownerships across cell interfaces. What do you think?

**Comment by marcfehling** [comment]
Further, I just realised that the DoFs of a `FE_Q(2)` element are enumerated like this:
```
2---7---3
|   |   |
4---8---5
|   |   |
0---6---1
```
This is not in accordance with the hp paper (see Fig. 3 there). Is this desired behaviour, or did I understand something wrong?

**Comment by bangerth** [comment]
On 09/24/2018 02:54 PM, marcfehling wrote:
> We should discuss if we want to consider a common criterion for all 
> objects, i.e. vertices, lines and quads, so that we do have unique 
> ownerships across cell interfaces. What do you think?

I don't really care much one way or the other. I just found it 
surprising. It may be less surprising if we did the same for vertices as 
we do for lines/quads, but it's only worth the change if it doesn't 
require much work to come up with a patch.

**Comment by marcfehling** [comment]
I guess #7234 fixed this. The issue can be closed.
