### ISSUE TITLE
Undefined references in AD classes when compiling with -O0

### ISSUE THREAD

**Issue by tamiko** [dealii/dealii#7211]
@jppelteret Would you mind to have a look at http://cdash.kyomu.43-1.org/testDetails.php?test=30048420&build=4774 ? :smiley:

**Comment by tamiko** [comment]
In reference to #7207

**Comment by jppelteret** [comment]
Sure, I'll look into this when my linux machine is simulation-free (likely only next week). I guess that [this](https://stackoverflow.com/q/8016780) is the issue.

**Comment by masterleinad** [comment]
Yes, you have to define the `static const` variables as well since they are odr-used in the test.
It's quite interesting that we didn't see the problem before and that it depends on the compiler optimization flags. Apparently, the variables have been treated as compile-time constants before.

You probably just have to extend the compiler switch in https://github.com/dealii/dealii/blob/master/include/deal.II/differentiation/ad/ad_number_traits.h#L947 to also do something for `gcc`.

It seems that we have already been looking at this issue at some point...

**Comment by jppelteret** [comment]
> You probably just have to extend the compiler switch in https://github.com/dealii/dealii/blob/master/include/deal.II/differentiation/ad/ad_number_traits.h#L947 to also do something for gcc.

Thanks, that was the plan :-) Patch should be coming in soon.

**Comment by jppelteret** [comment]
BTW. According to [this post](https://stackoverflow.com/a/28846608), this redundant declaration is unnecessary with c++17 is enabled. Maybe I (or we) had this enabled and so didn't see a failure before now.

**Comment by masterleinad** [comment]
I wished all the compilers were conforming to the C++17 behavior already and we could just use `constexpr` instead of `static const` everywhere...
