### ISSUE TITLE
Doesn't link with arpack

### ISSUE THREAD

**Issue by yurivict** [dealii/dealii#7292]
I have ```arpack-ng-3.6.3``` installed that includes pArpack. It only has shared libs, and no static libs.
```DEAL_II_WITH_ARPACK=ON``` is set.

configure prints:
```
-- 
-- Include /usr/ports/math/deal.ii/work/dealii-9.0.0/cmake/configure/configure_arpack.cmake
-- Found ARPACK_LIBRARY
--   ARPACK_LIBRARIES: /usr/local/lib/libarpack.so;/usr/local/lib/libopenblas.so;m;c;gcc_s;gcc
--   ARPACK_LINKER_FLAGS: -Wl,-rpath=/usr/local/lib/gcc7  -L/usr/local/lib/gcc7 -B/usr/local/bin -fstack-protector -L/usr/local/lib
-- Found ARPACK
-- DEAL_II_WITH_ARPACK successfully set up with external dependencies.
--
```
, but the shared lib doesn't get linked with arpack libs in the end.

Also ```ARPACK_LIBRARIES``` doesn't include /usr/local/lib/libparpack.so, despite you saying here https://github.com/dealii/dealii/issues/7267 that it automatically detects pArpack.

OS: FreeBSD 11.2

**Comment by davydden** [comment]
> but the shared lib doesn't get linked with arpack libs in the end.

please upload `detailed.log`.

Are you sure you build `deal.II` with MPI? If not, we don't look for pArpack.

Also, if you use `arpack` (instead of `arpack-ng`), then, as I said, there is Fortran symbol collision.
We do not check for collision, but unconditionally disable pArpack if Scalapack is also there, see [this](https://github.com/dealii/dealii/blob/master/cmake/modules/FindARPACK.cmake#L55-L71). 

If you know that you won't have these issues, you can set `-DDEAL_II_ARPACK_WITH_PARPACK=ON`.

p.s. 

> despite you saying here #7267 that it automatically detects pArpack.

if you mean myself, the I never claimed it, to quote I said

> deal.II can distinguish between Arpack or Arpack + pArpack.

which means that we can use serial only or serial + MPI. But yes, deal.II will automatically pickup both with limitations noted above.

**Comment by yurivict** [comment]
Here is ```detailed.log```: https://people.freebsd.org/~yuri/deal.II-arpack-detailed.log
Only Lapack and Arpack are enabled, MPI is not.

**Comment by yurivict** [comment]
> in this case we, of course, we won't look for pArpack as this is an MPI version of Arpack.

Clarification: Arpack itself is MPI-enabled. libparpack.so is installed. But you don't look at this because MPI is disabled, which is fine.

Currently you don't link to Arpack at all, this is a problem.

**Comment by davydden** [comment]
> Currently you don't link to Arpack at all, this is a problem.

just to clarify, do you have linker error when building? If so, can you post? Why do you think Arpack is not being linked?

On the second look, your log looks perfectly normal to me.

**Comment by tamiko** [comment]
@yurivict The whole arpack interface is implemented in a single header file `deal.II/lac/arpack_soler.h` - when you look at your compile output you will see that you do indeed link against arpack, with something like
```
[...] -Wl,--as-needed [...] -larpack [...]
```
The as-needed switch removes arpack again from the dynamic section because we simply do not use any symbol (exported by that library) internally - this is perfectly fine. Our project configuration will make sure that end-user projects will have arpack in the link line again.

**Comment by yurivict** [comment]
Ok, thanks, this explains it.
