### ISSUE TITLE
OpenMP as an alternative to TBB

### ISSUE THREAD

**Issue by davydden** [dealii/dealii#7300]
this is not meant as "which one is better", but rather noting that many libraries deal.II can be used with MPI+X opted for OpenMP ([Tpetra](https://trilinos.org/packages/tpetra/) would be the first in the list, but dense parallel [SLATE](https://icl.utk.edu/slate/) also uses OpenMP, same with [GHOST](https://github.com/RRZE-HPC/GHOST) linear algebra library developed here in Erlangen).

I think we should eventually support OpenMP as an alternative to TBB so that we can get full potential out of third party libraries. 

Probably most crucial parts where we want to keep multithreading are

- [ ] assembly of stiffness matrices
- [ ] matrix-free operators

**Comment by Rombur** [comment]
I agree. I have also been to discussions about how to share threads between different libraries and a large number of people were in favor of assuming that everybody is using OpenMP. So it's possible that people will come up with an OpenMP-only solution.

**Comment by tjhei** [comment]
I think the only useful approach would be to reimplement ``WorkStream::run`` using OpenMP by using something like ``omp task``.

**Comment by bangerth** [comment]
There are only three places left where we explicitly use TBB in ways that are not easy to substitute:

1. In the `ThreadLocalStorage` class
2. In `WorkStream`
3. In `new_task`

Replacing `new_task` would in principle not be difficult using the C++11 classes, but I have not done that because I didn't want us to have two different subsystems creating threads and tasks (TBB-based and C++11 runtime based). `WorkStream` is, in my opinion, going to be really very very hard to replace with OpenMP. I would not have the first idea how to do that. One could replace `ThreadLocalStorage` by a pure C++11 solution without too much trouble (namely, a `std::map<std::thread::id_type,T>`).

We also use the TBB in `parallel::parallel_for`, but suspect that this could easily be replaced by OpenMP.

I have to admit that I don't understand why people use OpenMP as a task model. OpenMP doesn't return a handle to a task, and so one can not easily start some work and later wait for it to finish. I think it's a completely stupid model, even less useful than the basic C++11 classes (which are missing many higher order pieces of functionality currently provided by the TBB). I continue to think that I'm probably missing something about OpenMP, but I just don't see how one could implement something like matrix assembly in an efficient way with OpenMP. It's a great model to parallelize the inner loops; it's a poor model to parallelize the outer algorithms.

**Comment by jppelteret** [comment]
We would need to be careful as not all versions of `clang` support OpenMP (see, for example, [here](https://stackoverflow.com/a/33358625) for some clang OpenMP confusion). Only "recent" ones do. So we would have to decide whether the earliest compatible version is sufficiently old for us to make the switch.

**Comment by davydden** [comment]
> us to make the switch.

to clarify, I did not mean to switch, but rather provide an alternative so that if one uses those third party libraries with OpenMP there will be at least some support of multi-threading within the deal.II. We don't have remove all TBB parts. But of course, it is a pain to support both ;-(

**Comment by bangerth** [comment]
Does anyone know, by the way, whether the C++11 threading and OpenMP threading sub-systems are integrated on typical compilers? In other words, if you create a C++11 task, is it scheduled by the same scheduler as a task you create via OpenMP?

(I would *hope* so, of course, but *knowing* would be better :-) )

**Comment by Rombur** [comment]
@bangerth According to [this](https://stackoverflow.com/questions/13837696/can-i-safely-use-openmp-with-c11/13839719#13839719), it's implementation dependent. There is also this 
```
I asked once a member of the OpenMP ARB and the unofficial response was that interoperability
between OpenMP and any other threading paradigm will probably never make it into the 
specification, but that most vendors will anyway Do The Right Thing (tm) 
```
from [here](https://stackoverflow.com/questions/41309299/mixing-c11-atomics-and-openmp).

**Comment by bangerth** [comment]
I suspected that it's implementation defined, but was mostly wondering what one would see in the wild. The statement you found suggests that the OpenMP threadpool may also be used for C++11 tasks.

**Comment by davydden** [comment]
another PR reminded me about [this observation](https://groups.google.com/d/msg/dealii/Bscoa3OhU28/dHMkNdb3CgAJ) :

> if one is not careful and mixes multithreaded Blas/Lapack + multithreading via TBB in deal.II,
then calls to Lapack's invert() can take 1.371e+03s instead of 1.445e+00s

to clarify, here I did NOT call `openblas` functions from TBB-multithreaded parts of deal.II.

there is also a relevant discussion in [this google forum post](https://groups.google.com/forum/?fromgroups#!searchin/dealii/openblas|sort:date/dealii/wef3v6HVKyo/jMuM3IDDKSkJ) where issues with TBB inside deal.II were due to blas/lapack library.

**Comment by drwells** [comment]
We've done a decent job getting rid of tbb-specific stuff recently so that we can switch to task flow or something else. Are people still interested in considering openMP? If not we should just migrate this discussion into the more general one on future threading.

**Comment by bangerth** [comment]
No, moving from TBB to TaskFlow will move us from homegrown solutions to C++ standards features which are also the basis for compilers' OpenMP implementations. There is no longer a reason to build on OpenMP given that we can do most of what we want with standard C++ and libraries built on it.
