### ISSUE TITLE
Use better names for SIMD widths in vectorization.h

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#7321]
The file `include/deal.II/base/vectorization.h` has this comment:
```
// Note:
// The flag DEAL_II_COMPILER_VECTORIZATION_LEVEL is essentially constructed
// according to the following scheme
// #ifdef __AVX512F__
// #define DEAL_II_COMPILER_VECTORIZATION_LEVEL 3
// #elif defined (__AVX__)
// #define DEAL_II_COMPILER_VECTORIZATION_LEVEL 2
// #elif defined (__SSE2__)
// #define DEAL_II_COMPILER_VECTORIZATION_LEVEL 1
// #else
// #define DEAL_II_COMPILER_VECTORIZATION_LEVEL 0
// #endif
// In addition to checking the flags __AVX__ and __SSE2__, a CMake test,
// 'check_01_cpu_features.cmake', ensures that these feature are not only
// present in the compilation unit but also working properly.
```

This seems outdated with the merge of the Altivec patch #6629.

**Comment by kronbichler** [comment]
It is true that this is outdated, the question is how exactly we want to phrase things. I assume that at some point in the future, we will also have this class for ARM processors (maybe Neon, but very likely at least [SVE](https://community.arm.com/tools/hpc/b/hpc/posts/technology-update-the-scalable-vector-extension-sve-for-the-armv8-a-architecture)), at which point the current description becomes clearly tedious. We saw this by the difficulties @dsambit had with fixing my mess in the `vectorization.h` file. The point is that we need two specifications, one is the width of the vectorization (which we check with the macro `DEAL_II_COMPILER_VECTORIZATION_LEVEL`) and the second one the type of architecture that each has to carry its own specifications (x86, PPC, Armv8-A).

I suggest we we augment the above comment with an including line:
```
The flag DEAL_II_COMPILER_VECTORIZATION_LEVEL specifies the width of the
vector types, with 1 denoting 128 bit, 2 denoting 256 bit, 3 denoting 512 bit, and so
on. On x86 or x86-64 architectures, the flag is essentially constructed according to
the following scheme:
```
We can then add a final sentence that says:
```
Similarly, vectorization with AltiVec (IBM Power) also sets the variable
DEAL_II_COMPILER_VECTORIZATION_LEVEL to 1.
```

Does everybody agree upon this fix or should we look for another solution. I would be happy to also look for other variants regarding the compiler flag - and we need that macro to avoid mixing the architecture specified when configuring deal.II and the architecture when e.g. compiling a user project because 98% of our users will have not clue how debug these things without the error we print in `vectorization.h`.

**Comment by bangerth** [comment]
Couldn't you use the number of bits instead of 1 -> 128, 2 -> 256, ... ? I think that might be easier to understand.

Though I think that's also not exactly what you want. It's conceivable that there is a platform that has 256 bits for 8 floats, but not for 4 doubles. So in essence you'd have to have a 2d grid (one dimension vector length, the other with two entries, float and double) where you record yes/no for support. It would probably be not too awkward to just store this in two flags like you already have, say
```
  DEAL_II_HIGHEST_DOUBLE_VECTORIZATION_LENGTH  (=0, 64, 128, 256, 512, ...)
  DEAL_II_HIGHEST_FLOAT_VECTORIZATION_LENGTH (=0, 64, 128, 256, 512, ...)
```
For MMX, the first would be set to zero, the latter to 64.

But then I'm not really an expert in this area. This may all be besides the point...

**Comment by kronbichler** [comment]
We should make the change in the machinery as suggested in the last comment. But we won't be able to make it for the 9.1 release, so I'm adjusting the target milestone.

**Comment by bangerth** [comment]
@kronbichler @peterrum -- could I put this back on your radar?
