### ISSUE TITLE
copy_triangulation removes limit_level_difference_at_vertices flag

### ISSUE THREAD

**Issue by mwichro** [dealii/dealii#7581]
I noticed that if I do the following:
```
	parallel::distributed::Triangulation<dim>   triangulation(MPI_COMM_WORLD,
	parallel::distributed::Triangulation<dim>::limit_level_difference_at_vertices,
        parallel::distributed::Triangulation<dim>::construct_multigrid_hierarchy);
        Triangulation<dim>  other_tria;
         //do something with other tria
        triangulation.copy_triangulation(other_tria);
	dof_handler_u.distribute_dofs(fe_velocity);
	dof_handler_u.distribute_mg_dofs();
```
I got an error: 
```
An error occurred in line <1275> of file </home/mwichro/lib/dealii/source/dofs/dof_handler.cc> in function
    void dealii::DoFHandler<dim, spacedim>::distribute_mg_dofs() [with int dim = 2; int spacedim = 2]
The violated condition was: 
    ((tria->get_mesh_smoothing() & Triangulation<dim, spacedim>::limit_level_difference_at_vertices) != Triangulation<dim, spacedim>::none)
Additional information: 
    The mesh smoothing requirement 'limit_level_difference_at_vertices' has to be set for using multigrid!
```
This can be fixed by   

Triangulation<dim>  other_tria(Triangulation<dim>::limit_level_difference_at_vertices);

**Comment by bangerth** [comment]
Oh, I only now realize that the error isn't produced during copying, but in `distribute_mg_dofs()`. I see the issue now.

**Comment by bangerth** [comment]
Actually no, I think the error is still reasonable. When you copy a triangulation, you also copy its flags. That's because you may have put stricter requirements when you created the triangulation, but when you copied another triangulation into the current one, you get the mesh as it is regardless of the requirements. So if you want `limit_level_difference_at_vertices` at the destination, you need to set it at the source before copying.

**Comment by masterleinad** [comment]
Ah, I originally thought this problem appeared when copying to a `distributed::Triangulation`.
