### ISSUE TITLE
Update canonical links on homepage

### ISSUE THREAD

**Issue by tamiko** [dealii/dealii#7636]
Independent of #7628 we have to do the following two things with the current documentation:
 - [ ] retroactively run the script on all archived versions of the documentation
 - [ ] create the `/current/` redirection to the currently stable version.

@guidokanschat *ping* :-)

**Comment by dangars** [comment]
@tamiko  and @masterleinad, @bangerth When I google "PETSc deal.ii" I get the documentation of 8.5.0.

I'm not an expert in SEO, but I think that there are several possible reasons.

- Google takes between 4 days and 4 weeks to update the indexation. If there are major changes in the website, it can decide to wait a little bit to re-index.
- The canonical link is a "hint" for google. It can be ignored by Google.
- There is no direct link to https://www.dealii.org/current/ in http://www.dealii.org

I see that there is a tab in www.dealii.org that points to the old versions of the documentation. There is another tab to Dev.

And there is another tab that points to 9.0.0 (current). How about the links in this tab point to https://www.dealii.org/current/ ? The name of the tab can be 9.0.0 or current, but it will point to current instead of 9.0.0. That way people click on https://www.dealii.org/current/ and then it becomes the "main" source of information for deal.ii.

That is my suggestion as _"non-expert"_ in SEO.

**Comment by tjhei** [comment]
the /current/ redirect exists now. I just updated the website header to link to it (under 9.0). I also modified "all versions" a bit.

Give it an hour to update...

**Comment by dangars** [comment]
Thanks @tjhei ! This looks good :)
Just a small typo: Manual should point to https://www.dealii.org/current/doxygen/deal.II/index.html instead of "curent"

**Comment by tjhei** [comment]
fixed!
