### ISSUE TITLE
Implement flexible variant of conjugate gradients

### ISSUE THREAD

**Issue by kronbichler** [dealii/dealii#7723]
As discussed in https://github.com/dealii/dealii/pull/7709#issuecomment-462887959 we want to implement a flexible variant of the conjugate gradient method, which replaces the computation of beta through `z_{k+1}^T r_{k+1} / z_k^T r_k` by the [Polak-Ribiere formula](https://en.wikipedia.org/wiki/Conjugate_gradient_method#The_flexible_preconditioned_conjugate_gradient_method) `z_{k+1}^T (r_{k+1}-r_k) / z_k^T r_k`. The additional term `z_{k+1}^T r_k` will be zero for a constant preconditioner.

Before I start implementing, we should clarify where we want to implement the method as a separate class `SolverFCG`, in analogy to `SolverFGMRES`, or integrate it into `SolverCG` instead. While a user would likely prefer a separate class, we would need to replicate around 200 lines of code. All I need for implementing the flexible variant is one more vector and one more inner product (on the latter I'm not sure if it's really needed yet).

**Comment by tjhei** [comment]
> the flexible variant is one more vector and one more inner product

which means it is too expensive to do this by default.

> Before I start implementing, we should clarify where we want to implement the method as a separate class `SolverFCG`, in analogy to `SolverFGMRES`

I don't have a strong opinion either way, but my vote would be to add an option to SolverCG. The reason is that it is a minor difference in algorithm and we don't need to repeat the mistake (in my opinion) in FGMRES where the two implementations keep diverging over the years.

**Comment by bangerth** [comment]
On 2/13/19 12:15 AM, Martin Kronbichler wrote:
> Before I start implementing, we should clarify where we want to 
> implement the method as a separate class |SolverFCG|, in analogy to 
> |SolverFGMRES|, or integrate it into |SolverCG| instead.
> 

I would have suggested a separate class, but now I'm at odds with Timo 
:-) (The code in these solvers has been outstandingly stable over the 
years, so the code duplication problem is not so severe as in cases 
where we have more turnover and need to remember more that there are 
other places one would need to change in similar ways.)

But it's not something I feel strongly enough about. How much more 
complicated the logic will be is, I think, the question for you to 
answer. If you find that the conditional becomes too complicated to 
read, then use a separate class; otherwise integrate it into the same class.

(You can also re-use the class but duplicate the code of the actual 
iteration into two separate blocks that each look like the textbook 
versions of the two algorithms. Then you won't have to have the |if| 
statement somewhere right in the middle. But you don't need to duplicate 
the whole class.)

**Comment by masterleinad** [comment]
Let's postpone.

**Comment by peterrum** [comment]
@kronbichler Do you still intend to work on this? Or is this issue out of date? At some time, we should move the cache-efficient CG implementation from the CEED benchmark (https://github.com/kronbichler/mf_data_locality) here.

**Comment by kronbichler** [comment]
This should be done at some point because it is a useful feature, especially since it only needs four or five lines of code to do the other operation. The more "difficult" part that prevented this so far is the interface to be decided upon.

**Comment by bangerth** [comment]
Out of curiosity, the "flexible" variant is useful when one has a non-constant preconditioner such as an approximate inverse provided via an iterative solver. Does it also help if the matrix itself is non-constant?

My student @juleoc02 has a problem where he's trying to solve with a matrix of the form `K=BA^{-1}B^T` (actually, much more complex, but this will do for exposition) where `A^{-1}` is provided via an iterative solver. We don't have a preconditioner, and he's finding that it gets very difficult to solve with `K` under certain conditions. We don't know what causes this, but one possibility is that `A^{-1}` done via an iterative solver is just not a constant operator. Would using F-CG help here?

(One could of course then ask "but what matrix are you solving a linear system with anyway if it is not constant" and that's a good question, but you get the idea I assume.)

**Comment by kronbichler** [comment]
> Does it also help if the matrix itself is non-constant?

I would have to check the optimization literature about nonlinear conjugate gradient operations. I would intuitively say that a different form of the residual rather than the incremental update `r = r - alpha * (A * p)` would be necessary, but it might still be worth a try to check the F-CG.
