### ISSUE TITLE
Change name of "Recent changes" header file

### ISSUE THREAD

**Issue by kronbichler** [dealii/dealii#7725]
On the header menu our homepage, we have a link to the "Recent changes" from the "Dev" menu item. This link becomes notoriously broken because it links to something like https://www.dealii.org/developer/doxygen/deal.II/changes_after_9_0_0.html (I hope I fixed by going to `..._9_0_1.html` for now on the homepage svn). How about naming the file we create in `doc/news/changes/header` into something more stable, say `changes_since_last_release.html`? This avoids the burden to also update the homepage html for each release. (We would of course also need to modify the release todo list.)

**Comment by tjhei** [comment]
Makes sense. Just calling it "recent_changes.html" would also be fine.

**Comment by bangerth** [comment]
On 2/13/19 8:33 AM, Timo Heister wrote:
> Makes sense. Just calling it "recent_changes.html" would also be fine.

The problem is that the file name is chosen by doxygen automatically, 
based on the title of the @page construct. So pick something that's 
descriptive but doesn't include a version number. "Changes since the 
last release" seems reasonable. You'll then get some filename, and 
that's the one we're going to use, whatever it is!
