### ISSUE TITLE
Add/augment wiki entry for solver non-convergence

### ISSUE THREAD

**Issue by jppelteret** [dealii/dealii#7759]
There are already some wiki entries in place to deal with solver non-convergence, but none deal with the case when this kind of error is thrown:
```
An error occurred in line <455> of file <../dealii/include/deal.II/lac/solver_cg.h> in function
    void dealii::SolverCG<VectorType>::solve(const MatrixType&, VectorType&, const VectorType&, const PreconditionerType&) [with MatrixType = dealii::SparseMatrix<double>; PreconditionerType = dealii::SparseILU<double>; VectorType = dealii::Vector<double>]
The violated condition was: 
    false
Additional information: 
Iterative method reported convergence failure in step 1000. The residual in the last step was 800.487
```
Questions around this seem to appear sufficiently regularly on the forum to warrant an entry in the FAQ.

**Comment by kronbichler** [comment]
As this is simply a wiki entry, it is not excluded that we might get to it before the release in a week, but I'd still postpone the official date.

**Comment by kronbichler** [comment]
I think we have a pretty verbose error message nowadays, https://github.com/dealii/dealii/blob/0c85fb896c973de0e12a5bd0687a2a9fcf8fa0b7/include/deal.II/lac/solver_control.h#L109-L125
so I think we should close this unless there are volunteers to write even more for the wiki. (To be honest, this text seems to have been present for a long time since 2014 with revision 52e426ac41c43cda5d66e60686d7e8a7f42f375f.)
