### ISSUE TITLE
Teuchos::TimeMonitorSurrogateImpl and code profiling

### ISSUE THREAD

**Issue by davydden** [dealii/dealii#7865]
I was running a code profiling today and noticed a strange thing: inside one of the function which does not use Trilinos at all, `10%` of time was spent (according to macOS's Instruments.app) in `Teuchos::RCP<Teuchos::TimeMonitorSurrogateImpl>::debug_assert_valid_ptr() const`. 
The code is some flavor of matrix-free operator.

I don't use TPetra or Teuchos anywhere, and don't include any headers either. 

Could this be (in any shape or form) related to the recently merge TPetra wrappers? https://github.com/dealii/dealii/pull/7180 
I tried to profile `step-37` and don't see anything similar.

However, If I disable `TPetra` wrappers in deal.II `DEAL_II_TRILINOS_WITH_TPETRA=OFF` the problem is gone and I don't see this function anymore in profiler.

**Comment by Rombur** [comment]
@davydden I don't think that's the real problem because if you look [here](https://trilinos.org/docs/r12.4/packages/teuchos/browser/doc/html/Teuchos__Ptr_8hpp_source.html#l00164) at line 164 you see that in release mode the function is a no-op.

**Comment by davydden** [comment]
> in release mode the function is a no-op.

I certainly profile in `release` build of my project, but `TEUCHOS_DEBUG` might still be `true` for some reason.

I still not a bit fun of those functions appearing in the user code without being explicitly asked for, even if they are supposed to be harmless in `release` mode.

**Comment by Rombur** [comment]
But you do need to enable the timer monitor explicitly: see [here](https://github.com/trilinos/Trilinos/blob/a568a4b232cbf4346c645178358bd13c154b5d5c/cmake/tribits/core/package_arch/TribitsPackageMacros.cmake#L490). I think that the problem is from your profiler. How can a function that you need to enable explicitly **and** is a no-op can appear in your profiling.

**Comment by davydden** [comment]
> I think that the problem is from your profiler. How can a function that you need to enable explicitly and is a no-op can appear in your profiling.

I have absolutely no idea, but I do NOT enable it anyhow. But I also don't see how it could be a problem of profiler, it can't simply dream up this function, right?

**Comment by Rombur** [comment]
> But I also don't see how it could be a problem of profiler, it can't simply dream up this function, right?

Do you have more than one version of Trilinos installed on your machine? Maybe it's the optimization step that changes the code too much of the optimizer and you get a random function from Trilinos? You could run your code in gdb and put a breakpoint in the function to see where it is called from.

**Comment by davydden** [comment]
> Do you have more than one version of Trilinos installed on your machine?

yes, but they are in a separate prefixes (via Spack), so there is now way I mix them accidentally.

> You could run your code in gdb and put a breakpoint in the function to see where it is called from.

I will check this a bit later...

**Comment by bangerth** [comment]
On 3/27/19 12:09 PM, Denis Davydov wrote:
>     You could run your code in gdb and put a breakpoint in the function
>     to see where it is called from.
> 
> I will check this a bit later...

Or check in your profiler whether it shows you where that function was 
called from. It may be running on a background thread, and you'd have to 
find out where that thread was created.

**Comment by kronbichler** [comment]
> I have absolutely no idea, but I do NOT enable it anyhow. But I also don't see how it could be a problem of profiler, it can't simply dream up this function, right?

In release mode, this often not entirely obvious for the compiler to which code line a certain assembly code line should be link. So, after a series of optimization steps (where the compiler might do common subexpression elimination, just to name one of several dozens of candidates), the compiler might have lost track of where all those common expressions came from, so it ends up in a random place.

I've seen a series of similar problems with Intel Advisor over the last years - the only way to understand whether this is a real problem is to 
(a) look at the assembler code - does anything unexpected appear (which might be hard if you don't read assembler), and/or
(b) check whether actual timings change when you enable/disable tpetra -> if only within the usual 1-2% noise, then it is just a matter of the compiler messing up the line annotations of the debug/profiling information.

**Comment by davydden** [comment]
thanks for explanation, @kronbichler . I will have a closer look...

**Comment by davydden** [comment]
looks like it was a false[1] alarm, apologies for the noise. I rebuilt deal.II with `-g` in `release` flags:
```
-DCMAKE_CXX_FLAGS="-march=native" -DCMAKE_CXX_FLAGS_RELEASE="-O3 -ffp-contract=fast -g"
```
run through profiler to see what's happening and did not see TimeMonitorSurrogateImpl anymore.

[1] I was upgrading the software stack and also bumped the Trilinos version, there is a very little chance that this was the reason. But I don't have neither time nor will to investigate this any further as the issue is gone.
