### ISSUE TITLE
get_mg_dof_indices is deprecated?

### ISSUE THREAD

**Issue by davydden** [dealii/dealii#7887]
noticed that `cell->get_mg_dof_indices()` is deprecated in https://github.com/dealii/dealii/pull/7554, but for what? Maybe we should point users in documentation to the right one to use. It's also used internally, btw.

**Comment by masterleinad** [comment]
The [documentation](https://www.dealii.org/developer/doxygen/deal.II/classDoFCellAccessor.html#ab50a7eaa607d7b075cd4d04a9437980a) says:
> Deprecated:
    Use get_active_or_mg_dof_indices() with level_cell_iterator returned from begin_mg().

and
> It is highly recommended to use the function get_active_or_mg_dof_indices() in generic loops in lieu of get_dof_indices() or get_mg_dof_indices().

**Comment by kronbichler** [comment]
The point where I am with @davydden is the fact that we make internal use of this variable at a number of places where it would be a bit annoying to let the iterator decide about it and then  `get_active_or_mg_dof_indices()` do the right thing. While I see the value in terms of generic iterator programming, it bites us at some places because we do not consequentially use iterators only. Take for example this one: https://www.dealii.org/developer/doxygen/deal.II/classMatrixFree.html#a5e7db9ef51c24f2796c70caec8718c74 
It can return an active or a level dof iterator depending on a parameter we set, and there is no way to use two different return types within the same function. In the best of places, we would make the state `level` vs `active` a boolean variable rather than a template argument. But that ship has sailed.

**Comment by davydden** [comment]
@masterleinad 

oh, i guess i confused it with https://www.dealii.org/developer/doxygen/deal.II/classDoFAccessor.html#a6f41994037037a54e116d0b0815d166e

sorry about this.

**Comment by tjhei** [comment]
> The point where I am with @davydden is the fact that we make internal use of this variable at a number of places where it would be a bit annoying to let the iterator decide about it

Yeah, I stumbled on this in one of the applications. I like to express the fact that I am grabbing level dofs but I am no longer allowed to do so. :-(
