### ISSUE TITLE
Bug in rectangular TrilinosWrappers::SparseMatrix

### ISSUE THREAD

**Issue by Rombur** [dealii/dealii#7904]
It looks to me that there is a bug in `TrilinosWrappers::SparseMatrix`. When we use two `IndexSet` to create a sparse matrix, it looks to me that one of the `IndexSet` is never used. See [here](https://github.com/dealii/dealii/blob/master/source/lac/trilinos_sparse_matrix.cc#L250) where `column_space_map` is not passed to the constructor of the Epetra matrix and so we are creating a square matrix.

**Comment by tjhei** [comment]
it looks weird, yes.
But you probably are calling https://github.com/dealii/dealii/blob/master/source/lac/trilinos_sparse_matrix.cc#L366 right?
So then there seems to be a missing third argument for the column space map:
https://trilinos.org/docs/dev/packages/epetra/doc/html/classEpetra__FECrsMatrix.html#a5db6dcfbb015559ea1c9674e3eb41f5e

**Comment by kronbichler** [comment]
> When we use two `IndexSet` to create a sparse matrix, it looks to me that one of the `IndexSet` is never used.

It is used [here](https://github.com/dealii/dealii/blob/master/source/lac/trilinos_sparse_matrix.cc#L1220) and [here](https://github.com/dealii/dealii/blob/master/source/lac/trilinos_sparse_matrix.cc#L1225). What we denote as the 'colum space map' is actually the domain map, i.e., the map of the vectors the matrix is to be multiplied with. What we call the 'row map' is range map, i.e., the map of the vectors that come out from a matrix-vector product. The matrices themselves have rows and columns partitioned differently (this is what you set in the constructor of `Epetra_CrsMatrix`). Now we use the same row partitioning as range vector partitioning (so the matrix rows and vector rows are distributed the same), but of course you cannot set a 1:1 map for the columns because that would eliminate any overlap between processors. So when you only set one map for the `Epetra_CrsMatrix`, you only specify the row map (which is later found to be identical to the range map) and leave the column map open. It is determined inside `FillComplete` from the entries in the the rows of the matrix. The relation between the domain map and the column map (in the Trilinos speak, not in our slight misuse of the term) determines what ghost exchange is done.

**Comment by kronbichler** [comment]
Feel free to re-open in case there is something that does not work as expected - but the current issue is what it is by design.

**Comment by Rombur** [comment]
Thanks for the explanation.
