### ISSUE TITLE
Possible issue with `constraints.reinit(locally_relevant_dofs);`

### ISSUE THREAD

**Issue by jppelteret** [dealii/dealii#8028]
Maybe I misused `constraints.reinit(locally_relevant_dofs);`, but I think that there might be a bug related to this. In the call to `AffineConstraints::distribute_local_to_global` I hit this error
```
An error occurred in line <1745> of file <path/dealii/include/deal.II/lac/affine_constraints.h> in function
    size_type dealii::AffineConstraints<double>::calculate_line_index(const size_type) const [number = double]
The violated condition was:
    local_lines.is_element(line_n)
Additional information:
    The index set given to this constraints object indicates constraints for degree of freedom 0 should not be stored by this object, but a constraint is being added.
```
for this very simple problem.
```c++
#include <deal.II/base/function.h>
#include <deal.II/base/index_set.h>
#include <deal.II/base/quadrature_lib.h>

#include <deal.II/distributed/tria.h>

#include <deal.II/dofs/dof_tools.h>

#include <deal.II/fe/fe_q.h>

#include <deal.II/grid/grid_generator.h>

#include <deal.II/meshworker/copy_data.h>
#include <deal.II/meshworker/mesh_loop.h>
#include <deal.II/meshworker/scratch_data.h>

#include <deal.II/lac/affine_constraints.h>
#include <deal.II/lac/dynamic_sparsity_pattern.h>

#include <deal.II/numerics/vector_tools.h>

#include <deal.II/lac/trilinos_precondition.h>
#include <deal.II/lac/trilinos_sparse_matrix.h>
#include <deal.II/lac/trilinos_vector.h>

using namespace dealii;


int
main(int argc, char *argv[])
{
  constexpr int dim = 2;
  constexpr int spacedim = 2;
  constexpr unsigned int fe_degree = 1;

  Utilities::MPI::MPI_InitFinalize mpi_initialization(argc, argv);
  MPI_Comm mpi_communicator (MPI_COMM_WORLD);

  const FE_Q<dim, spacedim> fe(fe_degree);
  const QGauss<dim>         cell_quadrature(fe.degree+1);

  parallel::distributed::Triangulation<dim, spacedim> tria (mpi_communicator);
  DoFHandler<dim, spacedim> dof_handler(tria);

  const ZeroFunction<spacedim> boundary_function;

  AffineConstraints<double> constraints;
  TrilinosWrappers::MPI::Vector locally_relevant_solution;

  IndexSet locally_owned_dofs;
  IndexSet locally_relevant_dofs;

  GridGenerator::hyper_L(tria);
  tria.refine_global(1);

  dof_handler.distribute_dofs(fe);

  locally_owned_dofs = dof_handler.locally_owned_dofs();
  DoFTools::extract_locally_relevant_dofs(dof_handler, locally_relevant_dofs);

  constraints.clear();
  constraints.reinit(locally_relevant_dofs);
  DoFTools::make_hanging_node_constraints(dof_handler, constraints);
  VectorTools::interpolate_boundary_values(dof_handler,
                                           0,
                                           boundary_function,
                                           constraints);

  constraints.close();

  TrilinosWrappers::SparseMatrix system_matrix;
  {
    DynamicSparsityPattern dsp(locally_relevant_dofs);

    DoFTools::make_sparsity_pattern(dof_handler, dsp, constraints, false);
    SparsityTools::distribute_sparsity_pattern(
      dsp,
      dof_handler.n_locally_owned_dofs_per_processor(),
      mpi_communicator,
      locally_relevant_dofs);

    system_matrix.reinit(locally_owned_dofs,
                         locally_owned_dofs,
                         dsp,
                         mpi_communicator);
  }

  TrilinosWrappers::MPI::Vector system_rhs(locally_owned_dofs, mpi_communicator);

  const UpdateFlags cell_flags = update_default;

  using ScratchData = MeshWorker::ScratchData<dim, spacedim>;
  using CopyData    = MeshWorker::CopyData<1, 1, 1>;
  using Iterator = decltype(dof_handler.begin_active());

  ScratchData scratch(fe, cell_quadrature, cell_flags);
  CopyData    copy(fe.dofs_per_cell);

  auto cell_worker =
    [](const Iterator &cell, ScratchData &scratch_data, CopyData &copy_data) {
      scratch_data.reinit(cell);
      copy_data = 0;
      copy_data.local_dof_indices[0] = scratch_data.get_local_dof_indices();
    };

  auto copier = [&constraints, &system_matrix, &system_rhs](const CopyData &copy_data) {
    constraints.distribute_local_to_global(
      copy_data.matrices[0], copy_data.vectors[0], 
      copy_data.local_dof_indices[0], 
      system_matrix, system_rhs);
  };

  MeshWorker::mesh_loop(dof_handler.active_cell_iterators(), cell_worker, 
                        copier, scratch, copy, 
                        MeshWorker::assemble_own_cells);

  system_matrix.compress(VectorOperation::add);
  system_rhs.compress(VectorOperation::add);
}
```

I believe that I duplicated all of the relevant parts correctly from `step-40`. Is this a bug or have I done something wrong? Removing the line `constraints.reinit(locally_relevant_dofs);` alleviates the problem, but as discussed in `step-40` this is not the ideal solution.

**Comment by jppelteret** [comment]
This has been a case of user error. I forgot to limit `mesh_loop()` to only locally owned cells:
```
    const auto filtered_iterator_range =
      filter_iterators(dof_handler.active_cell_iterators(),
                       IteratorFilters::LocallyOwnedCell());

    MeshWorker::mesh_loop(filtered_iterator_range, cell_worker, 
                          copier, scratch, copy, 
                          MeshWorker::assemble_own_cells);
```

**Comment by tjhei** [comment]
wait, I guess ``assemble_own_cells`` will not trigger the ``cell_action`` but still call the copier, right? I don't see a reason for calling the copier for cases where we don't do anything. Should I submit a PR?

**Comment by jppelteret** [comment]
Yes, that would be great thanks!

**Comment by tjhei** [comment]
Well, it is not that simple as we can not communicate to the copier if works needs to be done. One way is to do this (see the lines I marked):
```
#include <deal.II/base/function.h>
#include <deal.II/base/index_set.h>
#include <deal.II/base/quadrature_lib.h>

#include <deal.II/distributed/tria.h>

#include <deal.II/dofs/dof_tools.h>

#include <deal.II/fe/fe_q.h>

#include <deal.II/grid/grid_generator.h>

#include <deal.II/meshworker/copy_data.h>
#include <deal.II/meshworker/mesh_loop.h>
#include <deal.II/meshworker/scratch_data.h>

#include <deal.II/lac/affine_constraints.h>
#include <deal.II/lac/dynamic_sparsity_pattern.h>

#include <deal.II/numerics/vector_tools.h>

#include <deal.II/lac/trilinos_precondition.h>
#include <deal.II/lac/trilinos_sparse_matrix.h>
#include <deal.II/lac/trilinos_vector.h>

using namespace dealii;


int
main(int argc, char *argv[])
{
  constexpr int dim = 2;
  constexpr int spacedim = 2;
  constexpr unsigned int fe_degree = 1;

  Utilities::MPI::MPI_InitFinalize mpi_initialization(argc, argv);
  MPI_Comm mpi_communicator (MPI_COMM_WORLD);

  const FE_Q<dim, spacedim> fe(fe_degree);
  const QGauss<dim>         cell_quadrature(fe.degree+1);

  parallel::distributed::Triangulation<dim, spacedim> tria (mpi_communicator);
  DoFHandler<dim, spacedim> dof_handler(tria);

  const ZeroFunction<spacedim> boundary_function;

  AffineConstraints<double> constraints;
  TrilinosWrappers::MPI::Vector locally_relevant_solution;

  IndexSet locally_owned_dofs;
  IndexSet locally_relevant_dofs;

  GridGenerator::hyper_L(tria);
  tria.refine_global(1);

  dof_handler.distribute_dofs(fe);

  locally_owned_dofs = dof_handler.locally_owned_dofs();
  DoFTools::extract_locally_relevant_dofs(dof_handler, locally_relevant_dofs);

  constraints.clear();
  constraints.reinit(locally_relevant_dofs);
  DoFTools::make_hanging_node_constraints(dof_handler, constraints);
  VectorTools::interpolate_boundary_values(dof_handler,
                                           0,
                                           boundary_function,
                                           constraints);

  constraints.close();

  TrilinosWrappers::SparseMatrix system_matrix;
  {
    DynamicSparsityPattern dsp(locally_relevant_dofs);

    DoFTools::make_sparsity_pattern(dof_handler, dsp, constraints, false);
    SparsityTools::distribute_sparsity_pattern(
      dsp,
      dof_handler.n_locally_owned_dofs_per_processor(),
      mpi_communicator,
      locally_relevant_dofs);

    system_matrix.reinit(locally_owned_dofs,
                         locally_owned_dofs,
                         dsp,
                         mpi_communicator);
  }

  TrilinosWrappers::MPI::Vector system_rhs(locally_owned_dofs, mpi_communicator);

  const UpdateFlags cell_flags = update_default;

  using ScratchData = MeshWorker::ScratchData<dim, spacedim>;
  using CopyData    = MeshWorker::CopyData<1, 1, 1>;
  using Iterator = decltype(dof_handler.begin_active());

  ScratchData scratch(fe, cell_quadrature, cell_flags);
  CopyData    copy(fe.dofs_per_cell);
  copy.local_dof_indices[0].clear(); // ****  

  auto cell_worker =
    [](const Iterator &cell, ScratchData &scratch_data, CopyData &copy_data) {
      scratch_data.reinit(cell);
      copy_data = 0;
      copy_data.local_dof_indices[0] = scratch_data.get_local_dof_indices();
    };

  auto copier = [&constraints, &system_matrix, &system_rhs](const CopyData &copy_data) {
	if (copy_data.local_dof_indices[0].size()) // ****
	constraints.distribute_local_to_global(
	  copy_data.matrices[0], copy_data.vectors[0], 
	  copy_data.local_dof_indices[0], 
	  system_matrix, system_rhs);
  };

  MeshWorker::mesh_loop(dof_handler.active_cell_iterators(), cell_worker, 
                        copier, scratch, copy, 
                        MeshWorker::assemble_own_cells);

  system_matrix.compress(VectorOperation::add);
  system_rhs.compress(VectorOperation::add);
}
```

**Comment by tjhei** [comment]
@luca-heltai do you have a suggestion here? I think having an invalid copy object is not a bad idea because you will crash instead of operating on wrong data.
The problem is that we can not tell inside the copier if the worker is skipping this cell.

**Comment by luca-heltai** [comment]
Mmmm... maybe it is safer to check wether the cell is locally owned internally in mesh loop? We are assuming the user is educated to this, but we may just as well add a (maybe reduntant?) check that we only assemble on locally owned cells, rather than trying hard to invalidate workier/copier...

**Comment by tjhei** [comment]
> wether the cell is locally owned internally in mesh loop?

We do this check for the cell worker (based on the flags the user specifies). The logic when to run the copier is more complicated (it is needed when the cell has a face we own even if the cell is not locally owned etc.), so we currently do it in every situation.

We could replicate the whole logic (check cell and face owners/flags) before calling the user's copier, but I wonder if this is a bit too complicated. If you think this is the right way to go, I can make a PR for that.

> rather than trying hard to invalidate workier/copier...

You don't need to invalidate the worker, just defer allocation to when it is used rather than allocating before the call to mesh_loop.

**Comment by luca-heltai** [comment]
> We could replicate the whole logic (check cell and face owners/flags) before calling the user's copier, but I wonder if this is a bit too complicated. If you think this is the right way to go, I can make a PR for that.

How about setting a flag whenever any type of work has been done (and checking that flag later before actually calling the copier?)

**Comment by tjhei** [comment]
> How about setting a flag whenever any type of work has been done

This would need to be stored somewhere in the copy data, right? This is currently a template type so we can't add a bool without wrapping it in another type (again: possible but complicated).

**Comment by luca-heltai** [comment]
> This would need to be stored somewhere in the copy data, right? This is currently a template type so we can't add a bool without wrapping it in another type (again: possible but complicated).

I mean a temporary boolean in mesh_loop. Why should it be stored in the copy data? It is the user's responsability to do whatever they need to do with worker and copier, we should not force an interface to these, except for the calling signature.

`mesh_loop` knows if at least one worker (be it face or cell, or boundary worker) has been called, and it should only call the copier if at least one worker was called. With this check, the problem above would not have appeared, since no worker at all would have been called, and therefore also the copier would not have been called.

**Comment by tjhei** [comment]
> I mean a temporary boolean in mesh_loop. Why should it be stored in the copy data? It is the user's responsability to do whatever they need to do with worker and copier, we should not force an interface to these, except for the calling signature.

I am not sure how that would work, sorry. You would need a boolean for each cell, or not? That means you need to store this in the copy_data.
For the example above, the problem is that we run the copier also for non-owned cells but work only on owned cells.

**Comment by bangerth** [comment]
Let me try to understand this: We call the worker on a cell where it decides to not do anything and leaves the `CopyData` object unchanged, then we call the copier which doesn't know that nothing has changed and ends up copying the *old* contents of the `CopyData` object into the global matrix a second/third/... time. This is clearly a bug.

I think this could be solved by passing a flag to the copier that indicates whether a worker has been called at all for this cell. One could of course put such a flag into the `CopyData` object, but the easier way to do this would be to simply pass it as a separate argument to the `worker` function, in addition to the `const CopyData` reference. (To make this work with `WorkStream` requires one additional level of lambda functions that unpack things because `WorkStream`'s copier takes only one argument -- but that can easily be done.)

But the underlying question you are all skirting is that it is easily conceivable that a `worker` function decides to not do any work on a given cell -- because it's an artificial/ghost cell, or because of any other reason (for example because it's not at the boundary and we're only integrating boundary terms). This is not something we can foresee in the library, nor test. The only solution is to document (and implement in our examples) that if a `worker` decides not to to anything on a cell, then it needs to do one of the following two things: (i) pass this kind of information on to the `copier` so that the latter also knows not to do anything; or (ii) that the `worker` sets the `CopyData` object to the neutral element of the operation the `copier` implements -- which generally would be to set all local matrices and vectors to zero so that the addition that the `copier` performs is a no-op.

If `MeshWorker::run()` decides for a cell not to run the worker, then it should also not run the copier because in that case the worker has no opportunity to do either (i) or (ii) above.

**Comment by tjhei** [comment]
> We call the worker on a cell where it decides to not do anything and leaves the `CopyData` object unchanged, then we call the copier which doesn't know that nothing has changed and ends up copying the _old_ contents of the `CopyData` object into the global matrix a second/third/... time. This is clearly a bug.

No. We have a cell that is not locally owned that is in the iterator range (in the example above we pass active_cell_iterators()). The flag ``assemble_own_cells`` means that we do not call the worker but the current code will call the copier.
We also do not run the copier with "old contents" but with the default data. This is zeroed out in the example above (but distribute_local_to_global still tries to copy the zero entries into non-local rows and crashed).


> If `MeshWorker::run()` decides for a cell not to run the worker, then it should also not run the copier because in that case the worker has no opportunity to do either (i) or (ii) above.

We set the copy data to the default, so the copier can do (ii). See my "solution" in the code I posted above (check if ``local_dof_indices`` is empty).

**Comment by tjhei** [comment]
> . (To make this work with `WorkStream` requires one additional level of lambda functions that unpack things because `WorkStream`'s copier takes only one argument -- but that can easily be done.)

I would think one would need to create a new ``CopyData`` type that contains a bool and the user's CopyData and then call the user's copy function with her data if the bool says that we need to call it. Or is there a more clever way to do this?

**Comment by tjhei** [comment]
I see the following options:
1. Store a bool per cell (in a new CopyData object) and call the worker only if work was done.
2. Let the user deal with this in the copier by detecting the default state. This means ``MeshWorker::CopyData<1, 1, 1>;`` should be adjusted to not allocate data (see my example above).
3. Ignore the problem and let users specify an appropriate iterator range (see comment with the "fix" from JP above)

I don't have any experience with the ``MeshWorker::CopyData<1, 1, 1>;``  but I assume that some logic to determine if work on faces/cells was done is needed anyways for it to be useful.  I don't find any example in the tests that actually assembles cell/face terms using these objects in parallel (summing a scalar does of course work, as you can do +=0). But I admit that I also haven't tried to use it. The problem is that I expect them to be impossible to use if you have face terms in parallel (and you do real assembly, not just summing up a scalar).

**Comment by bangerth** [comment]
On 5/7/19 3:01 PM, Timo Heister wrote:
> I would think one would need to create a new |CopyData| type that 
> contains a bool and the user's CopyData and then call the user's copy 
> function with her data if the bool says that we need to call it. Or is 
> there a more clever way to do this?

This new type is `std::pair<bool, CopyData>`. That's in essence what I 
had in mind.

**Comment by tjhei** [comment]
> That's in essence what I had in mind.

ah, okay then. This is doable, but I don't think it is super useful in the general case (you can have cell terms on some cells and face terms on other cells) unless we give several flags to the user...

**Comment by luca-heltai** [comment]
```
for(auto cell: iterators) {
  bool work_was_done = false;
  if(condition_on_cell_is_met) {
     work_was_done = true;
     cell_worker();
 } 
 for(face...) {
    if(condition_on_face_is_met) {
       work_was_done = true;
       face_worker();
    }
   ....
   if(work_was_done)
     copier();
```

**Comment by luca-heltai** [comment]
I think that we should not try to be too smart. In practice `mesh_loop` was designed to make things easier for assembling in parallel, and in general you need to know what you are doing, and there is no easy recipy for that. 

My two cents would be to simply enforce that workstream is called with a filtered iterator internally in `mesh_loop` (which was my original suggestion, but I guess I did not explained it too clearly), unless the user specifically asks to make work on not owned cells. 

The only thing that we could do to make life sligthly easier is this:

- do we need to work on not owned cells? call workstream with the input range
- we don't? call workstream with a filtered iterator ourselves

The user must be aware of what he is asking the worker and the copier to do, and he should make sure that things are done properly. I don't think we should do anything else here.

**Comment by luca-heltai** [comment]
The reason why I'm saying this, is because mesh_loop is not thought to work only with CopyData<n1, n2, n3>, but with any copydata, and, *by design*, all work is done first on the cell, its faces, and its boundary faces (with the same copydata), and then the copier is called.

Maybe we should simply document this better, and let the user choose their own path.

**Comment by jppelteret** [comment]
After reading through @luca-heltai's explanation, I agree that simply explaining things a bit better and perhaps giving a small code example for the `p::d::Tria` case might be the easiest solution here. I was a bit surprised that the copier is called since a _light browse_ through the code suggested that everything was already filtered with some `locally_owned` flag or something like that. That said, I put my hands up again and remind everyone that this was a silly mistake on my part (at least, I feel that this is). I've open up #8053 to give some examples on when to use filtered iterators for locally owned cells.
