### ISSUE TITLE
Provide some documentation for package maintainers

### ISSUE THREAD

**Issue by tamiko** [dealii/dealii#8292]
We should document some packaging best practices and configuration nobs to make it easier to package deal.II for various *nix distributions.

In reference to #8290, #8291

**Comment by drwells** [comment]
I just fixed some issues with the deal.II AUR package. I am writing down my changes here so that we don't have to look this up again later.

deal.II will install a bunch of files that don't belong in `/usr/`, so the `PKGBUILD` file deletes them:
```
  rm "${pkgdir}/${installation_prefix}/LICENSE.md"
  rm "${pkgdir}/${installation_prefix}/README.md"
  rm "${pkgdir}/${installation_prefix}/detailed.log"
  rm "${pkgdir}/${installation_prefix}/summary.log"
```
`LICENSE.md` should be installed in the correct place for the distribution instead:
```
  install -D -m644 "${srcdir}/${_realname}-$pkgver/LICENSE.md" "${pkgdir}/usr/share/licenses/${_realname}-$pkgver/LICENSE.md"
```

**Comment by drwells** [comment]
Other suggestions: 
- the configuration flag `-DDEAL_II_WITH_64BIT_INDICES` should match whatever PETSc does
- the bundled packages should be disabled via `-DDEAL_II_ALLOW_BUNDLED=OFF`
- deal.II sets its own flags in debug and optimized mode with GCC, clang, intel, and MSVC that are reasonable and usually don't need to be altered
- underlinkage with GSL may be a problem (it is on Arch Linux)
