### ISSUE TITLE
Current master has compilation errors related to constexpr in tensor.h

### ISSUE THREAD

**Issue by tcclevenger** [dealii/dealii#8387]
When trying to compile on the palmetto cluster in Clemson I have come across the following errors when trying to compile the current master version: 

_required from here
/home/tcleven/deal-git/dealii/include/deal.II/base/tensor.h:1933:5: error: uninitialized variable ‘result’ in ‘constexpr’ function
     result;
     ^~~~~~

This same error occurs in many places. 

It should be noted:
DEAL_II_WITH_CXX14 = ON
DEAL_II_WITH_CXX17 = OFF 
I'm attaching the detailed.log. Let me know if you need any other information from me.
[detailed.log](https://github.com/dealii/dealii/files/3398921/detailed.log)

**Comment by masterleinad** [comment]
Can you print the complete error message? `Tensor` should have a default constructor that initializes it.

**Comment by rezarastak** [comment]
I think the error comes from this:

If `Number = OtherNumber = VectorizedArray<double>` and `rank_1 == rank_2 == 1` then the complicated type for `result`
```c++
typename Tensor<rank_1 + rank_2 - 2, dim,
                   typename ProductType<Number, OtherNumber>::type>::tensor_type
= typename Tensor<0, dim, VectorizedArray<double> >::tensor_type
```
simplifies to `VectorizedArray<double>` which doesn't have a default constructor. The compiler should not give this error because we never call `Operator*` with `Number = OtherNumber = VectorizedArray<double>` in constexpr context. So it should be fine with an uninitialized value for result. But this specific compiler has a different idea.

**Comment by tcclevenger** [comment]
Here is the full error output:
[error.log](https://github.com/dealii/dealii/files/3399250/error.log)

**Comment by masterleinad** [comment]
Can you try
```
 typename Tensor<rank_1 + rank_2 - 2,
                   dim,
                   typename ProductType<Number, OtherNumber>::type>::tensor_type
  result {};
```
?
instead of
```
 typename Tensor<rank_1 + rank_2 - 2,
                   dim,
                   typename ProductType<Number, OtherNumber>::type>::tensor_type
  result;
```

**Comment by tcclevenger** [comment]
This worked. I created a pull request here: https://github.com/dealii/dealii/pull/8388

**Comment by bangerth** [comment]
These fixes make me uncomfortable. We can fix this in the library, but we can't rely on users doing this in their codes and surely someone will get an incredibly difficult to track down bug into their codes because they don't initialize their local variables *explicitly* -- which we don't require to do for any other type.

I'd very much rather we find a way to coerce the compiler to make sure everything is initialized. Do we know why this isn't done?

**Comment by kronbichler** [comment]
I guess we should add the constructor from `Number` to `VectorizedArray<Number>` which would have avoided the problem. (But skip the default initialization of the members, so we do not pay a price unless the conversion `Number` -> `VectorizedArray<Number>` is requested explicitly.) This really makes `VectorizedArray<double>` more compatible with `double` and we agreed that we do not need the strict POD property.

**Comment by masterleinad** [comment]
Actually, the problem was with `double` and not with `VectorizedArray<double>`. There is not all that much we can do about that. https://godbolt.org/z/MosCJb

**Comment by masterleinad** [comment]
> These fixes make me uncomfortable. We can fix this in the library, but we can't rely on users doing this in their codes and surely someone will get an incredibly difficult to track down bug into their codes because they don't initialize their local variables _explicitly_ -- which we don't require to do for any other type.

This problem only appears in `constexpr` functions and the error message is pretty straight forward, isn't it? I am just surprised that we didn't see this problem with other compilers.

**Comment by bangerth** [comment]
@masterleinad :
I think I'm not clear what exactly is happening. Are you saying that the variable is only uninitialized if we are in a `constexpr` function, whereas the variable would be initialized properly if it was a non-`constexpr` function? In other words, that whether or not a variable is initialized depends on what kind of function we have? If that were the case, there is indeed no problem because we would get this kind of error whenever we forget the initializer.

Or is it the case that the variable is *always* uninitialized, but that this is only an error if we are in a `constexpr` function? (While it is allowed, although not useful, if we are in a regular function.) This would be dangerous.

I would be surprised if the first was the case. C++ is pretty generally consistent in determining initialization based on the kind of type and the constructors it has. It would surprise me if initialization depends on the *context* in which a variable appears.

**Comment by masterleinad** [comment]
> Or is it the case that the variable is _always_ uninitialized, but that this is only an error if we are in a `constexpr` function? (While it is allowed, although not useful, if we are in a regular function.) This would be dangerous.

This. All variables need to be initialized **in their constructors** in `constexpr` functions. Value initialization is fine, though, and this is what we're doing in #8388. Thus, the problem we were seeing here is not specific to `VectorizedArray` but related to all types that are not initialized in the constructor, like `int` and `double` and other fundamental types. 

Why do you say that this is dangerous?

**Comment by bangerth** [comment]
It's dangerous because we should now go through all of the places where we use `VectorizedArray` and make sure that these variables are indeed value-initialized -- which I understand was not necessary. This includes all of the places where the name `VectorizedArray` isn't spelled out, but is a template argument.

Or are you saying that `VectorizedArray` was never initialized in the constructor, and that we just never heard about this because that was fine with the compiler?

**Comment by masterleinad** [comment]
> Or are you saying that `VectorizedArray` was never initialized in the constructor, and that we just never heard about this because that was fine with the compiler?

This. The error message here explicitly mentioned `double` and not `VectorizedArray<double>` (although both of them don't initialize the represented value when default-initialized).
We should see all the places where we use such types in `constexpr` functions already. It doesn't matter if they are used in a `constexpr` context or not.

**Comment by bangerth** [comment]
I see. Thanks for the clarification.

**Comment by tcclevenger** [comment]
Update: I ran across this same issue again. My solution in my own code was to add `{}` after `result` in lines 1908 and 2116 of the current include/base/tensor.h in master. I am not sure if this is how you guys want it to be fix, let me know if this works and I can make a pull request.

**Comment by masterleinad** [comment]
See https://github.com/dealii/dealii/pull/8474.

**Comment by masterleinad** [comment]
It seems that I missed one spot over there, so I just pushed some more value initializations. We could of course also split that pull request up.

**Comment by tcclevenger** [comment]
Thanks @masterleinad! I'm now compiling error free on that cluster.
