### ISSUE TITLE
Too many inline functions in trilinos_sparse_matrix.h

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#853]
There are a lot of inline functions at the bottom of trilinos_sparse_matrix.h -- many of which do expensive stuff such as matrix-vector products, for which inlining certainly isn't going to help much. Many of these functions should, IMHO, move to the .cc file.

**Comment by tamiko** [comment]
> for which inlining certainly isn't going to help much. 

Or, for which inlining is certainly not happening :-]

**Comment by kronbichler** [comment]
>Or, for which inlining is certainly not happening :-]

I agree on the case for the functions `SparseMatrix::set` and `SparseMatrix::add` that both span more than 100 lines. The reason they are inline is because these used to be reasonably small (and performance-sensitive) methods back in 2008, but they have grown way beyond the point where inlining would make any sense. Also, basically all former bottlenecks have been removed when I rewrote `ConstraintMatrix::distribute_local_to_global` in 2009/2010.

Regarding functions with expensive calls such as vmult: The reason they were inline before was that they strated out from a single line of code similar to many other simple but expensive calls such as `linfty_norm()`. They could very well move to the .cc file, but for vmult the slight complication is that it is a template and we need to instantiate it (for `TrilinosWrappers::VectorBase`, `dealii::Vector<double>`, `dealii::parallel::distributed::Vector<double>`). That said, I agree and will open a PR today.

**Comment by bangerth** [comment]
@kronbichler : I didn't mean for you to get to it right away -- more as a reminder to myself. But thanks of course for taking care of it! I think any kind of reduction is already better, no need to go to lengths moving functions for which this would be a major hassle including instantiations etc.

**Comment by kronbichler** [comment]
No problem, I had this on my agenda as well... ;-)
