### ISSUE TITLE
Consider replacing int by uint8_t for all dimension variables

### ISSUE THREAD

**Issue by krishnakumarg1984** [dealii/dealii#8684]
In step-4 of the tutorial program, the benefits of dimension independent coding is very convincingly presented. However, with so much careful attention to `types`, it is a bit surprising that the `dim` parameter is left as a plain old `int`. 

For instance, `dim` cannot be negative nor can it practically be `65535`.  With bare int, there is also compiler/platform dependent ambiguity on the integer size. Considering that fetching from memory is expensive (in the context of the project's viability to potentially reach exascale levels in the future), perhaps we can use
```
#include<cstdint>
uint8_t dim
```
It is reasonable to assume that there is almost no situation where more than 8 unsigned bits (i.e. 255 dimensions) are needed for `dim` (or `spacedim` for that matter).  I cannot quantify the performance gains arising out of this (it might be negligible), but at-least this principle is consistent with making the user think about these things (and it is an easy optimisation). I just express an opinion here; It is absolutely fine if the maintainers of deal.ii choose to disagree with me on this.

**Comment by peterrum** [comment]
I agree that dimension independent coding is a cool feature.

Also, I agree with `int` being an odd type for `dim`. I would rather use `unsigned int`. But changing `int` to any other type (`int8_t` or `unsigned int`) internally would be quite a lot of work (for hardly any performance benefit since dim is in most cases just a template parameter)...

**Comment by krishnakumarg1984** [comment]
@peterrum thank you.

IMHO, `int` should have failed `deal.ii`'s suite of tests, isn't it? Or is there no assertion to test for zero or negative values for `dim` in the test-suite?

**Comment by drwells** [comment]
I think that we have had this discussion in the past but I cannot locate the issue right now. I would appreciate it if someone would find it.

A few quick comments:
1. Since this is a template parameter it is almost always optimized away by the compiler. While I have not checked, I very strongly doubt that changing the numerical type will change the generated code in any way inside hot loops.
2. Changing types has the disadvantage that we can no longer print `dim` and `spacedim` without casts since `uint8_t` is almost always an alias for `char`.
3. `0` is an acceptable value for `dim` in some circumstances (e.g., vertices have `structdim = 0`).

**Comment by Rombur** [comment]
> I think that we have had this discussion in the past but I cannot locate the issue right now.

See here https://github.com/dealii/dealii/issues/2266 The TLDR is that we could change it but nobody had a really good reason why we should.

**Comment by krishnakumarg1984** [comment]
@drwells if not the size_t version, at the least, `dim` and `spacedim` should be `unsigned`. This won't break anything, while logically conveying the idea that these can't be negative.

**Comment by bangerth** [comment]
I am to fault for the choice. I made it back in the summer of 1997 in a pre-decessor set of classes to deal.II. I was young and inexperienced :-)

@drwells summarizes the issue well: `uint8_t` is awkward because it doesn't print well. `unsigned int` would be more appropriate and if we had to redo it today, that's what we would choose. One could write a patch with several 1000 lines that changes things everywhere, but because at the time of compiling the dimension is always a known number, the code that results from the compiler will be exactly the same. In other words, it would be the "right thing to do", but at an effort that has not convinced anyone that it's worth doing.

It might be interesting to see how hard it would actually be if anyone tried to make such a change :-)

**Comment by krishnakumarg1984** [comment]
If it's a simple project-wide `find-and-replace` kind of thing, I am up for the challenge. The task is to 
replace all
`int dim` and `int spacedim`
with 

`unsigned int dim` and `unsigned int spacedim`

right?

**Comment by masterleinad** [comment]
> If it's a simple project-wide `find-and-replace` kind of thing, I am up for the challenge. The task is to replace all `int dim` and `int spacedim` with `unsigned int dim` and `unsigned int spacedim` right?

Yes, and compiling and testing. I would assume that you get a number of warnings of the kind "empty loops don't make sense" for code using loops like
```
for (unsigned int i=0; i<dim; ++i)
{
  ...
}
```
which is pretty annoying.

**Comment by peterrum** [comment]
And comparing `int` with `unsigned int`...

**Comment by drwells** [comment]
We would also have to change template-templates, e.g., `template <int, int> class DoFHandlerType`, forward declarations, etc.; its a very involved change.

**Comment by tjhei** [comment]
> It might be interesting to see how hard it would actually be if anyone tried to make such a change :-)

Is is a _lot_ more involved than replacing "int dim" by "unsigned int dim". 
This also has the potential to break (or at least encourage changes to) every single code written based on deal.II with no advantage, so I am against making this change.

**Comment by krishnakumarg1984** [comment]
Okay, after reading all the insightful comments here, I concur that making any changes has a disproportionately high cost for little technical benefit (apart from a small semantic/logical improvement).  Hence, I am voting to close this issue.

**Comment by drwells** [comment]
Its a good question but I think we have reached a consensus to let it be.
