### ISSUE TITLE
Disagreement between MappingQ and MappingFEField using find_all_active_cells_around_point

### ISSUE THREAD

**Issue by dougshidong** [dealii/dealii#8850]
I am trying to use the GridTools function find_all_active_cells_around_point with a MappingFEField in [this post](https://groups.google.com/d/msg/dealii/8ta3DmMCwsE/EJhfX71qBAAJ) and there is unfortunately some error I can't catch using gdb.

I then wanted to confirm that MappingFEField could be used with that function and created the following test

[find_all_active_cells_around_point_mapping_fe_field_02.zip](https://github.com/dealii/dealii/files/3649948/find_all_active_cells_around_point_mapping_fe_field_02.zip)

This is basically a copy of tests/grid/find_all_active_cells_around_point_02.cc, except that it uses MappingFEField instead of MappingQGeneric. According to the [documentation](https://www.dealii.org/developer/doxygen/deal.II/classMappingFEField.html#a92a567d3e25d60d28bfa8a00ae9e13da), I should get the same results since I am using FE_Q and get_vector_position, so I copied 

output grid/find_all_active_cells_around_point_02.output
to 
grid/find_all_active_cells_around_point_mapping_fe_field_02.output. 

However, I do end up with a few different results.

**Comment by kronbichler** [comment]
I think the culprit is this line here:
https://github.com/dealii/dealii/blob/c87481cc7e6f18f4dd81726262b7144898343964/include/deal.II/numerics/vector_tools.templates.h#L9700
It should be `MappingQGeneric` because `MappingQ` does not curve the inner cells. I am working on a smaller test to reproduce things.
This issue again raises the question that we should make `MappingQ == MappingQGeneric` and remove the strange optimization of applying the linear Q1 mapping on interior cells: curved volume manifolds are widespread in deal.II nowadays, and then using `MappingQ` with degree > 1 on the boundary cells and `MappingQ1` on the cells adjacent to those cells leads to gaps in the grid. The intuition to use `MappingQ` even happens for us experienced developers, so I vote to make the incompatible change of setting the `use_mapping_q_on_all_cells` to `true` as a default here:
https://github.com/dealii/dealii/blob/c87481cc7e6f18f4dd81726262b7144898343964/include/deal.II/fe/mapping_q.h#L103
One must be EXTREMELY cautious when using the `false` case, and I do not think we should make this premature optimization the default.

**Comment by kronbichler** [comment]
I have added a slight variant (lower degree in 3D to keep cost for test suite feasible, running both MappingQGeneric and MappingFEField) to #9827.

**Comment by dougshidong** [comment]
I had forgotten about this issue; it was definitely the MappingQ/MappingQGeneric, I fixed this in my code about 2 weeks ago.

Additionally, the use of MappingQ over MappingQGeneric to initialize MappingFEField offers no advantage since the MappingFEField will be the same high-order degree everywhere, cancelling any cost savings from bi/tri/linear elements.

Thank you for the follow-up.

**Comment by kronbichler** [comment]
I was a bit slow on this, but worked on a related topic (test failure during development) and noticed this problem. It's good to have things fixed, and thanks for the nice test case!

**Comment by bangerth** [comment]
I would not object making `using MappingQ = MappingQGeneric` the default. The `MappingQ` class comes from an era when we did not have manifolds. It should just go.
