### ISSUE TITLE
SegFault in ConsensusAlgorithmProcess::process_request

### ISSUE THREAD

**Issue by tjhei** [dealii/dealii#8929]
I am seeing the following crash (intel 19.0.5 with 1792 MPI ranks and about 2 million DoFs):
```
dealii::Utilities::MPI::ComputeIndexOwner::ConsensusAlgorithmProcess::process_request
[c137-061:30925:0:30925] Caught signal 11 (Segmentation fault: address not mapped to object at address 0x3f116d0)
==== backtrace (tid:  30925) ====
 0 0x000000000a29ccf0 dealii::Utilities::MPI::ComputeIndexOwner::ConsensusAlgorithmProcess::process_request()  ???:0
 1 0x000000000a297d04 dealii::Utilities::MPI::ConsensusAlgorithm_NBX<unsigned int, unsigned int>::process_requests()  ???:0
 2 0x000000000a297259 dealii::Utilities::MPI::ConsensusAlgorithm_NBX<unsigned int, unsigned int>::run()  ???:0
 3 0x000000000a294fb6 dealii::Utilities::MPI::compute_index_owner()  ???:0
 4 0x000000000b7096b2 dealii::internal::MGTransfer::fill_copy_indices<3, 3>()  ???:0
 5 0x000000000b68003c dealii::(anonymous namespace)::fill_internal<3, 3, double>()  mg_level_global_transfer.cc:0
 6 0x000000000b6a3130 dealii::MGLevelGlobalTransfer<dealii::LinearAlgebra::distributed::Vector<double, dealii::MemorySpace::Host> >::fill_and_communicate_copy_indices<3, 3>()  ???:0
 7 0x000000000b966f23 dealii::MGTransferMatrixFree<3, double>::build()  ???:0
 8 0x00000000012c6f90 aspect::StokesMatrixFreeHandler<3>::setup_dofs()  ???:0
 9 0x0000000001095022 aspect::Simulator<3>::setup_dofs()  ???:0
10 0x00000000010a5fd9 aspect::Simulator<3>::refine_mesh()  ???:0
11 0x000000000111b4b6 aspect::Simulator<3>::maybe_do_initial_refinement()  ???:0
12 0x000000000108fba5 aspect::Simulator<3>::run()  ???:0
13 0x0000000000ac3060 run_simulator<3>()  main.cc:0
14 0x0000000000aaa3ee main()  ???:0
15 0x0000000000022495 __libc_start_main()  ???:0
```
I find it scary to ``emplace_back()`` for ``request_buffers`` and ``request_requests`` followed by an ``MPI_Isend`` because this could cause an allocation invalidating the memory, or not?
Before I dig much deeper into the code, @peterrum @kronbichler do you have an idea what the problem might be?

FYI: @tcclevenger

**Comment by kronbichler** [comment]
I think `request_requests` looks indeed safe because it is of type `std::vector<std::shared_ptr<MPI_Request>>`, so the shared pointer makes sure that the ownership is transfered when `emplace_back` reallocates. On the other hand, that is likely not the case for `request_buffers` of type `std::vector<std::vector<T2>>`, where we copy the vector upon reallocation of the outer `std::vector`. @peterrum can you have a look?

And thanks @tjhei for investigating this far!

**Comment by tjhei** [comment]
I would have guessed that the vector<vector<T2>> should be safe as well because the outer one should do a move assignment. I don't see any other obvious place where we can segfault though.

**Comment by tjhei** [comment]
This seems to fix the crashes for me: https://github.com/dealii/dealii/compare/master...tjhei:pr8930

It contains #8930, #8933, and most notably two MPI_Barrier() around the constructor of Partitioner. While not elegant, it is better than crashing in weird places. :-)
I am trying to see if the Barrier alone makes it work now.
Any suggestion for something less aggressive than these barriers, @peterrum @kronbichler ?

**Comment by tjhei** [comment]
update: I can confirm that #8930 is needed, so we should merge it.

**Comment by peterrum** [comment]
@tjhei thanks for debugging and finding the issue! I can see that you have removed a `#  ifdef DEBUG` around a barrier. Did that make any difference?

I have the feeling that multiple calls to the consensus algorithm (originating from different multigrid levels) get mixed up... I think @kronbichler had a similar issue, but I thought we fixed it...

If we have to add a barrier. Let's choose another place (than the constructor). @tjhei Could you increase the number here https://github.com/dealii/dealii/blob/a5ed68a04ac4966e6acab48fa428dc414e618bb1/source/base/mpi.cc#L1384 to infinity and test the code this way. If `ConsensusAlgorithm_PEX` works, the problem lies within `ConsensusAlgorithm_NBX`; so we would need to add a barrier here...

**Comment by tjhei** [comment]
> Did that make any difference?

I am checking right now which of the changes are indeed necessary. Will report back.
The comment left there made me think this is indeed a problem (that we did not understand fully at that time).

> (originating from different multigrid levels) get mixed up...

Yes, this is why I started adding barriers :-)

**Comment by tjhei** [comment]
>  if (Utilities::MPI::n_mpi_processes(comm) > 99)

Oh no, this is the first time I see this line of code. I have seen several other bugs over the last couple of weeks that only seem to show up with 100+ MPI ranks... :-(

**Comment by peterrum** [comment]
> Oh no, this is the first time I see this line of code. I have seen several other bugs over the last couple of weeks that only seem to show up with 100+ MPI ranks... :-(

Sorry about that. This was intended to be some kind of optimization. `ConsensusAlgorithm_NBX` is supposed to be faster and less memory hungry for large number of processes.

**Comment by tjhei** [comment]
> I am checking right now which of the changes are indeed necessary. Will report back.

it looks like I need:
a) #8930 
b) barriers around the Partitioner() constructor
c) barrier in clean_up_and_end_communication()

If I leave out any of one them, I will crash at some point.

**Comment by peterrum** [comment]
Same issue with `ConsensusAlgorithm_PEX`?

**Comment by peterrum** [comment]
Putting the barriers into the constructor of `Partitioner` is really odd. The second barrier should not be necessary since there is already one at `clean_up_and_end_communication`. It would be great if the first barrier could be moved closer to the consensus algorithm. First try: add the barriers here:
https://github.com/dealii/dealii/blob/a5ed68a04ac4966e6acab48fa428dc414e618bb1/source/base/mpi.cc#L1395-L1400

**Comment by kronbichler** [comment]
> barriers around the Partitioner() constructor

I guess for the final code we want to move the barriers either [here](https://github.com/dealii/dealii/blob/master/source/base/partitioner.cc#L222) and [here](https://github.com/dealii/dealii/blob/master/source/base/partitioner.cc#L238) or within the `ConsensusAlgorithmSelector::run()` function - depending on whether the necessary locking is within the constructor of `ConsensusAlgorithmPayload`.

**Comment by kronbichler** [comment]
@peterrum you were a few seconds faster than me... :wink:

**Comment by peterrum** [comment]
> depending on whether the necessary locking is within the constructor of ConsensusAlgorithmPayload

That should not happen. If that happens some communications (possible in the user code) have not terminated yet...

**Comment by tjhei** [comment]
> Putting the barriers into the constructor of `Partitioner` is really odd. The second barrier should not be necessary since there is already one at `clean_up_and_end_communication`.

I am sure I don't understand things fully and I don't claim the current approach has the minimum number of barriers. I am just showing you what works and what doesn't in the hope that you two can figure out what is happening. ;-)

**Comment by tjhei** [comment]
> Same issue with `ConsensusAlgorithm_PEX`?

With master + disabling NBX I get the partitioner segfault (which I assume would be fixed with the barrier around set_ghost_indices (in the constructor):
```
 0 0x000000000a4f527d dealii::Utilities::MPI::internal::ComputeIndexOwner::ConsensusAlgorithmPayload::get_requesters()  ???:0
 1 0x000000000a4f18b6 dealii::Utilities::MPI::Partitioner::set_ghost_indices()  ???:0
 2 0x000000000a4f0611 dealii::Utilities::MPI::Partitioner::Partitioner()  ???:0
 3 0x00000000094ad2f4 dealii::internal::DoFHandlerImplementation::Policy::ParallelDistributed<dealii::DoFHandler<3, 3> >::renumber_dofs()  ???:0
 4 0x0000000009021264 dealii::DoFHandler<3, 3>::renumber_dofs()  ???:0
 5 0x00000000095266f4 dealii::DoFRenumbering::hierarchical<dealii::DoFHandler<3, 3> >()  ???:0
 6 0x00000000012bc6b8 aspect::StokesMatrixFreeHandler<3>::setup_dofs()  ???:0
 7 0x000000000108e632 aspect::Simulator<3>::setup_dofs()  ???:0
 8 0x00000000010884d3 aspect::Simulator<3>::run()  ???:0
 9 0x0000000000abe9a0 run_simulator<3>()  main.cc:0
10 0x0000000000aa5d2e main()  ???:0
11 0x0000000000022495 __libc_start_main()  ???:0
12 0x00000000008aaee9 _start()  ???:0
```

**Comment by peterrum** [comment]
>  I am just showing you what works and what doesn't in the hope that you two can figure out what is happening. ;-)

It is much appreciated! Can you share a failing program?

**Comment by bangerth** [comment]
On 10/20/19 6:21 AM, Peter Munch wrote:
> I have the feeling that multiple calls to the consensus algorithm (originating 
> from different multigrid levels) get mixed up... I think @kronbichler 
> <https://github.com/kronbichler> had a similar issue, but I thought we fixed it...

If that is so, then usually because you call send/receives from the same 
process with the same MPI tag. You could do something like this:

   static int mpi_tag = 1234;   // starting tag
   ...
   MPI_Send (..., mpi_tag);
   ...
   MPI_Recv (..., mpi_tag);


   ++mpi_tag;    // make sure the next call uses a different tag.

**Comment by tjhei** [comment]
> It is much appreciated! Can you share a failing program?

I can, but it is somewhat messy as you need a specific ASPECT branch (and as such Trilinos as well).

**Comment by tjhei** [comment]
> If that is so, then usually because you call send/receives from the same process with the same MPI tag. You could do something like this:

This is a good suggestion, but I have two practical concerns:
1. There can still be the (rare) crash if one of the fixed ids happens to be the same as the one here. This will be impossible to debug or find.
2. This assumes that every rank enters the function the same number of times. It will break if you have two different communicators (that don't span all ranks).

So, one would need a rotating tag for each communicator (and you would hope that those happen to never overlap as well).

**Comment by tjhei** [comment]
By the way, I am fairly certain there is a race condition based on MPI tag in ConsensusAlgorithmPayload::get_requesters() if called twice in succession.

**Comment by tjhei** [comment]
> So, one would need a rotating tag for each communicator (and you would hope that those happen to never overlap as well).

or, we could duplicate the communicator for complicated algorithms like ConsensusAlgorithm, which will fix all of these problems. I am not sure what the cost of doing that is,  @kronbichler @peterrum ? I think it involves some global communication at least for some MPI implementations. Maybe an MPI reduce from rank 0 to get a unique tag would be cheaper. ;-)

**Comment by bangerth** [comment]
On 10/21/19 5:07 AM, Timo Heister wrote:
>  1. There can still be the (rare) crash if one of the fixed ids happens to be
>     the same as the one here. This will be impossible to debug or find.

Correct. But that's the same as currently where we have no control at all over 
which tags are used.


>  2. This assumes that every rank enters the function the same number of times.
>     It will break if you have two different communicators (that don't span all
>     ranks).

Ah yes, good point. That's bad. We don't know how to make this work 
per-communicator because we have no way to id a communicator uniquely across 
processors...

**Comment by tjhei** [comment]
> Correct. But that's the same as currently where we have no control at all over which tags are used.

I rather have something that is easier to reproduce, which allows us to fix things correctly.

> Ah yes, good point. That's bad. We don't know how to make this work per-communicator because we have no way to id a communicator uniquely across processors...

Option 1: MPI_Broadcast from rank 0 who increments tags.
Option 2: Same tag, but with a duplicated communicator.

**Comment by kronbichler** [comment]
I would be fine with duplicating communicators. These functions are rather expensive anyway so a barrier (or even broadcast) does not matter - as long as the cost does not approach that of a `Allgather` or similar collective where all processors send to all, i.e., `O(N^2)` messages in the end rather than `O(N log(N))`.

**Comment by kronbichler** [comment]
To be more specific, we could duplicate the communicators for the sake of setting up these data structures, and then resort to a standard communicator again. (If we cannot find the few spots necessary to place the barriers, which I assume is difficult.)

**Comment by tjhei** [comment]
@kronbichler @peterrum : What is reason for this logic:
https://github.com/dealii/dealii/blob/90bf29cd84c235b2ab5cf209700c3defdeb5537b/source/base/mpi.cc#L1309-L1310
?

**Comment by tjhei** [comment]
> To be more specific, we could duplicate the communicators for the sake of setting up these data structures, and then resort to a standard communicator again.

I agree. I added duplicated communicators in all places that showed up in my hangs and crashes, see the separate PRs that I opened: #8956 #8955 #8953

While there is many different places where the duplication can be done, I put it as close as possible to the nonblocking communications itself (see Dictionary for example) to make all individual operations safe. Otherwise, one might forget to do the duplication when parts are used in different places in the future. I am open to other suggestions, of course. 

@peterrum I am especially interested in what you prefer as you made a different choice when you talked to me yesterday (https://github.com/peterrum/dealii/commit/fd7648f7766b63d72a9bdbaa99d0283b45362973).

**Comment by kronbichler** [comment]
> @kronbichler @peterrum : What is reason for this logic:
> https://github.com/dealii/dealii/blob/90bf29cd84c235b2ab5cf209700c3defdeb5537b/source/base/mpi.cc#L1309-L1310

This is a left-over from experimenting with the large-scale implementation. I think we can remove the `else` case and the parameter. @peterrum?

**Comment by bangerth** [comment]
I'll add a story about duplicating communicators that some of you know: Some ten years ago, I struggled with finding a bug for about a week because it only led to segfaults many thousands of time steps into long running simulations. The ultimate cause was that the MPI implementation at the time just assigned each new communicator a short int, and when you had ended up duplicating communicators 65k times, you just ran out of integers and the program crashed. That's despite the fact that these communicators were all properly released again. It was excruciatingly difficult to find this.

If we go down the road of duplicating communicators frequently, someone ought to test that we can create/destroy essentially infinite numbers of communicators these days.

**Comment by peterrum** [comment]
> If we go down the road of duplicating communicators frequently, someone ought to test that we can create/destroy essentially infinite numbers of communicators these days.

@bangerth thanks for you comment!

**Comment by peterrum** [comment]
> This is a left-over from experimenting with the large-scale implementation. I think we can remove the else case and the parameter. @peterrum?

Not, quite.  The idea (of which I did forget till now) was to move the else implementation in `compute_point_to_point_communication_pattern`. I will create a PR for that once we have converged to a solution which works on Frontera!

**Comment by peterrum** [comment]
> @peterrum I am especially interested in what you prefer as you made a different choice when you talked to me yesterday (peterrum@fd7648f).

@tjhei Thanks for your efforts! Let's discuss the options in PR #8955 first.

**Comment by tjhei** [comment]
The bug was caused by conflicts in nonblocking communication and has been fixed on master.
