### ISSUE TITLE
Do not transfer MPI communicator for p::s::Tria::copy_tria

### ISSUE THREAD

**Issue by agrayver** [dealii/dealii#8969]
I use p::s::Tria::copy_triangulation and it turns to copy the MPI communicator:

https://github.com/dealii/dealii/blob/1634ecf9dd790e9a0d132711586f180c8c9f2f2e/source/distributed/tria_base.cc#L74-L80

This breaks my workflow where I create p::s::Tria on a sub-communicator and want to copy only the content of p::s::Tria, but not the communicator ownership. 

Can we make the line 80 above optional? I can submit a PR. 

On that note, the doc of this method seems somewhat ambiguous:

> This function also partitions triangulation based on the MPI communicator provided to the constructor.

What constructor is meant here? That of the argument?

**Comment by masterleinad** [comment]
What is your use case here? Do you want to drop processors that contain no cells or do you simply want to duplicate the communicator?
I could see to make it an option as long as the default case is not changed.

**Comment by agrayver** [comment]
> What is your use case here? Do you want to drop processors that contain no cells or do you simply want to duplicate the communicator?

I split communicator (MPI_Comm_split) and create a set of p::s::Tria for each subcommunicator. Smth like:

```
p::s::Tria tria(MPI_COMM_WORLD)
// work with tria / create / refine / etc

subcom = MPI_Comm_split(MPI_COMM_WORLD)
p::s::Tria tria_sub(subcom)
tria.copy_triangulation(tria_sub) // THIS WILL MAKE tria_sub belong to the MPI_COMM_WORLD
```

> I could see to make it an option as long as the default case is not changed.

Yes, essentially I am thinking of replacing the current method signature with (note optional bool):

```
TriangulationBase<dim, spacedim>::copy_triangulation(
    const dealii::Triangulation<dim, spacedim> &other_tria, bool transfer_communicator = true)
```

Depending on the flag, the communicator won't be copied.

**Comment by bangerth** [comment]
On 10/31/19 3:04 AM, Alexander Grayver wrote:
> |subcom = MPI_Comm_split(MPI_COMM_WORLD) p::s::Tria tria_sub(subcom) 
> tria.copy_triangulation(tria_sub) // THIS WILL MAKE tria_sub belong to the 
> MPI_COMM_WORLD|

I don't think I understand this statement. Are you saying that `tria` now 
operates on `subcom` or `MPI_COMM_WORLD`? I think it should continue to work 
on subcom because that's what the triangulation was initialized with -- in 
other words, copying the communicator would *always* be a wrong, and so be a 
bug that I think ought to be fixed.

Want to write a patch for that, and document in the comments for that function 
that it copies the *cells*, but not the communicator, of the source triangulation?
