### ISSUE TITLE
PointerComparison::equal incorrectly assumes that pointers with different types point to different memory locations

### ISSUE THREAD

**Issue by tamiko** [dealii/dealii#903]
Minimal example:
```
class A {};
class B: public A {};

int main ()
{
  B b;
  B *p_b = &b;
  A *p_a = &b;

  std::cout << (static_cast<void *>(p_b) == static_cast<void *>(p_a)) << std::endl;
  std::cout << PointerComparison::equal(p_b, p_a) << std::endl;
}
```

**Comment by bangerth** [comment]
Interesting case. I'm not sure whether the cast to `void*` is the best approach to test for object equality because this will fail even though you probably still want to say that the objects are equal:
```
class A1 {};
class A2 {};
class B: public A1, public A2 {};

int main ()
{
  B b;
  B *p_b = &b;
  A2 *p_a2 = &b;

  std::cout << (static_cast<void *>(p_b) == static_cast<void *>(p_a2)) << std::endl;
  std::cout << PointerComparison::equal(p_b, p_a2) << std::endl;
}
```
Here, both lines will report `false`. What you need to achieve is that you test whether one is convertible to the other, and then compare the converted pointers. Of course, this still fails in a case like this:
```
class B {};
class A1 : public B {};
class A2 : public B {};
class D: public A1, public A2 {};

int main ()
{
  D d;
  A1 *p_a1 = &d;
  A2 *p_a2 = &d;

  std::cout << (static_cast<void *>(p_a1) == static_cast<void *>(p_a2)) << std::endl;
  std::cout << PointerComparison::equal(p_a1, p_a2) << std::endl;
}
```
Here, objects of type A1 are not convertible into objects of type A2, and the other way around. `p_a1` and `p_a2` also have different addresses. Yet, they point to the same object. How will you detect this?

**Comment by tamiko** [comment]
> ```
> class B {};
> class A1 : public B {};
> class A2 : public B {};
> class D: public A1, public A2 {};
>
> int main ()
> {
>   D d;
>   A1 *p_a1 = &d;
>   A2 *p_a2 = &d;
>
>   std::cout << (static_cast<void *>(p_a1) == static_cast<void *>(p_a2)) << std::endl;
>   std::cout << PointerComparison::equal(p_a1, p_a2) << std::endl;
> }
> ```

But here p_a1 and p_a2 refer to distinct memory locations.

**Comment by bangerth** [comment]
As they do in my first example above. You are using the fact that the pointers point to the same address only because the first base object and the derived object happen to be at the same location. (Which may or may not be guaranteed by the standard.) But the second base and the derived object definitely are not -- so the pointers point to different locations, but still to the same object.

**Comment by bangerth** [comment]
So how do we resolve this issue?

**Comment by drwells** [comment]
I talked about this with @tjhei and he presented the following circumstance.

Consider the following diamond inheritance, where all objects contain at least one member variable (so their sizes are always at least one byte and the size of `I` is at least 24 bytes):
```
    P
  /   \
 /     \
A       B
 \     /
  \   /
    I
```

and suppose that `A` and `B` inherit virtually from `P`. If we have the following variables:

```cpp
I i;
A *a = &i;
B *b = &i;
```

then the values of `a` and `b` will not be equal, they will not have the same type, and they still point to the same object. Since, to the best of my knowledge, it is not possible (without C++11; we could do it there with hacks and `decltype`, I think) to check if two types have the same base class (and whether or not that inheritance is virtual), we have no way to return true in this case and false in the case where they point to different instances of `I`.

Almost all of the usages of `PointerComparison` are for comparing two different vectors. Since most of those base classes are abstract I don't think that ignoring this case and just conservatively saying that they do not point to the same object will hurt us. I suppose that if we really need it we can make a function implement something dependent on the types they know, but a generic implementation of this does not seem feasible.

Hence, I recommend closing this.

**Comment by bangerth** [comment]
I'm also ok with closing this. The point of the class was to enable things like this:
```
  void
  SparseMatrix::vmult (Vector<T> &dst,
                                    Vector<U> &src)
  {
    Assert (some_condition, ExcMessage ("source and destination vector must not be the same!"));
```
Here, `some_condition` can not simply be `&dst==&src` because the compiler will complain about comparing pointers to incompatible types if `T` is not equal to `U`. Consequently, I needed to come up with something that allows the comparison to happen if the data types are the same, and otherwise always returns false.

If the documentation does not adequately represents this purpose, then we ought to update the documentation. But I think that the implementation does what it's supposed to do.
