### ISSUE TITLE
Inconsistent ParticleHandler numbering

### ISSUE THREAD

**Issue by luca-heltai** [dealii/dealii#9046]
While working with @blaisb, we found out that the `insert_particles` method is inconsistent w.r.t. numbering of the particles. In particular, lines 136 to 139 of particle_handler.cc show that if we have no particles, the next_free_particle_index will be 1, instead of 0 (the logic is correct whenever we have particles, but not if no particles are present yet), meaning that the indices of particles, when adding particles using `insert_particles` that takes a vector of locations will have their ids start at one. 

This is because in the `insert_particles` that takes a vector of locations the `update_cached_numbers` is called *both* at the beginning (line 314) and at the end (line 365), while in the `insert_particles` that takes a vector of particles it is only called at the end.

Is there a reason to call `update_cached_numbers` at the beginning of `insert_particles`? 

@gassmoeller

**Comment by gassmoeller** [comment]
Hi Luca,
you are right the two functions insert_particles handle this inconsistently. I think the reason for that is the consistency of the particle indices (i.e. that even in parallel computations each particle should get a unique index). The one function takes already generated particles, i.e. the user must have taken care to generate unique IDs. The other only takes positions and generates particles itself (so it needs to know the next free particle IDs). Because there are some functions that can change the next free particle ids without updating the cached numbers for performance reasons, e.g. only inserting a single particle in `insert_particle`, we can not be sure the cached numbers are up-to-date, but for `insert_particles (new_particles)` that does not matter, while for `insert_particles(positions)` it does.

I think the correct way to work around this would be to rework `update_cached_numbers`. The problem is that it can not distinguish between 1 particle with index 0 (locally_highest_index == 0), and no particle (locally_highest_index == 0). Therefore, next_free_particle_index is set to 1 in that function in either case. Maybe we can change the function to correctly set `next_free_particle_index` to 0 if `global_number_of_particles == 0`?

**Comment by blaisb** [comment]
Hi Rene/Luca
I think this could be a good simple fix. Following Rene explanation, the `insert_particles` would need to call `update_cached_numbers` twice if we want it guarantee that a unique ID per particle is used.
Do you want me to open a pull request for this?
