### ISSUE TITLE
LAPACK template wrappers should probably have an additional parameters for every char*

### ISSUE THREAD

**Issue by davydden** [dealii/dealii#9123]
see https://bitbucket.org/blaze-lib/blaze/issues/251/undefined-behaviour-due-to-lapack

**Comment by drwells** [comment]
It should be possible to do this semi-automatically by modifying the script that generates wrappers. Have we observed this problem yet?

**Comment by masterleinad** [comment]
This would likely also fix the problem with the unity build with `Tpetra`.

**Comment by drwells** [comment]
@masterleinad Do we have an open issue for the problem with Tpetra + unity build?

**Comment by masterleinad** [comment]
No, we don't.

**Comment by bangerth** [comment]
It's hard to believe that calling a function with the wrong number of arguments yields anything that even remotely works. My only explanation is that we've only ever used Lapack implementations that really do have that argument list, and no hidden arguments. I mean, with as many arguments as these functions have, arguments get pushed onto the stack and the implementation would access random memory in place of what's supposed to be in these locations. The only way why this could have worked is because the argument is a string (`char *`) for which the implementation of the function only ever checks the first fixed number of bytes and ignores the length passed as the "hidden" argument -- in other words, the hidden arguments are never read. This can only work if function arguments are arranged on the stack in an order so that the first few arguments are nearest to the stack pointer, so that their location (relative to the stack pointer) is independent of the last few arguments.

How exactly does the failure mode look like with these more recent compilers?

**Comment by drwells** [comment]
While this is technically a problem, in practice we are yet to actually encounter this bug so we can't do anything. Lets close until one of us can actually reproduce this - until then there is nothing to do.
