### ISSUE TITLE
Conflict in LAPACK function prototypes

### ISSUE THREAD

**Issue by drwells** [dealii/dealii#9135]
This came up in the slack channel but we should track it here so it doesn't get lost. @masterleinad wrote

> So what do we do with the unity builds that have Tpetra support enabled? Kokkoskernels managed to forward declare the LAPACK functions with a wrong signature (fixed by now) that is in conflict with the ones we have in include/deal.II/lac/lapack_templates.h . Should we disallow unity builds in this case or disallow using Trilinos? I tend to the first option.

We declare our own LAPACK prototypes in the header `lapack_templates.h`. These may not be compatible with other declarations since those prototypes try to enforce const-correctness based on LAPACK's own documentation. Note that overloading is not allowed since we have to use `extern "C"` to correctly link with Fortran.

We can get around this by isolating `lapack_templates.h`, which is only `#include`ed in three other headers now: `lac/qr.h`, `lac/full_matrix.templates.h`, and `lac/utilities.h` and two source files: `lac/lapack_full_matrix.cc` and `lac/tridiagonal_matrix.cc`. More exactly, we should try to avoid including it in headers and then unconditionally remove those source files in which it appears from the list of unity build files.

**Comment by drwells** [comment]
@masterleinad out of curiousity, would you please point me to where Kokkos defines its own LAPACK wrappers?

**Comment by masterleinad** [comment]
> @masterleinad out of curiousity, would you please point me to where Kokkos defines its own LAPACK wrappers?

It's in `kokkos/kokkos-kernels`, not `kokkos/kokkos`:
https://github.com/kokkos/kokkos-kernels/blob/master/src/impl/tpls/KokkosBlas_Host_tpl.cpp

**Comment by drwells** [comment]
I am surprised that we haven't run into this before - we are clearly not the only project that wrote our own header for LAPACK.

**Comment by drwells** [comment]
I think the right solution would be to require `lapacke` which is the approved C interface to LAPACK. The UNC clusters have it. Switching would also, I believe, fix #9123. A disadvantage is that `lapacke` doesn't provide a direct interface and instead makes us specify the matrix order for each function call.

**Comment by Rombur** [comment]
I've used `lapacke` in one project and it was kind of a mess to know if it was installed and if not how to install it. It was different for each LAPACK library. Overall I don't recommend using it.

**Comment by bangerth** [comment]
It's hard to believe that calling a function with the wrong number of arguments yields anything that even remotely works. My only explanation is that we've only ever used Lapack implementations that really do have that argument list, and no hidden arguments. I mean, with as many arguments as these functions have, arguments get pushed onto the stack and the implementation would access random memory in place of what's supposed to be in these locations. The only way why this could have worked is because the argument is a string (`char *`) for which the implementation of the function only ever checks the first fixed number of bytes and ignores the length passed as the "hidden" argument -- in other words, the hidden arguments are never read. This can only work if function arguments are arranged on the stack in an order so that the first few arguments are nearest to the stack pointer, so that their location (relative to the stack pointer) is independent of the last few arguments.

How exactly does the failure mode look like with these more recent compilers?

**Comment by drwells** [comment]
@bangerth I agree with everything you wrote, but isn't that the issue tracked by #9123?

**Comment by bangerth** [comment]
Yes, should have been there.

**Comment by drwells** [comment]
@masterleinad one more question: you mentioned that this was fixed in kokkos-kernels. What released version of Trilinos causes the problem with the unity build?

**Comment by masterleinad** [comment]
It's a problem up to (and including) Trilinos 12.14 (see https://github.com/trilinos/Trilinos/blob/trilinos-release-12-14-branch/packages/kokkos-kernels/src/impl/tpls/KokkosBlas1_axpby_tpl_spec_decl.hpp)
