### ISSUE TITLE
CMake cannot find LAPACK

### ISSUE THREAD

**Issue by zhiyuanzhai** [dealii/dealii#9169]
I was trying to build deal.II from source :
```
cmake .. -DCMAKE_INSTALL_PREFIX=/opt/local -DDEAL_II_WITH_UMFPACK=ON -DDEAL_II_WITH_LAPACK=ON -DLAPACK_LIBRARIES="/opt/local/lib/lapack"
```
The following error occurred :
```
-- Include /Users/xuzhiyuan/Downloads/dealii-9.1.1/cmake/configure/configure_1_lapack.cmake
-- Performing Test DEAL_II_HAVE_FLAG_pthread
WARNING: Target "cmTC_0bfea" requests linking to directory "/opt/local/lib/lapack".  Targets may link only to libraries.  CMake is dropping the item.
-- Performing Test DEAL_II_HAVE_FLAG_pthread - Success
-- Performing Test LAPACK_SYMBOL_CHECK
WARNING: Target "cmTC_ee63e" requests linking to directory "/opt/local/lib/lapack".  Targets may link only to libraries.  CMake is dropping the item.
-- Performing Test LAPACK_SYMBOL_CHECK - Failed
-- Could not find a sufficient BLAS/LAPACK installation: BLAS/LAPACK symbol check failed! Consult CMakeFiles/CMakeError.log for further information.
-- Performing Test MKL_SYMBOL_CHECK
WARNING: Target "cmTC_11875" requests linking to directory "/opt/local/lib/lapack".  Targets may link only to libraries.  CMake is dropping the item.
-- Performing Test MKL_SYMBOL_CHECK - Failed
-- Use other than Intel MKL implementation of BLAS/LAPACK (consult CMakeFiles/CMakeError.log for further information).
-- DEAL_II_WITH_LAPACK has unmet external dependencies.
CMake Error at cmake/macros/macro_configure_feature.cmake:112 (MESSAGE):


  Could not find the lapack library!

  Could not find a sufficient BLAS/LAPACK installation:

  BLAS/LAPACK symbol check failed! This usually means that your BLAS/LAPACK
  installation is incomplete or the link line is broken.  Consult

    CMakeFiles/CMakeError.log

  for further information.

  Please ensure that a suitable lapack library is installed on your computer.

  If the library is not at a default location, either provide some hints for
  autodetection, or set the relevant variables by hand in ccmake.

Call Stack (most recent call first):
  cmake/macros/macro_configure_feature.cmake:269 (FEATURE_ERROR_MESSAGE)
  cmake/configure/configure_1_lapack.cmake:116 (CONFIGURE_FEATURE)
  cmake/macros/macro_verbose_include.cmake:19 (INCLUDE)
  CMakeLists.txt:124 (VERBOSE_INCLUDE)
```
It looks like an issue with my LAPACK installation. But I think it's not likely to go wrong as I've installed the lapack through MacPorts. 
Then I'm stuck.

Error Log : [CMakeError.log](https://github.com/dealii/dealii/files/3960791/CMakeError.log)

OS : macOS Catalina 10.15.2
Fortran Compiler : `ifort`
C/C++ Compiler  : `clang`

**Comment by tamiko** [comment]
> cmake .. -DCMAKE_INSTALL_PREFIX=/opt/local -DDEAL_II_WITH_UMFPACK=ON -DDEAL_II_WITH_LAPACK=ON -DLAPACK_LIBRARIES="/opt/local/lib/lapack"

> WARNING: Target "cmTC_0bfea" requests linking to directory "/opt/local/lib/lapack".  Targets may link only to libraries.  CMake is dropping the item.

You specified a directory instead of a library. In order for deal.II to
pick up lapack you either have to specify the full path to the library

  -DLAPACK_LIBRARIES="/opt/local/lib/lapack/liblapack.so"

or specify the directory via

  -DCMAKE_PREFIX_PATH="/opt/local/lib/lapack"

**Comment by drwells** [comment]
@zhiyuanzhai did this solve your issue?

**Comment by drwells** [comment]
As far as I can tell this is not an issue with our configuration scripts so lets close for now.

**Comment by Lancelof2019** [comment]
- Use other than Intel MKL implementation of BLAS/LAPACK (consult CMakeFiles/CMakeError.log for further information).
-- DEAL_II_WITH_LAPACK has unmet external dependencies.
CMake Error at cmake/macros/macro_configure_feature.cmake:112 (message):
  

  Could not find the lapack library!

  Could not find a sufficient BLAS/LAPACK installation:

  BLAS/LAPACK symbol check failed! This usually means that your BLAS/LAPACK
  installation is incomplete or the link line is broken.  Consult

    CMakeFiles/CMakeError.log

  for further information.

  Please ensure that a suitable lapack library is installed on your computer.

  If the library is not at a default location, either provide some hints for
  autodetection,


set(BLAS_LIBRARIES "/path/to/other/blas/library")
set(LAPACK_LIBRARIES "/path/to/other/lapack/library")

Through the information has been updated ,there is no progress at all.

**Comment by Lancelof2019** [comment]
Hello,

I have one question when I installed dealII(version 9.5.0-pre) during compiling.

I use :cmake -DCMAKE_INSTALL_PREFIX=/usr/local/dealII -DLAPACK_FOUND=true  -DDEAL_II_WITH_UMFPACK=ON -DDEAL_II_WITH_LAPACK=ON -DLAPACK_LIBRARIES="/usr/local/lib64/libblas.a;/usr/local/lib64/liblapack.a" ./..

Because I need to use umfpack

From cmake error information below it said that the installation of blas and lapack are not be found.



cmake Error information
''''
Include /var/install/dealii/cmake/configure/configure_00_threads.cmake
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- 
-- Include /var/install/dealii/cmake/configure/configure_10_lapack.cmake
-- Looking for Fortran sgemm
-- Looking for Fortran sgemm - not found
-- Looking for Fortran sgemm
-- Looking for Fortran sgemm - not found
-- Looking for Fortran sgemm
-- Looking for Fortran sgemm - found
-- Found BLAS: /usr/local/lib64/libopenblas.a;-pthread  
-- Found LAPACK: /usr/local/lib64/libblas.a;/usr/local/lib64/liblapack.a  
-- Processing LAPACK variables and targets
-- Processing LAPACK variables and targets - Done
-- Performing Test LAPACK_SYMBOL_CHECK
-- Performing Test LAPACK_SYMBOL_CHECK - Failed
-- Could not find a sufficient BLAS/LAPACK installation: BLAS/LAPACK symbol check failed! Consult CMakeFiles/CMakeError.log for further information.
-- Performing Test MKL_SYMBOL_CHECK
-- Performing Test MKL_SYMBOL_CHECK - Failed
-- Use other than Intel MKL implementation of BLAS/LAPACK (consult CMakeFiles/CMakeError.log for further information).
-- DEAL_II_WITH_LAPACK has unmet external dependencies.
CMake Error at cmake/macros/macro_configure_feature.cmake:112 (message):
  

  Could not find the lapack library!

  Could not find a sufficient BLAS/LAPACK installation:

  BLAS/LAPACK symbol check failed! This usually means that your BLAS/LAPACK
  installation is incomplete or the link line is broken.  Consult

    CMakeFiles/CMakeError.log

  for further information.

''''

These are what I found
But actually I got :
1.
/usr/lib64/liblapack.so.3
/usr/lib64/liblapack.so.3.8
/usr/lib64/liblapack.so.3.8.0
/usr/lib64/liblapacke.so.3
/usr/lib64/liblapacke.so.3.8
/usr/lib64/liblapacke.so.3.8.0

and 
2.
/usr/lib64/libopenblas.so.0
/usr/lib64/libopenblasp.so.0
/usr/lib64/libblas64_.so.3
/usr/lib64/libblas64_.so.3.8
/usr/lib64/libblas64_.so.3.8.0
/usr/lib64/libcblas64_.so.3
/usr/lib64/libcblas64_.so.3.8
/usr/lib64/libcblas64_.so.3.8.0
/usr/lib64/libblas.so.3
/usr/lib64/libblas.so.3.8
/usr/lib64/libblas.so.3.8.0
/usr/lib64/libcblas.so.3
/usr/lib64/libcblas.so.3.8
/usr/lib64/libcblas.so.3.8.0
/usr/lib64/libopenblas-r0.3.12.so
/usr/lib64/libopenblasp-r0.3.12.so


besides ,in CMakeLists.txt,(cmake version 3.20):
3.

message(STATUS "This is CMake ${CMAKE_VERSION}")
message(STATUS "")

set(BLAS_LIBRARIES "/usr/local/lib64/libblas.a")
set(LAPACK_LIBRARIES "/usr/local/lib64/liblapack.a")
set(CMAKE_LIBRARY_PATH ${CMAKE_LIBRARY_PATH} /usr/lib64)

cmake_minimum_required(VERSION 3.13.4)
#
# We support all policy changes up to version 3.11.
#
cmake_policy(VERSION 3.13.4)


4.Moreover,I tried to install SuiteSparse individually.However,I got the same issue with same error information

Could anyone provide hint or suggestions?

**Comment by marcfehling** [comment]
Some similar problem popped up recently in #15260.

I would suggest to provide hints for directories and let cmake try to find them. Specifying libraries directly is cumbersome and error prone.
https://github.com/dealii/dealii/blob/b9ad0d30d386cb29911363e883f8263fee752e67/cmake/modules/FindDEAL_II_LAPACK.cmake#L40-L41

Since your installation of `LAPACK` is in `/usr/local/lib64/` which is a standard directory, you might be lucky that you don't have to specify any directory at all.

Try to configure deal.II only with the `-DDEAL_II_WITH_LAPACK=ON` option. If that fails, try to add `-DLAPACK_DIR=/usr/local/lib64/`. Hope this helps!
