### ISSUE TITLE
Create/Load grid with local refinement

### ISSUE THREAD

**Issue by luca-heltai** [dealii/dealii#9192]
@nicola-giuliani 

In a project we are following, it has become necessary to have an input-output format that supports grids with local refinement.

While it is quite easy to store this information in a vtk file (we just save all cells, including inactive ones, maybe with information about what level they belong to in a cell-data field), it is not so trivial to create a triangulation from this information.

I would like to discuss here what would the best approach be. We were thinking of adding a Triangulation::create_triangulation that takes vector versions of the current arguments, one per level, and that internally figures out child-parent relationship, and fills in a grid that is locally refined.

The current implementation would then be simply calling the new one, with argument vectors containing a single level (the coarsest).

The following is the proposed interface:
```
virtual void create_triangulation (const std::vector< Point< spacedim >> &vertices, const std::vector< std::vector< CellData< dim >> > &cells_per_level, const std::vector< SubCellData > & subcelldata_per_level)
```

Before we start implementing stuff, we thought it would be a good idea to hear what others think.

**Comment by peterrum** [comment]
@luca-heltai This sound similar to what I have implemented in `parallel::fullydistributed::Triangulation`. There we have `create_triangulation()` which takes a `ConstructionData`:

https://github.com/dealii/dealii/blob/1759d6ebcf275384e21e1fe02e369cc9d514fc88/include/deal.II/distributed/fully_distributed_tria.h#L311-L312

`ConstructionData` contains the information to construct each level of the triangulation (in the form of vectors). It is defined here:
https://github.com/dealii/dealii/blob/1759d6ebcf275384e21e1fe02e369cc9d514fc88/include/deal.II/distributed/fully_distributed_tria.h#L71-L208

This is the implementation of `create_triangulation`:

https://github.com/dealii/dealii/blob/1759d6ebcf275384e21e1fe02e369cc9d514fc88/source/distributed/fully_distributed_tria.cc#L49-L265

in which also the child-parent relationship is figured out.

Is this what you were thinking about? If yes it would be nice if would could keep `p:d:t` and `p:f:t` consistent. I am open to adjust the `ConstructionData` so that it matches your need!

**Comment by bangerth** [comment]
There is also the `PerisistentTriangulation` class that can do this already in the case where the triangulation is both read and written by deal.II. 

I have often thought that it might make sense to actually define a file format for hierarchically refined meshes, for example based on the XML-based VTU format with some extensions. I could imagine this turning into a nice ACM TOMS paper :-)

**Comment by luca-heltai** [comment]
@peterrum , That's exactly what is needed. How much work would it be to move the implementation to Triangulation instead of having it in p::f::t ?

@bangerth I already use that class, however it has the defect of not beeing easy to visualize (without going through deal.II again). What I had in mind is exactly what you describe: using the xml (or text) format of vtk to export and import level information. In order for that to be usable, then I'd need something like what @peterrum has already implemented for p::f::t

**Comment by peterrum** [comment]
> How much work would it be to move the implementation to Triangulation instead of having it in p::f::t ?

It depends on what you exactly want to do and what you mean under `Triangulation` . Moving a large part of the code in `p:f:t` to the serial `dealii::Triangulation` would be probably no problem, since my code essentially constructs a serial triangulation with a pre-processing step (map of locally-relevant coarse-grid cells to globally-unique coarse grid cells) and a post-processing step (setting the subdomain ids).

But to make it work for `p:d:t` might be a problem (?) if the grid repartitions after every refinement step...

I guess the new method `Triangulation::create_triangulation` could take a `ConstructionData`, however, with fewer fields compared to the `p:f:t`-case. The needed fields are highlighted with `needed` in the following listing:
```cpp
    template <int dim> 
     struct CellData 
     { 
       // needed: to determine path of cell
       CellId::binary_type id; 

       // not needed: only in parallel  
       types::subdomain_id subdomain_id; 

       // not needed: only in parallel    
       types::subdomain_id level_subdomain_id; 
  
       // needed  
       types::material_id manifold_id; 
  
       // needed
       std::array<types::manifold_id, GeometryInfo<dim>::lines_per_cell> 
         manifold_line_ids; 
  
       // needed
       std::array<types::manifold_id, 
                  dim == 1 ? 1 : GeometryInfo<3>::quads_per_cell> 
         manifold_quad_ids; 
  
       // needed
       std::vector<std::pair<unsigned int, types::boundary_id>> boundary_ids; 
     }; 
  
     template <int dim, int spacedim> 
     struct ConstructionData 
     { 
       // needed
       std::vector<dealii::CellData<dim>> coarse_cells; 
  
       // needed
       std::vector<Point<spacedim>> coarse_cell_vertices; 
  
       // not needed: only in parallel
       std::vector<types::coarse_cell_id> coarse_cell_index_to_coarse_cell_id; 
  
       // needed
       std::vector<std::vector<CellData<dim>>> cell_infos; 
  
       // not needed: only in parallel
       MPI_Comm comm; 
  
       // needed: smoothing, ...
       Settings settings; 
     }; 
```

Finally, this `ConstructionData` has to be setup. Maybe you could checkout the functions in the `parallel::fullydistributed::Utilities` namespace.

If the description sounds fine, I can create after Christmas an initial PR in which I create the new method in `dealii::Triangulation`, so that you can adjust it to your needs.

Btw.: it would be really cool if `ConstructionData` could be created from VTK files. Currently, I can serialize and deserialize it via Boost (see tests/serialization/parallel_fullydistributed_construction_data_1.cc)

**Comment by bangerth** [comment]
I agree that an elegant way to do what you want to achieve here is if we had functions that read a VTK/gmsh/... file and just return the necessary objects in some way. The current approach with attaching a triangulation to the `GridIn` object, and that having that class's member functions fill the triangulation behind everyone's back is not elegant.
