### ISSUE TITLE
Update TBB to use its latest CMake-based build system

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#9212]
We have sort of a difficult way of integrating the bundled TBB: We built our own CMake scripts that compiles the TBB in a way we think is useful, and then include the object files into `libdeal_II.so`. That was necessary because the build system of TBB was "difficult" in the past. But it's become easier: They now have CMake builds themselves. I think we ought to use that if we can to build a libtbb.so, install that along with our libraries, and then make sure we link with it. 

See
https://software.intel.com/en-us/articles/intel-threading-building-blocks-release-notes

**Comment by tamiko** [comment]
@bangerth 
> We have sort of a difficult way of integrating the bundled TBB: We built our own CMake scripts that compiles the TBB in a way we think is useful, and then include the object files into libdeal_II.so. 

Actually, we do that for all bundled dependencies (boost, muparser, tbb, umfpack). I chose this approach to avoid having to execute a foreign build system and having external libraries installed (that have a chance to clash with the user environment). In particular, just compiling the external dependency into the library has the advantage that we avoid a whole class of problems with external libtbb.so (or similar) when it comes to symbol clashes.

> I think we ought to use that if we can to build a libtbb.so, install that along with our libraries, and then make sure we link with it.

I am a bit worried that such a change would introduce more problems than benefits: This approach adds quite a bit of complexity (rpath management, library installation) and the potential for symbol clashes if tbb happens to be in the transitive link interface by chance.

I also don't see an immediate advantage. We currently, don't need transitive linking for tbb (because we use tbb through our internal wrappers exclusively).

**Comment by bangerth** [comment]
I see your points. My worry is that it's hard to update to a newer version of the TBB because you never know what files they have added/removed/split and that need for our `CMakeLists.txt` to be updated. Our own `CMakeLists.txt` also contains a set of funny compiler flags and other things that happen to be right for GCC -- but does it work for Windows, for example?

But let's leave it as is -- it's not broken unless we know that it is.

**Comment by bangerth** [comment]
As a matter of fact (and maybe making my point), we do not bundle TBB on Windows...

**Comment by tamiko** [comment]
Let's close for now :-)
