### ISSUE TITLE
Double check the derivation in step-47

### ISSUE THREAD

**Issue by drwells** [dealii/dealii#9317]
A followup to the conversation in #9111: we should verify that the derivation in the introduction matches the implementation.

**Comment by bangerth** [comment]
Specifically, this relates to the mismatch between terms implemented for the right hand side and the terms described in the introduction.

**Comment by tjhei** [comment]
The term is correct as far as I can tell, but I will go through and fix the derivation.

**Comment by bangerth** [comment]
I think that the implementation is correct but that the documentation is missing a term.

**Comment by bangerth** [comment]
@sophy1029 -- you asked what there is left to do for this tutorial program. I forgot that there is also this issue here: The documentation and the implementation do not match for the right hand side. If you had a bit of time, we could use help in figuring out which part is correct (I think that the implementation is correct) and updating the other side. You probably just need to compare this with what the papers on the topic say.

**Comment by bangerth** [comment]
Fixed by #9451.
