### ISSUE TITLE
[Step-49] Documentation review: Gmsh capabilities need update?

### ISSUE THREAD

**Issue by krishnakumarg1984** [dealii/dealii#9324]
Step-49 tutorial claims that

>Gmsh can generate unstructured 2d quad meshes, but in 3d it can only extrude 2d meshes to get hexahedral meshes. 3D meshing of unstructured geometry into hexahedra is not supported at the time of writing this tutorial (early 2013)

I am a complete newbie in mesh generation, but going through the [latest reference manual for  gmsh, section 6 Mesh module](http://gmsh.info/doc/texinfo/gmsh.html), it looks like the limitations on 3D meshes have long been addressed? 

For instance, quoting the linked manual,
_" The 3D structured algorithms generate tetrahedra, hexahedra, prisms and pyramids, depending on the type of the surface meshes they are based on. All meshes can be subdivided to generate fully quadrangular or fully hexahedral meshes with the Mesh.SubdivisionAlgorihm option (see Mesh options list). "_  Apart from this, there are quite a few other places which mention 8-noded hexahedra in the gmsh documentation.  

Does this warrant an update to Step-49?

**Comment by blaisb** [comment]
Indeed, GMSH now provides an option which allows the subdividision of all unstructured meshes into hexahedra. However, I recall @luca-heltai  mentioning that the resulting elements and be sometimes ordered in an incorrect fashion (alternating sign of the jacobian) and that these meshes would be incorrectly read by deal.II because of this. I am unsure if this is the case, but it would be worth it to test it before adapting the comment.

**Comment by krishnakumarg1984** [comment]
I see. If this is indeed the case, deal.II's test suite should catch it, I think. If any of the experts here see a value in this and are comfortable with gmsh, they could perhaps test these newer gmsh features in an experimental branch of deal.ii.

**Comment by bangerth** [comment]
The experts have already spoken above.
