### ISSUE TITLE
[Step-10] Remove long double from example step and improve discussion of round-off errors

### ISSUE THREAD

**Issue by krishnakumarg1984** [dealii/dealii#9341]
In Step-10, we have

>Since we would like to compute the difference between two numbers which are quite accurate, with the accuracy of the computed approximation to π being in the range of the number of digits which a double variable can hold, we rather declare the reference value as a long double and give it a number of extra digits:
`const long double pi = 3.141592653589793238462643L;`

From my fairly rudimentary understanding of the C++ language, this may not be the best practice? The number of precision bits of `long double` strongly depends on a) compiler, b) OS and c) machine architecture.

Perhaps a better idea is to replace it with a predictable size of `pi` using a suitable multi-precision library. Since a standard Deal.II installation already bundles boost, do the developers think it is worth replacing this with the facilities provided by [`boost.multiprecision`](https://www.boost.org/doc/libs/1_72_0/libs/multiprecision/doc/html/index.html) for example?

**Comment by bangerth** [comment]
The use of `long double` is silly. It dates to a time when we thought that we should show as many possible ways of doing things as we could. We no longer believe that that is true -- it's not about showing what *could* be done, but thinking about *why one would do something* that facilitates *learning*.

If you wanted to play with that, I'd accept a patch that just changes all uses of `long double` to `double` and updates the results. I bet that the results are essentially identical.

**Comment by kronbichler** [comment]
Without having looked into it more closely, I would add that the case is not as trivial as it seems due to roundoff. The tutorial essentially has a linear way of adding entries, from which it is known that the error behaves as `n * machine_epsilon`, where `n` is the number of elements accumulated. The reason is that we keep adding small numbers (the local value at the quadrature point) to the big number of holding the sum of all previous content, which makes one lose as many digits as there are in the difference between the local result and the global sum. `long double` avoids some of the issues as it provides three additional digits of accuracy, but I'm pretty sure that at least the computation by area should get worse when switching to `double`. So in case we switch (which I guess would make sense), I would recommend to at least mention the problem with roundoff for this kind of sums, and mention pairwise addition or [Kahan summation](https://en.wikipedia.org/wiki/Kahan_summation_algorithm).

**Comment by kronbichler** [comment]
As to the original question: Multiple precision libraries won't help much here, because we are fundamentally limited by the accuracy in the representation of the grid vertices (double variables), the additional points acquired by `MappingQGeneric` (double variables), the evaluation of the polynomials and their first derivative within the mapping (double variables), and the Gaussian quadrature points (double variables). So the multiprecision part would really only help the roundoff accumulation in the summation, and local results cannot be more accurate unless all the ingredients I mention above were templated in the number type, which is outside the scope of our library.

**Comment by krishnakumarg1984** [comment]
>As to the original question: Multiple precision libraries won't help much here, because we are fundamentally limited by the accuracy in the representation of the grid vertices  ....

OK. Given this information, I think we should replace `long double` with just `double`, at least for step-10.

>If you wanted to play with that, I'd accept a patch that just changes all uses of long double to double and updates the results. I bet that the results are essentially identical.

My current installation is v9.1.1, although I am referring to the `master` branch of tutorials since they sometimes contain recent updates and better clarifications.  Is it okay if I submit the patch for step-10 with results based on `v9.1.1`?

**Comment by krishnakumarg1984** [comment]
As a JFYI, `long double` occurs 105 times in the library.  73 occurrences in the `include/` directory, 22 times in the  'source/` directory and 10 times in the `examples/` directory!

**Comment by bangerth** [comment]
On 1/16/20 7:42 AM, Krishnakumar Gopalakrishnan wrote:
> My current installation is v9.1.1, although I am referring to the |master| 
> branch of tutorials since they sometimes contain recent updates and better 
> clarifications. Is it okay if I submit the patch for step-10 with results 
> based on |v9.1.1|?

Yes.

**Comment by tamiko** [comment]
I suggest that this makes a neat small starter project (doable in an hour or so) with the following three tasks:
 - [ ] remove `long double` from the example step
 - [ ] make sure that the example step still works as intended
 - [ ] and as @kronbichler puts it: "I would recommend to at least mention the problem with roundoff for this kind of sums, and mention pairwise addition or Kahan summation."

**Comment by kronbichler** [comment]
Not high priority, so I'm postponing it.
