### ISSUE TITLE
[Step-7] Improve/Clarify the introduction to the Helmholtz equation

### ISSUE THREAD

**Issue by krishnakumarg1984** [dealii/dealii#9395]
In Step-7, the following statement introduces the equation to be solved.

>The equation that we want to solve here is the Helmholtz equation "with the nice sign": 

There are a couple of issues with this

1.  Not everyone is familiar with the Helmholtz equation. Looking at Wikipedia suggests that this particular form of the equation is the __Inhomogenous Helmholtz equation__ with possible eigen values of $\pm 1$. This appears only a bit further in the Wikipedia article

2. We don't understand the remark about the "niceness" of sign. In particular, what is the "not nice' form of the equation? Why was that form "not nice" or alternatively, what is so nice about this form? 

3. Why was $k=1$ chosen as the Eigenvalue here?

**Comment by drwells** [comment]
This is like the question on functional analysis - we cannot possibly explain the entire mathematical background of every single problem. This is the nice sign because one ends up with a positive definite matrix instead of a semidefinite matrix.

We are not computing any eigenfunctions here, we are just solving an elliptic PDE. That is a very different problem from step-7.

Ultimately, these questions about the Helmholtz equation (and how to efficiently compute its spectra) are not the point of step-7, so I think its fine to leave things as-is; if people care about this equation as more than a sample elliptic PDE then they should read a book on PDEs - its completely outside the scope of our documentation.

**Comment by bangerth** [comment]
See also #9411.
