### ISSUE TITLE
Dealing with clamped boundary conditions in step-47

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#9426]
@sophy1029 -- here is another issue that would be nice to address in a "Possibilities for extensions" section at the end of the results: The program at the moment implements the kind of boundary conditions where one prescribes the value and the normal derivative of the solution. In the introduction, this is described as the "clamped case".

It would be nice if we could also discuss how to deal with the other "free" boundary case where
```
  u = g
  Delta u = h              // in the actual "free" case, we have h=0
```
If you could look into the papers we based the implementation on to see how this is handled, that would be much appreciated. We could then convert this into a section in the results.

**Comment by sophy1029** [comment]
Compared to the clamped case implemented in the tutorial, in the simply supported condition, there are only contributions from interior edges instead of all edges on the LHS of the scheme. 
Then on the right hand side, there would be no contributions from symmetrization and stabilization terms, but have Delta u =h as the boundary condition (if h = 0, then on the RHS, there's only integral( f ,v )). Does it correct?
How should we add this case to the result section? Shall we provide derivations of the FEM scheme?

**Comment by bangerth** [comment]
I think it would be nice if we could have a section in the "Possibilities for extensions" at the bottom of the "Results" section that derives how the weak formulation of the problem looks like for the simply supported case with `h != 0`. Do you think you could write something up for this?

**Comment by sophy1029** [comment]
Yes, of course!

**Comment by masterleinad** [comment]
@sophy1029 What's the status here?

**Comment by sophy1029** [comment]
@masterleinad  Please check #9558 
We are checking whether the derivation for the new boundary condition case is correct.
