### ISSUE TITLE
ParameterHandler::add_parameter () not working properly for...

### ISSUE THREAD

**Issue by peterrum** [dealii/dealii#9427]
... `parse_input_from_json ()` and probably not for `parse_input_from_xml ()`.

My observation is (via calling `print_parameters`) that the parameters are read correctly but the values are not set registered during `add_parameter` are not set with the values from the input file. I guess the created actions are not called...

@luca-heltai :is my observation right?

FYI @lpsaavedra

**Comment by luca-heltai** [comment]
Yes. You are right. 

The `read_xml_recursively` function directly changes the property tree, and does not have a way to call the actions. Both `parse_input_from_json` and `parse_input_from_xml` call `read_xml_recursively`, and change directly the internal `boost::property_tree` object.

My suggestion would be to change that function to actually call the `ParameterHandler::set` method, instead of modifying directly the property tree.

Alternatively, these are the lines that should be copied and adjusted in the `read_xml_recursively`, after the entry is actually set:

~~~
       // then also execute the actions associated with this
       // parameter (if any have been provided)
       const boost::optional<std::string> action_indices_as_string =
         entries->get_optional<std::string>(path + path_separator + "actions");
       if (action_indices_as_string)
         {
           std::vector<int> action_indices = Utilities::string_to_int(
             Utilities::split_string_list(action_indices_as_string.get()));
           for (const unsigned int index : action_indices)
             if (actions.size() >= index + 1)
               actions[index](new_value);
         }
 ~~~

**Comment by luca-heltai** [comment]
Actually, only the first option is viable. The vector of actions is *not* contained in the property tree. Only their indices. read_xml_recursively should be changed to accept a parameter handler as destination, and simply call `prm.set(entry, value)` instead of doing it explicitly on the tree.
