### ISSUE TITLE
Using 4 elements for Tensor<1,dim>

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#9535]
Here's a thought I've occasionally had, but never wrote down. I suspect that @kronbichler is the only one who can really answer it :-)

In its simplest form, `Tensor<1,dim>` stores `dim` entries. That's not quite true because what we really do (after @tamiko got rid of the `Tensor<1,dim>` specialization) is that `Tensor<rank,dim>` does
```
  Tensor<rank_ - 1, dim, Number> values[(dim != 0) ? dim : 1];
```
but `Tensor<0,dim>` stores a single `double` and nothing else.

But let's pretend for a moment that `Tensor<1,dim>` stored
```
  double values[dim];
```
What if we *always* did this instead:
```
  double values[(dim+3)/4*4];
```
This way, we always stored multiples of four elements. Then we could actually use the following instead:
```
  VectorizedArray<double,(dim+3)/4*4> values;
```
Now, all the functions that access individual entries would continue to look just like before and, furthermore, would continue to prohibit access to elements beyond the `dim`'th one, so it is initialized to zero and will always remain at zero.

The interesting part now comes from doing things like dot products between two `Tensor<1,dim>`, or between `Tensor<2,dim>` and `Tensor<1,dim>`: Because we have a full set of four elements, we can use things such as AVX (or, if we only rounded up to a multiple of 2, the SSE2) instructions that can do the dot product in just one instruction. We don't need the loop over the elements, nor the accumulation of results that likely lead to some pipeline stall. One might suggest that it would also accelerate the product between `Tensor<2,dim>` and `Tensor<1,dim>` objects. At the same time, the additional memory required is likely going to be rather minimal.

What do you say, @kronbichler ?

**Comment by kronbichler** [comment]
This has been lurking around for a while waiting for me. The answer is a bit complicated, so I will try to approach some of the issues at hand in this first comment.

To store a tensor as `double values[(dim+3)/4*4];` or `VectorizedArray<double,(dim+3)/4*4> values` (with appropriate fall-backs) would have some charm indeed for the reasons you describe. Let me raise the *buts* now:
- This does increase the memory consumption of some of the large data structures. All arrays keeping tensors of derivatives would include additional padding. While this could be tolerated for things we keep in `FEValues`, I am not so sure about the list of vertices in a triangulation.
- The most profitable case would be situations like this one (a random location I am familiar with, there are certainly thousands): https://github.com/dealii/dealii/blob/fb3d08b3d0ecdc05f258fda7e9cb2e38f8ab9a0b/source/fe/mapping_q_generic.cc#L1270-L1271
We could collapse the loop over `j` and let the data vectorized array handle it. However, cases like dot products are not really a big win. What you gain is the multiplications that you possibly do before the addition. But for the latter, you need something called a *horizontal* add operation, combining the results in various SIMD lanes rather than doing operations on each entry in parallel. This is slower and one typically tries to avoid it. It does not gain much latency-wise because the fastest way to add say 4 entries is to add the first and third entry and second and fourth in parallel, and then the first and second result. So latency-wise this is pairwise summation and not better before `dim=4` which is already rare for us.

Given these two considerations, I have a hard time to see that it would *always* be profitable. It sometimes is, maybe even in the majority of use cases as long as the additional memory transfer from the padded elements does not matter. But then there are other cases where it is not a win. I think this would make up for a nice project for someone with enough time and genuine interest in code optimization, but I would not make it a priority. One typically tries to find other opportunities to apply SIMD data structures in case the innermost operation is a loop (say the second-outer loop).

**Comment by bangerth** [comment]
@kronbichler -- thanks for thinking this through! I guess this might not be worth keeping open then?

(I found the discussion of the latencies interesting. I had assumed that there is the equivalent to a fma operation that computes the dot product between two SIMD data structures, rather than first the element-wise product and then the horizontal add. It's curious that that isn't the case given that surely a dot product is a common case. At least in 2d, this would equate to a "fmma" operation where there are two multiplications that are then added together.)

**Comment by kronbichler** [comment]
Yes, let us close this for now. We might get back to some variant at some point, but not without substantial work and a good strategy.
