### ISSUE TITLE
discuss 64bit typedef in places outside of DoFs

### ISSUE THREAD

**Issue by tjhei** [dealii/dealii#9550]
(prompted by a comment in #9548)

We currently have: ``types::coarse_cell_id`` and ``types::global_dof_index``, which are both 64 bit (unsigned long long int) if DEAL_II_WITH_64BIT_INDICES is set.

There is several other places in the library where 32 bits are not enough, for example the global number of cells (n_global_active_cells() etc). We currently use the global_dof_index as the return value for that, which seems somewhat awkward.

Should we change that? If yes, a few options come to mind:
1. Rename ``types::global_dof_index`` to ``types::global_index`` and use everywhere. This breaks a lot of code.
2. Unconditionally use size_t (or a typedef) for things where performance doesn't matter (for the global number of cells for example). I kind of like that this simplify things and reduces bugs (we no longer have two different code paths).
3. Leave things as is (use global_dof_index everyhwere)
4. Add a new typedef that is an alias for global_dof_index.

**Comment by drwells** [comment]
2. seems like the right idea - any time we return a size I think we should use `std::size_t`.

**Comment by bangerth** [comment]
I'm a big fan of `typedef`s (i.e., option 4) because that provides some kind of implicit documentation as well. If a function returns a `types::global_dof_index`, you know that it returns something that is related to one particular DoF, or their number. Similarly, if a function takes a vector of `global_dof_index`, you know that it isn't a vector of numbers of cells, for example. So there is an implicit usefulness to using `typedef`s because they provide context to what a function or argument is that would otherwise have to be expressed in words in the documentation.

So I would prefer option 4.

**Comment by kronbichler** [comment]
One problem with too many `typedef`s is that it increases the load of notation a new user needs to go through - even if we find words that are perfectly intuitive to us developers, a newcomer might have a completely different view and feel the threshold to get used with the terms of deal.II to be overly high. Therefore I am agreeing with @drwells that we should try `std::size_t` (or the STL concept `size_type`) as much as possible for sizes because it reduces the mental load; we cannot use them for all numbers in arrays because 32 bit integers take half the memory of 64 bit integers and there are many memory-bound situations, so there needs to be a compromise somewhat (and this is the reason why we do still have lots of `unsigned int`s around).

**Comment by tjhei** [comment]
It seems that in places where we are not concerned about performance/memory, we can unconditionally use a 64 bit type (like n_global_active_cells). But we also don't gain much by doing so.
I don't feel strongly about a new typedef vs std::size_t, but using types::global_dof_index does not have much support. 

@bangerth what name would you give the typedef? I am struggling to come up with a good name: ``global_cell_index``? ``cell_index``? ``cell_count``? They all don't quite fit the return value of n_global_active_cells. Maybe this is a sign that size_t is a better choice?

**Comment by bangerth** [comment]
I'd call it `global_cell_index`. The *number* of cells is simply the largest used index plus one, in the same way as `n_dofs()` returns `global_dof_index`.

**Comment by tjhei** [comment]
Any other comments? Should we have a vote?
1. Introduce ``types::global_cell_index`` and use in appropriate places. Vote :+1: 
2. Keep things as is. :-1: (use types::global_dof_index)
3. Use ``std::size_t``. Vote :heart:  
4. Something else: :rocket:

**Comment by bangerth** [comment]
Looks like `types::global_dof_index` might just so scrape through ;-)

**Comment by bangerth** [comment]
Oh, no, now it's a tie! What do we do? The status quo has no votes at all...

**Comment by tamiko** [comment]
@bangerth Call in the tie breaker.

**Comment by tamiko** [comment]
Maybe that is just a personal preference but I like `types::global_cell_index` more. For three reasons (a) we can simply typedef it to whatever we want, (b) I like to have distinct types (Haskell *cough* *cough*), (c) if we ever decide this was a bad idea we can just sed `types::global_cell_index` into `std::size_t` and call it a day. The other way round - not so much.

**Comment by bangerth** [comment]
Amen! :-)

**Comment by bangerth** [comment]
Tie breaker: You know how I voted :-)

(I'm even willing to do some of the work.)

**Comment by tjhei** [comment]
> (I'm even willing to do some of the work.)

alright, would you mind introducing the typedef? I can replace the 3-4 places afterwards.

**Comment by bangerth** [comment]
Will do.

Looking at this, it's interesting that we already have
```
  using global_vertex_index = ...
  using coarse_cell_id = ...
  using particle_index = ...
```
all following the same pattern. I think it makes sense to stick with this scheme.
