### ISSUE TITLE
face-based loop warnings

### ISSUE THREAD

**Issue by tjhei** [dealii/dealii#9609]
I am getting a bunch of warnings as a result of #9603 (?):
```

In file included from /home/heister/deal-git/source/fe/fe_tools_interpolate.cc:17:
/home/heister/deal-git/include/deal.II/fe/fe_tools_interpolate.templates.h:179:37: warning: unused variable 'face' [-Wunused-variable]
            for (const unsigned int face : GeometryInfo<dim>::face_indices())
                                    ^
/home/heister/deal-git/include/deal.II/fe/fe_tools_interpolate.templates.h:335:37: warning: unused variable 'face' [-Wunused-variable]
            for (const unsigned int face : GeometryInfo<dim>::face_indices())
                                    ^
/home/heister/deal-git/include/deal.II/fe/fe_tools_interpolate.templates.h:670:37: warning: unused variable 'face' [-Wunused-variable]
            for (const unsigned int face : GeometryInfo<dim>::face_indices())
                                    ^
3 warnings generated.
```

@bangerth can you take a look?

This is with clang 6.0

**Comment by kronbichler** [comment]
I see the warnings also with gcc. This is annoying since we have this code:
https://github.com/dealii/dealii/blob/3579e25ebac32b81091546abd0636dd01bc3df2d/include/deal.II/fe/fe_tools_interpolate.templates.h#L179-L182

I am not sure if range-based for loops are still nicer than adding a `(void)face;` in the loop at this place. At the same time, we cannot add something like a `(void)` to the statement in the `Assert` macro in release mode because we rely on the fact that the condition is not generated at all for expensive checks.

**Comment by tjhei** [comment]
Annoying, yes. I would wrap the whole expression in ``#ifdef DEBUG``. Still not ideal though.

**Comment by bangerth** [comment]
I'll take a look.
