### ISSUE TITLE
More GeometryInfo::..._indices() functions?

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#9620]
I like range-based for loops quite a lot, as they are concise and as they also exist in other languages. My best guess is that they are going to become pretty idiomatic.

We've introduced a number of ways how these can be used: `triangulation.active_cell_iterators()`, `GeometryInfo::face_indices()`, etc. There are definitely more opportunities in `GeometryInfo` for this: `vertex_indices()`, `line_indices()`, etc could all be introduced.

What does everyone think about adding these functions and using them widely?

**Comment by drwells** [comment]
We should at least add vertex indices - we loop over vertices pretty frequently.

**Comment by masterleinad** [comment]
I don't feel that strongly about adding range-based for loop in cases where the underlying object is just a number. I think the current syntax is fine there as well.

**Comment by drwells** [comment]
A lot happened since we introduced this PR - in particular we basically rewrote the entire library to use ranged for loops for these things based on the number of lines, vertices, etc. of the current element in order to get simplex support working. Put another way - we achieved this in a different way.
