### ISSUE TITLE
Expensive structures being regenerated at each sort_particles_into_subdomains_and_cells for particle_handler

### ISSUE THREAD

**Issue by blaisb** [dealii/dealii#9626]
The sort_particles_into_subdomains_and_cells locates particles within the cells and distribute them correctly across processors. This functions is intended to be used after particles were moved. Consequently, it can be called a very large amount of times in a simulation.
For some of our initial benchmark, if you have a relatively small number of particles, >66% of this routine is spent calling two functions:

```
       // Create a map from vertices to adjacent cells
       const std::vector<
         std::set<typename Triangulation<dim, spacedim>::active_cell_iterator>>
         vertex_to_cells(GridTools::vertex_to_cell_map(*triangulation));

```
```
       // Create a corresponding map of vectors from vertex to cell center
       const std::vector<std::vector<Tensor<1, spacedim>>>
         vertex_to_cell_centers(
           GridTools::vertex_to_cell_centers_directions(*triangulation,
                                                        vertex_to_cells));
```

For a given triangulation, these structures are static. Consequently, they could be re-used from iteration to iteration. I would like to think of a mechanism that would allow us to provide these structures to ensure that we are not regenerating them on the fly. This would greatly reduce the computational cost in our case (like, severely). Does anybody have a suggestion? I can write the modification and make a pull request, but what would be the best way to proceed?

@shahabgol @gassmoeller @luca-heltai , you may have ideas?

**Comment by gassmoeller** [comment]
Hi Bruno,

> Consequently, it can be called a very large amount of times in a simulation.

This is true, although it happens probably only a few times per time step; depending on the particle advection scheme, once after each integration step. But you are right i can see that becoming a problem if you have many cells and relatively few particles. In my application I usually have lots of particles and relatively few cells, which is why these calls where never very expensive for me. One way to handle it would be to cache the information inside the ParticleHandler class as new member variables. You could update these members whenever the triangulation is changed by connecting a new function `update_triangulation_cache` to the `triangulation->signals.any_change` signal inside of the `initialize` function of the ParticleHandler. This would trigger an update whenever the triangulation is deformed or refinement/coarsening happens.
One thing to consider is the memory consumption of this cache. It would permanently require around `n_vertices * 2^dim * sizeof(active_cell_iterator)` memory. I am not sure how big active cell iterators are, maybe others have more experience with this. Anyway I do not think it would be prohibitively expensive in terms of memory. Let me know if you want to go ahead with this idea and get stuck.

**Comment by blaisb** [comment]
Hi Rene,
This is very similar to what I had imagined for a solution. I think it's a good idea. I don't think the memory overhead would be that critical (and in the case that the structure is this big, it truly means that it is expensive to recalculate often).
Let me work on a pull request related to this. I won't hesitate to reach out if I have questions :). Thanks for the quick answer :)!

**Comment by bangerth** [comment]
On 3/5/20 9:36 AM, Rene Gassmoeller wrote:
> It would permanently require around |n_vertices * 2^dim * 
> sizeof(active_cell_iterator)| memory. I am not sure how big active cell 
> iterators are, maybe others have more experience with this.

2 pointers plus 2 integers. So depending on how the compiler wants to 
align member variables, either 24 or 32 bytes. Let's say 32 bytes, then 
in 3d you'll store 256 bytes per vertex. If you had a scalar Q1 element, 
then that would correspond to about 20 additional entries per row of the 
matrix -- about the same as you would probably have for a Q1 element, 
but far less than what you have, for example, if you were to solve a 
vector-valued Stokes problem.

**Comment by blaisb** [comment]
> On 3/5/20 9:36 AM, Rene Gassmoeller wrote: It would permanently require around |n_vertices * 2^dim * sizeof(active_cell_iterator)| memory. I am not sure how big active cell iterators are, maybe others have more experience with this.
> 2 pointers plus 2 integers. So depending on how the compiler wants to align member variables, either 24 or 32 bytes. Let's say 32 bytes, then in 3d you'll store 256 bytes per vertex. If you had a scalar Q1 element, then that would correspond to about 20 additional entries per row of the matrix -- about the same as you would probably have for a Q1 element, but far less than what you have, for example, if you were to solve a vector-valued Stokes problem.

Good point. So would it be a bad thing to have this structured buffered within the class by default? It seems like a memory footprint, but rebuilding that structure on the fly is really killing it for us (since we have say 10k particle on >10k cells). Is it better to have both options? I am not sure what the good call to make is here. Buffer, or buffer optionally?

**Comment by bangerth** [comment]
On 3/5/20 7:03 PM, Bruno Blais wrote:
> Good point. So would it be a bad thing to have this structured buffered within 
> the class by default? It seems like a memory footprint, but rebuilding that 
> structure on the fly is really killing it for us (since we have say 10k 
> particle on >10k cells). Is it better to have both options? I am not sure what 
> the good call to make is here. Buffer, or buffer optionally?

If you have a lot of particles, then the structure is relatively cheap. If you 
have few particles, then it seems like a win as far as CPU time is concerned. 
It seems like you only win -- let's go with it, and if it turns out to be too 
expensive, you can always rethink the approach.

**Comment by luca-heltai** [comment]
Ciao @blaisb. I remember we discussed a lot about this. I think that we should have a SmartPointer to the Triangulation as a member of ParticleHandler, as well as a GridTools::Cache object. I agree that memory wise this would add some footprint, but I think it would a wise choice in all cases.
