### ISSUE TITLE
[Step-52] Dopri error in the results incorrect?

### ISSUE THREAD

**Issue by krishnakumarg1984** [dealii/dealii#9684]
In the [9.1](https://dealii.org/current/doxygen/deal.II/step_52.html#Results) as well as the [dev](https://dealii.org/developer/doxygen/deal.II/step_52.html#Results) version of step-52 tutorial, the dopri error is reported as __0.0165485__  taking __119__ steps to achieve the desired tolerance.

However, in my simulations, I get dopri error to be __5.59e-5__ . This can't just be written off due to machine-specific rounding error since this is three orders of magnitude lower than that reported in the tutorial, with roughly the same no. of steps (121 in my case).

So, the Dormand-Prince simulator seems to be the most accurate one. Can someone else independently verify this?

**Comment by bangerth** [comment]
What happens if you try this with previous versions of deal.II?

**Comment by krishnakumarg1984** [comment]
@bangerth Did you mean v8.5.0 or v9.0.0?   I tried it with v9.1.1 .

Do we expect a difference due to some improvement in the ODE solver between those releases? I am asking because it is non-trivial effort to compile and run an older version of deal.ii (that tutorial also requires the additional effort of configuring the UMFPACK interface.)

**Comment by bangerth** [comment]
On 3/19/20 4:44 PM, Krishnakumar Gopalakrishnan wrote:
> @bangerth <https://github.com/bangerth> Did you mean v8.5.0 or v9.0.0? I tried 
> it with v9.1.1 .

Either would be interesting to try. It is not uncommon that there are 
improvements in library code that have an effect on a tutorial program -- but 
if nobody notices at the time, then the tutorial is never updated. It would be 
interesting to see when that change happened.


> Do we expect a difference due to some improvement in the ODE solver between 
> those releases? I am asking because it is non-trivial effort to compile and 
> run an older version of deal.ii (that tutorial also requires the additional 
> effort of configuring the UMFPACK interface.)

The latter should always be available, shouldn't it? I think that at least for 
this tutorial, you don't need any of the external packages.

**Comment by krishnakumarg1984** [comment]
Looks like the corresponding [source file for that tutorial](https://github.com/dealii/dealii/blob/master/examples/step-52/doc/results.dox) hasn't been updated for the last 4 years.  (Sep 16 , 2016).  

Looks like there was a deal.II version 8.4.2 that released a few days prior to that (Sep 3, 2016). Maybe I can try with that. 

Also, it is worth noting that the errors reported for all other implicit, explicit and embedded simulators look exactly the same. Somehow only Dopri looks so drastically different.

**Comment by krishnakumarg1984** [comment]
In v9.1.1, with Cash-Karp I get an error of 0.0678 in 106 steps,  whereas the tutorial promises 5 orders of magnitude improvements, 8.59366e-07 !!. 

Did Cash-Karp become worse between releases?

**Comment by bangerth** [comment]
On 3/19/20 5:26 PM, Krishnakumar Gopalakrishnan wrote:
> Did Cash-Karp become worse between releases?

That, too, would be nice to investigate :-)

**Comment by Rombur** [comment]
I think this can be explained by round-off error:
Tutorial:
```
Embedded explicit methods:
Heun-Euler:               error=0.0073012
                steps performed=284
Bogacki-Shampine:         error=0.000403281
                steps performed=181
Dopri:                    error=0.0165485
                steps performed=119
Fehlberg:                 error=0.00104926
                steps performed=106
Cash-Karp:                error=8.59366e-07
                steps performed=107
```
Master debug
```
Embedded explicit methods:
final time step 0.024
Heun-Euler:               error=0.0073012
                steps performed=284
final time step 0.0274464
Bogacki-Shampine:         error=0.000406488
                steps performed=181
final time step 0.046091
Dopri:                    error=0.00302879
                steps performed=120
final time step 0.0195315
Fehlberg:                 error=0.000609176
                steps performed=106
final time step 0.0868327
Cash-Karp:                error=0.0738035
                steps performed=106
```
Master release (clang 10 with O3)
```
Embedded explicit methods:
final time step 0.024
Heun-Euler:               error=0.0073012
                steps performed=284
final time step 0.0274464
Bogacki-Shampine:         error=0.000406488
                steps performed=181
final time step 0.046091
Dopri:                    error=0.00302879
                steps performed=120
final time step 0.0195315
Fehlberg:                 error=0.000609176
                steps performed=106
final time step 0.0868327
Cash-Karp:                error=0.0738035
                steps performed=106
```
Master release (clang 10 with Ofast)
```
Embedded explicit methods:
final time step 0.024
Heun-Euler:               error=0.0073012
                steps performed=284
final time step 0.0440352
Bogacki-Shampine:         error=0.000401145
                steps performed=181
final time step 0.0542175
Dopri:                    error=3.13204e-05
                steps performed=121
final time step 0.0195315
Fehlberg:                 error=0.0023747
                steps performed=106
final time step 0.0502059
Cash-Karp:                error=8.4552e-05
                steps performed=107
```
You see that there is a big difference between Ofast and the other results. The thing with OFast is that the compiler is allowed more liberty in the way it optimizes the code which gives different round-off. You can see that except for `Heun-Euler` and `Fehlberg` the last time step is different, since we are looking at the error at one point in time and not over the whole time, we can expect different error. Imagine that you compute the error at one point and you use AMR, depending on how the mesh is refined the error will change quite a bit at this point but it should be pretty stable if you look a the error over the whole domain. Honestly, the only strange result is for `Fehlberg` where we would expect an error closer for Ofast and O3. However, since we are adding a bunch of small numbers this is not too alarming.

**Comment by bangerth** [comment]
That would be concerning if the error differs by a factor of 100 based on 
round-off:

Debug:
Dopri:                    error=0.00302879
                 steps performed=120
final time step 0.0195315

Release:
Dopri:                    error=3.13204e-05
                 steps performed=121
final time step 0.0195315

I bet that there is a subtle bug somewhere that due to round-off (or a poorly 
chosen tolerance), in one case we make another step (or don't) and so evaluate 
the solution at a time that is wrong by one dt. If you do this, then the value 
you evaluate, f(t+dt), is always wrong by O(dt) because
   f(t+dt) = f(t)         + dt * f'(t)
           = what we want + O(dt)
It would be worthwhile printing out at what times the solution is integrated. 
I'd bet a beer that in debug mode, 120 time steps get us to T+eps and we stop, 
whereas in release mode it gets us to T-eps and we do one whole time step more 
(rather than doing one time step of size eps more, or stretching the last time 
step from dt to dt+eps).

I think that the DiscreteTime class of @rezarastak in #8824 does exactly this 
kind of stretching.

**Comment by Rombur** [comment]
@bangerth you are missreading the reading result the time steps are different

final time step 0.046091
Dopri:                    error=0.00302879
                steps performed=120

final time step 0.0542175
Dopri:                    error=3.13204e-05
                steps performed=121
final time step 0.0195315

**Comment by kronbichler** [comment]
@Rombur should we postpone?

**Comment by Rombur** [comment]
I'll try to take a look this week end

**Comment by krishnakumarg1984** [comment]
@bangerth and @kronbichler  Can you also please take a look at the issue wherein with adaptive RK methods, the simulation does not stop at exactly the final time-step?

**Comment by rezarastak** [comment]
> I think that the DiscreteTime class of @rezarastak in #8824 does exactly this
kind of stretching.

Yes! By using `DiscreteTime` we can ensure that in all cases, the time-stepping ends exactly at the final time. Perhaps that would allow more consistent comparison of the performances of the solvers.

**Comment by Rombur** [comment]
> @bangerth and @kronbichler Can you also please take a look at the issue wherein with adaptive RK methods, the simulation does not stop at exactly the final time-step?

Which time does the simulation stop for you? It works correctly for me on the current master. These [lines](https://github.com/dealii/dealii/blob/master/examples/step-52/step-52.cc#L626-L627) should make sure that we get the exact final time. I am not sure why it wouldn't work. 
As for the difference in errors, I have re-run with gcc 8.0 and an updated version of clang 10 with Ofast (I was using a pre-release version) and they all give me the same result (which I have posted earlier). I just want to make clear that for the case of the embedded methods, the final error is relevant only in the sense that the error should be less than 0.1. These methods will adapt the time step so that the error is less than 0.1 and so the error is printed just as a sanity check. What matters is the number of time steps. The smallest the number, the "better" the method. Note also that because we need to reduce the last time step to get the exact final time, the error should be smaller than a regular time step. For example, for Cash-Karp, the final time step  is reduced from `0.0897524` to `0.0868327` while for Fehlberg the final time step is reduced from `0.0880603` to `0.0195315`. This is reflected in the error with Cash-Karp having an error of `0.0738035` (which is good because close of our tolerance of `0.1` whereas Fehlberg has an error of `0.000609176` (which is much smaller than our tolerance but can be explained because we reduced the time step a lot more). 

I can update the results in step-52 if this helps.

**Comment by krishnakumarg1984** [comment]
@bangerth @Rombur  Apologies for asking. A code that I am currently developing depends upon precise termination time of adaptive solvers. Are we planning to address this issue for the 9.2 release?

**Comment by Rombur** [comment]
@krishnakumarg1984 I am sorry but I cannot reproduce your problem. step-52 stops exactly at the time it should. You will need to provide the exact step to reproduce the problem.

**Comment by bangerth** [comment]
@krishnakumarg1984 -- I'm afraid it's too late in the release cycle to get this fixed. We should make fixing this a priority for 9.3, but whatever limited resources we have as a project are tied up in other things until the release, and the combined effort to test and re-test after every patch just doesn't justify holding up things any further.

What it will take to get this fixed is (i) being able to reproduce the bug, (ii) pointing out where in the algorithm the problem lies, (iii) finding a solution for the problem. We could use help for sure with (i) and (ii) at least, but also (iii).

**Comment by krishnakumarg1984** [comment]
Can we start looking into this now that 9.2 release is done?

**Comment by krishnakumarg1984** [comment]
@bangerth I am 100% certain that the simulation stops  before the finish time. You may load the PVDu file in Paraview and check it out. For example, for a certain solver, the last recorded time-step is like 9.978 sec (instead of 10 sec).

**Comment by Rombur** [comment]
> You may load the PVDu file in Paraview and check it out.

Oh OK I understand what you mean now. The simulation does not stop before the finish time. However, we only output the solution every 10 time steps otherwise we end up with too many output files. So if the number of time step is not a multiple of 10, you don't see the final time. Remove the `if` condition just above `output_results` and you will get an output for every time step.

**Comment by bangerth** [comment]
This is no longer relevant given that step-52 has been removed. See https://github.com/dealii/dealii/issues/17386, https://github.com/dealii/dealii/pull/17395, https://github.com/dealii/dealii/pull/17398.
